### ISSUE TITLE
[RFE] Bypass mechanism for builtin filter chains

### ISSUE THREAD

**Issue by Celti** [OpenSMTPD/OpenSMTPD#1010]
In an ideal world, every legitimate mailserver would be properly configured, or at the very least the server admins would be responsive. The world is _not_ ideal, so the existing filter mechanism could use a bypass/exception action to either end filter processing, or perhaps more usefully skip to the end of the current filter chain.

Something like the following seems intuitive, but not knowing much about opensmtpd's internals I'm not sure if it's realistically that simple.
```
table trusted_hosts file:/etc/mail/trusted_hosts

filter check_dyndns phase connect match rdns regex { '.*\.dyn\..*', '.*\.dsl\..*' } \
    disconnect "550 no residential connections"
filter check_rdns phase connect match !rdns disconnect "550 invalid rDNS"
filter check_fcrdns phase connect match !fcrdns disconnect "550 invalid FCrDNS"
filter check_whitelist phase connect match src <trusted_hosts> next-chain

filter check_hosts chain { whitelist_ptr, check_dyndns, check_rdns, check_fcrdns }
```

**Comment by poolpOrg** [comment]
This has been implemented and is pending review by fellow OpenBSD hackers.

**Comment by poolpOrg** [comment]
Sorry, didn't follow up on this but the diff was committed ;-)

    filter foobar phase mail-from match src <trusted_hosts> bypass

**Comment by kousu** [comment]
For people like me wondering: this feature came out in [6.7](https://github.com/OpenSMTPD/OpenSMTPD/releases/tag/6.7.0p1), so it is [in Debian 11](https://packages.debian.org/bullseye/opensmtpd) but not [Debian 10](https://packages.debian.org/buster/opensmtpd) or even [10's backports](https://packages.debian.org/buster-backports/opensmtpd). But 11 is coming out this week, so just upgrade if you can and you'll be able to use this!
