### ISSUE TITLE
Relay timeout

### ISSUE THREAD

**Issue by timothee-haudebourg** [OpenSMTPD/OpenSMTPD#1015]
I'm having trouble relaying mails through a very basic opensmtpd server.
If I understand the output of `smtpd -dv` (given below), it fails to connect to the recipient domain with a timeout (that or it fails to find a route? Not sure). I tried with different domains. Same everytime.

I can receive emails without difficulties.

```
debug: mta: new [connector:[]->[relay:target-domain.net],0x10000]
debug: mta: connecting with [connector:[]->[relay:target-domain.net],0x0]
debug: mta-routing: searching new route for [connector:[]->[relay:target-domain.net],0x0]...
debug: mta-routing: selecting candidate route [] <-> IPv6:1111:1111:1111:1::1
[ ... ]
debug: mta-routing: spawning new connection on [] <-> IPv6:1111:1111:1111:1::1
debug: mta: 0xc77218: spawned for relay [relay:target-domain.net]
debug: mta: connecting with [connector:[]->[relay:target-domain.net],0x0]
debug: mta: cannot use [relay:target-domain.net] before 2s
debug: mta-routing: no route available for [connector:[]->[relay:target-domain.net],0x0]: must wait a bit
debug: mta: retrying to connect on [connector:[]->[relay:target-domain.net],0x0] in 2s...
debug: mta: draining [relay:target-domain.net] refcount=3, ntask=2, nconnector=1, nconn=1
debug: mta: scheduling relay [relay:target-domain.net] in 1s...
[ ... ]
debug: mta: ... timeout for [relay:target-domain.net]
debug: mta: draining [relay:target-domain.net] refcount=2, ntask=2, nconnector=1, nconn=1
debug: mta: querying source for [relay:target-domain.net]...
debug: mta: ... got source for [relay:target-domain.net]: []
debug: mta: connecting with [connector:[]->[relay:target-domain.net],0x20000]
debug: mta: cancelling connector timeout
debug: mta: cannot use [relay:target-domain.net] before 1s
debug: mta-routing: no route available for [connector:[]->[relay:target-domain.net],0x0]: must wait a bit
debug: mta: retrying to connect on [connector:[]->[relay:target-domain.net],0x0] in 1s...
debug: mta: draining [relay:target-domain.net] refcount=3, ntask=2, nconnector=1, nconn=1
debug: mta: scheduling relay [relay:target-domain.net] in 10s...
```
Note that the domains and IP have been anonymized. Any idea what could be the root of the problem?

**Comment by poolpOrg** [comment]
Very likely your provider blocking outgoing port 25On Dec 1, 2019 18:13, Timothée Haudebourg <notifications@github.com> wrote:I'm having trouble relaying mails through a very basic opensmtpd server.
If I understand the output of smtpd -dv (given below), it fails to connect to the recipient domain with a timeout (that or it fails to find a route? Not sure). I tried with different domains. Same everytime.
I can receive emails without difficulties.
debug: mta: new [connector:[]->[relay:target-domain.net],0x10000]
debug: mta: connecting with [connector:[]->[relay:target-domain.net],0x0]
debug: mta-routing: searching new route for [connector:[]->[relay:target-domain.net],0x0]...
debug: mta-routing: selecting candidate route [] <-> IPv6:1111:1111:1111:1::1
[ ... ]
debug: mta-routing: spawning new connection on [] <-> IPv6:1111:1111:1111:1::1
debug: mta: 0xc77218: spawned for relay [relay:target-domain.net]
debug: mta: connecting with [connector:[]->[relay:target-domain.net],0x0]
debug: mta: cannot use [relay:target-domain.net] before 2s
debug: mta-routing: no route available for [connector:[]->[relay:target-domain.net],0x0]: must wait a bit
debug: mta: retrying to connect on [connector:[]->[relay:target-domain.net],0x0] in 2s...
debug: mta: draining [relay:target-domain.net] refcount=3, ntask=2, nconnector=1, nconn=1
debug: mta: scheduling relay [relay:target-domain.net] in 1s...
[ ... ]
debug: mta: ... timeout for [relay:target-domain.net]
debug: mta: draining [relay:target-domain.net] refcount=2, ntask=2, nconnector=1, nconn=1
debug: mta: querying source for [relay:target-domain.net]...
debug: mta: ... got source for [relay:target-domain.net]: []
debug: mta: connecting with [connector:[]->[relay:target-domain.net],0x20000]
debug: mta: cancelling connector timeout
debug: mta: cannot use [relay:target-domain.net] before 1s
debug: mta-routing: no route available for [connector:[]->[relay:target-domain.net],0x0]: must wait a bit
debug: mta: retrying to connect on [connector:[]->[relay:target-domain.net],0x0] in 1s...
debug: mta: draining [relay:target-domain.net] refcount=3, ntask=2, nconnector=1, nconn=1
debug: mta: scheduling relay [relay:target-domain.net] in 10s...

Note that the domains and IP have been anonymized. Any idea what could be the root of the problem?

**Comment by timothee-haudebourg** [comment]
Thanks, that makes sense. But if that's the solution I'll feel like an idiot :)

**Comment by poolpOrg** [comment]
I'm almost 100% convinced this is the issue, I'll give you the benefit of the doubt and let you close the issue yourself when you confirm.

Don't worry feeling like an idiot, at least one person has this issue per week :-)

**Comment by timothee-haudebourg** [comment]
That was it, thanks a lot :)

**Comment by vladsf** [comment]
indeed. Always check if outgoing 587 port is not blocked by your service provider.
