### ISSUE TITLE
Clarification for filters in connection to actions

### ISSUE THREAD

**Issue by Anachron** [OpenSMTPD/OpenSMTPD#1016]
> First of all: Hats up to you sir! You've created an incredible valuable tool for the whole world and your sweat and heart and be seen at each part of the tool. `OpenSMTPD` is just so well that you can count me as a fan of yours!

Now about my "issue":

I'm eagerly reading about the upcoming filter api and all related improvements.
https://poolp.org/posts/2019-12-01/spf-aware-greylisting-and-filter-greylist/

For now I'm doing `in > dkimproxy_in > spampd > maildir` and `dkimproxy_out > out` for all domain mails, but in the future I'm planning to add `filter-greylist` and `clamav` (both for incoming and outgoing).

I was wondering whether this means I can replace my whole "action"  stack with a chain of filters? (Like in this example: https://poolp.org/posts/2019-09-14/setting-up-a-mail-server-with-opensmtpd-dovecot-and-rspamd/#configuring-opensmtpd) Or is there something stopping me from implementing the whole email stack with filters?
Especially since all this email relaying between tons and tons of tools is  getting harder to handle with each and every step one adds. When my currently target setup is finished I would be using 12 different ports, 6 for in and out respectively. 

Thanks for your hard work once again and for your time.

**Comment by poolpOrg** [comment]
> I was wondering whether this means I can replace my whole "action" stack with a chain of filters? (Like in this example: https://poolp.org/posts/2019-09-14/setting-up-a-mail-server-with-opensmtpd-dovecot-and-rspamd/#configuring-opensmtpd) Or is there something stopping me from implementing the whole email stack with filters?
>

That is exactly what it means.

If you are using a filter, then you don't need to use actions to reinject on different ports with tags, you just go:

    listen on all tls pki in.mailbrix.mx hostname in.mailbrix.mx filter { check_rdns, check_fcrdns, no_helo, eventlog, rspamd, senderscore, greylist }

and you define what action should be applied disregarding the filters.


> Thanks for your hard work once again and for your time.
>

Cheers,
