### ISSUE TITLE
How to debug crashed filters?

### ISSUE THREAD

**Issue by cross** [OpenSMTPD/OpenSMTPD#1017]
I am developing a filter in C, and have it printf logging to a file.  However, if/when something goes wrong and it crashes, I'm not sure how to find the issue.  (I was using gdb to attach and set breakpoints, but that only works if I'm tracking a specific failure in a specific place.  Not if "it seems fine" but crashes hours later.)

I found years-old issues in this repository about changes to generate core files for smtpd, and/or filters, but not sure if any of that applies now, as those were 2015/2016 comments.

Could you please recommend, or point to documentation, of the recommended processes to debug opensmtpd filters?  Thank you.

**Comment by poolpOrg** [comment]
There is no recommended process to debug filters because they may be written in a variety of languages and not all languages use the same debugging tools.

What you can do is either attach gdb, or use stderr-printing which will be available in smtpd logs.

**Comment by cross** [comment]
Thanks.  stderr-printing only works if you have some sense where to put them, but.  I was hoping that there was a known path where cores would show up, and a process for ensuring cores are enabled.  As mentioned, I saw issues about that that were years old, so was looking for a process that works with OpenSMTPd 6.6.x.
