### ISSUE TITLE
Issue with tilde character and LMTP

### ISSUE THREAD

**Issue by azmeuk** [OpenSMTPD/OpenSMTPD#1026]
I am trying to make [sourcehut lists](https://sr.ht/) work with OpenSMTPD 6.6.1 on FreeBSD 12.

In my configuration OpenSMTPD sends the mail to a sourcehut LMTP client.

```
listen on $interface tls pki lists.forge.mydomain.tld
action sourcehut lmtp "/tmp/lists.forge.mydomain.tld-lmtp.sock" rcpt-to \
    virtual { "@" = listssrht }
match from any for domain "lists.forge.mydomain.tld" action sourcehut
```

Sourcehut lists adresses have the format: [~user/listname@lists.forge.mydomain.tld](mailto:~user/listname@lists.forge.mydomain.tld). The tilde character does not seem to be handled correcty, since those are the commands received by the LMTP client:

```
LHLO localhost
MAIL FROM:<foobar@mydomain.tld>
RCPT TO:<:user/listname@lists.forge.mydomain.tld>
```

**Comment by ngortheone** [comment]
Thanks for the report, and sorry for slow response. We use sourcehut for our automation and we absolutely must fix this.
@poolpOrg, is this a security feature where unexpected chars get transformed?

**Comment by DemiMarie** [comment]
@azmeuk @ngortheone This should be fixed by now.  The characters were being transformed during variable expansion, but `mail.lmtp` now gets the information it needs from the environment instead.

**Comment by azmeuk** [comment]
I can confirm this works with opensmtpd 6.8
