### ISSUE TITLE
cant make opensmtpd 6.6.1p1

### ISSUE THREAD

**Issue by rossiV1** [OpenSMTPD/OpenSMTPD#1029]
hi. currently i am trying to install 6.6.1p1 but i cant install it

currently if i use the `make` command, it will show error.

> Makefile:768: recipe for target '../../smtpd/smtpd-ca.o' failed
make[3]: *** [../../smtpd/smtpd-ca.o] Error 1
make[3]: Leaving directory '/home/testdeb/opensmtpd-6.6.1p1/mk/smtpd'
Makefile:373: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/testdeb/opensmtpd-6.6.1p1/mk'
Makefile:420: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/testdeb/opensmtpd-6.6.1p1'
Makefile:352: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by poolpOrg** [comment]
Hello, that's not enough information to understand why build fails.

You shouldn't build 6.6.1p1 which had a security issue, use the latest release 6.6.3p1 instead:

https://github.com/OpenSMTPD/OpenSMTPD/releases/tag/6.6.3p1

**Comment by rossiV1** [comment]
sorry for the less information. i will include config.log as well.

i am currently building this version back because trying to work with blue team on detection. 

[smtpd.log](https://github.com/OpenSMTPD/OpenSMTPD/files/4218226/smtpd.log)

**Comment by rossiV1** [comment]
for this, i manage to use command `./bootstrap` and `./configure`

but cannot use make command and it shows error as above

**Comment by rossiV1** [comment]
on the side note. i use a freshly installed debian 9.1.1 to install this version of opensmtpd

**Comment by Anachron** [comment]
Well this is directly from the install file:

Briefly, the shell commands `./configure; make; make install' should

configure, build, and install this package. The following

more-detailed instructions are generic; see the `README' file for

instructions specific to this package.

**Comment by ngortheone** [comment]
@rossiV1 I am closing this one due to inactivity.
Please feel free to re-open this if you want to troubleshoot this more.
