### ISSUE TITLE
Move MDA selection to the parent process

### ISSUE THREAD

**Issue by DemiMarie** [OpenSMTPD/OpenSMTPD#1033]
Being able to select an arbitrary command as an MDA is equivalent to executing arbitrary code as root.  Even after delivery as root is removed, being able to execute arbitrary code as any unprivileged user is almost invariably enough to gain full root access.

One way to harden against similar vulnerabilities is for the envelope file to only contain the action, not the MDA itself.  The parent process will then choose the correct MDA based on its configuration.  If the MDA is secure, this prevents all command injection attacks.

**Comment by poolpOrg** [comment]
Sorry but I think this assessment is wrong:

> Being able to select an arbitrary command as an MDA is equivalent to executing arbitrary code as root.

This is only true ... if you allow executing MDA as root, which I've been arguing against since 2012:

https://github.com/openbsd/src/commit/69de27315438c961296e72e96fd27766a1a7345f#diff-2791b48617b3d76acc3148296d263d71

Then,  regarding that bit:

>Even after delivery as root is removed, being able to execute arbitrary code as any unprivileged user is almost invariably enough to gain full root access.

The delivery methods for which root was removed were precisely the ones that didn't allow full root access so this doesn't prove true in reality.

Futhermore, you can't prevent MDA from running arbitrary code because the MDA programming environment doesn't restrict what they can do. They're supposed to read from stdin, exit with a proper status, and what they do internally is none of the MTA business. A lot of people use custom MDA to inject mail into databases or popular MDA such as procmail / fdm / whatever-other-classifier, so you can't prevent MDA from running arbitrary code without breaking the expectations of a vast number of users... if we went that way, we would only support mbox / maildir / lmtp.


> One way to harden against similar vulnerabilities is for the envelope file to only contain the action, not the MDA itself. The parent process will then choose the correct MDA based on its configuration. If the MDA is secure, this prevents all command injection attacks.
>

You are suggesting to do what we did several years ago and which turned out to be a bad idea as it led to special cases all over the place. The MTA should not know what the MDA do because there should not be special cases.

We can prevent injection attacks by switching to the `exec*()` family.

**Comment by DemiMarie** [comment]
> > Even after delivery as root is removed, being able to execute arbitrary code as any unprivileged user is almost invariably enough to gain full root access.
> 
> The delivery methods for which root was removed were precisely the ones that didn't allow full root access so this doesn't prove true in reality.

Theoretically, you are correct.  In practice, if you can execute arbitrary code as a user with doas privileges, you can often compromise a user with privileges to run doas, and steal their password when they try to run doas (assuming they have doas set to require a password in the first place).

> Futhermore, you can't prevent MDA from running arbitrary code because the MDA programming environment doesn't restrict what they can do. They're supposed to read from stdin, exit with a proper status, and what they do internally is none of the MTA business. A lot of people use custom MDA to inject mail into databases or popular MDA such as procmail / fdm / whatever-other-classifier, so you can't prevent MDA from running arbitrary code without breaking the expectations of a vast number of users... if we went that way, we would only support mbox / maildir / lmtp.

I absolutely agree with that.

What I have a problem with is the unprivileged processes in OpenSMTPD being able to execute code as *any* user other than the one they are running as.  In particular, a bug in the SMTP client process should not be able to compromise any user’s account.  So this is really an insufficient privilege separation bug.

**Comment by poolpOrg** [comment]
> What I have a problem with is the unprivileged processes in OpenSMTPD being able to execute code as _any_ user other than the one they are running as.
>

Can you clarify this ?

No matter what we do, OpenSMTPD will _always_ have to fork() a process with the privileges of the recipient to be able to execute an MDA that the user possibly wrote and which OpenSMTPD knows nothing about.

If a user installs `fdm` in `~/bin/` and has a `~/.forward` with `|~/bin/fdm ...`, what are your expectations ?

Or to take a very extreme case, if a user writes `|/bin/rm -rf ~` in their `~/.forward` file, what are your expectations ?


> In particular, a bug in the SMTP client process should not be able to compromise any user’s account.
> 

Of course, I don't think anyone will argue it should.


> So this is really an insufficient privilege separation bug: the parent process should not trust its child process to give it the correct command to run.
> 

Then I have to ask again:

If a user installs `fdm` in `~/bin/` and has a `~/.forward` with `|~/bin/fdm ...`, what are your expectations and what is OpenSMTPD supposed to do ?


> That said, this issue is poorly phrased. Should I close this and file a new one?
>

The issue title is confusing indeed, but you can edit it, what matters the most is the proposal inside and I'm unsure what you're proposing at this point.

**Comment by DemiMarie** [comment]
> > Theoretically, you are correct. In practice, if you can execute arbitrary code as a user with doas privileges, you can often compromise a user with privileges to run doas, and steal their password when they try to run doas (assuming they have doas set to require a password in the first place).
> 
> This is the same problem as delivering to root: privileged accounts should be aliases, no matter if the account has privileged because it is uid 0 or because it has sudo / doas.

Agreed. Could this be made clearer in the documentation? I also consider being able to execute code as another user to be privilege escalation, even if the other user isn’t itself privileged.

I think we should warn about delivering to any user in the wheel group, which is traditionally used for administrative users with doas or sudo access.
 
> > What I have a problem with is the unprivileged processes in OpenSMTPD being able to execute code as _any_ user other than the one they are running as.
> 
> Can you clarify this ?
> 
> No matter what we do, OpenSMTPD will _always_ have to fork() a process with the privileges of the recipient to be able to execute an MDA that the user possibly wrote and which OpenSMTPD knows nothing about.
> 
> If a user installs `fdm` in `~/bin/` and has a `~/.forward` with `|~/bin/fdm ...`, what are your expectations ?

It should run.
 
> Or to take a very extreme case, if a user writes `|/bin/rm -rf ~` in their `~/.forward` file, what are your expectations ?

It should run.

> > In particular, a bug in the SMTP client process should not be able to compromise any user’s account.
> 
> Of course, I don't think anyone will argue it should.
> 
> > So this is really an insufficient privilege separation bug: the parent process should not trust its child process to give it the correct command to run.
> 
> Then I have to ask again:
> 
> If a user installs `fdm` in `~/bin/` and has a `~/.forward` with `|~/bin/fdm ...`, what are your expectations and what is OpenSMTPD supposed to do ?

`PROC_PARENT` should open `~/.forward`, see that it starts with `|`, and spawn the rest of the line as a shell command with the message as its standard input.  If `~/.forward` does not exist, `PROC_PARENT` should spawn the MDA that `smtpd.conf` says it should.

**Comment by DemiMarie** [comment]
Closing in favor of #1066.
