### ISSUE TITLE
Use execpromises and unveil() to sandbox MDAs

### ISSUE THREAD

**Issue by DemiMarie** [OpenSMTPD/OpenSMTPD#1034]
We should use the `execpromises` argument of `pledge(2)`, along with `unveil(2)`, to sandbox MDAs.  This ensures that a rogue MDA cannot write to anything it should not.  While we may not be able to do this for commands in `.forward` files, we can certainly do it for built-in MDAs.

The calls should be made in the parent process to protect against command injection and other similar vulnerabilities.

On Linux, we can use LSMs (SELinux and/or AppArmor) to similar effect.

**Comment by poolpOrg** [comment]
> We should use the `execpromises` argument of `pledge(2)`, along with `unveil(2)`, to sandbox MDAs.
>

What do you suggest for these ?


> This ensures that a rogue MDA cannot write to anything it should not. While we may not be able to do this for commands in `.forward` files, we can certainly do it for built-in MDAs.
> 

How do you know where an MDA allowed to write or not ?

How do you differentiate a built-in MDA from others ?

If I create a `~/.forward` calling `/usr/libexec/mail.maildir` is it a builtin MDA ?


> The calls should be made in the parent process to protect against command injection and other similar vulnerabilities.
> 

So the parent needs to know what the MDA do internally ?


> On Linux, we can use LSMs (SELinux and/or AppArmor) to similar effect.
> 

No opinion on that, I already told the community I'd accept diffs for this as long as they're maintained.

**Comment by DemiMarie** [comment]
Once we switch to `execle`, `pledge` and `unveil` can be handled by the MDA itself, and isn’t the job of OpenSMTPD.
