### ISSUE TITLE
[Question] multi-domain multi-interface setup

### ISSUE THREAD

**Issue by ngortheone** [OpenSMTPD/OpenSMTPD#1035]
Hey @poolpOrg 

I am finally building my new mailserver with opensmtpd and I've got a question about how to use one set of { opensmtpd, rspamd, dovecot }(read: one vm/jail/container)  to serve 2+ domains. I know that the most simple way to do this would be to create a vm/jail/container per domain, but that is not very resource-efficient.

So to formalize the question:  I have 2 Ethernet interfaces: `ena0` and `ena1`. Each interface has IP address that corresponds to its own domain. And I have 2 completely separate domains (`foo.com` and `bar.com`). Users of domain `foo.com` don't know anything about `bar.com` and vice versa.
```
ena0   1.1.1.1     foo.com
ena1   2.2.2.2     bar.com
```

Here is what I want:

- listen for incoming mail for domain `foo.com` on `ena0` only 
- listen for incoming mail for domain `bar.com` on `ena1` only

- accept mail for relay from `joe@bar.com` on  `ena0` only
- accept mail for relay from `bob@bar.com` on  `ena1` only

- make sure that outgoing mail from `joe@foo.com` is relayed from `ena0` (traffic exits through ena0)
- make sure that outgoing mail from `bob@bar.com` is relayed from `ena1` (traffic exits through ena1)

While reading through https://man.openbsd.org/smtpd.conf I can't quite understand how I can get this to work.

The approximate config I got so far :

```
# Keys for foo.com
pki mail.foo.com cert "/etc/ssl/foo.com.fullchain.pem"
pki mail.foo.com key "/etc/ssl/private/foo.com.key"

# Keys for bar.com
pki mail.bar.com cert "/etc/ssl/bar.com.fullchain.pem"
pki mail.bar.com key "/etc/ssl/private/bar.com.key"

# Listen for incoming mail on ena0
listen on ena0 tls-require pki mail.foo.com hostnames { 1.1.1.1 = mail.foo.com }

# Listen for incoming mail on ena1
listen on ena1 tls-require pki mail.bar.com hostnames { 2.2.2.2 = mail.bar.com }

```

and this is where I got stuck. I don't know how to listen for mail submission from `joe@foo.com` on `ena0` only. Any ideas?

-------------
Used materials
https://poolp.org/posts/2018-05-21/switching-to-opensmtpd-new-config/
https://poolp.org/posts/2019-09-14/setting-up-a-mail-server-with-opensmtpd-dovecot-and-rspamd/
https://man.openbsd.org/smtpd.conf

**Comment by whataboutpereira** [comment]
Off the top of my head, have a look at tagging the listen directives and then use tags in match rules.

**Comment by poolpOrg** [comment]
yeah, the tagging feature can be used for this:

    listen on en0 tag EN0
    listen on en1 tag EN1
    
    match tagged EN0 [...]
    match tagged EN1 [...]

**Comment by poolpOrg** [comment]
@InnotSagg:

```
# replace $if with the interface name:
#
listen on $if hostnames { ip1 = domain.1, ip2 = domain.2 }
```
