### ISSUE TITLE
[Feature] Add the possibility to specify minimum TLS version.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#1036]
Systems like RHEL 8/CentOS 8 are using a global crypto policy which by default restricts OpenSMTPD (and everything else using OpenSSL) to TLSv1.2.

Unfortunately there are lots of servers still out there using TLSv1/1.1 and instead of having them all switch to plain text when transmitting mail, it would be nice to allow TLSv1 in OpenSMTPD. Currently I have to set the global crypto policy for CentOS 8 to LEGACY, which allows TLSv1 for the whole system. 

I can fortunately overwrite the global crypto policy's ciphers with 'smtp ciphers'.

**Comment by poolpOrg** [comment]
too late for 6.7 but I have diffs that will hit the tree sometime in May very likely

**Comment by dfateyev** [comment]
More preferable as a protocols list (see "smtpd_tls_protocols", "smtp_tls_protocols" in Postfix, or a similar option in Nginx)

**Comment by poolpOrg** [comment]
Yes this is what will be done:

https://github.com/OpenSMTPD/OpenSMTPD/compare/libtls...libtls-issue-1024-protocols

**Comment by toxadx** [comment]
Will it be merged into 6.9?

**Comment by poolpOrg** [comment]
I don't know...

My libtls branch was never merged in OpenBSD due to lack of review and it no longer applies :-(

I know Eric Faurot is currently actively working again on bringing libtls support and if he pulls it before 6.9, I'll submit back all my diffs for review.

**Comment by ArchangeGabriel** [comment]
This was finally made available in 6.9 it seems, and thus made available in https://github.com/OpenSMTPD/OpenSMTPD/releases/tag/7.3.0p0:
> Allow to specify TLS protocols and ciphers per listener and relay action.

Relevant man pages bits: https://man.openbsd.org/smtpd.conf#protocols and https://man.openbsd.org/smtpd.conf#protocols~2.
