### ISSUE TITLE
[Question] execution user/group in pipe aliases

### ISSUE THREAD

**Issue by grmat** [OpenSMTPD/OpenSMTPD#1040]
Hi,

as other MTAs, OpenSMTPD allows `|command` aliases to pipe incoming mails to other executables. Those are executed under the daemon's unprivileged account, as documented.

E.g. Postfix allows to set up a separate aliases file for those pipe aliases, then takes its owner/group to execute the command. This is helpful for software like GNU Mailman, e.g. with OpenSMTPD and Mailman, I currently, I have to reconfigure/-build mailman with something like `--with-mail-gid=smtpd`. 

Does OpenSMTPD not support this by design or would you take a feature request on that?

**Comment by poolpOrg** [comment]
Hi,

I think aliases should not support command processing at all as handling these from a .forward file is equivalent but enforces the creation of a dedicated unprivileged user.

How would you go about adding user/gid to aliases ?

**Comment by grmat** [comment]
I wasn't aware of .forward files, I think they do exactly what I need. I should've read the docs more thoroughly. Sorry for the noise and thanks for the hint!
