### ISSUE TITLE
Filters API does not escape | character in email addresses

### ISSUE THREAD

**Issue by hblanks** [OpenSMTPD/OpenSMTPD#1041]
The OpenSMTPD filters API relies on `|` to delimit fields when sending with filter processes.

However, some fields, notably email addresses, contain user input, and this input can contain the pipe charcter, `|`.

It may thus be best to update the filters manpage to note that some lines may contain unescaped | characters, or to escape them.

Related: https://github.com/poolpOrg/filter-rspamd/issues/32

**Comment by poolpOrg** [comment]
discussed with @ericfaurot, the fields should be swapped so that user-supplied fields are always last, he will look into it this week-end.

this will require a protocol bump and some filters will need to be adapted.

**Comment by lfos** [comment]
Can we guarantee that there will always only be one user-supplied field, even with future protocol extensions?

**Comment by poolpOrg** [comment]
well, we define the protocol so we can certainly guarantee it yes

**Comment by lfos** [comment]
I am not convinced this is the best design decision. It seems too simple to support escaping, allow `|` everywhere and never consider that detail again when making future changes to the protocol.

If swapping the fields is your final solution, I would highliy recommend at least documenting the general design choice of having at most one user-supplied field and `|` being disallowed in all other fields.

Thanks for all the great work!

**Comment by poolpOrg** [comment]
Discussed with Eric, Joerg, Martijn and I, we believe it is the best approach:

- data-line already works this way and it never rose concerns
- no filter hook passing user-supplied info can pass more than one parameter by design
- there is no risk of accidentally doing that

Swapping the field is the solution chosen and will be committed shortly (documentation will follow)
