### ISSUE TITLE
smtpd crash "invalid input, shouldn't happen"

### ISSUE THREAD

**Issue by 310b8fb5** [OpenSMTPD/OpenSMTPD#1044]
I'm running rspamd/senderscore mostly as per the article Gilles posted.

I noted smtpd had crashed, and found this in my /var/log/maillog:
> Mar 28 15:44:02 host smtpd[31729]: eccaec04026b366e smtp connected address=104.140.80.26 host=mail.bridginglayabouts.com
> Mar 28 15:44:06 host smtpd[76743]: rspamd: 2020/03/28 15:44:06 invalid input, shouldn't happen
> Mar 28 15:44:06 host smtpd[95208]: warn: lost processor: rspamd exited abnormally
> Mar 28 15:44:06 host smtpd[95208]: Exiting

rspamd was still running after smtpd died. restarting smtpd seemed to work fine.

**Comment by poolpOrg** [comment]
Hi,

Can you specify which version of OpenSMTPD and filters you are running ?

This is likely related to https://github.com/poolpOrg/filter-rspamd/issues/32

Gilles

**Comment by 310b8fb5** [comment]
Whoops! Sorry. I had posted this in IRC a while back, and was not in the mindset to post all the info here apparently :)

> $ uname -a
> OpenBSD host.domain 6.6 GENERIC#7 amd64

> $ smtpd -h
> version: OpenSMTPD 6.6.0

**Comment by 310b8fb5** [comment]
Here's a bit more info:

> $ pkg_info ...
> rspamd-1.9.4        event-driven spam filtering system in C/Lua
> opensmtpd-filter-rspamd-0.1.4 rspamd integration to the OpenSMTPD daemon
> opensmtpd-filter-senderscore-0.1.0 SenderScore integration to the OpenSMTPD daemon

**Comment by poolpOrg** [comment]
This is related to a bug in filter-rspamd handling of events, I have fixed and will issue a new release today as well as a new package for OpenBSD
