### ISSUE TITLE
Fails to build with GCC-10

### ISSUE THREAD

**Issue by ryanakca** [OpenSMTPD/OpenSMTPD#1051]
OpenSMTPD fails to build in a test rebuild on at least amd64 with gcc-10/g++-10, but succeeds to build with gcc-9/g++-9.

The full build log can be found at:
http://people.debian.org/~doko/logs/gcc10-20200225/opensmtpd_6.6.4p1-1_unstable_gcc10.log
See the end for the errors.

This is Debian bug [#957644](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957644).

**Comment by dfateyev** [comment]
BTW, I have already reported it to Gilles. In short, GCC 10 introduced "-fno-common" by default.
https://gcc.gnu.org/gcc-10/porting_to.html#common

**Comment by poolpOrg** [comment]
I will dive into this next week as I'll focus on portable

**Comment by poolpOrg** [comment]
into it

**Comment by poolpOrg** [comment]
Fixed build with gcc-10 in branch "portable" and added a CI target for gcc10

I'll close the ticket but @dfateyev I would appreciate if you gave it a try on Fedora and open a separate ticket if you run into an issue

**Comment by dfateyev** [comment]
@poolpOrg checked, created #1058
