### ISSUE TITLE
invalid domain name in helo

### ISSUE THREAD

**Issue by antoniotvr** [OpenSMTPD/OpenSMTPD#1054]

**Comment by antoniotvr** [comment]
Hi.

I have this problem.

I have executed smtpd with option -dv (to see the relatime logs).

When a UPS system tries to connect via smtp to send an email I see this error line:

smtp failed-command command="HELO " result="501 5.5.4 Invalid command arguments: Invalid domain name"

I cannot set the domain name on the UPS so where can be the problem? How can be solved?

Regards

**Comment by poolpOrg** [comment]
Hi, there is nothing that can be done at OpenSMTPD level:

the hostname parameter to HELO/EHLO Is mandatory and your UPS is sending "HELO " instead of "HELO something", you need to figure out why it sends an empty hostname.

**Comment by antoniotvr** [comment]
Ok thank you.

I think that the email sent from ups it Is wrong so i will contact ups
manufacturer to indicate the bug.

Regards

Il sab 25 apr 2020, 11:07 Gilles Chehade <notifications@github.com> ha
scritto:
