### ISSUE TITLE
opensmtpd-filter-dkimsign for multiple domains?

### ISSUE THREAD

**Issue by myfirstnameispaul** [OpenSMTPD/OpenSMTPD#1057]
I installed `opensmtpd-filter-dkimsign` and edited `smtpd.conf`:
````
table aliases file:/etc/mail/aliases

filter "dkimsign" proc-exec "filter-dkimsign \
    -d example.com -s selector -t \
    -k /etc/mail/dkim/selector.key" user _dkimsign group _dkimsign

listen on socket filter "dkimsign"
listen on lo0 filter "dkimsign"

action "local_mail" mbox alias <aliases>
action "outbound" relay

match for local action "local_mail"
match for any action "outbound"
````

It works great for my purposes which is "proof of work" so my web server can inbox.

However, I'm not clear on how to configure for multiple domains?

**Comment by poolpOrg** [comment]
Please consider using the mailing list for configuration related questions as this is our bug tracker.

As a side-note, filter-dkimsign is an add-on, not part of the project, and as far as I know the author doesn't read issues here.
