### ISSUE TITLE
Broken syslog messages from OpenSMTPD v6.7.0 on CentOS 8.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#1059]
I tried out current portable a few days ago on CentOS 8, building it the exact same way that my 6.6.4p1 was built previously.

I'm running into weird log entries in /var/log/maillog:

```
May  2 12:32:13 centos8 smtpd[124028]: info: OpenSMTPD 6.7.0-portable starting
May  2 12:32:50 centos8 journal[124033]: y express[124033]: 6ad20154b7c9470a smtp connected address=local host=centos8

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

Syslog seems to get confused about the process that's logging.

I'm running it with the same systemd unit script as 6.6.4p1 (posted here: https://github.com/OpenSMTPD/OpenSMTPD/issues/1039#issuecomment-623426652).

Any ideas?

**Comment by dfateyev** [comment]
I can confirm it not only for EL7 (`systemd-239`), but all recent systemd versions, e.g. `systemd-245` under recent Fedora:

```
May 17 04:17:43 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24b54b9d4a3 smtp connected address=local host=fedora32-amd64.svc.xxxx.xxx
May 17 04:17:43 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24b54b9d4a3 smtp message msgid=a9f5e0cc size=529 nrcpt=1 proto=ESMTP
May 17 04:17:43 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24b54b9d4a3 smtp envelope evpid=a9f5e0cc7f3ac069 from=<root@fedora32-amd64.svc.xxxx.xxx> to=<xxx@xxx.com>
May 17 04:17:43 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24b54b9d4a3 smtp disconnected reason=quit
May 17 04:17:43 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24f3e08857b mta connecting address=smtp://64.233.164.27:25 host=lf-in-f27.1e100.net
May 17 04:17:43 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24f3e08857b mta connected
May 17 04:17:44 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24f3e08857b mta tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
May 17 04:17:44 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24f3e08857b mta server-cert-check result="success"
May 17 04:17:46 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24f3e08857b mta delivery evpid=a9f5e0cc7f3ac069 from=<root@fedora32-amd64.svc.xxxx.xxx> to=<xxx@xxx.com> rcpt=<-> source="192.168.18.200" relay="6>
May 17 04:17:56 fedora32-amd64.svc.xxxx.xxx smtpd[19980]: y express[19980]: eebcd24f3e08857b mta disconnected reason=quit messages=1

```
P.S. beside the issue itself, @poolpOrg I always wondered, why is there a two-word `"pony express"` process name vs one-word `"klondike"`, `"control"` ones? The common one-word process naming scheme looks more logical, IMO.

**Comment by ngortheone** [comment]
> I always wondered, why is there a two-word "pony express"
+1

Why not any of:
- pony-express
- ponyexpress
- pony
- express

?

**Comment by ngortheone** [comment]
But I think it also demonstrates closed-mindedness of systemd, it assumes that all processes have a single word names, instead of checking the process name.

**Comment by whataboutpereira** [comment]
Let's not forget it used to work with systemd up to 6.6.4p1.

**Comment by poolpOrg** [comment]
The process names should change, I had suggested new names but will send a diff after release to make this move forward.

**Comment by jdelic** [comment]
@poolpOrg have you investigated this by any chance? I really tried to figure out what changed... there is no reason why `pstat` would confuse systemd like that, right? The only reference to systemd not supporting spaces inside of any strings was connected to systemd unit names (i.e. the `.service` files themselves).

Or are you just taking the path of least resistance here (which is perfectly fine, I'd just like to know before I try to figure out what makes this problematic for systemd)?

**Comment by whataboutpereira** [comment]
> The process names should change, I had suggested new names but will send a diff after release to make this move forward.

Did something change with process handling between 6.6.4p1 and current portable that would break it for Systemd? I'm fairly certain "pony express" existed before and it worked without problems.

**Comment by poolpOrg** [comment]
@jdelic haven't investigated as I was focusing on preparing the portable release to match the OpenBSD release and these glitches can be solved in portable-specific patch level releases. OpenSMTPD doesn't ship systemd units so I'm not even sure this isn't a packaging issue at this point.

@whataboutpereira the "pony express" has existed since 2014 with this name yes

**Comment by whataboutpereira** [comment]
I don't know if it helps at all, but I spent a couple of hours trying out different commits with no progress.

These all build fine by have broken logging:

Feb 24:
https://github.com/OpenSMTPD/OpenSMTPD/tree/12c33f060e74270be27e991d153ed11fb6bb1dd5

Feb 23:
https://github.com/OpenSMTPD/OpenSMTPD/tree/b8a9e92fee36abd95b08a49d7487f81035f9d5fa

Feb 11 (looks to be 6.6.3p1, which is weird, because it worked from releases):
https://github.com/OpenSMTPD/OpenSMTPD/tree/b899a8b66885a97baf49b3300f4dd680127adfba

Feb 22:
What works is 6.6.4p1 downloaded from releases (Feb 24):

https://github.com/OpenSMTPD/OpenSMTPD/releases/download/6.6.4p1/opensmtpd-6.6.4p1.tar.gz

These both have broken logging:

https://www.opensmtpd.org/archives/opensmtpd-6.7.0p1.tar.gz
https://github.com/OpenSMTPD/OpenSMTPD/archive/6.7.0p1.tar.gz

**Comment by whataboutpereira** [comment]
I did some more testing the other day but without progress. I was thinking maybe the OpenBSD compat layer cleanup is now omitting something that works differently in CentOS compared to a previously overwritten function. But I'm grasping at straws here. :)

**Comment by whataboutpereira** [comment]
@jdelic Did you experience the same issue and also on CentOS/Fedora or another system?

**Comment by whataboutpereira** [comment]
I now tried renaming "pony express" to "pony-express" which resulted in:

```Jun 15 12:12:18 centos8 y-express[32587]: 2483455c63fb507c mta connected```

**Comment by harridu** [comment]
I am not using systemd but sysv init, and yet I have the same problem. AFAICT systemd is not to blame here.

**Comment by harridu** [comment]
Maybe you should consider to hard-wire the ident parameter to "smtpd" in the call to openlog (log.c, maybe others)?

**Comment by whataboutpereira** [comment]
I see something has changed in smtpd.c main() concerning __progname and setproctitle, but I'm unsure if it might be related.

**Comment by whataboutpereira** [comment]
Any ideas?

**Comment by whataboutpereira** [comment]
I suspect OpenBSD 6.8 will be out in the coming months. Any way to bring this issue to spotlight? Still using my own 6.6.4p1 on CentOS 8 due to this issue.

**Comment by greecemunky** [comment]
I think this issue was introduced in commit https://github.com/OpenSMTPD/OpenSMTPD/commit/34671dfe3ffc22a20d0032ceea5f96bc979ad917.  This is the first commit I've tested that exhibits this behaviour.

Logging works as expected when building against the commit just prior (https://github.com/OpenSMTPD/OpenSMTPD/commit/87a53a0b6fc41c0841720e0dd34aed4f45b997b6).

**Comment by greecemunky** [comment]
It may have to do with the new PROGNAME handling.  Working with commit https://github.com/OpenSMTPD/OpenSMTPD/commit/34671dfe3ffc22a20d0032ceea5f96bc979ad917 in CentOS 8, I can get it to act as it did before by making changes to the following files (virtually undoing some the changes this commit introduced):

- openbsd-compat/Makefile.am
  - comment out line `if NEED_PROGNAME` and corresponding `endif`, ensuring progname.c is always included
- smtpd/smtpd.c and smtpd/smtpctl.c
  - move line `__progname = ssh_get_progname(argv[0]);` outside the if block, so it always runs

I'm not suggesting this is the fix (to be honest I'm not exactly sure what is going on there), but it's my findings based on trial and error.

I _think_ this commit also introduced a function naming discrepancy, where function `ssh_get_progname` was renamed to `get_progname` (file openbsd-compat/progname.c), however references to it (found in smtpd/smtpd.c and smtpd/smtpctl.c) still call `ssh_get_progname`.  If you want to play with the above in your own environment, you'll need to take it into account (easiest to change the function's name back to `ssh_get_progname` in openbsd-compat/progname.c).

**Comment by whataboutpereira** [comment]
I did some further testing and I'm now also fairly certain commit https://github.com/OpenSMTPD/OpenSMTPD/commit/34671dfe3ffc22a20d0032ceea5f96bc979ad917 needs to be rolled back as get_progname (or ssh_get_progname - there are 2 versions in the code now) is needed even with libc __progname.

**Comment by whataboutpereira** [comment]
This is the minimum required to get syslog messages working again like they used to: https://github.com/OpenSMTPD/OpenSMTPD/pull/1094

**Comment by poolpOrg** [comment]
I will work on fixing this before issueing the portable 6.8.0p1 release

**Comment by poolpOrg** [comment]
Can you check if the issue still exists with the latest master commit ?

I need both !systemd and systemd systems to check that the fix is enough.

**Comment by whataboutpereira** [comment]
> Can you check if the issue still exists with the latest master commit ?
> 
> I need both !systemd and systemd systems to check that the fix is enough.

I tested the version posted to the mailing list and it looks fine now. Thanks!
