### ISSUE TITLE
TLSv1.3 client cipherlist breaks connectivity

### ISSUE THREAD

**Issue by freswa** [OpenSMTPD/OpenSMTPD#1060]
Since libressl `3.1.0` TLSv1.3 is enabled by default on the client side.
When using the option `smtp ciphers` with TLS 1.2 ciphers, any client connection to another server breaks with errors like
```
283b39764f0a208c mta error reason=IO Error: error:1404B410:SSL routines:ST_CONNECT:sslv3 alert handshake failure
```
Disabling `smtp ciphers` completely resolves the issue. I tried to add the TLSv1.3 ciphers (according to OpenSSL) to the list with no luck.

How can one specify the `smtp ciphers` without breaking TLSv1.3 compatibility?

**Comment by 4a6f656c** [comment]
You can specify `TLSv1.3` to include all TLSv1.3 cipher suites, or the names listed in:

```$ openssl ciphers -v TLSv1.3
AEAD-AES256-GCM-SHA384  TLSv1.3 Kx=TLSv1.3  Au=TLSv1.3 Enc=AESGCM(256) Mac=AEAD
AEAD-CHACHA20-POLY1305-SHA256 TLSv1.3 Kx=TLSv1.3  Au=TLSv1.3 Enc=ChaCha20-Poly1305 Mac=AEAD
AEAD-AES128-GCM-SHA256  TLSv1.3 Kx=TLSv1.3  Au=TLSv1.3 Enc=AESGCM(128) Mac=AEAD
```

FWIW this will be improved in the LibreSSL 3.1.1 release - there are aliases included for the OpenSSL/RFC names and if you do not explicitly modify TLSv1.3 cipher suites, they're automatically included in addition to your cipher suite string.

**Comment by freswa** [comment]
Thanks
