### ISSUE TITLE
part of build instructions doesn't work

### ISSUE THREAD

**Issue by Dravion** [OpenSMTPD/OpenSMTPD#1064]
The command

git clone -b portable git://github.com/OpenSMTPD/OpenSMTPD.git opensmtpd

Results in Error:
 git clone -b portable git://github.com/OpenSMTPD/OpenSMTPD.git opensmtpd
Cloning into 'opensmtpd'...
fatal: Remote branch portable not found in upstream origin

Did i something wrong?

**Comment by poolpOrg** [comment]
hellow,

you didn't do something wrong, branch portable became master a few days ago and I forgot to update the README accordingly, this is fixed now.

**Comment by Dravion** [comment]
Oh, good to know.
Thanks!
