### ISSUE TITLE
do_encrypt adds extra argument and causes encrypt to fail

### ISSUE THREAD

**Issue by Kimplul** [OpenSMTPD/OpenSMTPD#1069]
If I try calling 
```smtpctl encrypt *any string*``` 
I get the error
 ```usage: encrypt <string>```

I dug around and found out that ```do_encrypt``` in ```usr.sbin/smtpd/smtpctrl.c``` calls ```encrypt``` with 
```execl(PATH_ENCRYPT, "encrypt", "--", p, (char *)NULL);```
 but ```contrib/libexec/encrypt.c``` only takes one argument, and adding ```--``` as an argument in front of the string to be encrypted causes the error.

Is there a reason for why the two dashes were added and should ```encrypt.c``` or ```smptctrl.c``` be changed?

**Comment by studentiks** [comment]
Doing `echo -n "my_password" | smtpctl encrypt` outputs hash of "--" instead of "my_password". Workaround (in archlinux) is to use `echo -n "my_password" | /usr/lib/smtpd/opensmtpd/encrypt`

**Comment by ssartor** [comment]
Does not look like this fix was included in the latest portable version (6.7.1p1)

**Comment by gearnode** [comment]
While the patch was release, on FreeBSD you can use:
```
echo "mypassword" | /usr/local/libexec/opensmtpd/encrypt
```

**Comment by poolpOrg** [comment]
The fix was merged and will be part of the upcoming 6.8.0p1 release
