### ISSUE TITLE
Fails to build from source on Mac OS X 10.15.6

### ISSUE THREAD

**Issue by ryanakca** [OpenSMTPD/OpenSMTPD#1079]
The current HEAD `1bcf247e4a0bef00ea3c4c8e8e9c5343bf2999a7` fails to build from source on Mac OS X 10.15.6:

```
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in openbsd-compat
make[2]: Nothing to be done for `all'.
Making all in mk
Making all in smtpd
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../usr.sbin/smtpd -I../../openbsd-compat -I../../openbsd-compat/err_h -I../../openbsd-compat/paths_h -I../../openbsd-compat/libasr -I. -I/opt/local/include -I/opt/local/include  -DSMTPD_CONFDIR=\"/etc/mail\" -DPATH_CHROOT=\"/var/empty\" -DPATH_SMTPCTL=\"/opt/local/sbin/smtpctl\" -DPATH_MAILLOCAL=\"/opt/local/libexec/opensmtpd/mail.local\" -DPATH_MAKEMAP=\"/opt/local/sbin/makemap\" -DPATH_LIBEXEC=\"/opt/local/libexec/opensmtpd\" -DHAVE_CONFIG_H -DIO_TLS -DCA_FILE=\"/etc/ssl/cert.pem\" -g -O2  -Qunused-arguments -Wunknown-warning-option -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset  -D_GNU_SOURCE -DNEED_EVENT_ASR_RUN -c -o ../../usr.sbin/smtpd/smtpd-parse.o `test -f '../../usr.sbin/smtpd/parse.c' || echo './'`../../usr.sbin/smtpd/parse.c
../../usr.sbin/smtpd/parse.y:201:13: error: typedef redefinition with different types ('int' vs 'struct YYSTYPE')
typedef int YYSTYPE;
            ^
../../usr.sbin/smtpd/parse.y:178:3: note: previous definition is here
} YYSTYPE;
  ^
1 error generated.
make[3]: *** [../../usr.sbin/smtpd/smtpd-parse.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I am using macports to provide libevent and openssl. `configure` was invoked as:
`./configure --prefix=/opt/local --with-libevent=/opt/local --with-libssl=/opt/local --with-gnu-ld --sysconfdir=/etc/mail`

**Comment by ryanakca** [comment]
It turns out that the built-in version of bison (2.3) is 14 years old and installing a modern version of bison gets around the above errors. The next place where opensmtpd FTBFS is:

```
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in openbsd-compat
make[2]: Nothing to be done for `all'.
Making all in mk
Making all in smtpd
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../usr.sbin/smtpd -I../../openbsd-compat -I../../openbsd-compat/err_h -I../../openbsd-compat/paths_h -I../../openbsd-compat/libasr -I. -I/opt/local/include -I/opt/local/include  -DSMTPD_CONFDIR=\"/etc/mail\" -DPATH_CHROOT=\"/var/empty\" -DPATH_SMTPCTL=\"/opt/local/sbin/smtpctl\" -DPATH_MAILLOCAL=\"/opt/local/libexec/opensmtpd/mail.local\" -DPATH_MAKEMAP=\"/opt/local/sbin/makemap\" -DPATH_LIBEXEC=\"/opt/local/libexec/opensmtpd\" -DHAVE_CONFIG_H -DIO_TLS -DCA_FILE=\"/etc/ssl/cert.pem\" -g -O2  -Qunused-arguments -Wunknown-warning-option -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset  -D_GNU_SOURCE -DNEED_EVENT_ASR_RUN -c -o ../../usr.sbin/smtpd/smtpd-smtpd.o `test -f '../../usr.sbin/smtpd/smtpd.c' || echo './'`../../usr.sbin/smtpd/smtpd.c
../../usr.sbin/smtpd/smtpd.c:673:6: error: implicit declaration of function 'RAND_status' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (RAND_status() != 1)
            ^
../../usr.sbin/smtpd/smtpd.c:746:8: warning: 'daemon' is deprecated: first deprecated in macOS 10.5 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
                        if (daemon(0, 0) == -1)
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:292:6: note: 'daemon' has been explicitly marked deprecated here
int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
../../usr.sbin/smtpd/smtpd.c:919:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
../../usr.sbin/smtpd/smtpd.c:1045:2: warning: variable 'pp' is used uninitialized whenever switch default is taken [-Wsometimes-uninitialized]
        default:
        ^~~~~~~
../../usr.sbin/smtpd/smtpd.c:1049:7: note: uninitialized use occurs here
        if (*pp)
             ^~
../../usr.sbin/smtpd/smtpd.c:1018:23: note: initialize the variable 'pp' to silence this warning
        struct mproc *p, **pp;
                             ^
                              = NULL
3 warnings and 1 error generated.
make[3]: *** [../../usr.sbin/smtpd/smtpd-smtpd.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by gearnode** [comment]
The issue should be fixed with the #1098

**Comment by poolpOrg** [comment]
fix merged

**Comment by unbeatable-101** [comment]
> The current HEAD `1bcf247e4a0bef00ea3c4c8e8e9c5343bf2999a7` fails to build from source on Mac OS X 10.15.6:
> 
> ```
> /Library/Developer/CommandLineTools/usr/bin/make  all-recursive
> Making all in openbsd-compat
> make[2]: Nothing to be done for `all'.
> Making all in mk
> Making all in smtpd
> gcc -DHAVE_CONFIG_H -I. -I../..  -I../../usr.sbin/smtpd -I../../openbsd-compat -I../../openbsd-compat/err_h -I../../openbsd-compat/paths_h -I../../openbsd-compat/libasr -I. -I/opt/local/include -I/opt/local/include  -DSMTPD_CONFDIR=\"/etc/mail\" -DPATH_CHROOT=\"/var/empty\" -DPATH_SMTPCTL=\"/opt/local/sbin/smtpctl\" -DPATH_MAILLOCAL=\"/opt/local/libexec/opensmtpd/mail.local\" -DPATH_MAKEMAP=\"/opt/local/sbin/makemap\" -DPATH_LIBEXEC=\"/opt/local/libexec/opensmtpd\" -DHAVE_CONFIG_H -DIO_TLS -DCA_FILE=\"/etc/ssl/cert.pem\" -g -O2  -Qunused-arguments -Wunknown-warning-option -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset  -D_GNU_SOURCE -DNEED_EVENT_ASR_RUN -c -o ../../usr.sbin/smtpd/smtpd-parse.o `test -f '../../usr.sbin/smtpd/parse.c' || echo './'`../../usr.sbin/smtpd/parse.c
> ../../usr.sbin/smtpd/parse.y:201:13: error: typedef redefinition with different types ('int' vs 'struct YYSTYPE')
> typedef int YYSTYPE;
>             ^
> ../../usr.sbin/smtpd/parse.y:178:3: note: previous definition is here
> } YYSTYPE;
>   ^
> 1 error generated.
> make[3]: *** [../../usr.sbin/smtpd/smtpd-parse.o] Error 1
> make[2]: *** [all-recursive] Error 1
> make[1]: *** [all-recursive] Error 1
> make: *** [all] Error 2
> ```
> 
> I am using macports to provide libevent and openssl. `configure` was invoked as: `./configure --prefix=/opt/local --with-libevent=/opt/local --with-libssl=/opt/local --with-gnu-ld --sysconfdir=/etc/mail`

This error is happening to me on macOS 12.1. `configure` was invoked with `./configure --with-libevent=/opt/homebrew`
