### ISSUE TITLE
Updating OpenSMTPD from 6.6.4p1 to 6.7.1p1 makes it reject email with `ORCPT=rfc822;root`

### ISSUE THREAD

**Issue by Ekleog** [OpenSMTPD/OpenSMTPD#1084]
The log message is the following:
`smtp failed-command command="RCPT TO:<[censored]> ORCPT=rfc822;root" result="553 ORCPT address syntax error"`
and the bounce message is:
```
<[censored]> (expanded from <root>): host
    grym.ekleog.org[94.23.42.210] said: 553 ORCPT address syntax error (in
    reply to RCPT TO command)
```

Emails coming from the same mail server, to the same email address, and with the same configuration of my OpenSMTPD server, were accepted when I was running the 6.6.4p1. To the best of my knowledge, the sending server did not change at the time this issue started happening.

Said sending email server is running postfix, which may be customized for ORCPT but I'd be surprised if we ever did that.

RFC3461 states:
```
   Ideally, the "xtext" portion of the original-recipient-address should
   contain, in encoded form, the same sequence of characters that the
   sender used to specify the recipient.  However, for a message
   gatewayed from an environment (such as X.400) in which a recipient
   address is not a simple string of printable characters, the
   representation of recipient address must be defined by a
   specification for gatewaying between DSNs and that environment.
```

As such, I'm thinking syntax-checking the ORCPT parameter may be an OpenSMTPD bug introduced between 6.6.4p1 and 6.7.1p1? Unfortunately, I didn't have much time to investigate more for now…

Either way, thank you for OpenSMTPD!

**Comment by Ekleog** [comment]
Here is an example telnet reproducer:
```
220 llwynog.ekleog.org ESMTP OpenSMTPD
EHLO test
250-llwynog.ekleog.org Hello test [::1], pleased to meet you
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-SIZE 36700160
250-DSN
250 HELP
MAIL FROM:<foo@bar.com>
250 2.0.0 Ok
RCPT TO:<test@example.com> ORCPT=rfc822;root
553 ORCPT address syntax error
```

Given the `DSN` extension given, I think the `ORCPT` keyword is supposed to be handled.

It sounds to me like OpenSMTPD interprets the appendix of RFC3461 way too strictly: it says
```
        RFC822 mailbox addresses are generally expected to be of the
        form

                [route] addr-spec

        where "route" and "addr-spec" are defined in [2], and the
        "domain" portions of both "route" and "addr-spec" are fully-
        qualified domain names that are registered in the DNS.  However,
        an MTA MUST NOT modify an address obtained from the message
        envelope to force it to conform to syntax rules.
```
and OpenSMTPD probably understands the “However” part of it differently than I/postfix do. (and also in a way that's hard to match with the quote of RFC3461 that I provided in my message above)

Here, the program generating such emails is a postfix instance receiving email to root, which then has an alias for root pointing to an email that's handled by an OpenSMTPD server. As such, I don't think it's niche enough to warrant rejecting the message at SMTP time, especially as it's (probably) allowed by the RFC.

What do you think?

**Comment by poolpOrg** [comment]
22:20 < umaxx> __gilles: I believe you can close github #1084 I committed the fix in -current

**Comment by Ekleog** [comment]
Great, thank you!
