### ISSUE TITLE
Feature request: argon2[i/d/id] password hash scheme

### ISSUE THREAD

**Issue by freswa** [OpenSMTPD/OpenSMTPD#1097]
Argon2 is the winner of password hashing competition held at July 2015.
Though it doesn't seem to be support by OpenSMTPD yet.

The official implementation is available here: https://github.com/P-H-C/phc-winner-argon2

**Comment by poolpOrg** [comment]
OpenSMTPD doesn't implement hashing itself but relies on the host-provided `crypt()` function which may or may not provide argon2 as its beyond the scope of the daemon. If OpenSMTPD were to implement argon2 locally, the credentials could not be validated by `crypt()` and would require a custom validation function which would make argon2 a special case compared to all other hashing functions.

There are work-arounds if you absolutely need argon2 but a special case is likely not going to happen.
