### ISSUE TITLE
Macro not expanded in smarthost string

### ISSUE THREAD

**Issue by pacien** [OpenSMTPD/OpenSMTPD#1101]
I have something like the following in my configuration:

```
main_server = 1.2.3.4
# [...]
action "relay_to_main" relay host smtp://$main_server
```

The macro doesn't seem to be expanded in the smarthost string; the following shows up in the logs:

```
warn: Failed to parse smarthost smtp://$main_server
```

I'm running OpenSMTPD version 6.7.1p1 on NixOS.

**Comment by poolpOrg** [comment]
can you try the following instead ?

    main_server = smtp://1.2.3.4
    
    action "relay_to_main" relay host $main_server

OpenSMTPD uses the same parser as other OpenBSD daemons and I don't see how it could expand macros that are embedded within a string, I doubt this works on any OpenBSD daemon.

**Comment by pacien** [comment]
An issue is that I'm also using this macro in a match rule:

```
match rule from src $main_server […]
```

**Comment by poolpOrg** [comment]
Maybe you need two macros then, I don't think you can achieve what you want with just one macro

**Comment by poolpOrg** [comment]
I confirm this won't be changed:

1- it is a behaviour shared with all OpenBSD daemons, it won't diverge in OpenSMTPD
2- it also would lead to ambiguities as $ may be valid in a string (think credentials)

The fix is to use two macros
