### ISSUE TITLE
opensmtpd-filter-dkimsign on debian

### ISSUE THREAD

**Issue by bchtrue** [OpenSMTPD/OpenSMTPD#1107]
Hello, I'm on debian 10 (buster). 
Packages from buster-backports: opensmtpd and opensmtpd-extras 

Opensmtpd immediately exit with the following code in config: 

```
filter "dkimsign" proc-exec "filter-dkimsign -d server.com -s mylabel \
    -k /etc/mail/dkim/server.com-private.key" user _dkimsign group _dkimsign
```

```
Dec 10 20:08:48 server.com systemd[1]: Starting OpenSMTPD SMTP server...
Dec 10 20:08:48 server.com smtpd[12738]: info: OpenSMTPD 6.6.4p1 starting
Dec 10 20:08:48 server.com systemd[1]: Started OpenSMTPD SMTP server.
Dec 10 20:08:48 server.com systemd[1]: opensmtpd.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 20:08:48 server.com systemd[1]: opensmtpd.service: Failed with result 'exit-code'.

```

Is this mean that my opensmtpd-extras does not have filter-dkimsign? At least I can't user it from term as `filter-dkimsign`, but not sure that it must be available at terminal. Docs say nothing about that. 
Also I can't understand what is user _dkimsign group _dkimsign ? Must I create this user on the system and change ownersip of keys to this user and group? 

Sorry, lack of documentations. Don't know what to do to setup DKIM.

Thanks

**Comment by poolpOrg** [comment]
Hello,

You should really contact the author of the filter directly, the filter is not part of the project and I don't know if he even reads this issue tracker.

Can't help myself as I don't use or know that code, I rely on rspamd for DKIM signing.

Gilles

**Comment by bchtrue** [comment]
@poolpOrg thanks. I will also try to setup rspamd. You use it without rspamd addon? 

Hope that one day DKIM will be integrated into main code of opensmptd.

**Comment by poolpOrg** [comment]
No, I use with the addon I wrote 😄

**Comment by poolpOrg** [comment]
To contact the author of filter-dkim-sign: martijn@ openbsd.org

His repositories as not on GitHub, he self-hosts them: http://imperialat.at/dev/
