### ISSUE TITLE
"smtpctl encrypt" not taking any input on Alpine

### ISSUE THREAD

**Issue by UniqueActive** [OpenSMTPD/OpenSMTPD#1125]
Hello,
I am trying to set up OpenSMTPD on Alpine and could not get it to accept the hashes generated by "doveadm pw -s BLF-CRYPT" so I wanted to use "smtpctl encrypt", but I am facing the following issue:

When calling "smtpctl encrypt" with no arguments, it spits out a random hash without me providing any input or even having the chance to. I do not get prompted to enter something like on OpenBSD.

When calling it like "smtpctl encrypt 'text'" or "smtpctl encrypt text", it returns "usage: encrypt \<string\>"

My version is OpenSMTPD 6.7.1p1 and I tried this in the ash and bash shells. Any help would be appreciated as I have no clue what the issue may be!

**Comment by ArchangeGabriel** [comment]
Duplicate of https://github.com/OpenSMTPD/OpenSMTPD/issues/1069, fixed by https://github.com/OpenSMTPD/OpenSMTPD/pull/1073 which was released as part of 6.8.0p1.

**Comment by UniqueActive** [comment]
I apologize, I did not see that while searching the issues! Thank you!
