### ISSUE TITLE
Setting port only for relays

### ISSUE THREAD

**Issue by Nisto** [OpenSMTPD/OpenSMTPD#1128]
Not sure if I'm going about doing this the right way to be honest, or if it can even be achieved. I'm hoping to be able to set up a very simple "no-reply" (i.e. outbound-only) mailer, without the need for an external SMTP server such as Gmail.

However, currently, it seems you can't specify a port for relays unless you also explicitly specify a host (thus also skipping MX lookups). So, unless I use an external SMTP host for relays, I'm stuck with port 25, which is blocked by my ISP.

I've got OpenBSD running in a VM which isn't visible on the Internet (no proper domain). I've verified that I can at least send mails through ports 465 and 587 via Gmail. Right now, my smtpd.conf looks like this:

```
table aliases file:/etc/mail/aliases

listen on socket
listen on lo0

action "local_mail" mbox alias <aliases>
action "outbound" relay

match from local for local action "local_mail"
match from local for any action "outbound"
```

When running `echo 'test' | mail -s 'test' name@example.com ; tail -f /var/log/maillog` I'm seeing:
`mta connecting address=smtp://x.x.x.x:25 host=x`

Changing `action "outbound" relay` to `action "outbound" relay tls` at least changes the protocol:
`mta connecting address=smtp+tls://x.x.x.x:25 host=x`

But as you can see, it still connects via port 25. This is about as close as I've managed to get to changing the port though, I guess.

Is there any way to connect via a different port, like 465 or 587? Or could it be implemented?

**Comment by ArchangeGabriel** [comment]
So just in case anyone else stumble upon this: no, this is not possible, you cannot chose what ports other servers in the world are listening to. And that is port 25.
