### ISSUE TITLE
Mail forward from Outlook results in "421 server internal error"

### ISSUE THREAD

**Issue by CyberTailor** [OpenSMTPD/OpenSMTPD#1143]
Mail delivery from all other providers works fine.

Trace log: https://sysrq.in/tmp/smtpd.log

**Comment by whataboutpereira** [comment]
Check your Rspamd logs - "421 server internal error" is a tempfail from filter-rspamd.

https://github.com/poolpOrg/filter-rspamd/blob/0f0aeabb34a72c64d5898d0eb9c2cf40fdd219cc/filter-rspamd.go#L249

**Comment by CyberTailor** [comment]
This is caused by rspamd segfaults, indeed
