### ISSUE TITLE
would OpenSMTPD be a right choice for single-user MTA mail spool on Android?

### ISSUE THREAD

**Issue by cnst** [OpenSMTPD/OpenSMTPD#1145]
I'm looking into https://github.com/termux/termux-packages/issues/7633 -- adding any mail spool package into single-user Termux on unrooted Android.

I'm curious on your thoughts of what would it take to get OpenSMTPD working on Android without root privilidges, in single-user mode, entirely for the purposes of doing mail spooling, without acting as an SMTP server for the outside world at all, and without delivering local mail at all, either.  (Smarthost functionality not required -- in fact, it's expressly required that it works without having to configure anything as a user, other than the `From:` and `To:` fields in a mail client like `mutt`.)

I imagine the install scripts would have to be redone, and some priviledge separation taken care of.  Would any changes to make something like this work be welcome back upstream to OpenSMTPD, or should they all be done as local patches just within the termux pkg system?

Is there any easy way to get just the mail spooling out of OpenSMTPD, without the server and the local delivery bits?  E.g., just the `mta` subsystem for `schedule remote transfers`, without `smtp` and without `mda` subsystems?  I've looked into [`sendmail(8)`](http://mdoc.su/o/sendmail.8) and `smtpd(8)` manual pages, but nothing stood out, other than the `-P` option that describes pausing one of the 3 subsystems mentioned above.

Would it make sense to have an `mta`-only version of OpenSMTPD on your side, for example?

Is the `mta` subsystem the only thing that's required to accept mail locally from mutt, and perform mail spooling, MX lookup, and delivery attempts to remote hosts, both directly and maybe also through a smarthost if desired?  Can the other two subsystems be ripped out easily and/or at all?

Is there any other package you could recommend for this task instead?  It seems like the `msmtp` package is often a suggestion, but it doesn't seem to do any spooling, doesn't seem to be capable of MX lookup, and requires manual smarthost configuration for each installation.

**Comment by poolpOrg** [comment]
answered on the mailing list, sorry
