### ISSUE TITLE
NOOP doesn't ignore the parameter string (RFC non-conformance)

### ISSUE THREAD

**Issue by sjbronner** [OpenSMTPD/OpenSMTPD#1148]
RFC 5321 contains the following text about NOOP:

> 4.1.1.9.  NOOP (NOOP)
> 
>    If a parameter string is specified, servers SHOULD ignore it.

OpenSMTPD 6.8.0p2 responds as follows:

```
 % nc 127.0.0.1 25
220 tucson ESMTP OpenSMTPD
noop
250 2.0.0 Ok
noop abc
500 5.5.4 Invalid command arguments: command does not accept arguments.
```

The key word SHOULD is defined as follows in RFC 2119:

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there
> may exist valid reasons in particular circumstances to ignore a
> particular item, but the full implications must be understood and
> carefully weighed before choosing a different course.

It seems to me that the case for choosing a different course is most likely not given with the parameter string to NOOP. And therefore I believe that its implementation is non-conforming and am making the case to modify it. If this idea meets with approval, I would be happy to work on this and submit a pull request.

**Comment by poolpOrg** [comment]
Hello,

Good catch, that was overseen.

Feel free to submit a diff, thanks
