### ISSUE TITLE
RSET not allowed at this point (RFC non-conformance)

### ISSUE THREAD

**Issue by sjbronner** [OpenSMTPD/OpenSMTPD#1149]
RFC 5321 contais the following statements about RSET:

> 4.1.1.5.  RESET (RSET)
>
>    A reset command may be issued by the client at any time.  It is effectively
>    equivalent to a NOOP (i.e., it has no effect) if issued immediately after
>    EHLO, before EHLO is issued in the session, after an end of data indicator
>    has been sent and acknowledged, or immediately before a QUIT.

> 4.1.4.  Order of Commands
>
>    The NOOP, HELP, EXPN, VRFY, and RSET commands can be used at any time
>    during a session, or without previously initializing a session.  SMTP
>    servers SHOULD process these normally (that is, not return a 503
>    code) even if no EHLO command has yet been received; clients SHOULD
>    open a session with EHLO before sending these commands.

OpenSMTPD 6.8.0p2 responds as follows:

```
% nc 127.0.0.1 25
220 tucson ESMTP OpenSMTPD
rset
503 5.5.1 Invalid command: Command not allowed at this point.
```

The key word SHOULD is defined as follows in RFC 2119:

> SHOULD  This word, or the adjective "RECOMMENDED", mean that there
> may exist valid reasons in particular circumstances to ignore a
> particular item, but the full implications must be understood and
> carefully weighed before choosing a different course.

It seems to me that the case for choosing a different course is most likely not
given with RSET. And therefore I believe that rejecting the command at any time
is non-conforming and am making the case to modify it. If this idea meets with
approval, I would be happy to work on this and submit a pull request.

**Comment by poolpOrg** [comment]
Same as #1147 really as the two were worked together.

Unless there is real-world case of this breaking a legitimate MTA or client, this prevents attackers from playing state games with RSET/EHLO in an attempt to maintain a session active indefinitely.

Not closing so you can elaborate if this solves an issue you faced in practice.

**Comment by sjbronner** [comment]
Closing with #1147.
