### ISSUE TITLE
syntax error when adding protocols or ciphers

### ISSUE THREAD

**Issue by lifeofguenter** [OpenSMTPD/OpenSMTPD#1165]
When adding `protocols "secure" ciphers "secure"` I get a "syntax error"

**Comment by ArchangeGabriel** [comment]
What distro are you on? They are not available on Linux yet, only BSD.

**Comment by lifeofguenter** [comment]
Yes it was on Linux, closing for now then.

**Comment by ArchangeGabriel** [comment]
See https://github.com/OpenSMTPD/OpenSMTPD/discussions/1152 for why it’s not available.
