### ISSUE TITLE
Disable SSL permission check

### ISSUE THREAD

**Issue by Trumeet** [OpenSMTPD/OpenSMTPD#1167]
I'm using acme.sh to automatically renew my OpenSMTPd SSL certs. I run it in a separate user and group (acme:acme) to avoid running it as root. Therefore, in order to enable it writing to cert files, I set the public key to `acme:acme 664` and the private key to `acme:acme 660`. However, OpenSMTPd hard coded a check to enforce the files to be owned by root and they must not be group writable, which makes acme impossible to work. I would like to have a choice for that.

**Comment by ArchangeGabriel** [comment]
This is bad practice, and OpenSMTPD is right to not allow it. You don’t need to access the private key to renew a certificate, only a CSR.

I don’t know acme.sh, but I use acme-tiny with this script (started from a systemd timer and running as `acme:acme`):
```
#!/usr/bin/sh

for domain in $(find /etc/acme -type d -not -path /etc/acme); do
    echo "Checking certificate expiry date for ${domain##*/}…"
    openssl x509 -noout -checkend 2592000 -in ${domain}/fullchain.pem > /dev/null 2>&1 && echo "Certificate not expiring within 30 days, skipping." && continue
    echo "Renewing certificate for ${domain##*/}…"
    /usr/bin/acme-tiny --account-key /etc/acme/accountkey.pem --csr ${domain}/csr.pem --acme-dir /var/lib/acme/ > ${domain}/fullchain_new.pem || exit
done
```
Then I have a `ExecStartPost`, handled by systemd itself (! prefixed) that basically does this:
```
#!/usr/bin/sh
for domain in $(find /etc/acme -type d -not -path /etc/acme); do
    if [ -f ${domain}/fullchain_new.pem ]; then # The certificate was renewed
        echo "Replacing certificate and fixing permissions for ${domain##*/}…"
        mv ${domain}/fullchain{_new,}.pem
        chown root:root ${domain}/fullchain.pem
        chmod 444 ${domain}/fullchain.pem
        # Splitting for some needs
        FULLCHAIN=$(<${domain}/fullchain.pem)
        echo "${FULLCHAIN%%-----END CERTIFICATE-----*}-----END CERTIFICATE-----" > ${domain}/cert.pem
        echo -e "${FULLCHAIN#*-----END CERTIFICATE-----}" | sed '/./,$!d' > ${domain}/chain.pem
    fi
done
```

I can provide the full instructions (initial set-up, systemd service and timer, etc.) if wanted.

**Comment by Trumeet** [comment]
@ArchangeGabriel

acme.sh has the ability to automatically write to the installed cert and private key files and execute an arbitrary command to reload the related services. I'd not want to manually chown and chmod the certs every time by myself.

**Comment by ArchangeGabriel** [comment]
I’m not doing it manually of course. As I said, everything runs automatically on a systemd timer (including reloading affected services that I did not show above, and OCSP priming if you use nginx and OCSP staple).

The tool getting the certificate should not be allowed to touch the private key, EOL.

**Comment by Trumeet** [comment]
OK, I'll have a try on that approach. Anyways, I'd still like to have the choice.
