### ISSUE TITLE
bootstrap stopped at aclocal on FreeBSD13

### ISSUE THREAD

**Issue by Tomon613** [OpenSMTPD/OpenSMTPD#1169]
I'm trying to build opensmtpd from latest source on FreeBSD 13.
Running bootstrap, and stopped at aclocal with the below message:

```
$ ./bootstrap
+ test yes '=' yes
+ libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
+ test -n '' -a ! '' '=' . -a -f ltmain.sh
+ aclocal-1.16 -I m4
ld-elf.so.1: /usr/local/lib/perl5/5.32/mach/CORE/libperl.so.5.32: Undefined symbol "strerror_l@FBSD_1.6"
Use of uninitialized value $macro in exists at /usr/local/bin/aclocal-1.16 line 820, <GEN91> line 454.
$
```
Pleas tell me how to fix it?

**Comment by Tomon613** [comment]
Bootstrap went well on upgraded kernel ( recompiled kernel), thank you.

**Comment by orbea** [comment]
@omar-polo This likely works since PR https://github.com/OpenSMTPD/OpenSMTPD/pull/1204 was merged?

**Comment by omar-polo** [comment]
@orbea I really doubt it.  I'm not knowledgeable about perl, but this smells like forgetting to rebuild perl modules after a perl update or some other kind of corruption.

I've briefly tested on FreeBSD 13.2 and `./bootstrap && ./configure && make` work for me.  are you still having issues @Tomon613 ?

**Comment by omar-polo** [comment]
Since it doesn't seem to be specific to OpenSMTPD (judging from the ld.so on libperl) I'll close this for now.  @Tomon613 feel free to re-open in case.

Thanks!
