### ISSUE TITLE
NO TLS error: Cannot connect from outlook 365 (current version) client

### ISSUE THREAD

**Issue by modigithub** [OpenSMTPD/OpenSMTPD#1187]
hi,
i cannot open my Mailserver from my local mail outlook client.
The connectiondata are the following:
![image](https://user-images.githubusercontent.com/108171635/198825715-884dfc1d-236e-4b06-af02-5711dace5502.png)

the result is:
![image](https://user-images.githubusercontent.com/108171635/198825738-b6e5575b-4ed6-40d0-b503-91a4a7476f0c.png)

I tryed everything. But nothing worked. I think i missconfigured something but i cant see what. The log is allways the same:
![image](https://user-images.githubusercontent.com/108171635/198825815-93969542-2fd6-47e5-b79e-5474c9cf91de.png)

My dovecot config are the following:
![image](https://user-images.githubusercontent.com/108171635/198825836-ed455095-e956-497c-8978-2de421fbebdc.png)

and my smtp settings:
![image](https://user-images.githubusercontent.com/108171635/198825853-d09fd710-4610-4209-a607-d30aa70ce0f4.png)

I also tryed thunderburd. But there are the same problems. Is there a problem with my Config or is there a problem with opensmtpd?

I try to connecto from an windows 10 outlook 365 and the server os is a debian 11.
The mailserver is running. I can receive mails and i can sent mails.

Thank you  for help

**Comment by whataboutpereira** [comment]
Maybe run smtpd with debug and/or tracing.

Similar error here:

https://www.mail-archive.com/misc@openbsd.org/msg174452.html

**Comment by modigithub** [comment]
hi, thank you but i know that page and i also debuged the smtp. I post my debug message:
![image](https://user-images.githubusercontent.com/108171635/198841559-3585991e-500b-457e-8902-0be02e6ac0e9.png)
![image](https://user-images.githubusercontent.com/108171635/198841573-c2d98124-b847-4dd0-b56b-225c54b5e685.png)
if i try to login the only message i got from the debug is the red marked one. Can anyone help me?

**Comment by modigithub** [comment]
i made further tests. And if i execute the   everything seems to be ok:
TLS1.2 and TLS1.3 are working. And on my local maschine tls1.2 is enabled
![image](https://user-images.githubusercontent.com/108171635/198864820-7e61d54f-b8bf-400e-852c-e5ee06bede08.png)
HERE IS THE CERTIFICATE.
![image](https://user-images.githubusercontent.com/108171635/198864771-1634e317-ed00-452b-8b9f-389df4598e92.png)

**Comment by idfake** [comment]
Have you tried relaxing tls options a bit?
`listen on egress tls pki "mail.xxx.de" protocols "all" ciphers "compat"`

**Comment by modigithub** [comment]
Thanks for all comments. After endless testing, I decided to rewrite the configuration again. I changed the pki name. Almost all documentation says that you can use the domain name here. This is probably not supported in debian. After replacing the name with something else, everything works.
![image](https://user-images.githubusercontent.com/108171635/200115968-f4abf410-4d25-48c4-9e34-a2a7b9a700b7.png)
