### ISSUE TITLE
smtpd crash when trying to login with username with | character

### ISSUE THREAD

**Issue by it-bsi** [OpenSMTPD/OpenSMTPD#1213]
Hi,

when someone tries to login with a username that has | character
filter-rspamd crashes and brings OpenSMTPD down. The server runs Debian
11 with the following packages:

opensmtpd				6.8.0p2-3
opensmtpd-filter-rspamd		0.1.7-1+b5
opensmtpd-filter-senderscore	0.1.1-2+b6

I have a small/medium sized install with ~60/70 users and ~4000
emails flowing each day. A lot of people try to login with random
usernames and passwords from outside, for example last night:

Jun 13 21:55:50 localhost smtpd[5097]: cddac380a03fb936 smtp connected address=ip host=host
Jun 13 21:55:50 localhost smtpd[5097]: cddac380a03fb936 smtp tls ciphers=TLSv1.2:ECDHE-ECDSA-AES256-GCM-SHA384:256
Jun 13 21:55:52 localhost smtpd[5097]: cddac380a03fb936 smtp authentication user=VBA|spilWHHtemplateteams result=permfail
Jun 13 21:55:52 localhost smtpd[5096]: rspamd: 2023/06/13 21:55:52 invalid input, shouldn't happen
Jun 13 21:55:52 localhost smtpd[5092]: warn: lost processor: rspamd exited abnormally
Jun 13 21:55:52 localhost smtpd[5092]: Exiting

Someone tried to login with username "VBA|spilWHHtemplateteams"
and OpenSMTPD went down. It crashes if username has | in it, an example
session with mailutils:

$ mailutils smtp
smtp> connect -tls localhost.localdomain 465
220 localhost.localdomain ESMTP OpenSMTPD
smtp> ehlo localhost
CAPA: 8BITMIME
CAPA: ENHANCEDSTATUSCODES
CAPA: SIZE 12582912
CAPA: DSN
CAPA: AUTH PLAIN LOGIN
CAPA: HELP
smtp> set username |
smtp> set password ciao
smtp> auth plain
selected authentication mechanism PLAIN
Error: Input/output error
smtp>

And the relative mail.log:

Jun 14 08:55:22 localhost smtpd[14173]: 57f6e3d1b3d99bd8 smtp connected address=ip host=host
Jun 14 08:55:22 localhost smtpd[14173]: 57f6e3d1b3d99bd8 smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
Jun 14 08:55:43 localhost smtpd[14173]: 57f6e3d1b3d99bd8 smtp authentication user=| result=permfail
Jun 14 08:55:43 localhost smtpd[14172]: rspamd: 2023/06/14 08:55:43 invalid input, shouldn't happen
Jun 14 08:55:43 localhost smtpd[14168]: warn: lost processor: rspamd exited abnormally
Jun 14 08:55:43 localhost smtpd[14168]: Exiting

A similar issue was solved here: [https://github.com/OpenSMTPD/OpenSMTPD/issues/1041](https://github.com/OpenSMTPD/OpenSMTPD/issues/1041)

That issue was for email addresses, this happens for usernames when
trying to login. If the issue is of the same type i think username and
result need to be swapped in the filters protocol as it was done for
email addresses:

[https://man.openbsd.org/smtpd-filters#link-auth](https://man.openbsd.org/smtpd-filters#link-auth)

**Comment by omar-polo** [comment]
@poolpOrg has released a new version of filter-rspamd which address the issue and can be used on existing versions of OpenSMTPD: https://github.com/poolpOrg/filter-rspamd/releases/tag/v0.1.8
