### ISSUE TITLE
`smtpd: load_pki_keys: failed to load key file` with letsencrypt

### ISSUE THREAD

**Issue by zilti** [OpenSMTPD/OpenSMTPD#1219]

**Comment by omar-polo** [comment]
leaving a comment mostly for the archive; the cert should be `0644` and the key `0600`, both owned by root.

OpenSMTPD itself takes *lots* of precautions.  It drops privileges as soon as possible, and the private keys are only loaded in a separate process which doesn't talk to the network at all.
