### ISSUE TITLE
Mail not sent from root

### ISSUE THREAD

**Issue by LiohMoeller** [OpenSMTPD/OpenSMTPD#1220]
I have set up OpenSMTPD to send mails locally and external mails over a relay.

When I log in to the server as user (e.g. myuser) and become root with sudo or su - and try to send an email, the sender address is always myuser@myhost.tld instead of root@myhost.tld

**Comment by LiohMoeller** [comment]
The issue is unrelated to OpenSMTP but defined by the default mail command, in this case mailx

**Comment by omar-polo** [comment]
Yep, for mail(1) I guess you need to use `-r myuser` or `-r myuser@myhost.tld`.

(leaving the comment mostly for the archive.)
