### ISSUE TITLE
opensmtpd.org is down (returns 404s)

### ISSUE THREAD

**Issue by law** [OpenSMTPD/OpenSMTPD#1221]
Terribly sorry for the possibly-OT 'bug report', but I don't know of a better avenue for things of this nature.  Apparently opensmtpd.org is down or misconfigured - it returns HTTP-404 for everything from the root (https://www.opensmtpd.org/) to your donations page (https://www.opensmtpd.org/donations.html) etc.

**Comment by poolpOrg** [comment]
Hello,

Can you reload ?

I was performing a server maintenance, it's over now

Gilles

**Comment by whataboutpereira** [comment]
Getting a 403 here atm.

**Comment by law** [comment]
Thanks so much for the quick response!  At the moment, the 404 has changed to '403 Forbidden'.

**Comment by poolpOrg** [comment]
Uh 🧐

![image](https://github.com/OpenSMTPD/OpenSMTPD/assets/895503/5a941751-008b-4020-929e-e30cccc1f121)

**Comment by law** [comment]
Ohhh, I don't think you have an HTTP->HTTPS 301-redirect set up.  For some reason I was hitting http (getting 403s, etc), but forcing to https gets the expected page.

**Comment by poolpOrg** [comment]
You're right, it should be fixed now, can you try again ?

I have switched from OpenBSD httpd to nginx and had to rewrite the config, this bit got lost.

If everything's fine, I'll let you close the issue, thanks !

**Comment by law** [comment]
bam, works like a champ.   Thanks so much!
