### ISSUE TITLE
7.4.0p0: man pages are installed in wrong location

### ISSUE THREAD

**Issue by kloczek** [OpenSMTPD/OpenSMTPD#1231]
Just found that update to latest version some man pages have been installed in wrong location
```console
error: Installed (but unpackaged) file(s) found:
   /usr/share/man/1/smtp.1
   /usr/share/man/5/aliases.5
   /usr/share/man/5/forward.5
   /usr/share/man/5/smtpd.conf.5
   /usr/share/man/5/table.5
   /usr/share/man/7/smtpd-filters.7
   /usr/share/man/8/makemap.8
   /usr/share/man/8/newaliases.8
   /usr/share/man/8/sendmail.8
   /usr/share/man/8/smtpctl.8
   /usr/share/man/8/smtpd.8
```
Looks like in all .am files can be substituted `s/\$\(mansubdir\)/man/`

**Comment by omar-polo** [comment]
It seems I broke this in ebea68918a994ddaa43bb1aac769bc086f52e2f2, `mansubdir` is no longer defined and so we end up with that weird install path.  As a temporary workaround I guess defining `mansubdir=man` in the environment before calling `make install` should work, but it's an ugly and this needs to be fixed.  I won't be able to fix it and cut a release before tomorrow evening (CEST.)

I'm not sure actually if we should support the variable `mansubdir` or just use man as you propose.  The various `mail.*` utilities don't respect this `mansubdir` knob and noone complained so far.

As a quick fix for the 7.4 release however it'd be better to just reintroduce that hunk in `configure.ac`.

**Comment by kloczek** [comment]
Putting in variable something which is const does not make to much sense ..
Other observation: all `*_man_*` like `dist_man_*` automake variables can be replaced by `man_MANS`. Simpler->better ..

**Comment by omar-polo** [comment]
@kloczek Heh, I know but it's not exactly that easy.  We inherited (from openssh-portable I believe) a mechanism to convert mandoc to plan old man, so I'm not sure we can 'just' rename those automake variables.  (I know because I wanted to simplify this...)

Now, how useful is this today I'm not sure.  I don't think it would be unreasonable to just install the mandoc man pages as is... but with a broken release, I prefer to just fix it in the most simple way, and posticipate these tweaks for the next release.

Anyway, thanks for reporting!  We'll release a p1 soon; in the meantime I've committed the `configure.ac` fix.

**Comment by kloczek** [comment]
`man_MANS` handles as well cat files.
Instead implementing custom man pages build/install frameworks rules .. way better is use what automake provides OOTB.

If it is necessary to generate some files all what needs to be done is add make '.1 .5 .7: <list_of_input_giles>` make rule and because man_MAN will find those missing files will execute exact filter.

That script theatrically van handle man , doc (whatever it is) and roff cat files  however nothing else in amutomake files i prepared to handle anything else than pian man.

**Comment by kloczek** [comment]
Oher thing is taha none of the modern Unixes uses currently man cat files (roff output with injected exact terminal tyle control characters).

**Comment by kloczek** [comment]
> @kloczek Heh, I know but it's not exactly that easy. We inherited (from openssh-portable I believe)

You must be looking on some very old version of openssh-portable source. In current tree https://anongit.mindrot.org/openssh.git/ are only man pages.

**Comment by omar-polo** [comment]
We inherited it from a rather old version of openssh-portable configure.ac, many years ago, along with other things.  Then they were never updated/sync'ed, until I tried to do a sweep and broke `mansubdir` :(

I agree with you however, I just wanted to mention an historic fact.  Would you mind to send a PR for this?  I'd be happy to review/merge it.  (Otherwise, no problem!  I'll add it to my TODO list)

Thanks!

**Comment by kloczek** [comment]
If you want I try to make some PRs ..

**Comment by omar-polo** [comment]
7.4.0p1 is out now and has fixed this, so I'm going to close this issue.  Still, it would be nice to eventually clean up how manpages are handled... ;)

**Comment by omar-polo** [comment]
@Cellesti Exactly!  I've fixed in in the master branch.

**Comment by kloczek** [comment]
> 7.4.0p1 is out now and has fixed this, so I'm going to close this issue. Still, it would be nice to eventually clean up how manpages are handled... ;)

Just tested this new version and ..
```console
checking whether O_NONBLOCK is declared... yes
checking whether AF_LOCAL is declared... yes
checking whether PF_LOCAL is declared... yes
checking whether IPPORT_HILASTAUTO is declared... no
checking whether IPV6_ADDR_SCOPE_INTFACELOCAL is declared... no
checking whether WAIT_MYPGRP is declared... yes
checking whether LOG_PERROR is declared... yes
checking if compiler allows __attribute__ on return types... yes
configure: error: invalid man type: man
```
Really .. all that effort around man pages is pointless because 
```console
[tkloczko@pers-jacek opensmtpd-7.4.0p1]$ ./configure --help
`configure' configures OpenSMTPD-portable 7.4.0p1 to adapt to many kinds of systems.

Usage: ./configure [OPTION]... [VAR=VALUE]...

[..]

Fine tuning of the installation directories:
  --bindir=DIR            user executables [EPREFIX/bin]
  --sbindir=DIR           system admin executables [EPREFIX/sbin]
  --libexecdir=DIR        program executables [EPREFIX/libexec]
  --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
  --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --runstatedir=DIR       modifiable per-process data [LOCALSTATEDIR/run]
  --libdir=DIR            object code libraries [EPREFIX/lib]
  --includedir=DIR        C header files [PREFIX/include]
  --oldincludedir=DIR     C header files for non-gcc [/usr/include]
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
  --infodir=DIR           info documentation [DATAROOTDIR/info]
  --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
  --mandir=DIR            man documentation [DATAROOTDIR/man]     <<<<=== HERE
```

**Comment by omar-polo** [comment]
@kloczek yeah I know, I'm not lucky with the releases recently... I typoed the fix, forgetting a sigil and breaking `--with-mantype` (again!)

**Comment by kloczek** [comment]
> @kloczek yeah I know, I'm not lucky with the releases recently... I typoed the fix, forgetting a sigil and breaking `--with-mantype` (again!)

Please .. remove all that '<censored>`.

**Comment by omar-polo** [comment]
@kloczek sorry, not sure I understand what you mean.

**Comment by kloczek** [comment]
All man pages files should be listed in Makefile.am files in `man_MANS`.
Nothing else is needed.
