### ISSUE TITLE
smtp disconnected reason="io-error: error:0A080006:SSL routines::EVP lib"

### ISSUE THREAD

**Issue by kovmir** [OpenSMTPD/OpenSMTPD#1239]
My setup:
* Debian 12
* OpenSMTPD 6.8.0p2-4+b4
* OpenSSL OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)

Errors I get:
```
Dec 13 04:12:53 ... : d6d805afa1ad44c8 smtp connected address=x.x.x.x host=domain.tld
Dec 13 04:12:54 ... : debug: looking up pki "mail.mydomain.tld"
Dec 13 04:12:54 ... : debug: session_start_ssl: switching to SSL
Dec 13 04:12:54 ... : debug: pony: ecdsae_sign
Dec 13 04:12:54 ... : debug: pony: ecdsae_do_sign
Dec 13 04:12:54 ... : debug: SSL library error: io_dispatch_accept_tls:SSL_accept: error:0800007D:elliptic curve routines::missing private key
Dec 13 04:12:54 ... : debug: SSL library error: io_dispatch_accept_tls:SSL_accept: error:0A080006:SSL routines::EVP lib
Dec 13 04:12:54 ... : d6d805afa1ad44c8 smtp disconnected reason="io-error: error:0A080006:SSL routines::EVP lib"
```

My `smtpd.conf`: https://wiki.archlinux.org/title/OpenSMTPD#Craft_a_simple_smtpd.conf_setup

`Diagnostic-Code: X-Postcow; Cannot start TLS: handshake failure` is what the sender gets.

**Comment by omar-polo** [comment]
Hello,

```
Dec 13 04:12:54 ... : debug: SSL library error: io_dispatch_accept_tls:SSL_accept: error:0800007D:elliptic curve routines::missing private key
```

This is likely an issue with OpenSSL 3.

OpenSMTPD 6.8.0p2-4+b4 is quite old, can't you try with a more recent release?

**Comment by kovmir** [comment]
Debian packaging is way to hard for that. I am closing it for now.

**Comment by omar-polo** [comment]
Hi, I'm not familiar with debian packaging, but for unrelated matters I noticed that 7.4.0p1 is available in bookworm backports, maybe it could help? https://packages.debian.org/bookworm-backports/source/opensmtpd
