### ISSUE TITLE
Writing filters in C

### ISSUE THREAD

**Issue by 0x1F680** [OpenSMTPD/OpenSMTPD#1240]
I am trying to write a filter in C. So far, I can not seem to get the input from opensmtpd. I am trying to read stdin with getline. I read the man pages, it mentioned fd, but I am unsure how to implement i/o in this case. Any help appreciated.

This is in a loop for every line:
```
if ((char_len = getline(&line, &len, stdin)) < 1) {
            printf("Error getting line");
            return 1;
}
```

**Comment by omar-polo** [comment]
The sample code seems correct; opensmtpd runs the filter program and talks to it via stdin/stdout.  Can you please show a bit more of the program you're writing and how you're configuring your smtpd.conf?   You may also try to run `smtpd -dv -T filters` to enable extra logging for the filters.

You should print error messages to standard error though, otherwise opensmtpd will read them and try to interpret them as replies.

Also, you may be interested in taking a look at [libopensmtpd](https://imperialat.at/dev/libopensmtpd/) which is a C library to write opensmtpd filters.  It is packaged at least on OpenBSD.

**Comment by jdelic** [comment]
You can also check out [opensmtpd-filters-go](https://github.com/jdelic/opensmtpd-filters-go) as a helpful library to write filters in Go when you grow tired of C at any point :).

To add on to what Omar already said, you can also replace your filter in your config with [opensmtpd-filter-trace](https://github.com/jdelic/opensmtpd-filter-trace) to see if you get any output in `/tmp/filterlog.txt`. You should be able to just clone the repo and compile it. It provides good additional information to the output of the `smtpd` traces.

```
mkdir -p /tmp/go/src/github.com/jdelic
cd /tmp/go/src/github.com/jdelic/
git clone https://github.com/jdelic/opensmtpd-filter-trace
cd opensmtpd-filter-trace
export GOPATH=/tmp/go
go build
```

**Comment by 0x1F680** [comment]
Sorry for the late reply.

1. There is an initialization function and a main function. They both loop over getline(stdin).
2.  I use ```printf()``` to reply to smtpd.
3.  I know that the initialization function replies correctly and smtpd is fine with that - I get the data-line stream. 
4.  When I try to send any mail that goes through the filter, it just stalls infinitely...
5. I was doing some debugging (file logging in the filter), looks like I can only configure the filter, but I do not actually get any mail data streams... (i.e. the initialization function works fine, but the main loop is not getting an input).

This is the overall structure:
```
main() {
declare variables
run initialization function
while (1) {
getline(stdin)
if/else statements
printf( "the formatted dataline with sid and o_token" )
}
}

initialization() {
declare variables
while (1) {
--- same as the loop in main ---
}
return value
}
```

Could there be a problem with running getline in two separate functions?

**Comment by omar-polo** [comment]
@0x1F680 it's just a shot in the dark, but can you make sure you're including the trailing `\n` in the printf() calls in your main function?  I can see that you're including them in the `config|ready` reply, but not for example in the "memory not allocated for domain var" error message (which should also be print to standard error really).

If you don't include the `\n` the reply is not complete and that would explain why "it hangs".


P.S.: not part of your question, but I'd simplify the parsing of the hostname like this:

```
#include <err.h>

/* then, later in your init function */
while ((char_len = getline(&line, &len, stdin)) != -1) {
	if (line[char_len - 1] == '\n')
		line[--char_len] = '\0';

	if (strncmp(line, "config|ready", 12) == 0 && got_domain) {
		/* ... */
	} else if (!got_domain && strncmp(line, "config|admd|", 12) == 0) {
		*domain = strdup(line + 12);
		if (*domain == NULL)
			err(1, "strdup");
		got_domain = 1;
	}
}
```

The BSD functions [err(3) and warn(3)](http://man.openbsd.org/err.3) already take care of printing the error message to standard error, showing the `errno` and optionally terminating the program.

**Comment by 0x1F680** [comment]
@omar-polo Thanks for the simplification and the error functions, I will implement that!!

I think I understand the main issue. Looks like smtpd is not getting the ```config|ready``` reply from my filter. I have logged the inputs that the filter is getting and the steps taken. Looks like ```printf("register|filter|smtp-in|data-line\nregister|ready\n");``` is for some reason unsuccessful. I tried to remove that printf statement, and I am getting the identical results. I've also tried separating into 2 separate printf statements with ```\n```, also tried to use fprintf to stdout, same deal...

The log:
```
(In INIT FN)
(LOOP run)
config|smtpd-version|7.4.0
(LOOP run)
config|smtp-session-timeout|300
(LOOP run)
config|subsystem|smtp-in
(LOOP run)
config|admd|mx1.0x1f680.net
(LOOP run)
config|ready
(Theoretical printf reply) <- probably unsuccessful 
(In MAIN loop)
(LOOP run)
(Nothing after this ......) <- there is a getline statement waiting to read a line
```

Also, I've ensured that there is a ```\n``` in every reply, but again if that would be a problem in the main function, I would first log a stdin data-line from smtpd and log it, and then the filter would get stuck...

p.s. I am logging the lines right after the getline statement. The logging works in a test environment when running through the command line. In addition I am working on a simple logging filter for smtpd to test my theory, i.e. without any of the complex logic currently implemented...

Does smtpd expect an output somewhere else?

**Comment by omar-polo** [comment]
@0x1F680 another shoot in the dark, maybe it's the buffering done by the stdio layer?  can you try adding `fflush(stdout);` after the printf calls?  (or `setvbuf(stdout, NULL, _IOLBF, 0);` at the start of the main which should achieve the same effect.)

**Comment by idfake** [comment]
There is also a library for making C filters easier.
libopensmtpd is in packages. source and some implementation are at https://imperialat.at/dev/

**Comment by 0x1F680** [comment]
@omar-polo, that worked!!!!!!!
I forgot all about the buffering...
Looks like stdout was storing all the return. I've added a ```fflush(stdout)``` after the ```printf``` statements for initialization and end of email, and it works great!

THANKS!

**Comment by omar-polo** [comment]
@0x1F680 happy to know that it worked :)
