### ISSUE TITLE
Misinterpretation of escaped quotation marks in To/From/Cc 

### ISSUE THREAD

**Issue by TobiasEgg** [OpenSMTPD/OpenSMTPD#1242]
I believe I identified an issue with escaped quotation marks in From/To/Cc header fields, e.g.

To: "\\"Doe, John\\"" <john.doe@example.com>

will be misinterpreted by OpenSMTPD and the address will be modified to become

To: ""Doe@mail.example.com, John"" <john.doe@example.com>

While I do agree there is no point in formatting addresses that way and this is a bug in the mail client, the formatting is to my understanding in accordance to RFC. Hence OpenSMTPD should accept it.

**Comment by TobiasEgg** [comment]
For good measure a how to reproduce

```
mail# nc localhost 25
220 mail.example.org ESMTP OpenSMTPD
EHLO mail
250-mail.example.org Hello mail [127.0.0.1], pleased to meet you
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-SIZE 536870912
250-DSN
250 HELP
MAIL FROM: <user@example.org>
250 2.0.0 Ok
RCPT TO: <user@example.org>
250 2.1.5 Destination address valid: Recipient ok
DATA
354 Enter mail, end with "." on a line by itself
Subject: Test
From: "Doe, John" <user@example.org>
To: "\"Doe, John\"" <user@example.org>

Test

.
250 2.0.0 54bcc63d Message accepted for delivery
QUIT
221 2.0.0 Bye
```


Results in:

```
Return-Path: <user@example.org>
Delivered-To: user@example.org
Received: 
        by mail.example.org (OpenSMTPD) with ESMTP id 54bcc63d
        for <user@example.org>;
        Mon, 22 Jan 2024 10:12:02 +0100 (CET)
Subject: Test
From: "Doe, John" <user@example.org>
To: "\"Doe@mail.example.org, John\"" <user@example.org>
Date: Mon, 22 Jan 2024 10:12:02 +0100 (CET)
Message-ID: <3e58565e7e00bcc6@mail.example.org>

Test

```

**Comment by omar-polo** [comment]
Hello, thanks for reporting the issue.

This is a bug in the handling of the escape character inside the quotes.  I've sent a diff to tech@ which should fix this: <https://marc.info/?l=openbsd-tech&m=170592008624925&w=2>.

I've also turned it into PR #1243 for ease of testing.

**Comment by TobiasEgg** [comment]
Thank you Omar, 
I haven't patched my OpenSMTPD with your patch yet, however, from reading the code, I would assume that this would fix it.

**Comment by omar-polo** [comment]
The fix has been committed, thanks for reporting!
