### ISSUE TITLE
Build fails on macos 10.5.8: `error: ‘EAI_OVERFLOW’ undeclared`

### ISSUE THREAD

**Issue by barracuda156** [OpenSMTPD/OpenSMTPD#1246]
Could someone take a look into the matter?

```
:info:build depbase=`echo ../../openbsd-compat/libasr/gethostnamadr_async.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
:info:build 	/usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H -I. -I../..  -DIO_TLS -I../../usr.sbin/smtpd -I. -DSMTPD_CONFDIR=\"/opt/local/etc/opensmtpd\" -DPATH_CHROOT=\"/var/empty\" -DPATH_SMTPCTL=\"/opt/local/sbin/smtpctl\" -DPATH_MAILLOCAL=\"/opt/local/libexec/opensmtpd/mail.local\" -DPATH_MAKEMAP=\"/opt/local/sbin/makemap\" -DPATH_LIBEXEC=\"/opt/local/libexec/opensmtpd\" -DHAVE_CONFIG_H -I/opt/local/include -isystem/opt/local/include/LegacySupport -I/opt/local/include -I../../openbsd-compat -I../../openbsd-compat/libtls -I../../openbsd-compat/libasr  -pipe -Os -arch ppc -Qunused-arguments -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wno-pointer-sign -fno-strict-aliasing -fno-builtin-memset -std=gnu99 -MT ../../openbsd-compat/libasr/gethostnamadr_async.o -MD -MP -MF $depbase.Tpo -c -o ../../openbsd-compat/libasr/gethostnamadr_async.o ../../openbsd-compat/libasr/gethostnamadr_async.c &&\
:info:build 	mv -f $depbase.Tpo $depbase.Po
:info:build depbase=`echo ../../openbsd-compat/libasr/getnameinfo_async.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
:info:build 	/usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H -I. -I../..  -DIO_TLS -I../../usr.sbin/smtpd -I. -DSMTPD_CONFDIR=\"/opt/local/etc/opensmtpd\" -DPATH_CHROOT=\"/var/empty\" -DPATH_SMTPCTL=\"/opt/local/sbin/smtpctl\" -DPATH_MAILLOCAL=\"/opt/local/libexec/opensmtpd/mail.local\" -DPATH_MAKEMAP=\"/opt/local/sbin/makemap\" -DPATH_LIBEXEC=\"/opt/local/libexec/opensmtpd\" -DHAVE_CONFIG_H -I/opt/local/include -isystem/opt/local/include/LegacySupport -I/opt/local/include -I../../openbsd-compat -I../../openbsd-compat/libtls -I../../openbsd-compat/libasr  -pipe -Os -arch ppc -Qunused-arguments -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wno-pointer-sign -fno-strict-aliasing -fno-builtin-memset -std=gnu99 -MT ../../openbsd-compat/libasr/getnameinfo_async.o -MD -MP -MF $depbase.Tpo -c -o ../../openbsd-compat/libasr/getnameinfo_async.o ../../openbsd-compat/libasr/getnameinfo_async.c &&\
:info:build 	mv -f $depbase.Tpo $depbase.Po
:info:build ../../openbsd-compat/libasr/getnameinfo_async.c: In function ‘getnameinfo_async_run’:
:info:build ../../openbsd-compat/libasr/getnameinfo_async.c:109: error: ‘EAI_OVERFLOW’ undeclared (first use in this function)
:info:build ../../openbsd-compat/libasr/getnameinfo_async.c:109: error: (Each undeclared identifier is reported only once
:info:build ../../openbsd-compat/libasr/getnameinfo_async.c:109: error: for each function it appears in.)
:info:build ../../openbsd-compat/libasr/getnameinfo_async.c: In function ‘_servname’:
:info:build ../../openbsd-compat/libasr/getnameinfo_async.c:216: warning: unused variable ‘s’
:info:build make[3]: *** [../../openbsd-compat/libasr/getnameinfo_async.o] Error 1
```
[opensmtpd build log G4.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/14484795/opensmtpd.build.log.G4.txt)

**Comment by omar-polo** [comment]
Hello @barracuda156.  It seems that macos 10.5 doesn't have for some reason the `EAI_OVERFLOW` error define.  Does it builds if you replace it with `EAI_FAIL`?

btw, getnameinfo_async` is not even used in opensmtpd, it's built only because it's part of libasr, but we could trim unused files.

**Comment by barracuda156** [comment]
@omar-polo Thank you for responding!

`EAI_OVERFLOW` _is_ defined in fact in 10.5 SDK: https://github.com/barracuda156/macos-sdk/blob/42f8b4fd20e2c13d22386c0d909375ac7bf90376/MacOSX10.5.sdk/usr/include/netdb.h#L206-L208

However it is inside `_POSIX_C_SOURCE && !_DARWIN_C_SOURCE` clause, and defining `_POSIX_C_SOURCE` may break something else. (I cannot test at the moment, away from my PowerMacs.)

If it is not used in `opensmtpd`, perhaps an easier way is to skip it from the build.

`EAI_FAIL` is available unconditionally: https://github.com/barracuda156/macos-sdk/blob/42f8b4fd20e2c13d22386c0d909375ac7bf90376/MacOSX10.5.sdk/usr/include/netdb.h#L192

P. S. 10.6 on PowerPC has the same: https://github.com/barracuda156/10.6-PowerPC-SDKs/blob/10a190/MacOSX10.6.sdk/usr/include/netdb.h

**Comment by omar-polo** [comment]
@barracuda156 grep failed on me the other day, `getnameinfo_async`  is really used by smtpd, so we can't unlink that file from the build.

smtpd also uses `EAI_NODATA` which seems to be available only on the opposite condition `!_POSIX_C_SOURCE && _DARWIN_C_SOURCE`, but there is some glue for that in `openbsd-compat/defines.h`.  Maybe we can add more for `EAI_OVERFLOW` to turn it into `EAI_FAIL`.

I fear that adding `-D_POSIX_C_SOURCE` could have unpleasant surprises, and we're too close to the 7.5 release for experimenting with that.

**Comment by omar-polo** [comment]
@barracuda156 can you try #1247 and see if it works?  Thanks!

**Comment by barracuda156** [comment]
@omar-polo Thank you! While I cannot yet test personally, I have requested to try that and got confirmation that it builds now on 10.4.11 ppc. This should imply that 10.5–10.6 will work as well.

P. S. 10.4 header: https://github.com/alexey-lysiuk/macos-sdk/blob/main/MacOSX10.4u.sdk/usr/include/netdb.h

**Comment by omar-polo** [comment]
Thanks for testing!  I'm happy to know that know it builds also on 10.x too!

**Comment by barracuda156** [comment]
Builds fine on 10.6 for `ppc` (as expected, just confirming):
```
$ port -v installed OpenSMTPD
The following ports are currently installed:
  opensmtpd @7.4.0p1_0 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2024-03-13T14:25:50+0800'
```

**Comment by poolpOrg** [comment]
Does it run ? Sent from my iPhoneOn 13 Mar 2024, at 07:27, Sergey Fedorov ***@***.***> wrote:﻿
Builds fine on 10.6 for ppc (as expected, just confirming):
$ port -v installed OpenSMTPD
The following ports are currently installed:
  opensmtpd @7.4.0p1_0 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2024-03-13T14:25:50+0800'

**Comment by barracuda156** [comment]
@poolpOrg It happens that running tests does not work at the moment, for unrelated reason and for all systems: https://trac.macports.org/ticket/69456
I will run tests once that is fixed in Macports.
