### ISSUE TITLE
How to add additional recipient / dual delivery?

### ISSUE THREAD

**Issue by hoax** [OpenSMTPD/OpenSMTPD#1250]
I like to have all sent mail also to be delivered to specific user. Is there any possibility to with filters? I was able to write a filter to mangle _rcpt to_, but failed to add an additional entry.

**Comment by hoax** [comment]
I just found https://github.com/OpenSMTPD/OpenSMTPD/issues/791 where @poolpOrg mentioned dual delivery should be possible with filters. Can anyone suggest how? I just dug though the rfc and rcpt to only allows one address, no list :\.

**Comment by jdelic** [comment]
@hoax 
The filter can grab the whole original email and then send a new email to your other recipient address. You are right in that the filter can't modify the SMTP protocol conversation by injecting new commands into it. But something like the following would probably do what you want (please note that this code is an *example, that I have not tested at all!*).

```go
package main

import (
	"fmt"
	"github.com/emersion/go-sasl"
	"github.com/emersion/go-smtp"
	"github.com/jdelic/opensmtpd-filters-go"
	"log"
	"strings"
)

type RcptFilter struct {
	opensmtpd.SessionTrackingMixin
}

func (rf *RcptFilter) GetName() string {
	return "RCPT filter"
}

func secretCopyMail(msg []string) {
	log.Println("Secretly copying mail")
	auth := sasl.NewPlainClient("", "user", "password")
	to := []string{"recipient@example.net"}

	// just make absolutely sure that the relay does not send the new email to this filter again!
	err := smtp.SendMail("smtp.example.com:25", auth, "sender@example.org", to,
		strings.NewReader(strings.Join(msg[:], "\n")))
	if err != nil {
		log.Println(err)
	}
}

func (rf *RcptFilter) Commit(fw opensmtpd.FilterWrapper, ev opensmtpd.FilterEvent) {
	msg := make([]string, 1)
	session := rf.GetSession(ev.GetSessionId())
	msg = append(msg, fmt.Sprintf("Original From: %s\n", session.MailFrom))
	msg = append(msg, fmt.Sprintf("Original To: %s\n\n", session.RcptTo))
	msg = append(msg, session.Message...)

	go secretCopyMail(msg)

	ev.Responder().Proceed()
}

func main() {
	log.Println("Secret copy filter starting")

	rcptFilter := opensmtpd.NewFilter(&RcptFilter{})
	opensmtpd.Run(rcptFilter)
}
```

**Comment by hoax** [comment]
@jdelic thank you! Did not think of that simple solution. Only change I'll make is using imap to put the copy directly in a specific mailbox to keep the original recipients.
