### ISSUE TITLE
Code for the action: report of the filters is incomplete.

### ISSUE THREAD

**Issue by renegm** [OpenSMTPD/OpenSMTPD#1257]
With builtin filters the report action is possible. E.g:
`filter report_data phase data match mail-from regex {".*"} report "Tururu"`
 but not possible with proc filters. Returns error `Invalid directive: filter-result| etc...`
 The only place where the text "Invalid directive" exists is in:
[lka_filter.c#L670](https://github.com/OpenSMTPD/OpenSMTPD/blob/e3feaf24fd3b311277619266a92076557e0ca703/usr.sbin/smtpd/lka_filter.c#L670) 

```
		else if (strncmp(response, "disconnect|", 11) == 0)
			filter_result_disconnect(reqid, parameter);
		else
			fatalx("Invalid directive: %s", line);
```
looks like "report" escapes through the else

**Comment by omar-polo** [comment]
Hello, thanks for the report!

I think this is just an omission, I've sent a mail to tech@ with a diff that implements the report response for proc-filters too, let's see what @poolpOrg thinks :)

https://marc.info/?l=openbsd-tech&m=172320080004193&w=2

**Comment by renegm** [comment]
Great! Thanks

**Comment by renegm** [comment]
Hi @omar-polo
Related (and is part of the reason I was looking to make a report on filter). If I do a rewrite of, for example rcpt-to, the tx-rcpt report is going to indicate the old address not the rewritten  new one. A filter further down the chain, subscribed to that report will get the wrong information. That second filter would need to subscribe to the filter-response|...|rcpt-to|rewrite to get the correct information. And I think this happens in all cases when rewrite can be done.
This makes the reporting of things that allow rewrite almost useless. The information in the report may be true but we can't know that without looking at the filter-response_rewrite that may be there.
And at least, in the filters that I have looked at the code, everyone has the assumption that if they subscribe to the mail-from report they will receive the mail-from that is being processed.

**Comment by poolpOrg** [comment]
This was okayd, committed upstream and synced back by @omar-polo in 0b1c010

It'll be part of the next major release around October/November.
