### ISSUE TITLE
Intsalled on PI, internal Network, Domain does not exist

### ISSUE THREAD

**Issue by MuevCFO** [OpenSMTPD/OpenSMTPD#1263]
OpenSMTPD installed on Pi so system messages get sent to my public Fedora Box.  No incoming email from outside the Pi.

Some email does get delivered, but anything it looks like to root or asterisk fails.

 My error is:

> Oct 10 06:41:02 Allstar smtpd[1920452]: warn: queue: no return path!
> Oct 10 06:41:03 Allstar smtpd[1920451]: 0de8860588e2edae smtp connected address=local host=AllStar
> Oct 10 06:41:03 Allstar smtpd[1920451]: 0de8860588e2edae smtp message msgid=cc77361c size=1364 nrcpt=1 proto=ESMTP
> Oct 10 06:41:03 Allstar smtpd[1920451]: 0de8860588e2edae smtp envelope evpid=cc77361c8b347a7f from=<root@AllStar> to=<asterisk@AllStar>
> Oct 10 06:41:03 Allstar smtpd[1920451]: 0de8860588e2edae smtp disconnected reason=quit
> Oct 10 06:41:03 Allstar smtpd[1920451]: smtp-out: Failed to resolve MX for [relay:AllStar,smtp]: Domain does not exist
> Oct 10 06:41:03 Allstar smtpd[1920451]: 0000000000000000 mta delivery evpid=cc77361c8b347a7f from=<root@AllStar> to=<asterisk@AllStar> rcpt=<-> source="-" relay="AllStar" delay=0s result="PermFail" stat="Domain does not exist"
> Oct 10 06:41:04 Allstar smtpd[1920451]: 0de886092a59e560 smtp connected address=local host=AllStar
> Oct 10 06:41:04 Allstar smtpd[1920451]: 0de886092a59e560 smtp message msgid=c0860d5e size=2519 nrcpt=1 proto=ESMTP
> Oct 10 06:41:04 Allstar smtpd[1920451]: 0de886092a59e560 smtp envelope evpid=c0860d5ebad42413 from=<> to=<root@AllStar>
> Oct 10 06:41:04 Allstar smtpd[1920451]: 0de886092a59e560 smtp disconnected reason=quit
> Oct 10 06:41:04 Allstar smtpd[1920451]: smtp-out: Failed to resolve MX for [relay:AllStar,smtp]: Domain does not exist
> Oct 10 06:41:04 Allstar smtpd[1920451]: 0000000000000000 mta delivery evpid=c0860d5ebad42413 from=<> to=<root@AllStar> rcpt=<-> source="-" relay="AllStar" delay=0s result="PermFail" stat="Domain does not exist"
> Oct 10 06:41:04 Allstar smtpd[1920452]: warn: queue: no return path!

SMTPD.Conf

```
table relay_secrets file:/etc/smtpd/tables/relay_secrets


listen on lo \
    port 25 \
    hostname sbanetweb.com \
    mask-src

listen on socket \
    mask-src


action "relay_monitoring" \
    relay \
#    tls \
 #   host smtp://mcq.sbanetweb.com:587 \
 host smtp://mcq.sbanetweb.com:25 \
 #  auth <relay_secrets>


match \
    from local \
    mail-from "wbs@sbanetweb.com" \
    for any \
    action "relay_monitoring"

# MAIL FROM is a linux user account name
#match from local mail-from "root" for any action "relay_monitoring"
#match from local mail-from "www-data" for any action "relay_monitoring"
#match from local mail-from "prometheus-alertmanager" for any action "relay_monitoring"

match from any for any action "relay_monitoring"



pki Allstar.sbanetweb.com cert "/etc/smtpd/tables/SectigoCombo.pem"
pki Allstar.sbanetweb.com key "/etc/smtpd/tables/sbanetweb.com.pem"
pki Allstar.sbanetweb.com dhe auto
```

My relay_secrets is:

```
# Syntax: alias smtp-username:smtp-password

# SMTP account for booking confirmation emails
#webapp_booking booking@example.com:very-secure-password

# SMTP account for password reset emails
#webapp_pw_reset password-reset@example.com:super-secure-password

# SMTP account for all other emails
monitoring wbs:<secret>

```
Thank you.

**Comment by MuevCFO** [comment]
Found the right syntax


```
table relay_secrets file:/etc/smtpd/tables/relay_secrets

listen on lo \
    port 587 \
    hostname sbanetweb.com \
    mask-src

listen on socket \
    mask-src
action "local" relay
action "myserver" relay host smtp://mcq.sbanetweb.com

match mail-from "@Allstar" for any action "myserver"
match for local action "myserver"
match for any action "myserver"

pki Allstar.sbanetweb.com cert "/etc/smtpd/tables/SectigoCombo.pem"
pki Allstar.sbanetweb.com key "/etc/smtpd/tables/sbanetweb.com.pem"
pki Allstar.sbanetweb.com dhe auto
```

**Comment by omar-polo** [comment]
Glad that you fixed it in the end :)

just a minor notice:

```
action "relay_monitoring" \
    relay \
#    tls \
 #   host smtp://mcq.sbanetweb.com:587 \
 host smtp://mcq.sbanetweb.com:25 \
 #  auth <relay_secrets>
```

This won't work as you might expect, since the comment before `tls` will extend until the end of the (logical) line, so smtpd will just see `action relay_monitoring relay`.  It's documented and is a common behaviour, but it's also a bit annoying.  I've sent a diff to tech@ to allow to use braces to group `listen` options, and will propose the same for `action` too, so that you could ideally write

```
action relay_monitoring {
	relay tls
	host smtp://xyz.com
	# auth <relay_secrets>
}
```

**Comment by MuevCFO** [comment]
Thank you
