### ISSUE TITLE
[portable/asr] resolver: family preference IPv6 vs IPv4

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#182]
Summary from IRC:

ftigeot@ reported a bug where -portable will perform IPv4 before IPv6 lookups, bypassing the system preferences (IPv6 before IPv4 on DragonFlyBSD).

This is actually not a bug in OpenSMTPD but the default choice for the asynchronous resolver, asr, which it uses and which also happens to be the default system preferences on OpenBSD.

Note that it is NOT an issue and none of these preferences should prevent mail from being relayed or delivered:

If a host has both an IPv4 AND IPv6 address AND only listens on IPv6, smtpd will fail to connect to the IPv4 address a few times before attempting the IPv6 address. If we switch lookup preference, the same will happen in opposite way: if the host only listens on the IPv4 address, then smtpd will fail to connect to the IPv6 address a few times before attempting the IPv4 address. Either way, the connection will happen, mail will be relayed and besides the admin who gets logs mentionning connection failures, no one will notice.

The diff to switch family preference is two lines in contrib/asr/asr.c.

So. we have two choices:

1- decide it is up to the packagers to apply the diff as it is a system local policy;
2- decide to ship portable with the diff applied;

1) means that systems who prefer ipv6 over ipv4 will have to apply the diff;
2) means that systems who prefer ipv4 over ipv6 will have to apply the diff;

The loser gets extra logs :-)

Which one should we go for ?

[EDIT: THIS ONLY APPLIES TO PORTABLE]

**Comment by anyuta1166** [comment]
It seems that IPv6 over IPv4 preference was (erroneously?) dropped in commit https://github.com/OpenSMTPD/OpenSMTPD/commit/350a6b91f68e903a3e3900a98ab80b751e4578ae
7.3.0 & 7.4.0 prefer IPv4 over IPv6.

**Comment by omar-polo** [comment]
@anyuta1166 Yeah, my fault when sync'ing base libasr with the bundled one.  Will re-establish it as soon as possible, thanks for the report!

**Comment by omar-polo** [comment]
@anyuta1166 I've just re-added it, see e2703a1.  (we should probably document this knob somewhere however.)
