### ISSUE TITLE
mapping smtp auth to outgoing senders

### ISSUE THREAD

**Issue by zx2c4** [OpenSMTPD/OpenSMTPD#227]
I'd like to the following setup:

I have smtp authentication for validating users in order for them to
relay mail. I'd like certain users to only be allowed to send mail
from certain addresses. For example:

smtpusername: bob   ---> he may only send mail as bob@domain.com
smtpusername: tim   ---> he may only send mail as tim@domain.com
smtpusername: domainadmin   ---> he may only send mail as *@domain.com
smtpusername: hostadmin   ---> he may send mail as anybody

Can OpenSMTPD support such a mapping?

**Comment by poolpOrg** [comment]
work in progress, I might be done this week-end.

**Comment by fbettag** [comment]
Sweet!

**Comment by zx2c4** [comment]
You're a hero! Thanks, can't wait!

**Comment by poolpOrg** [comment]
committed to master / portable

**Comment by nfnty** [comment]
This feature needs documentation.

**Comment by poolpOrg** [comment]
Right, I'll open a ticket so this missing documentation gets fixed before release

**Comment by pvagner** [comment]
Is there a way I can retrieve the data for this mapping table from LDAP? I can't figure this out as it appears ldap backend only supports predefined set of table types.

**Comment by toxadx** [comment]
LDAP table is missing K_MAILADDRMAP.
That may be easily implemented by adding K_MAILADDRMAP to table_ldap.c

**Comment by emmatebibyte** [comment]
How do I assign multiple addresses to one user? Like:
`{ user = "@example.com","user@example2.com" }`

I have found no way to do this.
