### ISSUE TITLE
feature: show program version

### ISSUE THREAD

**Issue by dfateyev** [OpenSMTPD/OpenSMTPD#283]
Sometimes, especially for testing purposes, it's very useful to see the opensmtpd and/or snapshot version in smtp greeting and mail headers, like that: `220 xxx.xxx ESMTP OpenSMTPD 6.3`, `Received: by xxx.xxx (OpenSMTPD 6.3) with ESMTPA id 52aabc07` and `User-Agent: OpenSMTPD 6.3 enqueuer (Demoosh)`. 
It could be triggered with a parameter in config file, and set to "false" by default.

**Comment by sysfu** [comment]
I recently ran into a use case for a show version switch: Creating Ansible tests so OpenSMTPD can be updated using a configuration management tool.

Let's say there's a system you want to bring into a consistent state, but OpenSMTPD, being so reliable of course, has been running for years on end, and any version information in the maillogs is long gone. 

How can I determine what version is running, and if it needs upgrading? I can't of course, this is where a show version feature for either smtpd or smtpctl would come in handy.

**Comment by ledeuns** [comment]
Would the output of "smtpd -h" be of any help ?

**Comment by sysfu** [comment]
Yes! thank you, never occurred to be to use the -h switch to get the version.
