### ISSUE TITLE
support for TLSv1.2 protocol on inbound STARTTLS connections

### ISSUE THREAD

**Issue by sysfu** [OpenSMTPD/OpenSMTPD#438]
I recently enabled TLS on an OpenSMTPD server which is working well. I would like it to support TLSv1.2 on incoming connections however.

To test the supported ciphers on my mail server I'm using this command

```
openssl s_client -connect mail:25 -starttls smtp
```

Here are the results with the certificate info trimmed;

```
SSL handshake has read 2727 bytes and written 565 bytes

---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID:
:250 HELP
    Session-ID-ctx:
    Master-Key: A85ABEB5654906832E7FAC564A82CD01E769783A3FB2B46F9E5A93ED2A216AA38F23FA3D000764815DE7386E5255793E
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1396127106
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)

---
```

**Comment by sysfu** [comment]
Did the diff implementing SSL_CIPHER_description() ever get committed to the release version? 

I'm still seeing seeing ```version=TLSv1/SSLv3``` in my logs instead of ```version=TLSv1/SSLv3 (TLSv1.2)```

**Comment by poolpOrg** [comment]
Yes it got committed however it got overwritten when I brought back an updated ssl.c with tons of cosmetic changes from OpenBSD.

I'll bring it back in a few minutes

**Comment by sysfu** [comment]
Still not seeing this feature as of the 5.4.5 release.

Log sample:
```Apr 25 13:56:28 mx smtpd[24003]: smtp-in: Started TLS on session 0ee6af586e5d4d82: version=TLSv1/SSLv3, cipher=AES256-SHA, bits=256```

**Comment by poolpOrg** [comment]
This has been brought back to the master/portable branch which are going to be the next major release, it wasn't backported to 5.4.5 which is a minor bugfix release.

**Comment by poolpOrg** [comment]
On Sat, Apr 25, 2015 at 01:59:29PM -0700, Seth wrote:
> Still not seeing this feature as of the 5.4.5 release.
> 
> Log sample:
> ```Apr 25 13:56:28 mx smtpd[24003]: smtp-in: Started TLS on session 0ee6af586e5d4d82: version=TLSv1/SSLv3, cipher=AES256-SHA, bits=256```
> 

The code to log the exact TLS version is part of the branch that will be
used for our next major release in June:

     https://github.com/OpenSMTPD/OpenSMTPD/blob/master/smtpd/ssl.c#L350-L361


The 5.4.5 was a minor release to fix a DoS, we didn't backport code that
provided features / enhancements, only bug fixes.


-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg
