### ISSUE TITLE
deliver to [...] as specified_user

### ISSUE THREAD

**Issue by mneumann** [OpenSMTPD/OpenSMTPD#469]
We discussed that some time ago [here](http://marc.info/?l=opensmtpd-misc&m=139414826924669&w=2). Would be useful to have something like:

`accept [...] deliver to mda [...] as _dovecot`

or 

`accept [...] deliver to lmtp /var/run/dovecot/lmtp as _smtpq`

**Comment by nfnty** [comment]
The proposed fix doesn't work for me. `e->user` needs to be `e->dest` for Dovecot to accept the emails.
