### ISSUE TITLE
API's should beable to accept expansion vars like %{rcpt}

### ISSUE THREAD

**Issue by kusuriya** [OpenSMTPD/OpenSMTPD#471]
Just that the API for tables and the like should accept expansion so if I wanted to make a table query for SQL for example I could go and do 
SELECT * FROM Accepted_Domains_Table WHERE domain = %{rcpt.domain}
or could so something more complex
SELECT * From Users WHERE username = %{rcpt.username} AND domain = %{rcpt.domain}  
Having the expansions available to tables and the rest of the API would allow for more robust multi site configs.

**Comment by poolpOrg** [comment]
I'll close this ticket and copy the OP as a comment to #480 which is kind of a duplicate.
