### ISSUE TITLE
Please document filter interface

### ISSUE THREAD

**Issue by athompso** [OpenSMTPD/OpenSMTPD#477]
It is difficult for external developers to create filters (#476, #474, #473, #472, #172, #16) until they have fully read the source code, understand the style & idioms used, and internalize the structure of OpenSMTPD.
Not having spent the time yet to do all that, I don't even know if the Filter API is C-only [in which case I won't be contributing, sorry] or if it's pipe-based, or socket-based or... what?
Stub documentation (e.g. smtpd-filter(7): "<BOF>Filters must be linked at compile time using C APIs.  This section needs to be re-written with real information.<EOF>") is better than none whatsoever, in my opinion.  Yes, it takes time away from development, but will shut up people like me :grin: !

**Comment by poolpOrg** [comment]
A man page was introduced by Joerg Jung:

https://github.com/OpenSMTPD/OpenSMTPD-extras/blob/master/extras/wip/filters/filter_api.3
