### ISSUE TITLE
Feature Request: Make auth methods pluggable similar to tables/filters/backends

### ISSUE THREAD

**Issue by kusuriya** [OpenSMTPD/OpenSMTPD#481]
Make auth methods pluggable so they can be extended in a fashion similar to tables. This should allow users to write custome authentication methods to handle things like GSSAPI or NTLM.

**Comment by poolpOrg** [comment]
has not happened since 2014, unless someone comes with a use-case and a draft, this is unlikely to happen as I feel most use-cases can be solved through bsd_auth(3) or pam(3) unless proven wrong.
