### ISSUE TITLE
"warn: certificate has expired"

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#491]
this is not explicit at all

**Comment by sysfu** [comment]
Three months and no response, this should probably be closed

**Comment by poolpOrg** [comment]
Nope, the issue is not fixed and it is a nuisance, the ticket stays open.

**Comment by sysfu** [comment]
Sorry at first glance I thought it was someone opening up an issue with very minimal info.

So regarding the actual issue, instead of the existing text, maybe something like ```warn: the Server certificate for host mx1.poolp.org has expired, please alert the server admin```?

Granted the line ```warn: certificate has expired``` does not stand well alone, but when read in context with the other log entries above and below it was pretty clear to me what the meaning is.

```
Feb 11 09:41:14 mx smtpd[2629]: smtp-out: Connecting to smtp+tls://212.83.181.8:25 (mx1.poolp.org) on session 8d0c0948745ecee3...
Feb 11 09:41:14 mx smtpd[2629]: smtp-out: Connected on session 8d0c0948745ecee3
Feb 11 09:41:15 mx smtpd[2629]: smtp-in: Closing session 8d0c09421cb2f9a6
Feb 11 09:41:16 mx smtpd[2629]: smtp-out: Started TLS on session 8d0c0948745ecee3: version=TLSv1/SSLv3, cipher=ECDHE-RSA-CHACHA20-POLY1305, bits=256
Feb 11 09:41:16 mx smtpd[7060]: warn: certificate has expired
Feb 11 09:41:16 mx smtpd[2629]: smtp-out: Server certificate verification failed on session 8d0c0948745ecee3
```

**Comment by poolpOrg** [comment]
> So regarding the actual issue, instead of the existing text, maybe something like warn: the Server certificate for host mx1.poolp.org has expired, please alert the server admin?

Yes, however it is slightly trickier than it seems:

As you can see from your log sample, the warning was not issued by the same process that actually did the connection. The certificate checking is privilege-separated and the function who actually displays this warning doesn't know if the certificate was issued in a server or client context.

To be fixed, a bit of refactor is needed and unfortunately a bit of X509 code needs to be written.

There are other warnings that can trigger to so I can't slap a quick ambiguous message that will make sense because of the lines below and above, it needs to be fixed for real.

**Comment by poolpOrg** [comment]
I removed the warning, it has annoyed far too many people for too long, we'll find a better way to notify admin that local cert has expired.
