### ISSUE TITLE
Compilation on Alpine Linux

### ISSUE THREAD

**Issue by renaudallard** [OpenSMTPD/OpenSMTPD#495]
Hello,

Following the recent addition of the RFC2822 parser, I wanted to try compiling on Alpine Linux.
Then I got a few issues.
Some are solved by this "dirty" patch: https://arnor.org/files/opensmtpd-alpine.patch
But then I get:
strmode.c:85:28: error: 'S_ISUID' undeclared (first use in this function)
because it fails to include <sys/stat.h>

**Comment by poolpOrg** [comment]
I made very good progress on this, I'm THIS close to having smtpd running on Alpine.

**Comment by poolpOrg** [comment]
There you go:

    alpine:~/OpenSMTPD# smtpd -dv
    debug: init ssl-tree
    debug: init ca-tree
    debug: init ssl-tree
    info: OpenSMTPD portable starting
    debug: bounce warning after 4h
    debug: using "fs" queue backend
    debug: using "ramqueue" scheduler backend
    debug: using "ram" stat backend
    debug: parent_send_config_ruleset: reloading
    debug: parent_send_config: configuring pony process
    debug: parent_send_config: configuring ca process
    filter: building simple chains...
    filter: building complex chains...
    filter: done building complex chains
    debug: queue: done loading queue into scheduler
    debug: init private ssl-tree
    debug: ca_engine_init: using RSA privsep engine
    debug: smtp: listen on 127.0.0.1 port 25 flags 0x400 pki "" ca ""
    debug: smtp: will accept at most 2043 clients
    debug: smtpd: scanning offline queue...
    debug: smtpd: offline scanning done

I'll commit my changes, publish new libasr snapshot + new smtpd snapshot later today.
