### ISSUE TITLE
OpenSMTPD-portable for solaris

### ISSUE THREAD

**Issue by bsdsx** [OpenSMTPD/OpenSMTPD#500]
I'm trying to build OpenSMTPD on this hw:

$ uname a                                                                                                                                       
$ SunOS pouet 5.10 Generic_147147-26 sun4u sparc SUNW,Sun Fire-880                                                                                         

The usuals problems on this plateform are:
- no <err.h>
- no <path.h>
- no <ifaddrs.h>
- missing some #define 

Maybe 'openbsd-portable' is the best location for patches ?

**Comment by poolpOrg** [comment]
any news on this ?

**Comment by poolpOrg** [comment]
OP timeout, will reopen if there's any interest from a contributor
