### ISSUE TITLE
IPv6 handling in smtpd.conf does not work as expected

### ISSUE THREAD

**Issue by robberer** [OpenSMTPD/OpenSMTPD#501]
OpenSMTPD 5.4.2p1 (FreeBSD 10 ports)

`smtp://2001:ffff:ffff:ffff:0:0:0:2` results in `smtp-out: Failed to resolve MX for [relay:ipv6:2001:ffff:ffff:ffff:,port=2,mx]: No MX found for domain`

`smtp://[2001:ffff:ffff:ffff:0:0:0:2]:25` results in `smtp-out: Failed to resolve MX for [relay:[2001:ffff:ffff:ffff:0:0:0:2],port=25,mx]: No MX found for domain`

`smtp://2001:ffff:ffff:ffff:0:0:0:2:25` seems to work but looks really weird because manpage says `smtp://` URL prefix already point at SMTP which defaults to port 25

**Comment by poolpOrg** [comment]
It took some time but I've finally managed to spend some time on this issue.

The problem was that the parser in text_to_relayhost() was incorrect and assumed that anything behind the latest ':' was a port number.

I fixed the parsing logic to parse all notations:

    schema://hostname
    schema://hostname:port
