### ISSUE TITLE
"No MX found for domain" when running as a Backup MX

### ISSUE THREAD

**Issue by cortexcorepl** [OpenSMTPD/OpenSMTPD#513]
Today I upgraded to OpenSMTPD 5.4.4p1.  
Config:
```
pki mail2.domain.org certificate "/etc/ssl/certs/mail2.domain.org.pem" 
pki mail2.domain.org key "/etc/ssl/private/mail2.domain.org.key" 

listen on lo
listen on eth0 inet4 tls pki mail2.domain.org
bounce-warn 1d
expire 14d
accept for local deliver to mbox

accept from any for domain domain.org relay \
    backup mail2.domain.org tls verify
```

Errors:

```
Jan  1 22:28:26 mail2 smtpd[23533]: info: OpenSMTPD 5.4.4p1 starting
Jan  1 22:28:26 mail2 smtpd[23534]: info: startup
Jan  1 22:28:54 mail2 smtpd[23539]: smtp-in: New session 60a37def3e91c000 from host redacted [redacted]
Jan  1 22:28:58 mail2 smtpd[23539]: smtp-in: Accepted message 46197170 on session 60a37def3e91c000: from=<mail@someotherdomain.name>, to=<test@domain.org>, size=0, ndest=1, proto=ESMTP
Jan  1 22:28:58 mail2 smtpd[23539]: smtp-out: Failed to resolve MX for [relay:mail2.domain.org,starttls,mx]: No MX found for domain
Jan  1 22:28:58 mail2 smtpd[23539]: relay: TempFail for 46197170fb4519cf: session=0000000000000000, from=<mail@someotherdomain.name>, to=<test@domain.org>, rcpt=<->, source=-, relay=mail2.domain.org, delay=1s, stat=No MX found for domain
Jan  1 22:28:58 mail2 smtpd[23539]: smtp-in: Closing session 60a37def3e91c000
Jan  1 22:29:04 mail2 smtpd[23539]: smtp-out: Failed to resolve MX for [relay:mail2.domain.org,starttls,mx]: No MX found for domain
Jan  1 22:29:04 mail2 smtpd[23539]: relay: TempFail for d8582846e99080f6: session=0000000000000000, from=<mail@someotherdomain.name>, to=<test@domain.org>, rcpt=<->, source=-, relay=mail2.domain.org, delay=6m40s, stat=No MX found for domain
```
Setup:
mail1.domain.org - main mail server
mail2.domain.org - OpenSMTPD 5.4.4p1 on Debian with the issue.
mail3.domain.org - OpenSMTPD on OpenBSD 5.6 without this issue.

Issue:
When mail2 receives an email  addressed to test@domain.org it should forward it to mail1 , but it doesn't happen due to the errors above. Same config worked with earlier versions, and mail3 works fine with a comparable config. 
I didn't change the config nor any mx records. Just before upgrading mail2 operated as intended. Before upgrade version on mail2 was opensmtpd-201410040019p1. 

I therefore believe this is a regression in a newer version.

**Comment by dfateyev** [comment]
Make sure you've got "libasr" installed, now it's essential.

**Comment by cortexcorepl** [comment]
I did have libasr installed. However, now I have upgraded to libasr-1.0.0 and recompiled. While this problem is gone now, this one seems back https://github.com/OpenSMTPD/OpenSMTPD/issues/470

It seems thix fix is missing in the current stable: https://github.com/OpenSMTPD/OpenSMTPD/commit/4c05ad47b40eaf9f6d1cecfceecab116aa914f6d

Applied this fix and mail flow works again.

**Comment by dfateyev** [comment]
Well, that can be. Since I don't use backup MX here I've no idea.

**Comment by poolpOrg** [comment]
@cortexcorepl:

> Before upgrade version on mail2 was opensmtpd-201410040019p1.
> I therefore believe this is a regression in a newer version.

That's not really a regression, opensmtpd-201410.. is a snapshot of our portable branch which is far ahead of the stable releases in terms of code.

OpenSMTPD 5.4.4 was branched from OpenSMTPD 5.4.3 and is only contains fixes to bugs that were reported for that version.

You essentially "downgraded" from October code to May code with a few backports.
