### ISSUE TITLE
asr.h not found -- document libasr dependency

### ISSUE THREAD

**Issue by daniel-j-h** [OpenSMTPD/OpenSMTPD#521]
I'm unable to build the -portable branch on a Debian system. It seems like I need libasr:

> checking for asr.h... no
> configure: error: *** asr.h missing - please install first or check config.log ***

It's still in the tree but not used:

$ find . -name 'asr.h'
./smtpd/asr/asr.h

In addition, it also seems like to be more up to date than the stand alone libasr:
https://github.com/OpenSMTPD/libasr

So now I have to build libasr from this repository, as a dependency for opensmtpd to work.
Is this correct? What's the purpose of the in-tree libasr then?

Could you please clarify this.
And if the libasr repository is a dependency please be explicit about it in the README.

**Comment by ericfaurot** [comment]
This is a bit confusing, indeed.  Here is the story.

The smtpd/asr/ directory in the github repository is there to support
older OpenBSD releases, where asr was not natively available, or when
the API was still moving. It will eventually  be removed when we stop
supporting OpenBSD 5.5 and below, which is in a couple of months.

This directory is not meant to be used by the portable branch at all.
It's only left there to minimize the diff with master, and it must be
completely ignored.   

So for portable, you really need to install libasr first. The bug is
that this dependency is not checked in the configure script.

And you are right about the README file. It definitely needs an update.

**Comment by clongeau** [comment]
Eric, there is a check for libasr dependency since this commit:
https://github.com/OpenSMTPD/OpenSMTPD/commit/89deddbe30d4faba20392836285498aaf34dd934
Please tell me if it doesn't work

**Comment by ericfaurot** [comment]
Oh, I suppose this diff didn't make it to the release then...

**Comment by ericfaurot** [comment]
Ah, OP is mentioning -portable branch. So it's something else.

**Comment by ScrumpyJack** [comment]
I'm getting the same sort of problem. Initially the asr.h was missing, but I build a package of libasr and get the following from the opensmtpd configure script

checking for asr.h... yes
checking for asr_resolver in -lasr... no
configure: error: *** libasr missing - please install first or check config.log ***
alpine-dev-edge:~/OpenSMTPD$ apk info -L libasr
libasr-1.0.0-r0 contains:
usr/lib/libasr.a
usr/lib/libasr.so.0
usr/lib/libasr.so.0.0.0

alpine-dev-edge:~/OpenSMTPD$ apk info -L libasr-dev
libasr-dev-1.0.0-r0 contains:
usr/lib/libasr.so
usr/include/asr.h

Complete configure log here http://st.ilet.to/osmtpd.log

**Comment by ScrumpyJack** [comment]
I'm getting the same sort of problem. Initially asr.h was missing, but I built a package of libasr and get the following from the opensmtpd configure script

checking for asr.h... yes
checking for asr_resolver in -lasr... no
configure: error: *** libasr missing - please install first or check config.log ***
alpine-dev-edge:~/OpenSMTPD$ apk info -L libasr
libasr-1.0.0-r0 contains:
usr/lib/libasr.a
usr/lib/libasr.so.0
usr/lib/libasr.so.0.0.0

alpine-dev-edge:~/OpenSMTPD$ apk info -L libasr-dev
libasr-dev-1.0.0-r0 contains:
usr/lib/libasr.so
usr/include/asr.h

Complete configure log here http://st.ilet.to/osmtpd.log

**Comment by poolpOrg** [comment]
@ericfaurot @clongeau ?

**Comment by poolpOrg** [comment]
@daniel-j-h : i have added a note to the README that libasr is a dependency to OpenSMTPD with a direct link to the latest libasr release tarball.

@ScrumpyJack : your issue is unrelated, we currently don't build on Alpine Linux and there's a ticket opened for that (#495).

I'll close the ticket

**Comment by emanresu88** [comment]
Similar to @ScrumpyJack, I get the following on Centos 7 and Fedora 20.  Is OpenSMTPd known to compile on these platforms?

checking if inet_net_pton will link... no
checking for inet_net_pton in -lresolv... yes
checking if programs using libevent functions will link... no
./configure: line 19213: test: =: unary operator expected
checking for asr.h... yes
checking for asr_resolver in -lasr... no
configure: error: *** libasr missing - please install first or check config.log ***

**Comment by dfateyev** [comment]
@emanresu88 Yes, it is. Please see the official "opensmtpd" packages in standard Fedora repos, and in EPEL for RHEL6 and 7.

**Comment by brilnius** [comment]
FYI, I got the same error message "libasr missing", even after libasr installation.
It disappeared after libevent installation. Maybe a little issue in configure script.
For information, I found this in config.log:
```
configure:19270: checking for asr_resolver in -lasr
configure:19295: gcc -o conftest -g -O2  -fPIC -DPIC -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset    conftest.c -lasr  -levent -lcrypto -lssl -lz -lnsl  -lcrypt -lresolv >&5
/usr/bin/ld: cannot find -levent
```
It was on Linut Mint Debian Edition, using opensmtpd-5.7.3p1.tar.gz.

**Comment by dfateyev** [comment]
@brilnius first of all, `libevent` is a known dependency for opensmtpd, so it should present all in all. There could be a bit misleading message in theory but it never happens when dependencies are resolved according the list in README file.

**Comment by brilnius** [comment]
@dfateyev please don't see any reproach in my message. I only wanted to pass some information.
It seems that I was not the first one. So if other people come across the same problem they will probably end up on this page (like me) and this might be helpful to them.

**Comment by htinaunglu** [comment]
As per my experience,
installing `libasr-devel` solved the entire problem.

**Comment by dfateyev** [comment]
> installing `libasr-devel` solved the entire problem.

@htinaunglu this is no more actual: opensmtpd features a bundled version of `libasr` now.

**Comment by omar-polo** [comment]
Exactly.  The libasr repository was archived and OpenSMTPD bundles its own copy of it, even if found on the system.
