### ISSUE TITLE
Configtest mode doesn't detect an invalid key for queue encryption

### ISSUE THREAD

**Issue by breard-r** [OpenSMTPD/OpenSMTPD#525]
When a queue encryption key isn't a 16-byte random one in hexadecimal representation, `smtpd -n` fails to detect the error:

    -> cat /etc/smtpd/smtpd-invalid.conf
    listen on localhost
    queue encryption key invalid_key
    accept for local deliver to mbox
    -> smtpd -nf /etc/smtpd/smtpd-invalid.conf
    configuration OK

The invalid key will be detected only when smtpd will fail to start-up/restart, raising the following error: `fatal: crypto_setup: invalid key for queue encryption`

**Comment by poolpOrg** [comment]
Unable to test right now as I broke my operating system and can't build OpenSMTPD...

Can you apply the following diff and confirm that it fixes this issue ?

https://gist.github.com/poolpOrg/dbebb4b371cdc8cc7b46

I'll commit tomorrow if you confirm it does or if I fix my system and can test myself.

**Comment by breard-r** [comment]
Seems good to me, thanks! :)

    -> smtpd -nf /etc/smtpd/smtpd-invalid.conf
    fatal: crypto_setup: invalid key for queue encryption
    -> smtpd -nf /etc/smtpd/smtpd.conf # Valid config file
    configuration OK

**Comment by poolpOrg** [comment]
ok, committed
