### ISSUE TITLE
SIGSEGV on 5.4.4p1

### ISSUE THREAD

**Issue by breard-r** [OpenSMTPD/OpenSMTPD#526]
Since I upgraded OpenSMTPD from 5.4.2p1 to 5.4.4p1 (ArchLinux official packages), smtpd crashed when receiving an email and on start-up if the queue contains an email. Downgrading OpenSMTPD works fine, queued messages that were stuck because of the crash are delivered correctly. In both cases I used libasr 1.0.0.

    -> sudo strace -o smtpd -ff -tt smtpd -d
    -> ls smtpd.*
    smtpd.14596  smtpd.14597  smtpd.14598  smtpd.14599  smtpd.14600  smtpd.14601  smtpd.14602  smtpd.14603
    -> tail smtpd.14599
    21:29:56.570343 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"d\4\0\0\20\0\2\0\304\321\266T\0079\0\0\0\0\4\3\1\0\0\0I\0\1\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 3376
    21:29:56.570392 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"`\4\0\0\20\0\2\0\304\321\266T\0079\0\0\0\0\376\377\4\0\0\0\321\20\1\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 1120
    21:29:56.570419 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"\24\0\0\0\3\0\2\0\304\321\266T\0079\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 20
    21:29:56.570443 sendto(4, "\24\0\0\0\26\0\1\3\305\321\266T\0\0\0\0\0\0\0\0", 20, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 20
    21:29:56.570470 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"L\0\0\0\24\0\2\0\305\321\266T\0079\0\0\2\10\200\376\1\0\0\0\10\0\1\0\177\0\0\1"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 244
    21:29:56.570498 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"H\0\0\0\24\0\2\0\305\321\266T\0079\0\0\n\200\200\376\1\0\0\0\24\0\1\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 216
    21:29:56.570523 recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"\24\0\0\0\3\0\2\0\305\321\266T\0079\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 20
    21:29:56.570552 close(4)                = 0
    21:29:56.570578 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
    21:29:56.570805 +++ killed by SIGSEGV +++

Because the packaged binary is stripped, I re-built it the exact same way using the [ArchLinux tools](https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/opensmtpd), but without stripping it. Then, I ran it with valgrind:

    -> sudo valgrind --track-origins=yes --trace-children=yes ./smtpd.debug -d 2>valgrind.err.log
    -> cat valgrind.err.log
    […]
    smtp-in: Closing session 011b96cbd990f592
    ==20863== Invalid read of size 2
    ==20863==    at 0x51FCA7E: ??? (in /usr/lib/libasr.so.0.0.0)
    ==20863==    by 0x51F88C2: asr_run (in /usr/lib/libasr.so.0.0.0)
    ==20863==    by 0x446FAA: event_asr_dispatch (in /home/rodolphe/tmp/smtpd.debug)
    ==20863==    by 0x5415240: event_base_loop (in /usr/lib/libevent-2.0.so.5.1.9)
    ==20863==    by 0x41510B: lka (in /home/rodolphe/tmp/smtpd.debug)
    ==20863==    by 0x406DFE: main (in /home/rodolphe/tmp/smtpd.debug)
    ==20863==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
    ==20863==
    ==20863==
    ==20863== Process terminating with default action of signal 11 (SIGSEGV)
    ==20863==  Access not within mapped region at address 0x0
    ==20863==    at 0x51FCA7E: ??? (in /usr/lib/libasr.so.0.0.0)
    ==20863==    by 0x51F88C2: asr_run (in /usr/lib/libasr.so.0.0.0)
    ==20863==    by 0x446FAA: event_asr_dispatch (in /home/rodolphe/tmp/smtpd.debug)
    ==20863==    by 0x5415240: event_base_loop (in /usr/lib/libevent-2.0.so.5.1.9)
    ==20863==    by 0x41510B: lka (in /home/rodolphe/tmp/smtpd.debug)
    ==20863==    by 0x406DFE: main (in /home/rodolphe/tmp/smtpd.debug)
    ==20863==  If you believe this happened as a result of a stack
    ==20863==  overflow in your program's main thread (unlikely but
    ==20863==  possible), you can try to increase the size of the
    ==20863==  main thread stack using the --main-stacksize= flag.
    ==20863==  The main thread stack size used in this run was 8388608.
    ==20863==
    ==20863== HEAP SUMMARY:
    ==20863==     in use at exit: 437,387 bytes in 3,454 blocks
    ==20863==   total heap usage: 3,834 allocs, 380 frees, 650,454 bytes allocated
    ==20863==
    ==20863== LEAK SUMMARY:
    ==20863==    definitely lost: 307 bytes in 21 blocks
    ==20863==    indirectly lost: 490 bytes in 14 blocks
    ==20863==      possibly lost: 0 bytes in 0 blocks
    ==20863==    still reachable: 436,590 bytes in 3,419 blocks
    ==20863==         suppressed: 0 bytes in 0 blocks
    ==20863== Rerun with --leak-check=full to see details of leaked memory
    […]

**Comment by poolpOrg** [comment]
@ericfaurot needs to have a look at this ;-)

**Comment by kyrias** [comment]
I can confirm that I also has this issue. Currently downgraded to 5.4.2, but will be up for testing any fixes.

**Comment by kyrias** [comment]
I just did a quick bisect, though it was a bit annoying since a lot of the commits doesn't have portable-makefiles and such, but it breaks somewhere between 5234247 and 4052d6e

**Comment by kyrias** [comment]
Actually, disregard that, I can't reproduce this with opensmtpd-5.4.4p1 from git. Will try again with the release tarball.

**Comment by poolpOrg** [comment]
Issue not forgotten, I haven't been able to reproduce yet.

If either one of you can hand me access to a machine that reproduces the crash with sudo access I will debug asap

**Comment by poolpOrg** [comment]
This is being investigated with @breard-r, more informations coming soon.

**Comment by kyrias** [comment]
I could probably provide access if still needed.

**Comment by poolpOrg** [comment]
No need, issue was spotted and solved, thanks @breard-r  ;-)

The problem lies in libasr, not OpenSMTPD, I will commit the fix on github in a minute and publish a new libasr snapshot.

Either @ericfaurot or I will publish a new libasr minor release tomorrow

**Comment by breard-r** [comment]
It's been a pleasure :)  Thank you :+1:
