### ISSUE TITLE
hostnames

### ISSUE THREAD

**Issue by edgarpettijohn** [OpenSMTPD/OpenSMTPD#527]
Openbsd 5.6 through current
with this:
listen on egress hostnames { foo.bar, bar.baz }
I get this:
# /etc/rc.d/smtpd restart                                                                          
smtpd(ok)
smtpd(failed)
# /usr/sbin/smtpd -d
/etc/mail/smtpd.conf:9: invalid use of table "<dynamic:0>" as HOSTNAMES parameter

**Comment by edgarpettijohn** [comment]
Sorry about the font size copy/paste has weird results for me sometimes.

**Comment by poolpOrg** [comment]
Hmmm I must admit I implemented this with use of !dynamic tables in mind I may have forgotten to allow dynamic tables.

I'll have a look and fix in a few minutes.

**Comment by poolpOrg** [comment]
Err,

Sorry this is not a bug but a config error.

The `listen` configuration knob allows you to declare which hostname it will run under using the `hostname` option:

    # we are mx1.foobar.com, say so in banner and bounces
    listen on egress hostname mx1.foobar.com

If you run multiple IP addresses and want to advertise different hostnames, you can use the `hostnames` option which takes a table. However, as smtpd.conf(5) mentions:

                     [...] the hostnames
                     parameter may be specified to advertise a hostname based
                     on the source address.  Table names contains a mapping of
                     IP addresses to hostnames and smtpd(8) will automatically
                     select the name that matches its source address when
                     connected to the remote server.

Your example declares the table as a list of hostnames, not a mapping of IP to hostnames:

    listen on egress hostnames { foo.bar, bar.baz }

so OpenSMTPD doesn't know which hostname it should reply as.
