### ISSUE TITLE
Authentication temporarily failed for user user@domain

### ISSUE THREAD

**Issue by mohshami** [OpenSMTPD/OpenSMTPD#530]
Hi guys,

Running opensmtpd-5.4.2_4,1 on FreeBSD 10.0-RELEASE. With the following smtpd.conf file

<pre>
#PKI file locations
pki mailsrv.example.com certificate "/usr/local/etc/mail/cert/cert"
pki mailsrv.example.com key "/usr/local/etc/mail/cert/key"

# Accept email for these domains and recipients
table vdomains "file:/usr/local/etc/mail/vdomains"
table recipients "file:/usr/local/etc/mail/recipients"

# If you edit the file, you have to run "smtpctl update table aliases"
table aliases file:/etc/mail/aliases

# File where encrypted passwords are stored
table local_user_list passwd:/usr/local/etc/mail/passwd

# Listen for user logins on submission port
listen on 0.0.0.0 port submission tls pki mailsrv.example.com auth <local_user_list> hostname "mailsrv.example.com"

# To accept external mail
listen on 0.0.0.0

# Accept signed emails
listen on localhost port 10028 tag DKIM mask-source

# Forward incoming emails to Dovecot via LMTP
accept from any for domain <vdomains> recipient <recipients> relay via lmtp://127.0.0.1:2525

# Forward emails to local accounts to their MBOXs
accept for local alias <aliases> deliver to mbox

# Relay signed emails
accept tagged DKIM for any relay

# If an email was sent locally or through an authenticated user, sign
accept for any relay via smtp://127.0.0.1:10027
</pre>

And the following passwd file
<pre>
user1@example.com:$6$aoiuasdfhalsdfiu$2K1Ck/C/FKHeU5wqftVRuuQralARHm2EhAAxc1N3cOFfR4cggSGunhuWnJ3.SxB28h1B4b8oI6vXBxnPirJgB1:1001:1001::/vmail:/bin/nologin
users2@example.com:$6$aoiuasdfhalsdfiu$dsAcqmmDZl9CAcn78GrS6vck19iNx7aRE3UNkxrZWy/lDgQg0KDh.MgmJxxpfSTLWgSYpRC1RhGgTqubb8QM/1:1001:1001::/vmail:/bin/nologin
users3@test.com:$6$aoiuasdfhalsdfiu$wUDPF8uwDCPzw4HpcxlQTOI8JarPNVSFSG.p112Qi8ysBVrxLHYTcrGx1xZSM3ayEp1/8sAY0nX.OhMVubFH31:1001:1001::/vmail:/bin/nologin
</pre>

The first time a user tries to send an email, I get the following in the logs
<pre>
warn: user credentials lookup fail for local_user_list:user1@example.com
</pre>

Any emails sent afterwards are relayed normally.

**Comment by poolpOrg** [comment]
Hi,

I'm actually wondering if this issue isn't a side effect of another bug which was fixed after 5.4.2 was released (see: https://github.com/OpenSMTPD/OpenSMTPD-extras/commit/0c6f50979d56302540c4994b6f3843a61a712122)

Can you try rebuilding with table_passwd.c from: https://github.com/OpenSMTPD/OpenSMTPD-extras/blob/master/extras/tables/table-passwd/table_passwd.c

I suspect your bug will go away

**Comment by mohshami** [comment]
Hey man,

Now authentication fails all together

smtp-in: Authentication failed for user user1@example.com on session c510685ebd1fd47f

**Comment by poolpOrg** [comment]
fuck, i think the table_passwd.c from 5.4.4 and above has an incompatibility with 5.4.2 ...

I'm currently running a 5.4.4 opensmtpd and experience no problem with it :-/

**Comment by mohshami** [comment]
I'm currently running opensmtpd-5.4.2_4,1 through the FreeBSD ports.

Are there any special steps to compiling 5.4.4 on FreeBSD?

**Comment by sysfu** [comment]
The only special step (other than building and installing libasr first) is to add a few options to the configure command

```./configure --with-libevent-dir=/usr/local --sysconfdir=/usr/local/etc/mail/ --with-ssl-dir=/usr/local --with-mailwrapper```

**Comment by poolpOrg** [comment]
The FreeBSD maintainer has packaged 5.4.4 yesterday :-)

**Comment by mohshami** [comment]
Awesome, will check now :)

**Comment by mohshami** [comment]
Sadly it didn't work,

fatal: table_create: backend "passwd" does not exist

Installed from binary package as well as ports.

Changed the table type to file and no luck :(

**Comment by poolpOrg** [comment]
On Sun, Feb 15, 2015 at 01:19:32AM -0800, mohshami wrote:
> Sadly it didn't work,
> 
> fatal: table_create: backend "passwd" does not exist
> 
> Installed from binary package as well as ports.
> 
> Changed the table type to file and no luck :(
> 

Any chance you could pass by on IRC so we can troubleshoot together ?

#OpenSMTPD @ freenode

I'll be staying around all day

-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by poolpOrg** [comment]
So:

- Authentication failure was actually no longer a problem in latest table_passwd
- I fixed packaging of portable opensmtpd-extras so it works with FreeBSD
- while at it, I allowed empty lines in passwd maps + commenting a line

OP confirmed he no longer experiences issues, closing ticket
