### ISSUE TITLE
smtpd quits with poi

### ISSUE THREAD

**Issue by geepie** [OpenSMTPD/OpenSMTPD#540]
Without pki, the server is running without trouble.
When I add a pki, the daemon quits.

# uname -a
OpenBSD smtp2.rilk.com 5.6 GENERIC#5 amd64

# cat /etc/mail/smtpd.conf
pki smtp2.rilk.com certificate "/etc/mail/certs/smtp2cert.pem"
pki smtp2.rilk.com key "/etc/mail/certs/smtp2key.pem"
listen on lo0 port 10026 tag CLAM
listen on egress hostname smtp2.rilk.com
accept tagged CLAM for any relay
table ip_jgp {...}
table sender_jgp {...}
accept from source < ip_jgp > sender < sender_jgp > for any relay via smtp://127.0.0.1:10025

# smtpd -n
configuration OK

# /etc/rc.d/smtpd start                                                                                                                                      
smtpd(ok)

# tail -f /var/log/maillog
Feb 11 10:39:03 smtp2 smtpd[9891]: info: OpenSMTPD 5.4.3 starting
Feb 11 10:39:03 smtp2 smtpd[6965]: info: startup
Feb 11 10:39:03 smtp2 smtpd[6965]: warn: lost child: pony express terminated; signal 10
Feb 11 10:39:03 smtp2 smtpd[12743]: warn: lka -> pony: pipe closed
Feb 11 10:39:03 smtp2 smtpd[6376]: info: scheduler handler exiting
Feb 11 10:39:03 smtp2 smtpd[10002]: warn: queue -> pony: pipe closed
Feb 11 10:39:03 smtp2 smtpd[29713]: info: ca agent exiting
Feb 11 10:39:03 smtp2 smtpd[12565]: info: control process exiting
Feb 11 10:39:03 smtp2 smtpd[6965]: warn: parent terminating

# smtpd -dv            
debug: init ssl-tree
info: loading pki information for smtp2.rilk.com
info: OpenSMTPD 5.4.3 starting
debug: bounce warning after 4h
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
info: startup [debug mode]
debug: parent_send_config_ruleset: reloading
debug: ca_engine_init: using RSAX engine support
debug: init ssl-tree
debug: parent_send_config: configuring pony process
info: loading pki keys for smtp2.rilk.com
debug: parent_send_config: configuring ca process
debug: smtp: listen on 108.61.177.81 port 25 flags 0x400 pki ""
debug: init private ssl-tree
debug: smtp: listen on 127.0.0.1 port 10026 flags 0x400 pki ""
debug: smtp: listen on IPv6:fe80::1%lo0 port 10026 flags 0x400 pki ""
debug: smtp: listen on IPv6:::1 port 10026 flags 0x400 pki ""
warn: parent -> pony: pipe closed
warn: lka -> pony: pipe closed
warn: control -> pony: pipe closed
warn: ca -> pony: pipe closed
warn: scheduler -> control: pipe closed
warn: queue -> pony: pipe closed

**Comment by poolpOrg** [comment]
strange, are your certs RSA ?

**Comment by geepie** [comment]
Cert is DSA.

Errors from /var/log/maillog

Feb  3 05:45:10 smtp3 smtpd[19912]: smtp-out: Connecting to smtp+tls://145.226.35.30:25 (smtp1-inzi.e-i.net) on session 57af4dc2f62890b8...
Feb  3 05:45:10 smtp3 smtpd[19912]: smtp-out: Connected on session 57af4dc2f62890b8
Feb  3 05:45:11 smtp3 smtpd[19912]: smtp-out: Error on session 57af4dc2f62890b8: IO Error: error:1407741A:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert decode error

**Comment by poolpOrg** [comment]
On Thu, Feb 12, 2015 at 06:39:31AM -0800, geepie wrote:
> Cert is DSA.
> 
> Errors from /var/log/maillog
> 
> Feb  3 05:45:10 smtp3 smtpd[19912]: smtp-out: Connecting to smtp+tls://145.226.35.30:25 (smtp1-inzi.e-i.net) on session 57af4dc2f62890b8...
> Feb  3 05:45:10 smtp3 smtpd[19912]: smtp-out: Connected on session 57af4dc2f62890b8
> Feb  3 05:45:11 smtp3 smtpd[19912]: smtp-out: Error on session 57af4dc2f62890b8: IO Error: error:1407741A:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert decode error
> 

After heartbleed the code to deal with private keys has been privsep-ed
by reyk@, unfortunately it only supports RSA:

   https://github.com/OpenSMTPD/OpenSMTPD/issues/490


-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by geepie** [comment]
Hi Gilles,

With RSA Keys, ti works !
A better message in log would be helpful !

Cordialement,
Jean-Gérard Pailloncy

**Comment by poolpOrg** [comment]
Indeed, however DSA wasn't meant to be broken in the first place ;-)
