### ISSUE TITLE
‘struct dirent’ has no member named ‘d_namlen’

### ISSUE THREAD

**Issue by lhecker** [OpenSMTPD/OpenSMTPD#542]
https://github.com/OpenSMTPD/OpenSMTPD/commit/488d3a49a428d25a2dfdc4afc340b55b3c968ce3#diff-6641255a80b4407d59eaf41c20a64b38R386 introduces a regression:
Since "d_namlen" is not specified in POSIX, this is probably not going to compile on most systems (tested on Ubuntu 14.10).

`dp->d_namlen != 16` needs to be either removed or replaced with something else. AFAIK `d_namlen` is technically the same as `strlen(dp->d_name)`, while `strncmp(dp->d_name, msgid_str, 8)` is used just after that. Therefore you could also just replace it with:
```c
if (strlen(dp->d_name) != 16 || memcmp(dp->d_name, msgid_str, 8) != 0) {
    continue;
}
```

I think this should fix the issue and be about as fast or faster as the previous solution, since `strncmp` checks for \0 in both strings too.

**Comment by lhecker** [comment]
BTW: There is another build error since `SSL_CTX_use_certificate_chain` got renamed to `SSL_CTX_use_certificate_chain_mem`, which is a function that does not exist in OpenSSL, but only LibreSSL. But I'm not sure if this is a real bug, which I should submit, or working as intended. Fact is that it's not building the project without modifying the code to match OpenSSL.

**Comment by poolpOrg** [comment]
Can you open a different ticket for the openssl issue ?

I have worked on it yesterday so I'll look at it separately.

**Comment by poolpOrg** [comment]
fix applied to remove d_namlen and replace it with strlen(), thanks
