### ISSUE TITLE
Add connection tagging to Filter API

### ISSUE THREAD

**Issue by jirutka** [OpenSMTPD/OpenSMTPD#545]
It would be very useful to be able to _tag_ a connection in filter. Then we could use these tags in accept/reject rules.

**Comment by jirutka** [comment]
@poolpOrg What do you think about this feature? Is there any chance that it will be implemented soon?

**Comment by poolpOrg** [comment]
On Wed, Jun 03, 2015 at 11:55:17AM -0700, Jakub Jirutka wrote:
> @poolpOrg What do you think about this feature? Is there any chance that it will be implemented soon?
> 

Yes it has a chance of being implemented but not for this upcoming
release which will essentially contain the plumbing.

We're currently in a feature freeze until the July, at which point
we can extend the filter API and the features will be part of
later minor versions



-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by jirutka** [comment]
Great, thanks for answer!

**Comment by poolpOrg** [comment]
This will be handled as part of #773 which is assigned, closing the ticket as it is referenced there
