### ISSUE TITLE
OpenSMTPD portable 5.4.4p1 with LibreSSL portable 2.1.4 does not detect arc4random and arc4random_buf

### ISSUE THREAD

**Issue by rodyakin** [OpenSMTPD/OpenSMTPD#547]
The configure script fails to detect the presence of the arc4random and the arc4random_buf on Linux with system libcrypto coming from LibreSSL.  This results in building the internal versions of these functions (in openbsd-compat/arc4random.c ), which in turn results in a runtime bus error when running makemap or smtpctl encrypt -- since the encrypt utility is dynamically linked against libcrypto.  Adding "--with-libs=-lcrypto" to the configure arguments fixes the issue; but this should probably be handled automatically by the configure script.

$ ./configure 2>&1 | grep arc4
checking for arc4random... no
checking for arc4random_buf... no
checking for arc4random_stir... no
checking for arc4random_uniform... no

$ ./configure --with-libs=-lcrypto 2>&1 | grep arc4
checking for arc4random... yes
checking for arc4random_buf... yes
checking for arc4random_stir... no
checking for arc4random_uniform... no

**Comment by poolpOrg** [comment]
This is fixed and committed, will be part of next snapshot and major release.
