### ISSUE TITLE
mail.local and _PATH_MAILDIR

### ISSUE THREAD

**Issue by ajacoutot** [OpenSMTPD/OpenSMTPD#548]
Hi.

The mail.local in contrib ignores the --with-maildir configure flags and uses _PATH_MAILDIR from includes unconditionally. So when using mbox and MAILDIR does not exist, mail.local hangs forever trying to deliver to a non-existent directory.

**Comment by poolpOrg** [comment]
This no longer seems to be the case with current version of our master branch.

I have built with maildir set to /tmp and verified that _PATH_MAILDIR was properly set, closing the ticket.
