### ISSUE TITLE
Separate foregrounding and logging to stderr

### ISSUE THREAD

**Issue by chneukirchen** [OpenSMTPD/OpenSMTPD#550]
In the vein of #191: Modern init systems prefer when programs do not daemonize, but logging to syslog would still be appreciated due to more precise priorities than on stderr.

**Comment by poolpOrg** [comment]
You can now start OpenSMTPD with the -F option which will allow it to run foreground while retaining logging to syslog.

This has been committed to github, will be part of next snapshot and major release

**Comment by chneukirchen** [comment]
Thank you very much.

**Comment by chneukirchen** [comment]
I just realized its released now, but not mentioned in the manpage.

**Comment by poolpOrg** [comment]
indeed, please open a separate ticket and tag it as documentation & bug, we'll get this fixed
