### ISSUE TITLE
Configurable lookup in query for *sql backend

### ISSUE THREAD

**Issue by mischapeters** [OpenSMTPD/OpenSMTPD#552]
Currently the question marks are statically defined to either use the left hand side to the right hand side of an email address for the SQL lookup.

When hosting a lot of domains virtually it would be great if this could be configurable so the complete email address can be used as well. All my user information is currently stored as ```user@domain.tld``` and not ```user```.

This makes db maintenance also a lot easier imo. With the current query option with a lot of domains you would have a lot of duplicate entries. For example with a 100+ domains you would have 100 times "postmaster", "hostmaster", "abuse", "info", in the db tables.

When using the complete email address these entries would be:
- ```hostmaster@domain1.tld```
- ```hostmaster@domain2.tld```
- ...
- ```hostmaster@domain100.tld```

Storing it this way would prevent a lot of complicated queries. :)

**Comment by poolpOrg** [comment]
Isn't this the same as #480 by the way ?

**Comment by mischapeters** [comment]
Yes, that is indeed the same. You mentioned in your comments that it would be a nice feature. I would argue it's a must have feature! :)

**Comment by poolpOrg** [comment]
'k, I'll close this ticket as it is a duplicate and it confused me, the other one stays open and references this one now.

**Comment by mischapeters** [comment]
No problem. What confused you? Useful to know for the next time.

**Comment by poolpOrg** [comment]
I was just confused because since the other ticket described the same feature differently, I didn't know if you were asking for a different feature or not ;-)

**Comment by mischapeters** [comment]
I guess I missed your own feature request. :)
But good to see that you are looking at it. For now it's the only thing that is stopping me from going full production with OpenSMTPD.

The queries that I using in Postfix at the moment are:
Aliases: query = SELECT alias FROM aliases WHERE address = '%s' AND active='1'
Domains: query = SELECT domain AS virtual FROM domains WHERE domain='%s' AND active='1'
Mailboxes: query = SELECT maildir FROM mailboxes WHERE username = '%s' AND active='1'

This was also the reason for my question in regards to static UID and GID. As with virtual mailboxes it makes sense, at least imo, to have a single UID and GID.

Hope this helps.
