### ISSUE TITLE
Wrong user when sending email

### ISSUE THREAD

**Issue by Mitchou** [OpenSMTPD/OpenSMTPD#553]
Hi,
I'm new with OpenSTMPD but I've found something weird on FreeBSD 10.1.
I've install daemon from ports, here the version: OpenSMTPD 5.4.4p1
And here my basic config:

#cat /usr/local/etc/mail/aliases
root:me@myotherdomain.com
admin:me@myotherdomain.com
icinga:me@myotherdomain.com

#cat /usr/local/etc/mail/smtpd.conf
listen on lo0
listen on bge0 hostname mx.mydomain.net
table aliases file:/usr/local/etc/mail/aliases
accept from any for domain mydomain.net alias <aliases> deliver to maildir
accept for local alias <aliases> deliver to maildir
accept for any relay

First, I'm login to my server thought SSH, then when I send mail with "mail", my user (me) is used. Now I do "sudo su -l". Now I'm root and I resend mail with "mail", same user (me). Same result with just "su -l". Idem for Icinga (su -m icinga -> mail (me used)

This is from root:
echo test | mail -v -s "OpenSMTPd Test" admin@mydomain.net
<<< 220 mydomain.net ESMTP OpenSMTPD
>>> EHLO localhost
<<< 250-mydomain.net Hello localhost [local], pleased to meet you
<<< 250-8BITMIME
<<< 250-ENHANCEDSTATUSCODES
<<< 250-SIZE 36700160
<<< 250 HELP
>>> MAIL FROM:<me@mydomain.net>
<<< 250 2.0.0: Ok
>>> RCPT TO:<admin@mydomain.net>
<<< 250 2.1.5 Destination address valid: Recipient ok
>>> DATA
<<< 354 Enter mail, end with "." on a line by itself
>>> .
<<< 250 2.0.0: d29a31ef Message accepted for delivery
>>> QUIT
<<< 221 2.0.0: Bye

From Icinga user:
su -m icinga
echo test | mail -v -s "OpenSMTPd Test" admin@mydomain.net
<<< 220 mydomain.net ESMTP OpenSMTPD
>>> EHLO localhost
<<< 250-mydomain.net Hello localhost [local], pleased to meet you
<<< 250-8BITMIME
<<< 250-ENHANCEDSTATUSCODES
<<< 250-SIZE 36700160
<<< 250 HELP
>>> MAIL FROM:<me@mydomain.net>
<<< 250 2.0.0: Ok
>>> RCPT TO:<admin@mydomain.net>
<<< 250 2.1.5 Destination address valid: Recipient ok
>>> DATA
<<< 354 Enter mail, end with "." on a line by itself
>>> .
<<< 250 2.0.0: 308fd296 Message accepted for delivery
>>> QUIT
<<< 221 2.0.0: Bye

When I'm login directly to ssh with root, mail send correctly with root mail address. 
But for Icinga is very weird, when I launch daemon with root from my session (sudo su -l), alert mail is from my user. But if I launch it from root session (from ssh), root user is used...

I didn't think is normal... :-/

**Comment by poolpOrg** [comment]
This is a bug that was fixed after 5.4.4p1 was released and since no one complained, we didn't publish a patch level release.

I have created a 5.4.4p2 branch and backported the fix to it, I'll check which other minor fixes should be in that patchlevel release and release it next week.

Thanks
