### ISSUE TITLE
Drop Berkeley DB as a required dependency (at least for the portable branch)

### ISSUE THREAD

**Issue by vaygr** [OpenSMTPD/OpenSMTPD#557]
I'm fine on OpenBSD boxes with it (since it's included in a basesystem).

But it would be nice to use it on Linux boxes without this dependency. Personally, this is the only reason that prevents me from switching from Exim on several dozens of boxes where its functionality is redundant.

By the way, Exim allows some choice between db, gdbm and tdb. There's also ldbm.
And the projects like OpenLDAP and Postfix dropped db as a required dependency long ago.

I talked to __gilles on IRC about it a week ago or so. And he liked the idea.

**Comment by poolpOrg** [comment]
work in progress in a private branch, should be committed in a few days.

**Comment by poolpOrg** [comment]
committed, will be part of next snapshot and major release

**Comment by vaygr** [comment]
Woah, nice!

Can you point out to the commit/branch that has these corrections? I can't find it.

**Comment by poolpOrg** [comment]
On Thu, May 07, 2015 at 09:37:33AM -0700, Vlad Glagolev wrote:
> Woah, nice!
> 
> Can you point out to the commit/branch that has these corrections? I can't find it.
> 

Yup, the branch is "autohell", I'll let you spot the commits but they're
part of a larger cleanup of configure.ac that I'm not done with yet, you
should not expect them to apply to portable without further work.

It might not be part of next snapshot, but it'll be part of the first we
publish with the new configure.ac and will be part of the next release.


-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg
