### ISSUE TITLE
Add -T trace documentation to smtpd.8

### ISSUE THREAD

**Issue by Sp1l** [OpenSMTPD/OpenSMTPD#566]
The smtpd manpage is missing the `-T trace` option that is available (as can be seen from `smptd -h` invocation).
I'll try my hand at a bit of man-page authoring to provide a patch later.

**Comment by poolpOrg** [comment]
good, please let us know if you make progress on it or give up, i'll tag the ticket as waiting for feedback.

**Comment by Sp1l** [comment]
First time right :D #569 works fine for me on FreeBSD! Copied the texts from other man-pages and includes line-continuation and comments in makemap as well.
Would this also apply to the tables man-pages?

**Comment by poolpOrg** [comment]
nope smtpd(8) is enough.

I'm closing this ticket, your pull request was merged a while ago.
