### ISSUE TITLE
Add tag and or port to smtp trace output

### ISSUE THREAD

**Issue by Sp1l** [OpenSMTPD/OpenSMTPD#568]
Currently you can't see the ip:port specification nor the tag that is associated to an inbound smtp session when trace is enabled. Adding port and tag (when known) on a connection to the logged messages would help.

**Comment by poolpOrg** [comment]
log_trace(SMTP) will now log listener's hostname, port and tag upoin client connection.

This has just been committed, will be part of next snapshot and upcoming release.

**Comment by Sp1l** [comment]
Great, thanks!
