### ISSUE TITLE
Finer grained logging and log control.

### ISSUE THREAD

**Issue by nullstream** [OpenSMTPD/OpenSMTPD#570]
Please look at adding a more fine grained log control to the daemon.

For instance envelope receipt (eg. to,from,where to,where from [ip], size), rejection detail,  session and/or auth failure etc.

Bonus points to direct such details to a different syslog level (ie. envelope goes to .DEBUG, session failures go to .WARN etc).

Double bonus points to HUP config and change detail level without restart (ie. vebrose for debugging).

I really use the above features on qmail to debug spam delivery issues for friends (ie. didn't get X from Y) and use it to determine if issues generated up the chain (ie. spamd, sender) or downstream (spamassassin etc).

**Comment by dfateyev** [comment]
> Double bonus points to HUP config and change detail level without restart (ie. vebrose for debugging).

@nullstream discussed once #332, but anyway I do hope that it will eventually appear.

**Comment by poolpOrg** [comment]
There is ongoing work to improve the logging format.

I don't know yet how much flexibility we'll allow, we're trying to improve the log.c API in a way that allows other daemons to pick up our changes, it needs some thinking.

As for HUP, this is unlikely to happen in a near future for the reasons I explained in #332

**Comment by poolpOrg** [comment]
reading this ticket again, I'm a bit confused:

> For instance envelope receipt (eg. to,from,where to,where from [ip], size), rejection detail, session and/or auth failure etc.

we already log all of these today, maybe I'm misunderstanding what you want.

As for the bonus points:

The "log different kinds of entries to different syslog levels" is not going to happen because this is not what levels are for (we use them already to log warnings, debug and info which is what they're for) and we use a generic logging facility shared with other OpenBSD daemons where it wouldn't make sense. note that if you really want to classify your log lines, syslog can pipe logs into a filter and we add a "scope" to each log line precisely for the purpose of being able to split them in different files.

The HUP config reload without restart is a feature that has been discussed for a long time and there is no plan to support it for now because it is LOTS of kludge for very little profit. If someone has a way to add support for this, I'll be happy to review and integrate but it has to be a nice and fully working solution.

**Comment by nullstream** [comment]
On May 22, 2016, at 12:24 PM, Gilles Chehade <notifications@github.com> wrote:
> 
> reading this ticket again, I'm a bit confused:
> 
> For instance envelope receipt (eg. to,from,where to,where from [ip], size), rejection detail, session and/or auth failure etc.
> 
> we already log all of these today, maybe I'm misunderstanding what you want.

That is correct, at the time I asked I could not see that in the logs I had.
Looking at systems today with more recent versions of smtpd this is clear that what I was looking for is available.

> 
> As for the bonus points:
> 
> The "log different kinds of entries to different syslog levels" is not going to happen because this is not what levels are for (we use them already to log warnings, debug and info which is what they're for) and we use a generic logging facility shared with other OpenBSD daemons where it wouldn't make sense. note that if you really want to classify your log lines, syslog can pipe logs into a filter and we add a "scope" to each log line precisely for the purpose of being able to split them in different files.
> 
> The HUP config reload without restart is a feature that has been discussed for a long time and there is no plan to support it for now because it is LOTS of kludge for very little profit. If someone has a way to add support for this, I'll be happy to review and integrate but it has to be a nice and fully working solution.

Your intention and perspective is perfectly clear.
Close your issue/ticket/whatever it is called.

Apologies for wasting your time.

--
Sean

**Comment by poolpOrg** [comment]
No time wasted, just got a tiny bit confused 😀
Le 25 mai 2016 5:54 AM, Sean Cody <notifications@github.com> a écrit :On May 22, 2016, at 12:24 PM, Gilles Chehade <notifications@github.com> wrote:
> 
> reading this ticket again, I'm a bit confused:
> 
> For instance envelope receipt (eg. to,from,where to,where from [ip], size), rejection detail, session and/or auth failure etc.
> 
> we already log all of these today, maybe I'm misunderstanding what you want.

That is correct, at the time I asked I could not see that in the logs I had.
Looking at systems today with more recent versions of smtpd this is clear that what I was looking for is available.

> 
> As for the bonus points:
> 
> The "log different kinds of entries to different syslog levels" is not going to happen because this is not what levels are for (we use them already to log warnings, debug and info which is what they're for) and we use a generic logging facility shared with other OpenBSD daemons where it wouldn't make sense. note that if you really want to classify your log lines, syslog can pipe logs into a filter and we add a "scope" to each log line precisely for the purpose of being able to split them in different files.
> 
> The HUP config reload without restart is a feature that has been discussed for a long time and there is no plan to support it for now because it is LOTS of kludge for very little profit. If someone has a way to add support for this, I'll be happy to review and integrate but it has to be a nice and fully working solution.

Your intention and perspective is perfectly clear.
Close your issue/ticket/whatever it is called.

Apologies for wasting your time.

--
Sean
