### ISSUE TITLE
can't use pki key file protected

### ISSUE THREAD

**Issue by bsdsx** [OpenSMTPD/OpenSMTPD#589]
when i use a pki key file protected by a password, i get prompt only with -d or -n flag.
without flag, smtpd fail with:

fatal: load_pki_keys: failed tout load key file

**Comment by bsdsx** [comment]
Forgot version:

dsx@mini>uname -a
OpenBSD mini.bsdsx.fr 5.7 GENERIC#443 macppc
dsx@mini>/usr/sbin/smtpd -h
version: OpenSMTPD 5.4.4
usage: smtpd [-dhnv] [-D macro=value] [-f file] [-P system] [-T trace]

**Comment by snimmagadda** [comment]
This is now fixed in master branch. Please test using the latest code.

**Comment by bsdsx** [comment]
Hello,

I'm sorry but after test, i confirm my issue.

smtpd.c:702 if (daemon(0, 0) == -1)

at this point, no stdio/stdout/stderr

smtpd.c:720 fork_peers();

smtpd.c:833 post_fork(PROC_PARENT);

smtpd.c: 850   if (proc == PROC_CA) {
    load_pki_keys();
  }
load_pki_keys will fail because there is no stdio for read passphrase

**Comment by bsdsx** [comment]
s/stdio/stdin/g

**Comment by snimmagadda** [comment]
Hi, those line numbers aren't in sync with latest code. Please make sure your repository is in sync with latest code.

**Comment by bsdsx** [comment]
Hi, sorry for inconvenience, my sources come from 
https://www.opensmtpd.org/archives/opensmtpd-portable-latest.tar.gz
who's not sync whith master.

After read master and portable sources , i close this issue (load_pki_keys is call before daemon).
