### ISSUE TITLE
opensmtpd refuses to contact ipv4 smarthosts when DNS returns A and AAAA records

### ISSUE THREAD

**Issue by Alexander237** [OpenSMTPD/OpenSMTPD#624]
Dear SIrs.
We have issue with opensmtpd-5.7.1 (FreeBSD 10.1-RELEASE-p15)  configured to forward all email messages via outlook.office365 smart host.
Details of the issue and steps to reproduce:
all email goes to smarthost
% nslookup outlook.office365.com
Non-authoritative answer:
Name:    outlook-emeaeast.office365.com
Addresses:  2a01:111:f400:5175::2
          2a01:111:f400:5323::2
          2a01:111:f400:8014::2
          2a01:111:f400:882c::2
          2a01:111:f400:9828::2
          2a01:111:f400:8414::2
          2a01:111:f400:8828::2
          2a01:111:f400:f380::2
          132.245.34.34
          132.245.74.114
          132.245.61.226
          191.234.224.2
          134.170.68.82
          132.245.51.50
          132.245.56.114
Aliases:  outlook.office365.com
          lb.geo.office365.com
          outlook.office365.com.g.office365.com
opensmtpd starts endless loop of unsuccessful connecting to ipv6 addresses and do not try to connect smart host by ipv4 address. Workaround is to remove nameservers from /etc/resonv.conf and to add ip4 addresses of smart host to /etc/hosts.

Log:
Jul 22 00:20:30 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:882c::2 (2a01:111:f400:882c::2)
Jul 22 00:20:31 rgt001sm smtpd[667]: smtp-out: session b316ff9d39ce9d3f: connecting to tls://IPv6:2a01:111:f400:882c::2:587 (2a01:111:f400:882c::2)
Jul 22 00:20:31 rgt001sm smtpd[667]: smtp-out: session b316ff9d39ce9d3f: error: Connection failed: No route to host
Jul 22 00:20:31 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:882c::2 (2a01:111:f400:882c::2) for 15s
Jul 22 00:20:32 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:8014::2 (2a01:111:f400:8014::2)
Jul 22 00:20:33 rgt001sm smtpd[667]: smtp-out: session b316ff9e2b015b8b: connecting to tls://IPv6:2a01:111:f400:8014::2:587 (2a01:111:f400:8014::2)
Jul 22 00:20:33 rgt001sm smtpd[667]: smtp-out: session b316ff9e2b015b8b: error: Connection failed: No route to host
Jul 22 00:20:33 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:8014::2 (2a01:111:f400:8014::2) for 15s
Jul 22 00:20:34 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:5175::2 (2a01:111:f400:5175::2)
Jul 22 00:20:35 rgt001sm smtpd[667]: smtp-out: session b316ff9fc06c2cfc: connecting to tls://IPv6:2a01:111:f400:5175::2:587 (2a01:111:f400:5175::2)
Jul 22 00:20:35 rgt001sm smtpd[667]: smtp-out: session b316ff9fc06c2cfc: error: Connection failed: No route to host
Jul 22 00:20:35 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:5175::2 (2a01:111:f400:5175::2) for 15s
Jul 22 00:20:36 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:8828::2 (2a01:111:f400:8828::2)
Jul 22 00:20:37 rgt001sm smtpd[667]: smtp-out: session b316ffa01aa0d882: connecting to tls://IPv6:2a01:111:f400:8828::2:587 (2a01:111:f400:8828::2)
Jul 22 00:20:37 rgt001sm smtpd[667]: smtp-out: session b316ffa01aa0d882: error: Connection failed: No route to host
Jul 22 00:20:37 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:8828::2 (2a01:111:f400:8828::2) for 15s
Jul 22 00:20:38 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:f380::2 (2a01:111:f400:f380::2)
Jul 22 00:20:39 rgt001sm smtpd[667]: smtp-out: session b316ffa177f19571: connecting to tls://IPv6:2a01:111:f400:f380::2:587 (2a01:111:f400:f380::2)
Jul 22 00:20:39 rgt001sm smtpd[667]: smtp-out: session b316ffa177f19571: error: Connection failed: No route to host
Jul 22 00:20:39 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:f380::2 (2a01:111:f400:f380::2) for 15s
Jul 22 00:20:40 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:9828::2 (2a01:111:f400:9828::2)
Jul 22 00:20:41 rgt001sm smtpd[667]: smtp-out: session b316ffa2d75a7c07: connecting to tls://IPv6:2a01:111:f400:9828::2:587 (2a01:111:f400:9828::2)
Jul 22 00:20:41 rgt001sm smtpd[667]: smtp-out: session b316ffa2d75a7c07: error: Connection failed: No route to host
Jul 22 00:20:41 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:9828::2 (2a01:111:f400:9828::2) for 15s
Jul 22 00:20:42 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:8414::2 (2a01:111:f400:8414::2)
Jul 22 00:20:43 rgt001sm smtpd[667]: smtp-out: session b316ffa36cf94fa0: connecting to tls://IPv6:2a01:111:f400:8414::2:587 (2a01:111:f400:8414::2)
Jul 22 00:20:43 rgt001sm smtpd[667]: smtp-out: session b316ffa36cf94fa0: error: Connection failed: No route to host
Jul 22 00:20:43 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:8414::2 (2a01:111:f400:8414::2) for 15s
Jul 22 00:20:44 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:5323::2 (2a01:111:f400:5323::2)
Jul 22 00:20:45 rgt001sm smtpd[667]: smtp-out: session b316ffa4e4b513ac: connecting to tls://IPv6:2a01:111:f400:5323::2:587 (2a01:111:f400:5323::2)
Jul 22 00:20:45 rgt001sm smtpd[667]: smtp-out: session b316ffa4e4b513ac: error: Connection failed: No route to host
Jul 22 00:20:45 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:5323::2 (2a01:111:f400:5323::2) for 15s
Jul 22 00:20:46 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:882c::2 (2a01:111:f400:882c::2)
Jul 22 00:20:47 rgt001sm smtpd[667]: smtp-out: session b316ffa584f6ca23: connecting to tls://IPv6:2a01:111:f400:882c::2:587 (2a01:111:f400:882c::2)
Jul 22 00:20:47 rgt001sm smtpd[667]: smtp-out: session b316ffa584f6ca23: error: Connection failed: No route to host
Jul 22 00:20:47 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:882c::2 (2a01:111:f400:882c::2) for 15s
Jul 22 00:20:48 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:8014::2 (2a01:111:f400:8014::2)
Jul 22 00:20:49 rgt001sm smtpd[667]: smtp-out: session b316ffa680a5cb51: connecting to tls://IPv6:2a01:111:f400:8014::2:587 (2a01:111:f400:8014::2)
Jul 22 00:20:49 rgt001sm smtpd[667]: smtp-out: session b316ffa680a5cb51: error: Connection failed: No route to host
Jul 22 00:20:49 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:8014::2 (2a01:111:f400:8014::2) for 15s
Jul 22 00:20:50 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:5175::2 (2a01:111:f400:5175::2)
Jul 22 00:20:51 rgt001sm smtpd[667]: smtp-out: session b316ffa789e4aaea: connecting to tls://IPv6:2a01:111:f400:5175::2:587 (2a01:111:f400:5175::2)
Jul 22 00:20:51 rgt001sm smtpd[667]: smtp-out: session b316ffa789e4aaea: error: Connection failed: No route to host
Jul 22 00:20:51 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:5175::2 (2a01:111:f400:5175::2) for 15s
Jul 22 00:20:52 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:8828::2 (2a01:111:f400:8828::2)
Jul 22 00:20:53 rgt001sm smtpd[667]: smtp-out: session b316ffa8dc067bf9: connecting to tls://IPv6:2a01:111:f400:8828::2:587 (2a01:111:f400:8828::2)
Jul 22 00:20:53 rgt001sm smtpd[667]: smtp-out: session b316ffa8dc067bf9: error: Connection failed: No route to host
Jul 22 00:20:53 rgt001sm smtpd[667]: smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:8828::2 (2a01:111:f400:8828::2) for 15s
Jul 22 00:20:54 rgt001sm smtpd[667]: smtp-out: routing: Enabling route [] <-> IPv6:2a01:111:f400:f380::2 (2a01:111:f400:f380::2)
Jul 22 00:20:55 rgt001sm smtpd[667]: smtp-out: session b316ffa98e32161b: connecting to tls://IPv6:2a01:111:f400:f380::2:587 (2a01:111:f400:f380::2)
Jul 22 00:20:55 rgt001sm smtpd[667]: smtp-out: session b316ffa98e32161b: error: Connection failed: No route to host

**Comment by poolpOrg** [comment]
Our DNS expert is on vacation, I'll try to have a look by this week-end

**Comment by poolpOrg** [comment]
Can you confirm which version of libasr you are linking against ?

**Comment by Alexander237** [comment]
libasr-1.0.2

**Comment by poolpOrg** [comment]
Can you checkout libasr from github (https://github.com/OpenSMTPD/libasr.git) and tell me if it still happen ?

I have just fixed a bug and I'm unsure if it could be the cause of what you experience.

**Comment by Alexander237** [comment]
Hello.
I tested  libasr from github (https://github.com/OpenSMTPD/libasr.git). 
No changes. Issue remains the same.

**Comment by Alexander237** [comment]
Hello.
latest libasr from github (https://github.com/OpenSMTPD/libasr.git) does not help. 
Even with new libasr opensmtpd refuses to contact ipv4 smarthosts when DNS returns A and AAAA records. Any ideas?

**Comment by Alexander237** [comment]
Problem is relevant for opensmtpd-5.7.3.

**Comment by yonas** [comment]
I'm seeing this too. It's quickly filling up the log file.

**Comment by greecemunky** [comment]
Does it occur if you append `source <source>` after your `relay via` configuration option, in attempt all traffic to go out via an IPv4 address?  Example:

```
table tbl_local_ipv4_addr { x.x.x.x }
...
accept ... relay via smtp://outlook.office365.com source <tbl_local_ipv4_addr> ...
```

Replace `x.x.x.x` with one or more local IPv4 addresses used to connect to the smarthost _from_.

Interestingly, I think it worked without my suggestion in Ubuntu 14.04 LTS (OpenSMTPD 5.7.3p1, from ppa:segler-alex/opensmtpd), according to the below log:

```
...
smtp-out: session 16809a1c1ade9423: connecting to smtp://IPv6:2a01:111:f400:a400::2:25 (2a01:111:f400:a400::2)
smtp-out: session 16809a1c1ade9423: error: Connection failed: Network is unreachable
smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:a400::2 (2a01:111:f400:a400::2) for 15s
smtp-out: session 16809a1d6ad39e9b: connecting to smtp://IPv6:2a01:111:f400:a817::2:25 (2a01:111:f400:a817::2)
smtp-out: session 16809a1d6ad39e9b: error: Connection failed: Network is unreachable
smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:a817::2 (2a01:111:f400:a817::2) for 15s
smtp-out: session 16809a1e0d89f512: connecting to smtp://IPv6:2a01:111:f400:b400::2:25 (2a01:111:f400:b400::2)
smtp-out: session 16809a1e0d89f512: error: Connection failed: Network is unreachable
smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:b400::2 (2a01:111:f400:b400::2) for 15s
smtp-out: session 16809a1f3e8a5d87: connecting to smtp://IPv6:2a01:111:f400:5223::2:25 (2a01:111:f400:5223::2)
smtp-out: session 16809a1f3e8a5d87: error: Connection failed: Network is unreachable
smtp-out: routing: Disabling route [] <-> IPv6:2a01:111:f400:5223::2 (2a01:111:f400:5223::2) for 15s
smtp-out: session 16809a20099c03ad: connecting to smtp://132.245.160.34:25 (132.245.160.34)
smtp-out: session 16809a20099c03ad: evpid=d2f109171e700bd9, status=PermFail, from=<testfrom@testdomain.com>, to=<testto@testdomain.com>, rcpt=<->, source=x.x.x.x, relay=132.245.160.34 (132.245.160.34), delay=14s, stat=530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM
smtp-out: session 16809a20099c03ad: error: Connection closed unexpectedly
...
```

And after appending `source <source>`, no resolved IPv6 addresses were attempted:

```
smtp-out: session ec5c57d68229274a: connecting to smtp://191.234.140.34:25 (191.234.140.34)
smtp-out: session ec5c57d68229274a: evpid=df4d1abfe2b8f248, status=PermFail, from=<testfrom@testdomain.com>, to=<testto@testdomain.com>, rcpt=<->, source=x.x.x.x, relay=191.234.140.34 (191.234.140.34), delay=5s, stat=530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM
smtp-out: session ec5c57d68229274a: error: Connection closed unexpectedly
```

**Comment by ru2mm** [comment]
Thank you very much greecemunky for the simple and nice solution. It works in our environment!

**Comment by yonas** [comment]
Unfortunately it didn't work for me.

@ru2mm Could you copy/paste the rule that was causing this issue?

**Comment by greecemunky** [comment]
If the workaround doesn't work, it could be due to differences between portable and non-portable versions.

@yonas Care to provide relevant lines from your conf file (before and after), specifically the ```table``` and ```accept ... relay via``` lines?

After having made the change and restarting OpenSMTPD, can you paste an excerpt from the log file, as it may help?

**Comment by yonas** [comment]
@greecemunky `limit mta inet4` didn't seem to work either.

Here are my logs:

`Oct 14 13:33:08 mailserver smtpd[15132]: info: received signal SIGTERM, shutting down
Oct 14 13:33:08 mailserver smtpd[15135]: info: lookup agent exiting
Oct 14 13:33:08 mailserver smtpd[15133]: info: queue handler exiting
Oct 14 13:33:08 mailserver smtpd[15137]: info: pony agent exiting
Oct 14 13:33:08 mailserver smtpd[15134]: info: control process exiting
Oct 14 13:33:08 mailserver smtpd[15138]: info: ca agent exiting
Oct 14 13:33:08 mailserver smtpd[15136]: info: scheduler handler exiting
Oct 14 13:33:08 mailserver smtpd[15132]: warn: parent terminating
Oct 14 13:33:08 mailserver smtpd[15173]: info: OpenSMTPD 5.7.3p1 starting
Oct 14 13:33:08 mailserver smtpd[15174]: info: startup
Oct 14 13:33:08 mailserver smtpd[15179]: smtp-out: session fa33d5f506ce4121: connecting to smtp+tls://74.125.201.27:25 (in-in-f27.1e100.net)
Oct 14 13:34:23 mailserver smtpd[15179]: smtp-out: session fa33d5f506ce4121: error: Connection timeout
Oct 14 13:34:23 mailserver smtpd[15179]: smtp-out: routing: Disabling route [] <-> 74.125.201.27 (in-in-f27.1e100.net) for 15s
Oct 14 13:34:23 mailserver smtpd[15179]: smtp-out: session fa33d5f6c6c9dee3: connecting to smtp+tls://74.125.141.27:25 (vl-in-f27.1e100.net)
Oct 14 13:34:25 mailserver smtpd[15179]: smtp-out: session fa33d5f77528883c: connecting to smtp+tls://173.194.208.27:25 (ql-in-f27.1e100.net)
Oct 14 13:34:38 mailserver smtpd[15179]: smtp-out: routing: Enabling route [] <-> 74.125.201.27 (in-in-f27.1e100.net)
Oct 14 13:34:40 mailserver smtpd[15179]: smtp-out: session fa33d5f83315b572: connecting to smtp+tls://74.125.201.27:25 (in-in-f27.1e100.net)`


Here's my entire file with the source table:

`listen on lo0
listen on xn0

table relay_ipv4 { 10.9.0.1 }

accept from source { 192.168.0.0/24, 10.8.0.0/24, 10.9.0.0/24, 10.10.0.0/24 } for any relay via 10.9.0.1 source <relay_ipv4>
accept from local for local deliver to maildir`


Here's my entire file with `limit mta inet4`:

`listen on lo0
listen on xn0

limit mta inet4

accept from source { 192.168.0.0/24, 10.8.0.0/24, 10.9.0.0/24, 10.10.0.0/24 } for any relay via 10.9.0.1
accept from local for local deliver to maildir`

**Comment by greecemunky** [comment]
@yonas You are having issues communicating via IPv4, so your issue isn't the same as this.

Your conf suggests you're relaying via a private IP range but your logs indicate it's trying to send out via a public IP?  Maybe it is due to your host syntax.  The relay host name/IP should be prefixed with the protocol/method in URL format e.g. smtp:// .  Read the documentation for more complete examples.

**Comment by yonas** [comment]
@greecemunky Thanks, yes, that seems to be the issue. I cleared the queue via `rm -rf /var/spool/smtpd/*` and now everything looks good.

Thanks again for your help!

**Comment by greecemunky** [comment]
@yonas Instead of copying /etc/ssl/certs/ca-certificates.crt as you suggested, I suggest symlinking it instead as it may get updated via Ubuntu updates, if root certificates are updated.  So:

```ln -s /etc/ssl/certs/ca-certificates.crt /etc/ssl/cert.pem```

**Comment by yonas** [comment]
@greecemunky I tried that, but OpenSMTPD still complains about not finding /etc/ssl/cert.pem .

**Comment by greecemunky** [comment]
@yonas Interesting - it works for me for OpenSMTPD 5.4.1p1 (as per Ubuntu 14.04 LTS) and OpenSMTPD 5.7.3p1.  Could it be a permissions issue on your /etc/ssl/certs/ca-certificates.crt file?

Mine:
```
lrwxrwxrwx 1 root root     34 Oct 15 10:19 /etc/ssl/cert.pem -> /etc/ssl/certs/ca-certificates.crt
-rw-r--r-- 1 root root 273790 Sep 29 15:05 /etc/ssl/certs/ca-certificates.crt
```

That said, we should probably stop getting off-topic.  I'll stop responding unless related to the original issue.

**Comment by yonas** [comment]
@greecemunky I have the same permissions on the file, 644. Anyway, we can open another issue if anyone feels it's important enough ;-) Thanks again for your help.

**Comment by poolpOrg** [comment]
Ahem, so this issue is no longer an issue ? :-)

**Comment by ru2mm** [comment]
Yes, this issue was solved.

**Comment by ericfaurot** [comment]
thanks
