### ISSUE TITLE
"table senders" regression: syntax error

### ISSUE THREAD

**Issue by dwatteau** [OpenSMTPD/OpenSMTPD#629]
Hi,

The following configuration files:

`smtpd.conf`:
```
listen on lo0 # or localhost on Debian

table aliases db:/etc/mail/aliases.db # or "table aliases file:/etc/mail/aliases" on Debian
table senders file:/etc/mail/senders

accept for local alias <aliases> deliver to mbox
accept from local for any relay
```

`/etc/mail/senders`:
```
@something.example.com
```

work fine on OpenBSD 5.8 with OpenSMTPD 5.4.4, as well as Debian 7.8 with OpenSMTPD 5.4.4p1 (no syntax error).

But the same file doesn't work on Debian 7.8 with OpenSMTPD 5.7.1p1:
```
# smtpd -d -v
/etc/smtpd.conf:11: syntax error
```

Reading OpenSMTPD 5.7.1p1 `smtpd.conf(5)` and `table(5)`, I can't see what is wrong here.  Unless I'm mistaken, it looks like a regression, otherwise if it's a matter of a new syntax, this probably needs to be documented.

Thank you.

**Comment by poolpOrg** [comment]
Is this really your configuration file ?

The one you pasted is 7 lines long, the error message says the error occurs on line 11.

**Comment by dwatteau** [comment]
Ah, well, I had removed some comments to make my report simpler, sorry, but here you go:
```
# This is the smtpd server system-wide configuration file.
# See smtpd.conf(5) for more information.

#myrelay = "smtp://XX.XX.XX.XX"

# To accept external mail, replace with: listen on all
listen on localhost

# If you edit the file, you have to run "smtpctl update table aliases"
table aliases file:/etc/mail/aliases
table senders file:/etc/mail/senders

#limit mta inet4 session-mail-max 100 max-conn-per-domain 8

# Uncomment the following to accept external mail for domain "example.org"
#accept from any for domain "example.org" alias <aliases> deliver to mbox

accept for local alias <aliases> deliver to mbox
accept for any relay
```

Anyway, the syntax error was about this line:
```
table senders file:/etc/mail/senders
```

**Comment by poolpOrg** [comment]
I had overlooked the original message.

This is not a bug, you can't name your table after a reserved keyword which "senders" is.
It was probably working with your former version because you had the table named differently, senders has been a reserved keyword for well over a year.

    $ grep table /etc/mail/smtpd.conf  
    table foobar file:/etc/mail/senders.txt
    $ doas smtpd -n                    
    configuration OK
    $ grep table /etc/mail/smtpd.conf  
    table senders file:/etc/mail/senders.txt
    $ doas smtpd -n                    
    /etc/mail/smtpd.conf:5: syntax error
    $

Please confirm and close the ticket ;-)

**Comment by dwatteau** [comment]
(after a bit of IRC talk)

OK, thank you.  I was confused and thought `smtpd.conf(5)` told me I *had* to name my table `senders`. Sorry.

However, OpenSMTPD 5.4.4p1 did accept this syntax, but as you told me, OpenSMTPD 5.4.4p1 is a bit old now.  Sorry, and thanks again!

**Comment by poolpOrg** [comment]
After a second read, I can see how the documentation can confuse new users, I will try to improve.

reopening the ticket as a documentation bug

**Comment by poolpOrg** [comment]
I rewrote that part of the documentation & will work on making other ambiguous cases less ambiguous.
