### ISSUE TITLE
username in passwd file should be possible as full email address

### ISSUE THREAD

**Issue by blindmelon** [OpenSMTPD/OpenSMTPD#635]
Currently in a configuration like:
```
table domains file:/etc/smtpd/domains
table users passwd:/etc/smtpd/secrets
accept from any for domain <domains> userbase <users> deliver to lmtp "/var/run/dovecot/lmtp"
```
where /etc/smtpd/secrets contains usernames in the format of a full email address (e.g. myself@tonesofhome.net) smtpd only checks for "myself" and therefore returns 550 Invalid Recipient.

It should be possible to match against the full email address, therefore enabling multiple domains using a shared flat file list of users with dovecot.

Making all but the first two fields in the passwd file optional would also be a bonus towards dovecot compatibility, is probably something for another issue.

**Comment by widder** [comment]
You could work around this using sqlite 
https://hugo.barrera.io/journal/2015/02/15/opensmtpd-dovecot-shared-sql-db/

**Comment by poolpOrg** [comment]
This has been implemented so it doesn't need workarounds in development branch, it will be part of next release.

**Comment by blindmelon** [comment]
@poolpOrg I've just been trying this out in both the current release and in the latest snapshots, but I can't get it working. Could you point me in the right direction/towards the relevant change? By default it is still only looking for what comes before the "@"
