### ISSUE TITLE
/var/run -> /run

### ISSUE THREAD

**Issue by zx2c4** [OpenSMTPD/OpenSMTPD#637]
Some distributions are using /run instead of /var/run. In the Gentoo package, somebody changed it recently to do this:

    sed -i -e '/pidfile_path/s:_PATH_VARRUN:"/run/":' openbsd-compat/pidfile.c

This isn't very pretty. Could there be a switch to `--configure` for making this happen in portable?

**Comment by poolpOrg** [comment]
I can't think of a way to achieve this in configure.ac that isn't broken, can you suggest one ?

**Comment by poolpOrg** [comment]
no feedback ?

**Comment by zx2c4** [comment]
Autotools supports --runstatedir since 2013 I think.

**Comment by poolpOrg** [comment]
Can you please test code from git and confirm --with-path-pidfile fixes your issue ?

**Comment by bsdsx** [comment]
Latest git code don't fix this issue.
 
    $ ./configure --with-path-socket=/var/foobar_fail
    ...
    $ grep foobar_fail config.h
    #define SMTPD_SOCKDIR "/var/foobar_fail"
 
    $ ./configure --with-path-pidfile=/var/foobar_fail
    ...
    $ grep foobar_fail config.h
    $
 
There is somes differences in configure.ac between --with-path-socket and --with-path-pidfile.
 
with-path-socket:
 
- have default value (sockdir)
- test withval (the right variable to use)
- define SMTPD_SOCKDIR
 
with-path-pidfile:
 
- don't have default value
- test wrong variable (with_path-pidfile instead withval, may be a typo ?)
- don't define SMTP_RUNDIR (for example)
- define _PATH_VARRUN (can be already define in /usr/include/paths.h, bad idea imho)

**Comment by bsdsx** [comment]
I wrote a small configure.ac to resolv the problem:

    $ autoheader && autoconf configure.ac > configure 
    $ /bin/sh configure [--with-path-pidfile=/var/foobar]

On system without paths.h:

    $ /bin/sh configure 
    [ snip autoconf defaults checks ]
    checking paths.h usability... no
    checking paths.h presence... no
    checking for paths.h... no
    checking Discovering system pid directory... using /var/run from default value
    configure: creating ./config.status
    config.status: creating config.h
    
    OpenSMTPD has been configured with the following options:
    smtpd.pid dir: /var/run/

    $ /bin/sh configure --with-path-pidfile=/var/foobar
    [ snip autoconf defaults checks ]
    checking paths.h usability... no
    checking paths.h presence... no
    checking for paths.h... no
    checking Discovering system pid directory... using /var/run from default value
    configure: creating ./config.status
    config.status: creating config.h
    
    OpenSMTPD has been configured with the following options:
    smtpd.pid dir: /var/foobar/

On system with paths.h:

    $ /bin/sh configure
    [ snip autoconf defaults checks ]
    checking paths.h usability... yes
    checking paths.h presence... yes
    checking for paths.h... yes
    checking Discovering system pid directory... using /var/run/ from paths.h
    configure: creating ./config.status
    config.status: creating config.h
    
    OpenSMTPD has been configured with the following options:
    smtpd.pid dir: /var/run/

    $ /bin/sh configure --with-path-pidfile=/var/foobar
    [ snip autoconf defaults checks ]
    checking paths.h usability... yes
    checking paths.h presence... yes
    checking for paths.h... yes
    checking Discovering system pid directory... using /var/run/ from paths.h
    configure: creating ./config.status
    config.status: creating config.h
    
    OpenSMTPD has been configured with the following options:
    smtpd.pid dir: /var/foobar/

Patch openbsd-compat/defines.h:

    diff --git a/openbsd-compat/defines.h b/openbsd-compat/defines.h
    index 8d913f4..0a94d76 100644
    --- a/openbsd-compat/defines.h
    +++ b/openbsd-compat/defines.h
    @@ -497,10 +497,6 @@ typedef uint16_t   in_port_t;
     #define FPARSELN_UNESCALL       0x0f
     #endif
     
    -#ifndef _PATH_VARRUN
    -#define _PATH_VARRUN "/var/run/"
    -#endif
    -
     #ifdef HAVE_M_DATA
     #undef M_DATA
     #endif

Patch openbsd-compat/defines.h:

    diff --git a/openbsd-compat/pidfile.c b/openbsd-compat/pidfile.c
    index 386677e..4be68c2 100644
    --- a/openbsd-compat/pidfile.c
    +++ b/openbsd-compat/pidfile.c
    @@ -43,6 +43,10 @@
     #include <stdio.h>
     #include <stdlib.h>
     #include <unistd.h>
    +#ifdef _PATH_VARRUN
    +#undef _PATH_VARRUN
    +#endif
    +#define _PATH_VARRUN SMTPD_PIDDIR
     
     static char *pidfile_path;
     static pid_t pidfile_pid;

configure.ac:

    AC_INIT([foo], 1.0)
    
    AC_CONFIG_HEADER([config.h])
    
    AC_CHECK_HEADERS([paths.h])
    
    AC_MSG_CHECKING([Discovering system pid directory])
    piddir=/var/run
    AC_RUN_IFELSE(
        [
            AC_LANG_PROGRAM([[
    #include <stdio.h>
    #include <stdlib.h>
    #ifdef HAVE_PATHS_H
    #include <paths.h>
    #endif
    #define DATA "conftest.piddir"
            ]],
            [[
    #ifdef _PATH_VARRUN
    FILE *fd;
    int rc;
    
    if ((fd = fopen(DATA,"w")) == NULL) { exit(1); }
    if ((rc = fprintf(fd ,"%s\n", _PATH_VARRUN)) < 0) { exit(2); }
    exit(0);
    #else
    exit(-1);
    #endif
            ]])
        ],        [
            piddir=`cat conftest.piddir`
            AC_MSG_RESULT([using $piddir from paths.h])
        ],
        [
            AC_MSG_RESULT([using $piddir from default value])
        ]
    )
    
    AC_ARG_WITH([path-pidfile],
        [  --with-path-pidfile=PATH  Specify path to smtpd.pid directory (default=/var/run)],
        [
            if test -n "$withval" && test "x$withval" != "xno" && \
                test "x${withval}" != "xyes"; then
                piddir=$withval
            fi
        ]
    )
    
    # mimic _PATH_VARRUN
    case $piddir in
        */);;
        *) piddir="$piddir/"
    esac
    
    AC_DEFINE_UNQUOTED([SMTPD_PIDDIR], ["$piddir"], [Specify location of smtpd.pid])
    AC_SUBST([piddir])
    
    AC_OUTPUT
    
    echo "
    OpenSMTPD has been configured with the following options:
    smtpd.pid dir: $piddir
    "
