### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by gtozzi** [OpenSMTPD/OpenSMTPD#639]
I am using this config line to relay all mail for a given domain to a different SMTP

`accept from any for domain "example.com" relay via smtp://mysmtp.local`

When _mysmtp.local_ can't be resolved, the errors shown in maillog are:

> Oct  7 00:39:51 host smtpd[8204]: relay: TempFail for da22753dbfba3245: session=0000000000000000, from=someone@example.com, to=dest@example.com, rcpt=<->, source=-, relay=mysmtp.local, delay=1d4h26m40s, stat=No MX found for domain
> Oct  7 00:40:41 host smtpd[8204]: smtp-out: Failed to resolve MX for [relay:mysmtp.local,mx]: No MX found for domain

I think these messages are misleading, maybe even wrong. I suggest you to change them in this or a similar way:
- _"No MX found for domain"_ becomes _"Host not found"_
- _"Failed to resolve MX for [relay:mysmtp.local,mx]: No MX found for domain"_ becomes _"Failed to resolve host mysmtp.local"_

Thank you for writing and sharing this very good software, that's just my 2c.

**Comment by kusuriya** [comment]
Really the message itself is actually correct, just not for this item, IMO it needs to be:
```
Resolves domain but no MX records are present =  No MX found for domain
Tried to resolve a specific host for relay via or forward and no results come back = Hosname not found
Got a Host name from DNS but can not connect to the host with the data that came back = Host not found.
```

**Comment by ericfaurot** [comment]
I finally committed something that improves the situation.
