### ISSUE TITLE
"listen on any" bind fails if an address is on two interfaces

### ISSUE THREAD

**Issue by sthen** [OpenSMTPD/OpenSMTPD#641]
On my router at home, I have a routed /28 from my ISP, and the PPP address is within that /28 so it appears on two interfaces (pppoe0 and the lan). With "listen on any", smtpd tries to bind to it twice and the second one fails EADDRINUSE. To reproduce you could do e.g. 'ifconfig lo1 inet 10.1.1.1/27' and 'ifconfig lo2 inet 10.1.1.1/28'.

**Comment by poolpOrg** [comment]
@sthen

Your issue should go away if you use:

    listen on 0.0.0.0

Because when you use:

    listen on all

The `all` part is not a keyword to listen on all addresses but rather the name of the interface group `all` which turns out to contain both pppoe0 and your lan, and therefore try to bind both individually which causes the EADDRINUSE.

**Comment by obadz** [comment]
@poolpOrg, is there a way to do this that would work for both ipv4 & ipv6?

**Comment by poolpOrg** [comment]
OP timeout

@obadz only on systems that support interface groups.

**Comment by obadz** [comment]
@poolpOrg not sure why you closed this.

Seems like a pretty big issue not to be able to `listen` on both ipv4 and ipv6.

**Comment by poolpOrg** [comment]
Hu ?

I'll reopen, can you provide me with an example of "not being able to listen on both ipv4 and ipv6 ?

**Comment by obadz** [comment]
Sure, here's an example config:

```nix
    opensmtpd = {
      enable = true;
      serverConfiguration = ''
        table creds file:/${pkgs.writeText "creds" "blah notapassword"}
        table vdoms file:/${pkgs.writeText "vdoms" "test-domain.org"}
        table vmap  file:/${pkgs.writeText "vmap"  "a@test-domain.org b"}
        
        pki ${fullHostName} certificate  "/etc/smtpd-tls/${fullHostName}.crt"
        pki ${fullHostName} key          "/etc/smtpd-tls/${fullHostName}.key"

        listen on 0.0.0.0          tls                      pki ${fullHostName} tag inbound
        ${lib.optionalString ipv6 ''
        listen on ::               tls                      pki ${fullHostName} tag inbound
        ''}
        listen on 0.0.0.0 port 587 tls-require auth <creds> pki ${fullHostName} tag outbound

        accept tagged outbound from local for any relay                       hostname ${fullHostName}
        accept                 from local for any relay as "@${fullHostName}" hostname ${fullHostName}
        accept                 from any for domain <vdoms> virtual <vmap>
      '';
    };
```

if `ipv6` is true, opensmtpd crashes on startup with these log entries:

```
May 22 18:59:38 mxtest systemd[1]: Started opensmtpd.service.
May 22 18:59:38 mxtest smtpd[608]: info: OpenSMTPD 5.7.3p2 starting
May 22 18:59:38 mxtest smtpd[608]: info: startup
May 22 18:59:38 mxtest smtpd[608]: fatal: listen: Address already in use
May 22 18:59:38 mxtest smtpd[608]: warn: ca -> pony: pipe closed
May 22 18:59:38 mxtest smtpd[608]: warn: parent -> ca: pipe closed
May 22 18:59:38 mxtest systemd[1]: opensmtpd.service: Main process exited, code=exited, status=1/FAILURE
May 22 18:59:38 mxtest smtpd[608]: info: scheduler handler exiting
May 22 18:59:38 mxtest smtpd[608]: warn: lka -> parent: pipe closed
May 22 18:59:38 mxtest smtpd[608]: warn: control -> ca: pipe closed
May 22 18:59:38 mxtest smtpd[608]: warn: queue -> parent: pipe closed
May 22 18:59:38 mxtest systemd[1]: opensmtpd.service: Unit entered failed state.
May 22 18:59:38 mxtest systemd[1]: opensmtpd.service: Failed with result 'exit-code'.
```

If `ipv6`

**Comment by poolpOrg** [comment]
the problem you're experiencing is different from that of the OP and yours had a fix committed in time for OpenSMTPD 5.9.2p1, please confirm that you still experience the issue with latest version.

**Comment by obadz** [comment]
Upgraded (https://github.com/NixOS/nixpkgs/pull/15630/files) and now seems to work.

**Comment by poolpOrg** [comment]
good, closing again then

**Comment by obadz** [comment]
Thanks & sorry about this.
