### ISSUE TITLE
MDA issue

### ISSUE THREAD

**Issue by Niemi** [OpenSMTPD/OpenSMTPD#644]
Hi to all,
i'm not in list , please add my email when you responce.

after openbsd upgrade to current my MDA stops working for local delivery. Maybe i miss something.
smtpd version: info: OpenSMTPD 5.4.6 starting

[part of debug]
========================================================
debug: scheduler: evp:7c1ba6adf8fcec21 scheduled (mda)
mda: new user 20073f469cf8df1 for "<getpwnam>:niemi"
debug: lka: userinfo <getpwnam>:niemi
debug: mda: new session 020073f5956a5f1a for user "<getpwnam>:niemi" evpid 7c1ba6adf8fcec21
debug: mda: no more envelope for "<getpwnam>:niemi"
debug: mda: got message fd 4 for session 020073f5956a5f1a evpid 7c1ba6adf8fcec21
debug: mda: querying mda fd for session 020073f5956a5f1a evpid 7c1ba6adf8fcec21
debug: smtpd: forking mda for session 020073f5956a5f1a: "/home/niemi/Maildir" as niemi
debug: mda: got mda fd 5 for session 020073f5956a5f1a evpid 7c1ba6adf8fcec21
debug: mda: end-of-file for session 020073f5956a5f1a evpid 7c1ba6adf8fcec21
debug: smtpd: mda process done for session 020073f5956a5f1a: terminated; signal 9
delivery: TempFail for 7c1ba6adf8fcec21: from=<aleksei.kurepin@goswift.eu>, to=<niemi@suminovou.eu>, user=niemi, method=maildir, delay=42m42s, stat=Error (terminated; signal 9)
debug: mda: session 020073f5956a5f1a done
===============================================================
[smtpd.conf]
===============================================================
pki mail.suminovou.eu certificate "/etc/ssl/mail.suminovou.eu.crt"
pki mail.suminovou.eu key "/etc/ssl/private/mail.suminovou.eu.key"
pki web1.suminovou.eu certificate "/etc/ssl/starssl.web1.suminovou.eu.crt"
pki web1.suminovou.eu key "/etc/ssl/private/starssl.web1.suminovou.eu.wop.key"
pki web1.suminovou.eu dhparams "/etc/ssl/web1.suminovou.eu.dhp"
expire 1d
bounce-warn 1h,3h,6h,23h

listen on lo0 inet4
listen on lo0 inet4 port 10028 tag DKIM_OUT hostname mail.suminovou.eu
listen on egress inet4 tls pki web1.suminovou.eu auth-optional
listen on egress inet4 port submission tls-require pki web1.suminovou.eu auth mask-source
listen on egress inet4 port 465 tls-require pki web1.suminovou.eu auth mask-source
table aliases db:/etc/mail/aliases.db
table vusers file:/etc/mail/vusers
table vdomains file:/etc/mail/vdomains
table reject_sender file:/etc/mail/reject_sender

reject from any sender <reject_sender>
accept for local alias <aliases> deliver to maildir
accept from any for domain <vdomains> virtual <vusers> deliver to maildir
accept tagged DKIM_OUT for any relay source {xxx.xxx.xxx.xxx} hostname web1.suminovou.eu
accept from local for any relay via smtp://127.0.0.1:10027 hostname web1.suminovou.eu
======================================================================

**Comment by poolpOrg** [comment]
fixed in current

**Comment by Niemi** [comment]
Many thanks, it works :+1:
