### ISSUE TITLE
smtpd drops last header-field if mail has no body

### ISSUE THREAD

**Issue by satan1st** [OpenSMTPD/OpenSMTPD#646]
If you send a mail that only contains a header, the last field is dropped.
To Reproduce create a mail with only header, no body and no empty line and send
it over opensmtpd.

**Comment by poolpOrg** [comment]
reproduced, diff pending OP confirmation that it fixes issue.

**Comment by poolpOrg** [comment]
confirmed, will be committed tomorrow.
