### ISSUE TITLE
portable: sending mail doesn't work after upgrade to 201602031446

### ISSUE THREAD

**Issue by dfateyev** [OpenSMTPD/OpenSMTPD#652]
Got this issue after upgrade 5.7.3p1 to the recent snapshot.
```
$ echo "test message" | mail -s "test subject" denis@fateyev.com
  command failed: 550 Invalid recipient
...
Feb 06 00:56:10 fedora23-amd64.mydomain smtpd[23613]: smtp-in: Received disconnect from session e6ba31209b4ac0b8
Feb 06 00:57:29 fedora23-amd64.mydomain smtpd[23613]: smtp-in: New session e6ba312568e33059 from host fedora23-amd64.mydomain []
Feb 06 00:57:29 fedora23-amd64.mydomain smtpd[23613]: smtp-in: Failed command on session e6ba312568e33059: "RCPT TO:<send-mail@fedora23-amd64.mydomain> " => 550 Invalid recipient
Feb 06 00:57:29 fedora23-amd64.mydomain smtpd[23613]: smtp-in: Received disconnect from session e6ba312568e33059
Feb 06 00:59:32 fedora23-amd64.mydomain smtpd[23613]: smtp-in: New session e6ba312afa861648 from host fedora23-amd64.mydomain []
Feb 06 00:59:32 fedora23-amd64.mydomain smtpd[23613]: smtp-in: Failed command on session e6ba312afa861648: "RCPT TO:<send-mail@fedora23-amd64.mydomain> " => 550 Invalid recipient
Feb 06 00:59:32 fedora23-amd64.mydomain smtpd[23613]: smtp-in: Received disconnect from session e6ba312afa861648
Feb 06 01:05:13 fedora23-amd64.mydomain smtpd[23613]: smtp-in: New session e6ba312f65950f18 from host fedora23-amd64.mydomain []
Feb 06 01:05:13 fedora23-amd64.mydomain smtpd[23613]: smtp-in: Failed command on session e6ba312f65950f18: "RCPT TO:<send-mail@fedora23-amd64.mydomain> " => 550 Invalid recipient
Feb 06 01:05:13 fedora23-amd64.mydomain smtpd[23613]: smtp-in: Received disconnect from session e6ba312f65950f18
```
Seems an invalid recipient is used. The previous 5.7.3p1 version works with the same config / conditions without issues. Service config file:
```
# This is the smtpd server system-wide configuration file.
# See smtpd.conf(5) for more information.

# To accept external mail, replace with: listen on all
listen on localhost

# If you edit the file, you have to run "smtpctl update table aliases"
table aliases file:/etc/aliases

# Uncomment the following to accept external mail for domain "example.org"
#accept from any for domain "example.org" alias <aliases> deliver to mbox

accept for local alias <aliases> deliver to mbox
accept for any relay
```

**Comment by f-andrey** [comment]
Confirm
Dirty env fix
add aliases
````
send-mail:      root
-i:     root
-r:     root
````
and run ```smtpctl update table aliases```

````
Feb  7 03:21:03 bsdnir smtpd[67781]: smtp-in: Accepted message 3bc80484 on session 876f8e73fd333575: from=<andrey@mail....>, to=<send-mail@mail....>, si
ze=374, ndest=1, proto=ESMTP
Feb  7 03:21:03 bsdnir smtpd[67781]: smtp-in: Accepted message 3bc80484 on session 876f8e73fd333575: from=<andrey@mail....>, to=<-i@mail....>, size=374,
 ndest=1, proto=ESMTP
....
Feb  7 03:19:34 bsdnir smtpd[67781]: delivery: Ok for c25c40027935cdbf: from=<andrey@...>, to=<-r@mail....>, user=root, method=mbox, delay=1s, stat=Deli
vered
```

**Comment by poolpOrg** [comment]
Strange, it works for me on OpenBSD but I can reproduce your issue on FreeBSD and Debian.
I will fix and publish à new snapshot tonight.
Le 5 févr. 2016 8:25 PM, Denis Fateyev <notifications@github.com> a écrit :Got this issue after upgrade 573p1 to the recent snapshot

$ echo "test message" | mail -s "test subject" denis@fateyevcom
  command failed: 550 Invalid recipient

Feb 06 00:56:10 fedora23-amd64mydomain smtpd[23613]: smtp-in: Received disconnect from session e6ba31209b4ac0b8
Feb 06 00:57:29 fedora23-amd64mydomain smtpd[23613]: smtp-in: New session e6ba312568e33059 from host fedora23-amd64mydomain []
Feb 06 00:57:29 fedora23-amd64mydomain smtpd[23613]: smtp-in: Failed command on session e6ba312568e33059: "RCPT TO:<send-mail@fedora23-amd64mydomain> " => 550 Invalid recipient
Feb 06 00:57:29 fedora23-amd64mydomain smtpd[23613]: smtp-in: Received disconnect from session e6ba312568e33059
Feb 06 00:59:32 fedora23-amd64mydomain smtpd[23613]: smtp-in: New session e6ba312afa861648 from host fedora23-amd64mydomain []
Feb 06 00:59:32 fedora23-amd64mydomain smtpd[23613]: smtp-in: Failed command on session e6ba312afa861648: "RCPT TO:<send-mail@fedora23-amd64mydomain> " => 550 Invalid recipient
Feb 06 00:59:32 fedora23-amd64mydomain smtpd[23613]: smtp-in: Received disconnect from session e6ba312afa861648
Feb 06 01:05:13 fedora23-amd64mydomain smtpd[23613]: smtp-in: New session e6ba312f65950f18 from host fedora23-amd64mydomain []
Feb 06 01:05:13 fedora23-amd64mydomain smtpd[23613]: smtp-in: Failed command on session e6ba312f65950f18: "RCPT TO:<send-mail@fedora23-amd64mydomain> " => 550 Invalid recipient
Feb 06 01:05:13 fedora23-amd64mydomain smtpd[23613]: smtp-in: Received disconnect from session e6ba312f65950f18


Seems an invalid recipient is used The previous 573p1 version works with the same config / conditions without issues Service config file:

# This is the smtpd server system-wide configuration file
# See smtpdconf(5) for more information

# To accept external mail, replace with: listen on all
listen on localhost

# If you edit the file, you have to run "smtpctl update table aliases"
table aliases file:/etc/aliases

# Uncomment the following to accept external mail for domain "exampleorg"
#accept from any for domain "exampleorg" alias <aliases> deliver to mbox

accept for local alias <aliases> deliver to mbox
accept for any relay

**Comment by poolpOrg** [comment]
I was too optimistic about publishing a snapshot, I got preempted, but the issue is being worked on ;-)

**Comment by poolpOrg** [comment]
@snimmagadda seems to have figured out what's causing the issue.

We're currently working out a fix and will publish a snapshot for you to test right after we're done.

**Comment by poolpOrg** [comment]
snapshot has been published, please test & confirm !

**Comment by dfateyev** [comment]
Looks fixed to me.

**Comment by poolpOrg** [comment]
hooray!
