### ISSUE TITLE
portable: makemap broken in 201602031446

### ISSUE THREAD

**Issue by dfateyev** [OpenSMTPD/OpenSMTPD#653]
```
echo "mail1: postmaster" > aliases
echo "mail2: root" >> aliases
```
The stable 5.7.3p1 version:
```
# makemap -o aliases.db aliases
...
-rw-r--r--   1 root root   aliases
-rw-r--r--   1 root root   aliases.db
```
The latest snapshot (201602031446p1):
```
# makemap -o aliases.db aliases 
fop_read_meta: aliases.db.4mgsQmkpRxz: unexpected file type or format
dbopen: aliases.db.4mgsQmkpRxz: Invalid argument
```

**Comment by poolpOrg** [comment]
Rejoice, issue has been understood.

Basically, when we create a db mapping, we do not work in-place in order not to destroy an existing db if something went wrong.

Instead, we `mkstemp()` a new file, `dbopen()` it, work on it and ultimately overwrite an existing database with an atomic `rename()`. This means that the file is always empty when we `dbopen()` it at first.

Unfortunately, depending on your library, `dbopen()` may assume there's always metadata when you `dbopen()` an existing file.

A fix is ready and pending review, I'll let you know once we publish a snapshot with the fix in and will close the ticket when you confirm issue is gone (hint: it is gone ;p)

**Comment by poolpOrg** [comment]
snapshot has been published, please test & confirm !

**Comment by dfateyev** [comment]
Work fine with 'hash' and 'btree' db types. With 'dbm' it throws an error:
```
$ makemap -o aliases.db -d dbm aliases
DB_CREATE must be specified to create databases.
illegal record number size
illegal record number size
dbput: Invalid argument
```
Although I can't say from which version or snapshot it became being broken.

**Comment by poolpOrg** [comment]
So...

It could _never_ have worked on either one of OpenBSD or portable versions.

I will keep investigating for an hour or so but I think it can't be fixed and given that it has never worked and noone could ever create a db of that type, we should probably remove the dbm db type.

The reason has to do with dbm really requiring the file to be created with a particular header when we really want it created empty through mkstemp.

Any objection to remove if I don't find a way out ?

**Comment by dfateyev** [comment]
From my side there are no objections.
I personally use 'hash', and tried 'dbm' just to check all the things out.

**Comment by poolpOrg** [comment]
dbm db type was removed with ok millert@, jung@, sunil@
next snapshot will consider it an invalid type

Thanks for your reporting and testing Denis !
