### ISSUE TITLE
filters abort on startup due to ignoring 'with-privsep-path' compile option

### ISSUE THREAD

**Issue by ryanakca** [OpenSMTPD/OpenSMTPD#659]
In opensmtpd-extras 5.7.1, the `--with-privsep-path` configure option appears to be a no-op. As a result, the default path of `/var/empty` gets used. However, this path need not exist, which causes filters to to abort on startup (and hence all of opensmtpd to abort on startup). For example:

```
info: OpenSMTPD 5.7.3p2 starting
info: startup
warn: filter-api:monkey chroot: No such file or directory
fatal: filter-api: exiting
warn: pony -> monkey: imsg_read: Connection reset by peer
fatal: exiting: Connection reset by peer
warn: lka -> pony: pipe closed
warn: control -> pony: pipe closed
warn: queue -> pony: pipe closed
warn: parent -> pony: pipe closed
warn: scheduler -> control: pipe closed
warn: ca -> pony: pipe closed
```

**Comment by dfateyev** [comment]
Maybe the recent changes in packaging (http://permalink.gmane.org/gmane.mail.opensmtpd.general/3289) are in charge. I haven't checked for "opensmtpd-extras" though, but the option set for recent "opensmtpd" snapshots has been changed as described. The `"configure"` output could give you the definite answer.

**Comment by ryanakca** [comment]
The following patch appears to fix the issue: https://anonscm.debian.org/cgit/collab-maint/opensmtpd-extras.git/plain/debian/patches/03_PATH_CHROOT.diff . It applies against 5.7.1 is not needed for current HEAD.

**Comment by poolpOrg** [comment]
is this still an issue or can this ticket be closed ?

**Comment by ryanakca** [comment]
It's only an issue against 5.7.1, and was filed in case you were planning on releasing further point releases for 5.7.1. If not, please feel free to close.

**Comment by poolpOrg** [comment]
'k, we don't intend to release further 5.7.n, 5.9.n has been released on OpenBSD and I'm preparing the portable version this week ;-)
