### ISSUE TITLE
Offline message queuing broken in portable

### ISSUE THREAD

**Issue by wahjava** [OpenSMTPD/OpenSMTPD#660]
It seems like in commit c815f32, for offline mail queueing to work, `smtpctl` needs to be setgid, but this change never got propagated back to portable, or at least I am not able to find it, and due to this queuing email, when `smtpd` is down is broken.

Thanks!

**Comment by poolpOrg** [comment]
indeed, the Makefile.am that installs the smtpctl in portable lacks the proper chmod.

committed the fix, waiting for confirmation and i'll close the ticket.

**Comment by wahjava** [comment]
Thanks for quickly fixing the problem, and confirmed that it indeed fixes.
