### ISSUE TITLE
Segfault with LibreSSL on Linux

### ISSUE THREAD

**Issue by zx2c4** [OpenSMTPD/OpenSMTPD#662]
Follow up from http://comments.gmane.org/gmane.mail.opensmtpd.general/2986

Not sure if the title is exactly what the issue is, but when I use LibreSSL, something curious happens. Both LibreSSL and OpenSMTPD ship compat symbols for arc4random and arc4random_buf. OpenSMTPD seems to link its own even when LibreSSL is being used. This causes a segfault.

Downstream at Gentoo we successfully just disable compilation of arc4random and arc4random_buf from within OpenSMTPD when LibreSSL is being used:

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=8146a1f86e72210919cd8a0020aaf19838da0637

**Comment by poolpOrg** [comment]
yes, dealing with both OpenSSL and LibreSSL comes with dragons.

Depending if OpenSSL or LibreSSL is used and if your system provides arc4random part of its libc, you can end up in cases where arc4random is built from compat, which requires an SSL function that may or may not require arc4random itself.

There is no easy fix, we're reworking this entirely in the portable branch hoping to unfuck the situation before the 6.0 release.

**Comment by poolpOrg** [comment]
A fix for this issue has been merged and is part of the snapshot I published today.
Please confirm that the issue goes away for you.

**Comment by poolpOrg** [comment]
This is fixed according to other users, please reopen if you still experience the issue.

**Comment by nihilus** [comment]
I did fixed this on uClibc as described here: https://github.com/libressl-portable/openbsd/issues/78
