### ISSUE TITLE
Syntax Error when using no-dsn, dsn-notify or dsn-ret

### ISSUE THREAD

**Issue by Exiver** [OpenSMTPD/OpenSMTPD#669]
Hey,

i just compiled the latest portable Version (201602131907p1) on Ubuntu 14.04.04 and it works fine for me. I didnt use the Packet Manager Version because it does not support "dsn-ret headers".
But if i add the parameter dsn-ret with argument headers or dsn-notify with argument disable i get a syntax error.

Config:
> pki mail.***.*** key "/etc/ssl/private/domain.key"
> pki mail.***.*** certificate "/etc/ssl/private/chained.pem"
> pki mail.***.*** dhparams "/etc/ssl/private/dh4096.pem"
> ca mail.***.*** certificate "/etc/ssl/certs/ca-certificates.crt"
>
>
> listen on 0.0.0.0 port 25 hostname mail.***.*** tls pki mail.***.***
> listen on 0000::::: port 25 hostname mail.***.*** tls pki mail.***.***
>
> bounce-warn 1h, 6h, 2d
>
> #amavisd as smtp-relay, mails must be filtered
> listen on lo port 10025 tag Filtered
>
> #outgoing mail signed with dkim
> listen on lo port 10027 tag Signed
>
> [...]

When i add the parameters, the listen lines look like this:

> listen on 0.0.0.0 port 25 hostname mail.***.*** tls pki mail.***.*** dsn-ret headers
> listen on 0000::::: port 25 hostname mail.***.*** tls pki mail.***.*** dsn-ret headers

Error is 
/etc/smtpd.conf:11: syntax error

Maybe im just to stupid to use these parameters ;-)

Thanks for your help guys!

**Comment by edgarpettijohn** [comment]
try just no-dsn.  the manual at https://opensmtpd.org/smtpd.conf.5.html is ahead of the code I believe.

**Comment by poolpOrg** [comment]
yes, no-dsn has to be used, not a bug.
