### ISSUE TITLE
filter-dnsbl always seem to reject the message 

### ISSUE THREAD

**Issue by chiel1980** [OpenSMTPD/OpenSMTPD#672]
Hello,

it seems whenever I use filter-dnbl with several hostnames, the lookups always fail.
I tried using ipv6 lookups (although this is something opensmtpd does right?) and have the latest version of the master branch of OpenSMTPD-Extras (where this ipv4/ipv6 problem was solved with an earlier similar issue?).

The error I get is:
`smtp-in: New session 81cf3e1a4d9ef916 from host pro-mail-smtp-001.bol.com [185.14.168.222]
filter-pause[1337]: debug: on_connect: sleeping 5
filter-dnsbl-spamhaus[1336]: debug: on_connect: checking 222.168.14.185.zen.spamhaus.org.
filter-dnsbl-spamhaus[1336]: warn: session 81cf3e1a4d9ef916: event_dispatch: REJECT address
smtp-in: Failed command on session 81cf3e1a4d9ef916: "" => 554 5.7.1 Address in DNSBL
smtp-in: Closing session 81cf3e1a4d9ef916
debug: smtp: 0x24460a0: deleting session: done`

My (sniplet of relevant) config is:

f`ilter filter-pause pause
filter filter-regex regex
filter filter-dnsbl-spamhaus dnsbl "-h" "zen.spamhaus.org"
filter filter-spamassassin spamassassin "-s accept"
filter filter-clamav clamav
filter all chain filter-pause filter-regex filter-dnsbl-spamhaus filter-spamassassin filter-clamav
filter sub chain filter-pause filter-spamassassin filter-clamav`

Using Ubuntu 14.04.3 LTS with git branch of opensmtpd (OpenSMTPD 5.9.1p1)

What can I do to troubleshoot or further investigate this?

Michiel

**Comment by poolpOrg** [comment]
20:16 < umaxx> __gilles: also can you close #672 please? it is fixed in 4450ea79d1fb29e9c4ccde1805e120fd917b0dd6
