### ISSUE TITLE
add support for elliptic keys

### ISSUE THREAD

**Issue by martin61** [OpenSMTPD/OpenSMTPD#675]
current status:

To prevent private keys from leaking in case of a security issue in the network facing process, OpenSMTPD keeps keys in a separate process and does some magic to hand over the crypto operations to that process. Problem is that we don't have the code for EC yet. (Gilles Chehade)

So it works only for rsa keys at the moment - my whish would be to support EC as well :-)

Thanks Martin

**Comment by poolpOrg** [comment]
hi,

thanks for opening this PR but I'll close it, it is a duplicate from #556 ;-)
