### ISSUE TITLE
Tighten TLS security - enable usage of server side cipher ordering

### ISSUE THREAD

**Issue by martin61** [OpenSMTPD/OpenSMTPD#676]
Hi,

I have a proposal to tighten the TLS security: enable the usage of server side cipher ordering, e.g. in smtpd.conf with

    prefer-server-cipher-order yes

Current problem with a config like:

    ciphers EECDH+AES128+AESGCM:EECDH+AES256+AESGCM:EECDH+AES128+SHA256:EECDH+AES256+SHA384:EECDH+AES128+SHA:EECDH+AES256+SHA

will result on client side with:

	prio  ciphersuite                  protocols              pfs                 curves
	1     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-384,384bits  secp384r1
	2     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-384,384bits  secp384r1
	3     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-384,384bits  secp384r1
	4     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-384,384bits  secp384r1
	5     ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,P-384,384bits  secp384r1
	6     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-384,384bits  secp384r1

which is not the "desired" order from the config.

Thanks very much,
Martin

**Comment by ArchangeGabriel** [comment]
I second that request, especially in an area like SMTP where you can’t disable a lot of old ciphers without becoming unreachable from several mail providers.

**Comment by poolpOrg** [comment]
discussed with jsing@ and we'll follow his suggestion which is to enable server preference unconditionnally like is done in httpd

code has been committed to git and will be part of upcoming snapshots.

this was too late for upcoming OpenSMTPD 6.0.0 but will be included in following minor releases

**Comment by ArchangeGabriel** [comment]
Minor like in 6.x or 6.x.y?

**Comment by ArchangeGabriel** [comment]
Any news on this? Maybe with the switch to OpenSSL 1.1.x API?
