### ISSUE TITLE
smtpctl encrypt requires root (for no good reason?)

### ISSUE THREAD

**Issue by obadz** [OpenSMTPD/OpenSMTPD#678]
```
$ smtpctl encrypt blah
smtpctl: need root privileges
```

Feels like this should work fine unprivileged.

**Comment by poolpOrg** [comment]
nope, it should not.

smtpctl operates in two modes:

An enqueuer which **can be ran by any user** and which is essentially a SMTP client that knows how to enqueuer mail when the daemon is offline and knows how to request an SMTP session from OpenSMTPD through its smtpd.sock.

A control tool which **is meant to be used by a privileged user only** and which provides one command that **could** be used by an unprivileged user for the sole purpose of exposing these commands in a single place, which is the same between OpenBSD and other systems that don't ship `encrypt`, for the admin to work with.

Yes, `smtpctl encrypt` could technically be ran by an unprivileged user but it would require teaching `smtpctl` that there are commands that are for privileged users and others which are not... and `smtpctl encrypt` would be the only one that "are not".
