### ISSUE TITLE
mailq always displays "invalid" state for envelopes when daemon is running

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#681]
mailq always displays "invalid" state for envelopes when daemon is running.

**Comment by ericfaurot** [comment]
fixed in cvs

**Comment by poolpOrg** [comment]
I'll merge to github in an hour or so 
Le 29 avr. 2016 10:55 AM, Eric Faurot <notifications@github.com> a écrit :fixed in cvs
