### ISSUE TITLE
long lines

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#683]
long lines have been a constant issue for users.

on one side, RFC provides SHOULD and MUST to determine what is an acceptable line size, on another hand being too strict with this has proved to break communications frequently.

we need to reassess how we're handling them.

**Comment by poolpOrg** [comment]
@ericfaurot is working on a new headers and message parser which will make it easier to handle long lines correctly.

to be followed...

**Comment by dgwynne** [comment]
i just got bitten by some long lines other people were sending. who do i bribe for progress on this?

**Comment by poolpOrg** [comment]
No bribing required, it' s taking time because it has a few tentacles and requires rewriting some tricky code... but it's almost done for real.

**Comment by poolpOrg** [comment]
I'm preparing a quick fix to workaround and commit on Sunday.

**Comment by poolpOrg** [comment]
we've bumped considerably the line limit, this should fix user issues but itś  not the proper way to fix it which is still being worked on.

**Comment by poolpOrg** [comment]
@ericfaurot has committed a new message parser which can process long lines and which makes it possible to solve this ticket for good.

He is currently investigating if there are other areas that still work with long lines but we think there aren't and this ticket might be closed soon.

**Comment by poolpOrg** [comment]
committed, so long nuisance.
