### ISSUE TITLE
filters don't run for sendmail

### ISSUE THREAD

**Issue by yorickvP** [OpenSMTPD/OpenSMTPD#684]
I'm using filter-dkim-signer to DKIM sign my mail, and it works fine if I connect externally using smtp.
However, when I (or another package on my system) use sendmail, the filters don't get run and the mail is rejected because of DMARC.
It would be very nice to be able to run the filters for local enqueues, so that sendmail is usable for me.

**Comment by poolpOrg** [comment]
What version of OpenSMTPD are you using ?

**Comment by yorickvP** [comment]
5.7.3p2

**Comment by poolpOrg** [comment]
add:

enqueuer filter "..."

**Comment by yorickvP** [comment]
Thanks a lot! This works! It might be useful to have some documentation available online for the filters, but I understand they are still experimental.

**Comment by poolpOrg** [comment]
On upcoming 5.9.n we have introduced "listen on socket" which works like regular listeners so don't get too attached to this ;-)
