### ISSUE TITLE
extras: Honor `--sysconfdir` to allow to change config location

### ISSUE THREAD

**Issue by wlhlm** [OpenSMTPD/OpenSMTPD#686]
The `./configure`-script for the -extras package allows one to specify `--sysconfdir`. Unfortunately, the source code and manpages do not honor this setting at the moment.

Examples are [filter-monkey.conf](https://github.com/OpenSMTPD/OpenSMTPD-extras/blob/75ce8e40a0506db82b9592ea79159c78e49aa83c/extras/wip/filters/filter-monkey/filter_monkey.c#L32) and [filter-regex.conf](https://github.com/OpenSMTPD/OpenSMTPD-extras/blob/75ce8e40a0506db82b9592ea79159c78e49aa83c/extras/wip/filters/filter-regex/filter_regex.c#L36):
```c
#define MONKEY_CONF "/etc/mail/filter-monkey.conf"
```
Manpages also have this problem, for example:
```man
.Sh FILES
.Bl -tag -width "/etc/mail/filter-regex.conf" -compact
.It Pa /etc/mail/filter-regex.conf
Default
```

This would be helpful on Archlinux for example, where the smtpd configuration is stored in `/etc/smtpd` rather than `/etc/mail`, thus requiring sed-patching.

**Comment by poolpOrg** [comment]
fixed with commit a3aa3aebcc35600836d13728f910105e89f89e40 in -extras

**Comment by wlhlm** [comment]
Thank you! :heart:

**Comment by poolpOrg** [comment]
you're welcome :heart: 

though Joerg Jung did the diff ;-)
