### ISSUE TITLE
configure script detects LibreSSL as OpenBSD stdlib

### ISSUE THREAD

**Issue by chneukirchen** [OpenSMTPD/OpenSMTPD#691]
Since LibreSSL defines functions `reallocarray` etc, **but does not provide prototypes**, the current OpenSMTPD configure assumes it can use these and falls back to the implicit prototypes, which results in a pointer trunction for `reallocarray` and instant segfault in `sendmail(1)` when sending a mail (from `rcpt_add`).

I think the proper way to fix this is to use `AC_CHECK_DECLS` instead of `AC_CHECK_FUNCS` to ensure prototypes are there for all relevant functions.

**Comment by poolpOrg** [comment]
On Wed, May 18, 2016 at 06:49:44AM -0700, Christian Neukirchen wrote:
> Since LibreSSL defines functions `reallocarray` etc, **but does not provide prototypes**, the current OpenSMTPD configure assumes it can use these and falls back to the implicit prototypes, which results in a pointer trunction for `reallocarray` and instant segfault in `sendmail(1)` when sending a mail (from `rcpt_add`).
> 
> I think the proper way to fix this is to use `AC_CHECK_DECLS` instead of `AC_CHECK_FUNCS` to ensure prototypes are there for all relevant functions.
> 

mmh, I thought we checked reallocarray() independantly as part of the
regular functions checks...

can you tell me which environment you use ?

i'll reproduce, fix and eventually make a patchlevel release.



-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by chneukirchen** [comment]
I run Void Linux, an independent Linux distribution using LibreSSL as default SSL library.

`reallocarray` is checked in the huge `AC_CHECK_FUNCS` and exists as a symbol in `/usr/lib/libcrypto.a`, thus just linking with `-lcrypto` will pass the test.  But since there is no prototype, it will be called in a wrong way.

**Comment by poolpOrg** [comment]
yup, understood, I'll have a fix for you today

**Comment by chneukirchen** [comment]
I also think there is a problem with the prototypes for `arc4random_*`... i get spurious implicit definition warnings when I compile (even tho it properly locates the functions in `-lcrypto`).

**Comment by chneukirchen** [comment]
Build log: https://build.voidlinux.eu/builders/x86_64_builder/builds/23467/steps/shell_3/logs/stdio

**Comment by poolpOrg** [comment]
ok, I thought I understood the issue but turns out it was not what I assumed.

working on it.
