### ISSUE TITLE
Why can't we have aliases that point to errors on forward-only rules?

### ISSUE THREAD

**Issue by obadz** [OpenSMTPD/OpenSMTPD#693]
In `smtpd/lka_session.c` lines 440ish:

```c
	case EXPAND_ERROR:
		if (rule->r_forwardonly) {
			log_trace(TRACE_EXPAND, "expand: error matched on forward-only rule");
			lks->error = LKA_TEMPFAIL;
			break;
		}
```

**Comment by obadz** [comment]
cc // @poolpOrg @ericfaurot (?)

**Comment by poolpOrg** [comment]
because they're forward-only rules :-)

Can you explain your use-case ?
I'm pretty sure it can be solved with using a rule to match specific recipients with errors before your forward-only rule.

**Comment by obadz** [comment]
Well I «solved» it by removing forward-only from my rule but I'm not sure why I had to?

I have an MX on which there are no real users and that doesn't take any local deliveries, I want to have some catch-alls but also have certain aliases bounce back with errors. Isn't it best to have my rule be forward-only and have some aliases error out?

**Comment by poolpOrg** [comment]
But I don't understand why you don't do as follow:

    accept [...] for domain foobar.org recipient { g@, e@} aliases { g@ = error: ..., e@ = error: }
    accept [...] for domain foobar.org forward-only

one rule for your errors, one rule for your forward-only.

the question why forward-only doesn't allow errors is kind of answered in the keyword itself, it is ... forward only.
