### ISSUE TITLE
Make sure snapshots have right version numbers

### ISSUE THREAD

**Issue by wahjava** [OpenSMTPD/OpenSMTPD#700]
`SMTPD_VERSION` in most recent portable snapshot (`201605221711p1`) is `5.9.1`, which is not accurate, and should be fixed in the script/process that takes care of releases.

Thanks!

**Comment by poolpOrg** [comment]
ok, being worked on right now, next snapshot will have proper version

**Comment by poolpOrg** [comment]
snapshots published
