### ISSUE TITLE
--with-table-db no longer installs makemap nor newaliases

### ISSUE THREAD

**Issue by ryanakca** [OpenSMTPD/OpenSMTPD#703]
The configure option `--with-table-db` should install links for `makemap` and `newaliases` (pointing to `smtpctl`). Alternatively, please document that users wanting these two utilities should create the appropriate links themselves. (This issue occurs in 5.9.2p1.)

**Comment by poolpOrg** [comment]
can't this be handled in the package layer ?

**Comment by dfateyev** [comment]
BTW, I do it in the package spec: http://pkgs.fedoraproject.org/cgit/rpms/opensmtpd.git/tree/opensmtpd.spec#n149
Would be nice to have some out of box, but I don't insist ;-)

**Comment by ryanakca** [comment]
Indeed, it could be handled in the package layer. I currently do it in the package layer for Debian, but it would be nice if it were done out of the box. At the very least, how to obtain `makemap` and `newaliases` should be documented (I had to dig through the source to figure out what happened to them), especially since opensmtpd's `aliases(5)` references both `makemap(8)` and `newaliases(8)`.

**Comment by poolpOrg** [comment]
sorry for the delay, I was focusing on the filter leak/hang bug :-/

I would much prefer that this be documented for people who actually need it rather than play conditional links games in the build for a feature I'm trying hard to get rid of [1] :-)

[1] don't worry, it's a ten years plan.

**Comment by poolpOrg** [comment]
I've added a section in README to document the historical interfaces, it will be part of all upcoming snapshots and releases.
