### ISSUE TITLE
aliases man page

### ISSUE THREAD

**Issue by ScrumpyJack** [OpenSMTPD/OpenSMTPD#705]
>  user-part@domain-part
    An email address in RFC 5322 format (see mailaddr(7)). If an address extension is appended to the user-part, it is stripped so that an address such as user+ext@example.com will only use the part that precedes ‘+’ as a key.

This needs to be updated to reflect improvements in alias expansion

**Comment by poolpOrg** [comment]
fixed in OpenBSD, synching to git in a few minutes.
