### ISSUE TITLE
Can't parse ipv6 addresses

### ISSUE THREAD

**Issue by bsdsx** [OpenSMTPD/OpenSMTPD#713]
Create a table with a ipv6 address:

```
$ printf '2001:db8:85a3::8a2e:370:7334' > /tmp/networks
```

Create a simple smtpd.conf:

```
$ printf 'table networks file:/tmp/networks\naccept from source <networks>\n' > /tmp/smtpd.conf
```

Check smtpd.conf

```
$ smtpd -n -f /tmp/smtpd.conf
/tmp/smtpd.conf:2: invalid use of table "networks" as FROM parameter
```

Problem come from table_static.c, function table_static_parse:
...
strsep(&valp, " \t:");
...

ipv6 addresses are parse as hash (because ':' character) and generate a T_HASH table

**Comment by bsdsx** [comment]
printf 'table networks file:/tmp/networks\naccept from source <networks>\n' > /tmp/smtpd.conf

**Comment by poolpOrg** [comment]
This is VERY annoying, I discussed this with @ericfaurot and he was unimpressed by the only solution that I came up with and that was not invasive.

We'll try to come up with something during next week's hackathon

**Comment by poolpOrg** [comment]
@ericfaurot has found a very interesting way of fixing this, so he's taking the assignment :-p

**Comment by snimmagadda** [comment]
Could we borrow an idea from RFC 3986 (Generic URI Syntax) which mandates IPv6 address literals to be enclosed within square brackets for disambiguation?

**Comment by ericfaurot** [comment]
I committed the fix we discussed. see http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/smtpd/table_static.c?rev=1.17&content-type=text/x-cvsweb-markup
