### ISSUE TITLE
Configure error : install-sh, install.sh, or shtool

### ISSUE THREAD

**Issue by src386** [OpenSMTPD/OpenSMTPD#714]
Hello,
I'm trying to build opensmtpd portable (from git sources) on Debian 8 : 

    root@debian:/usr/src/opensmtpd# ./configure
    configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

(Yeah, I ran ./bootstrap and no errors).
Thanks.

**Comment by poolpOrg** [comment]
odd :-/

I'll get my hands on a Debian 8 soon and try to reproduce

**Comment by src386** [comment]
No problem with opensmtpd-201607021504p1.tar.gz, it's only with the git repo.

**Comment by poolpOrg** [comment]
On Tue, Aug 23, 2016 at 08:01:50AM -0700, Xavier C. wrote:
> No problem with opensmtpd-201607021504p1.tar.gz, it's only with the git repo.
> 

observed the same on an Ubuntu, will investigate

-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by poolpOrg** [comment]
actually I was experiencing another issue on Ubuntu, which I fixed yesterday.

I'm unable to reproduce your issue with a fresh clone, can you please try again with a fresh clone and let me know if this still happens ?

**Comment by src386** [comment]
Solved, thank you.
