### ISSUE TITLE
Enabling queue encryption results in 'result=TempFails tat=Could not get message fd'

### ISSUE THREAD

**Issue by ckeen** [OpenSMTPD/OpenSMTPD#717]
After an upgrade from 5.9 to 6.0 using OpenBSD's install kernel the system would no longer accept or send mails.

In the maillog I see:

Sep  1 13:09:51 mail smtpd[63271]: 803048d6687534c1 mta event=delivery evpid=e6bbb69fcbe1d2a4 from=<ckeen@here> to=<ckee@there> rcpt=<-> source=127.0.0.1 relay=127.0.0.1 (localhost) delay=0s result=TempFail stat=Could not get message fd

After disabling the encryption and compression clauses in my smtpd.conf and deleting the spool file, it works again.

I have narrowed it down to the queue encryption entry.

At least one person on #openbsd has confirmed that this is also an issue with -current's opensmtpd.

**Comment by poolpOrg** [comment]
@snimmagadda has pinpointed the issue to a particular libssl call, this doesn't happen when using OpenSSL so my guess is that it's a LibreSSL issue.

Investigating

**Comment by poolpOrg** [comment]
12:44 <bcook> seems to be, it passes with LibreSSL 2.3
12:44 <bcook> fails on 2.4 (libressl 2.4)

issue is being investigated by the  LibreSSL people, closing this ticket as we can't fix it smtpd side :)
