### ISSUE TITLE
smtpd 5.9.2p1 filter is started with parameter -d from smtpd commandline

### ISSUE THREAD

**Issue by zem** [OpenSMTPD/OpenSMTPD#720]
If that bug is already known or fixed please close, otherwise it should be investigated. 
I cant start my smtpd in foreground once I addded a filter. 

root@mail1:/etc/smtpd# smtpd -d
info: OpenSMTPD 5.9.2p1 starting
dnsbl: illegal option -- d
warn: filter-dnsbl: bad option
warn: pony -> dnsbl: imsg_read: Connection reset by peer
fatal: exiting: Connection reset by peer
...

from smtpd.conf: 
...
filter dnsbl dnsbl "-h" "dnsbl.inps.de"
...

**Comment by poolpOrg** [comment]
filters are not supported yet.
