### ISSUE TITLE
virtuals does not work with mysql

### ISSUE THREAD

**Issue by alex9434** [OpenSMTPD/OpenSMTPD#722]
Dear all,

I am trying to work with the virtuals in the sql table on Ubuntu 16.04 LTS. However, this does not seem to work. Here is my smtpd.conf:
# tables setup

table userinfo mysql:/etc/mail/mysql.conf
table aliases file:/etc/mail/mysql.conf
table domains mysql:/etc/mail/mysql.conf
table virtuals mysql:/etc/mail/mysql.conf

... (stuff left out)
# allow virtual domains

accept from any for domain <domains> userbase <userinfo> virtual <virtuals> deliver to mda "/usr/lib/dovecot/dovecot-lda -f %{sender} -d %{rcpt}"

mysql.conf is the following:
# smtpd.conf: table vusers mysql:/etc/mail/mysql.conf

host localhost
username database
password ***
database database
... (stuff left out)
# Virtuals lookup query
# 

query_virtuals select username, IF(LENGTH(password)>0,LEFT(username,LOCATE('@',username)-1),virtual) as login from dovecot_users where username="?";

The query returns the following result in mysql:
MariaDB [tine20]> select username, IF(LENGTH(password)>0,LEFT(username,LOCATE('@',username)-1),virtual) as login from dovecot_users where username="webmaster@example.com";
+-----------------------+-----------------------+
| username              | login                 |
+-----------------------+-----------------------+
| webmaster@example.com   | alexander@example.com |
+-----------------------+-----------------------+
1 row in set (0.00 sec)

However, when I try to send an email to webmaster, I get the following message:
220 example.com ESMTP OpenSMTPD
EHLO test.example.com
250-example.com Hello test.example.com [....], pleased to meet you
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-SIZE 36700160
250-DSN
250-STARTTLS
250 HELP
MAIL FROM:<ABSENDERADRESSE>
250 2.0.0: Ok
RCPT TO:webmaster@example.com
451 Temporary failure
Connection closed by foreign host.

smtp: 0x2053250: <<< RCPT TO:webmaster@example.com
filter: new query QK_QUERY QUERY_RCPT
filter: filter_drain_query cf48208c5f44acdd[QK_QUERY,QUERY_RCPT=webmaster@example.com,filter_session@0x203b0a0[datalen=0,eom=(nil),ofile=(nil)]]
filter: filter_end_query cf48208c5f44acdd[QK_QUERY,QUERY_RCPT=webmaster@example.com,filter_session@0x203b0a0[datalen=0,eom=(nil),ofile=(nil)]]
filter: query cf48208c5f44acdd done: status=FILTER_OK code=0 response="(null)"
mproc: pony -> lka: realloc 128 -> 512
mproc: pony -> lka : 270 IMSG_SMTP_EXPAND_RCPT
imsg: lka <- pony: IMSG_SMTP_EXPAND_RCPT (len=270)
expand: 0x204d6e8: expand_insert() called for address:webmaster@example.com[parent=(nil)]
expand: 0x204d6e8: inserted node 0x2051ad0
expand: lka_expand: address: webmaster@example.com [depth=0]
lookup: check “***" as NETADDR in table static:<anyhost> -> found
lookup: check “example.com" as DOMAIN in table proc:domains -> found
rule matched: accept from <anyhost> for  domain domains virtual virtuals deliver to mda "/usr/lib/dovecot/dovecot-lda -f %{sender} -d %{rcpt}"
lookup: lookup “webmaster@example.com" as ALIAS in table proc:virtuals -> -1
expand: lka_expand: error in virtual alias lookup
mproc: lka -> pony : 37 IMSG_SMTP_EXPAND_RCPT
expand: 0x204d6e8: clearing expand tree
imsg: pony <- lka: IMSG_SMTP_EXPAND_RCPT (len=37)
smtp: 0x2053250: >>> 451 Temporary failure
smtp-in: session cf4820872d29373f: received invalid command: "RCPT TO:webmaster@example.com"
smtp: 0x2053250: IO_LOWAT <io:0x2053298 fd=4 to=300000 fl=W ib=0 ob=0>

**Comment by jdelic** [comment]
I haven't yet seen `query_virtuals` anywhere. Are you sure you didn't mean `query_alias`?

Given an email address `query_alias` should return a single result, either another email address (i.e. building an alias chain) or a system user name for delivery.

**Comment by poolpOrg** [comment]
As @jdelic mentions, I think you got your query wrong.

Can you confirm that it works as expected using query_alias ?

**Comment by poolpOrg** [comment]
OP timeout
