### ISSUE TITLE
Filter API RFE: Allow changing the message envelope

### ISSUE THREAD

**Issue by jdelic** [OpenSMTPD/OpenSMTPD#729]
While playing with the current in-development filter API I realized that there is currently no way for a filter to modify the envelope data (i.e. `MAIL FROM` addresses or `RCPT *` addresses), but that would definitely be nice to have. Right now, if I read the source code correctly, the filter can only `accept` and `reject` and then parse and modify the `DATA` part of the message.

It would be great to have a `filter_accept_replace` callback that can submit a modified buffer so a filter can rewrite envelope data.

**Comment by jdelic** [comment]
Interestingly, #172 suggests that some support for this *does* exist, but the ticket isn't tied to a commit or branch and so I'm unable to figure out what code changes make that possible. 

@poolpOrg Since you worked on #172 back in the day... I'm perfectly willing to work through the source code to figure out how the mentioned changes work if this RFE is already implemented in the current code base, but can you point me in the right direction? :)

**Comment by poolpOrg** [comment]
This will be handled in #773 , closing this ticket as it is now referenced in the other one, will be taken into account there.
