### ISSUE TITLE
opensmtp

### ISSUE THREAD

**Issue by hongy19** [OpenSMTPD/OpenSMTPD#733]
Hi it seems opensmtp couldn't work with opendkim. Do we have any  DKIM solution except dkimproxy which is very old and doesn't update for long time.

**Comment by poolpOrg** [comment]
not at the moment, but this is a question that should be asked on the mailing list, not as a problem report. closing ticket

**Comment by poolpOrg** [comment]
not at the moment, but this is a question that should be asked on the mailing list, not as a problem report. closing ticket
