### ISSUE TITLE
rewrite from address

### ISSUE THREAD

**Issue by hongy19** [OpenSMTPD/OpenSMTPD#734]
Hi all,
how could rewrite from address? 
for example, when I use mail command to send email, my from address is "hongy19@xxx.mydomain.net" by default and how could I automatically change it to "hongy19@mydomain.net"?
I try to use senders in listen and as in relay, but both of them seem doesn't work.

thanks

```
table passwd file:/etc/smtpd/passwd
table aliases file:/etc/smtpd/aliases
table domainemail  { hongy19 = hongy19@mydomain.net}
listen on lo senders <domainemail> masquerade
listen on lo port 10028 tag DKIM
listen on ens3 tls pki mx.mydomain.net
accept for local alias <aliases> deliver to mbox
accept from any for domain "mydomain.net" alias <aliases> deliver to mbox
accept tagged DKIM for any relay as "@mydomain.net" pki mx.mydomain.net_
accept from local for any relay via smtp://127.0.0.1:10027
```

**Comment by poolpOrg** [comment]
Your address appears in two layers:

- the protocol, which is the address that is advertised before we send the content of the mail;
- the data, which is the address displayed in headers;

Which one are you talking about ?

**Comment by hongy19** [comment]
hi PoolpOrg, 
I am talking about second one, header in From.  My understanding is masquerade is used to change that one?

**Comment by jdelic** [comment]
@hongy19 
> I am talking about second one, header in From. My understanding is masquerade is used to change that one?

As @poolpOrg said, you have to distinguish between the so called "SMTP envelope data" that is sent over the wire in the protocol session in the `MAIL FROM` and `RCPT TO` stanzas and the Email headers prepended to the actual message which follows the `DATA` stanza.

As [smtpd.conf(5)](http://man.openbsd.org/smtpd.conf) states:
> If the senders parameter is used, then smtpd(8) will look up a mapping of username to email addresses to see whether the authenticated user is allowed to submit mail as the sender that was provided in the SMTP session. **In addition, if the masquerade option is provided, the From header will be rewritten to match the sender provided in the SMTP session.** (emphasis mine)

So the `masquerade` option *does not what you want*. It will replace the `From:` header with the envelope sender from the `MAIL FROM` stanza.

Instead, every email program is free to set its own `From:` header to whatever it wants it to be. Commonly these headers are not validated. Anti-spam measures care much more about the envelope data, which is where the actual mail routing takes place. If you don't explicitly specify the `From:` header value, most unix mail programs will use the logged in user, which seems to be what's happening to you. So your best bet is to configure `mail` correctly. Unfortunately on many systems `mail` is redirected to one of many different packages, so it's hard to specify what would work for you without knowing what you are using. 

Assuming `mail` is really `heirloom-mailx` on your system, take a look at [mailx(1)](https://linux.die.net/man/1/mail): `-r from-addr` would do what you want, if your version of `mailx` supports it. Alternatively, if your underlying system uses `sendmail` to send mail, you can probably pass the `-f` command-line option through mail, by doing:

```
mail -s "Subject" recipient@example.com -- -f hongy19@mydomain.net < body 
```

where the `--` will tell `mail` to pass everything after it to the underlying `sendmail`. Depending on what is installed you might also be able to simply update your local `.mailrc` to behave like you want it to. You should really have a look at `mail --help` or `man mail`.

If you *really* want to rewrite the `From:` header on an email through OpenSMTPD, you could use `accept ... relay via ...`, `listen on ... tag xxx` and `accept tagged xxx ...` and write your own  SMTP-speaking filter based off something [this abandoned example by me](https://github.com/jdelic/opensmtpd-plusdashfilter-server/blob/0967649d4710760da8a5ce7521c5e09571b21697/plusdashfilter/server.py). It's not that hard to do, but likely totally unnecessary if you can just configure your local `.mailrc` correctly.
