### ISSUE TITLE
filter-rspamd doc/man page missing

### ISSUE THREAD

**Issue by hostingnuggets** [OpenSMTPD/OpenSMTPD#736]
Hi,

I would like to test the filter-rspamd filter from the OpenBSD-extras but could not find any small documentation or man page associated with it. Can anyone give me a few hints how to use it? I would be happy to submit any issues found if that may help to progress with this filter.

Cheers

**Comment by poolpOrg** [comment]
filters in general are a work in progress.

filter-rspamd in particular is nowhere near working yet which is why it hasn't got a man page.

**Comment by hostingnuggets** [comment]
Exactly that's why I would like to test them and report issues in order to help you progress with the filters as these are a very important feature of OpenSMTPD. Where should I report my findings and issues?

**Comment by poolpOrg** [comment]
That's not how it works.

There's no point in testing and reporting issues if things are nowhere near working, we're not at a stage where we want people to report issues yet, we're at a stage where we want to be able to build things on monday that we'll break completely on wednesday without anyone complaining.

We'll publish a man page when we're ready for users to test

**Comment by hostingnuggets** [comment]
Ok I understand, thanks for taking the time and explaing.

I will then be more patient and test as soon as there is a man page ready.
