### ISSUE TITLE
Ideas: resilience features

### ISSUE THREAD

**Issue by chneukirchen** [OpenSMTPD/OpenSMTPD#740]
Comparing OpenSMTPD to Postfix a bit, I found some features that should be not very hard to add and probably are a good idea against malicious users.

- Detect HTTP request verbs and disconnect (e.g. when XHR requests are reflected to port 25.)
  This can be done by implementing the words GET/POST/HEAD etc.

- Count how many 5.5.1 errors were sent and disconnect after a certain amount.
  Postfix also seems to do an exponential timeout here.

**Comment by poolpOrg** [comment]
discussed with @ericfaurot , we're both opposed to the first idea.
The second idea will be part of #799
