### ISSUE TITLE
truncated error in email bounces

### ISSUE THREAD

**Issue by toddfries** [OpenSMTPD/OpenSMTPD#741]
`
2$ telnet gmail-smtp-in.l.google.com 25      
Trying 2607:f8b0:400e:c03::1a...
Connected to gmail-smtp-in.l.google.com.
Escape character is '^]'.
220 mx.google.com ESMTP w18si10449105pfg.227 - gsmtp
ehlo fries.net
250-mx.google.com at your service, [2607:f2f8:af98::3]
250-SIZE 157286400
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
mail from: <todd@fries.net>
250 2.1.0 OK w18si10449105pfg.227 - gsmtp
rcpt to: <toddfries@gmail.com>
250 2.1.5 OK w18si10449105pfg.227 - gsmtp
data
354  Go ahead w18si10449105pfg.227 - gsmtp
Subject: testing
From: <todd@fries.net>
To: <toddfries@gmail.com>

test
.
550-5.7.1 [2607:f2f8:af98::3] Our system has detected that this message does not
550-5.7.1 meet IPv6 sending guidelines regarding PTR records and authentication
550-5.7.1 . Please review
550-5.7.1  https://support.google.com/mail/?p=IPv6AuthError for more information
550 5.7.1 . w18si10449105pfg.227 - gsmtp
Connection closed by foreign host.
'
When the error shows up in the maillog and also in the email bounceback, it is only the last 550 line that is presented, therefore making the error impossible to troubleshoot without manually using telnet or similar.

**Comment by poolpOrg** [comment]
I implemented the line continuation concat in revision 1.76 of mta_session.c a few years ago:

https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/smtpd/mta_session.c.diff?r1=1.75&r2=1.76&f=h
