### ISSUE TITLE
Feature request: Allowing fallback relays when using "relay via"

### ISSUE THREAD

**Issue by mickaeltorres** [OpenSMTPD/OpenSMTPD#766]
It would be useful in certain situations to be able to specify multiple IPs/hosts for a "relay via" rule, without using a DNS MX lookup.
Either fallback or round robin would be nice.
Gilles suggested allowing something like "relay via <relay_table>", with relay_table containing the relays to try.

**Comment by poolpOrg** [comment]
This issue is being handled in ticket #772 with the grammar rewrite, it is actually already fixed in the new-grammar branch that I committed but requires a MTA fix which @ericfaurot is currently working on.

I'll close this ticket as it is now referenced in the other one.
