### ISSUE TITLE
Recipient tables are ignored for reject rules

### ISSUE THREAD

**Issue by jdelic** [OpenSMTPD/OpenSMTPD#767]
I tried to set up a `reject` rule that rejects incoming mail for any email address not part of a _type=mailaddr_ table in PostgreSQL.

```
table validrecipients postgres:/etc/smtpd/postgresql.table.conf
listen on "192.168.56.163" port 25 hostname "mail.example.com" tag UNFILTERED
reject tagged UNFILTERED from any recipient ! <validrecipients>
accept tagged UNFILTERED from any for any relay via "smtp://127.0.0.1:10026"
```

The table is set up as:

```
conninfo postgresql://[redacted]@127.0.0.1:5432/authserver
query_mailaddr    SELECT * FROM authserver_resolve_alias($1);
```

The database it set up correctly:

```
authserver=> SELECT * FROM authserver_resolve_alias('notexist@example.com');
 alias
-------
(0 rows)

authserver=> SELECT * FROM authserver_resolve_alias('test@example.com');
      alias
------------------
 test@example.com
(1 row)
```

When I test this setup using a telnet session:

```
[root@test ~]$ telnet 192.168.56.163 25
Trying 192.168.56.163...
Connected to 192.168.56.163.
Escape character is '^]'.
220 mail.example.com ESMTP OpenSMTPD
HELO example.com
250 mail.example.com Hello example.com [192.168.56.163], pleased to meet you
MAIL FROM: <sender@example.com>
250 2.0.0: Ok
RCPT TO: <notexist@example.com>
250 2.1.5 Destination address valid: Recipient ok
Connection closed by foreign host.
```

As you can see, the reject rule is not matched. I set up a trace and here are the relevant lines:

PostgreSQL statement log:
```
2017-02-02 15:42:03 UTC [13636-1] {redacted}@authserver LOG:  execute stmt3: SELECT * FROM authserver_resolve_alias($1);
2017-02-02 15:42:03 UTC [13636-2] [redacted]@authserver DETAIL:  parameters: $1 = 'notexist@example.com'
```

OpenSMTPD log:
```
lookup: check "192.168.56.163" as NETADDR in table static:<anyhost> -> found
lookup: check "notexist@example.com" as MAILADDR in table proc:validrecipients -> 0
rule matched: accept tagged UNFILTERED from <anyhost> for  domain <anydestination> relay via smtp://127.0.0.1:10026
```

I would have expected the reject rule to match and deny the email.

**Comment by jdelic** [comment]
In fact the most simple rule:

```
reject recipient { "notexist@example.com" }
```

will already not match. So that rules out the database code.

**Comment by jdelic** [comment]
This is OpenSSL 6.0.2p1 btw, on Debian Stretch.

**Comment by poolpOrg** [comment]
That can't be right :-/

I'll look into this (and other PR / issues) as soon as my exams are done on Saturday ;-)

**Comment by jdelic** [comment]
> I'll look into this (and other PR / issues) as soon as my exams are done on Saturday ;-)

no worries. And best of luck with your exams!

**Comment by poolpOrg** [comment]
I've tried to reproduce and code works as expected for me, both when using negation and not, I suspect your issue is because your 'reject' rule does not specify a 'for' parameter which causes it to default to 'for local'.

Can you confirm ?

    table v { gilles@laptop.poolp.org }
    reject from any for any recipient <v>

$ echo test | mail gilles@laptop.poolp.org 
send-mail: command failed: 550 Invalid recipient
$ echo test | mail root@laptop.poolp.org   
$

    table v { gilles@laptop.poolp.org }
    reject from any for any recipient ! <v>

$ echo test | mail gilles@laptop.poolp.org 
$ echo test | mail root@laptop.poolp.org   
send-mail: command failed: 550 Invalid recipient
$

**Comment by jdelic** [comment]
@poolpOrg 
> Can you confirm ?

Are you sure that your "550 invalid recipient" wasn't generated by the default reject when no rule matches?

I ran the following config:
```
listen on "192.168.56.163" port 25 hostname "mail.maurusnet.test"
reject from any recipient { notvalid@example.com }
```

and then the following session:
```
Trying 192.168.56.163...
Connected to 192.168.56.163.
Escape character is '^]'.
220 mail.maurusnet.test ESMTP OpenSMTPD
HELO example.com
250 mail.maurusnet.test Hello example.com [192.168.56.163], pleased to meet you
MAIL FROM: <test@example.com>
250 2.0.0: Ok
RCPT TO: <notvalid@example.com>
550 Invalid recipient
quit
221 2.0.0: Bye
```

and got the following logs:
```
741247078ef82b98 smtp event=connected address=192.168.56.163 host=auth.maurusnet.test
lookup: check "192.168.56.163" as NETADDR in table static:<anyhost> -> found
lookup: check "notvalid@example.com" as MAILADDR in table static:<dynamic:0> -> found
lookup: check "example.com" as DOMAIN in table static:<localnames> -> 0
no rule matched
741247078ef82b98 smtp event=failed-command command="RCPT TO: <notvalid@example.com>" result="550 Invalid recipient"
```

`no rule matched` seems wrong to me after `-> found`. Is that what happens on your end, too?

**Comment by poolpOrg** [comment]
You I'm sure that my test was correct, the reject was in front of my other local rules which will accept any mail submitted locally but I think you misread what I said.

Your reject rule does not provide a 'for' parameter which is equivalent to specifying 'for local' and in the example you just pasted, you did the same thing.

Unless your local machine has 'example.com' as its hostname, you should have:

    reject from any for domain example.com recipient { notvalid@example.com }

or

    reject from any for any recipient { notvalid@example.com }

or any variation depending on the scope you want to apply, but what you have:

    reject from any recipient { ... }

is essentially:

    reject from any for local recipient { ... }

**Comment by jdelic** [comment]
> Your reject rule does not provide a 'for' parameter which is equivalent to specifying 'for local' and in the example you just pasted, you did the same thing.

whoops, of course. Sorry, I was a bit distracted while running this test today :(. You are right:
```
listen on "192.168.56.163" port 25  hostname "mail.maurusnet.test"
reject from any for domain { example.com } recipient { notvalid@example.com }
```

yields:
```
cd1016922eef4d25 smtp event=connected address=192.168.56.163 host=auth.maurusnet.test
lookup: check "192.168.56.163" as NETADDR in table static:<anyhost> -> found
lookup: check "notvalid@example.com" as MAILADDR in table static:<dynamic:1> -> found
lookup: check "example.com" as DOMAIN in table static:<dynamic:0> -> found
rule matched: reject from <anyhost> for  domain <dynamic:0>
cd1016922eef4d25 smtp event=failed-command command="RCPT TO: <notvalid@example.com>" result="550 Invalid recipient"
cd1016922eef4d25 smtp event=closed reason=quit
```

So that works as intended. Thanks for pointing it out.

I guess the main take-away from this ticket is that [http://man.openbsd.org/smtpd.conf](smtpd.conf(5)) should make it more clear that `for local` is the default. It's clearly stated for `from local`, but not for `for local`. Should I file an additional ticket for that?

As an aside... is there any way for a `reject` rule to resolve virtuals/aliases before matching recipients?

**Comment by poolpOrg** [comment]
Yes, an improvement to the man page is in order, please open a ticket and I'll take care of it tomorrow during my cleanup round :-)

As for your other question, there's no way to resolve virtual/aliases before matching because of a semantic issue more than a technical issue. To be able to figure that a user does not exist for a domain, you need to be able to match a domain and not find the user within that domain. If we didn't match rule, we'd fall back to the next rule which would have lots of undesirable effects and would make some rulesets very hard to write.

**Comment by jdelic** [comment]
issue for man page update has been filed, so this can be closed afaict. Thanks @poolpOrg
