### ISSUE TITLE
Rework configuration and internal structures

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#772]
We made a mistake by having smtpd.conf rules perform both decision and action.

This has led to numerous issues, many that users are not aware of because they result in code being more complex than it should be, and many that users are aware of but don't realize are caused by this "try to shove decision and action in same rule".

There are currently several tickets that are a direct result of this as well as several requests that are just not doable like daemon config reload, envelopes catching up configuration change after a restart, ...

There's work in progress to rework configuration as well as the internal structures that are involved, it's going to take many weeks to be done right and it's going to take many months before we're confident we didn't introduce a regression.

I've finished the grammar already but I want the entire daemon adapted to the new structures before I open a discussion on the individual keywords, syntax & general bikeshed.

This will NOT make it to OpenSMTPD 6.1 in May 2017, this is likely to be part of the OpenSMTPD 6.2 release in November 2017.

**Comment by poolpOrg** [comment]
work has started in the branch new-config:
https://github.com/OpenSMTPD/OpenSMTPD/tree/new-config

as of today the following grammar is already parsed correctly:
https://gist.github.com/poolpOrg/1eaa948d5bfd82a49e1851b9dadc746e

while at it, I'm making a pass to clarify error messages and make them more uniform

**Comment by poolpOrg** [comment]
here's a sample of the dispatchers grammar that's correctly parsed:

[smtpd-dispatchers.conf.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/1193002/smtpd-dispatchers.conf.txt)

**Comment by poolpOrg** [comment]
HUGE progress made in that area.

The last two layers that require to be adapted are MTA and bounces which I'll start working on starting tomorrow.

**Comment by poolpOrg** [comment]
This is mostly done except for a regression in aliases resolution, being investigated.

**Comment by poolpOrg** [comment]
this is fully done, currently running on all my machines since last week, i'm cleaning up some keywords and rewriting the man page for smtpd.conf before submitting to hackers@ and closing this ticket.

**Comment by MrSorcus** [comment]
When will be released?

**Comment by poolpOrg** [comment]
It will be released "stable" in October/November with OpenBSD 6.4

The code is already available in the 'dispatcher' branch on github, this is what I'm running myself, and I will start the producing snapshots for testing in the next few days

The main issue is that we can't release this before rewriting the documentation and planning on how to help people migrate ;-)

**Comment by poolpOrg** [comment]
committed.
