### ISSUE TITLE
Multiple connections to smtp server, only one used

### ISSUE THREAD

**Issue by mickaeltorres** [OpenSMTPD/OpenSMTPD#774]
I'm seeing a strange thing happening on OpenSMTPD 6.0.2p1 on debian jessie.
For each each outbound mail I see three connections to the smtp server, with only one used:

Mar 17 14:56:09 mta-01 smtpd[26883]: ffffffff9325dfa0 smtp event=connected address=10.x.x.x host=10.x.x.x
Mar 17 14:56:09 mta-01 smtpd[26883]: ffffffff9325dfa0 smtp event=message msgid=c76c9ce0 from=<xxx@xxx.com> to=<yyy@yyy.fr> size=70124 ndest=1 proto=ESMTP
Mar 17 14:56:09 mta-01 smtpd[26883]: ffffffffc0d012fb mta event=connecting address=smtp+tls://z.z.z.z:25 host=z.z.z.z
Mar 17 14:56:09 mta-01 smtpd[26883]: 642d684c342f5b53 mta event=connecting address=smtp+tls://z.z.z.z:25 host=z.z.z.z
Mar 17 14:56:09 mta-01 smtpd[26883]: fffffffff0f6016d mta event=connecting address=smtp+tls://z.z.z.z:25 host=z.z.z.z
Mar 17 14:56:09 mta-01 smtpd[26883]: ffffffff9325dfa0 smtp event=closed reason=quit
Mar 17 14:56:09 mta-01 smtpd[26883]: fffffffff0f6016d mta event=connected
Mar 17 14:56:09 mta-01 smtpd[26883]: 642d684c342f5b53 mta event=connected
Mar 17 14:56:09 mta-01 smtpd[26883]: ffffffffc0d012fb mta event=connected
Mar 17 14:56:09 mta-01 smtpd[26883]: 642d684c342f5b53 mta event=starttls ciphers=version=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256
Mar 17 14:56:09 mta-01 smtpd[26883]: ffffffffc0d012fb mta event=starttls ciphers=version=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256
Mar 17 14:56:09 mta-01 smtpd[26883]: fffffffff0f6016d mta event=starttls ciphers=version=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256
Mar 17 14:56:09 mta-01 smtpd[26883]: smtp-out: Server certificate verification succeeded on session 642d684c342f5b53
Mar 17 14:56:09 mta-01 smtpd[26883]: smtp-out: Server certificate verification succeeded on session ffffffffc0d012fb
Mar 17 14:56:09 mta-01 smtpd[26883]: smtp-out: Server certificate verification succeeded on session fffffffff0f6016d
Mar 17 14:56:09 mta-01 smtpd[26883]: fffffffff0f6016d mta event=closed reason=quit messages=0
Mar 17 14:56:09 mta-01 smtpd[26883]: ffffffffc0d012fb mta event=closed reason=quit messages=0
Mar 17 14:56:09 mta-01 smtpd[26883]: 642d684c342f5b53 mta event=delivery evpid=c76c9ce0f61c0be1 from=<xxx@xxx.com> to=<yyy@yyy.fr> rcpt=<-> source=s.s.s.s relay=z.z.z.z (z.z.z.z) delay=0s result=Ok stat=250 2.0.0 294947rvkq-1 Message accepted for delivery

The configuration file is as follow:

limit mta session-transaction-delay 0
limit mta conn-delay-relay 0
limit mta conn-delay-route 0
listen on 10.s.s.s tag ext
listen on 10.t.t.t tag int mask-source
*#* ext to int
accept tagged ext from any for domain domain1 relay
...
accept tagged ext from any for domain domainX relay
*#* int to ext
accept tagged int from any for any relay

I see this behavior only on internal to ext mails.

**Comment by ericfaurot** [comment]
That is because you set all delays to 0. You need to set a little delay between two connections attempts, to give the first connection a little chance to handle the mail before the connection engine decides it is to initiate a new one.

**Comment by poolpOrg** [comment]
I still think it is a bug @ericfaurot, let me explain:

The engine should know that a connection is being established and not attempt to establish a new one when there's already one being established.

There are several cases where you really need to set delays to 0, @mickaeltorres has a use case where there's only one endpoint to outgoing mail (one smarthost with one IP address), if the delay is 1s then it caps outgoing mails and creates a bottleneck so that it will take an hour to relay 3600 mails which is quite a low limit for a big company.

A very similar use-case is that of dkimproxy/clamav/spampd & friends where you relay to localhost and everyone sets delay to 0 to avoid bottleneck in the incoming path.

**Comment by ericfaurot** [comment]
The engine could be improved yes, but the caping you describe is not what happens. You get one new connection every second while there are mails to send, not one mail per second.

**Comment by poolpOrg** [comment]
oh right, so basically he can keep the transaction delay to 0s while leaving the connection delay to whatever default value, agreed.

I still think we should have a smarter approach to connection establishing in the MTA improvements we plan, the MTA should gradually attempt to create new connections based on current state of connections + knowledge of mails in queue

**Comment by mickaeltorres** [comment]
I'll try to remove the following:
limit mta conn-delay-relay 0
limit mta conn-delay-route 0

Thanks guys!

**Comment by poolpOrg** [comment]
yes please then close the ticket yourself when you confirm the "issue" goes away :)

**Comment by poolpOrg** [comment]
confirmed by phone a loooong time ago
