### ISSUE TITLE
extras: filter-rspamd LINE_MAX is too low for processing rspamd output

### ISSUE THREAD

**Issue by nanoant** [OpenSMTPD/OpenSMTPD#783]
With latest version 1.5.7 rspamd is sending JSON output that is longer than 2048 (LINE_MAX), this causes `filter-rspamd` to fail parsing incomplete JSON with 421 on `IO_DISCONNECTION` and prevent delivering any mails if this filter is on.

Replacing in `rspamd.c`:
~~~c
iobuf_xinit(&tx->iobuf, LINE_MAX, LINE_MAX, "on_eom");
~~~
with:
~~~c
iobuf_xinit(&tx->iobuf, 0, 0, "on_eom");
~~~
(which implies maximum 64KB buffer instead 2KB) solves the issue.

**Comment by ArchangeGabriel** [comment]
Filters are not supported currently.

**Comment by nanoant** [comment]
@ArchangeGabriel I know it is not, but still some ppl (like me) use it successfully. Therefore instead of that one I created a push request: https://github.com/OpenSMTPD/OpenSMTPD-extras/pull/47 and closing this.
