### ISSUE TITLE
filter-dnsbl blocks all mail with: received invalid command ""

### ISSUE THREAD

**Issue by cyphunk** [OpenSMTPD/OpenSMTPD#784]
When using the dnsbl filter any email recieved results in this message:

May 10 10:08:02 project1 smtpd[23559]: smtp-in: session fabdeb090c47bd9e: received invalid command: ""

**Comment by ArchangeGabriel** [comment]
Filters are not supported currently.

**Comment by poolpOrg** [comment]
Filters are not supported, we'll handle bug reports when they are supported.
