### ISSUE TITLE
OpenSMTPD incompatible with Letsencrypt

### ISSUE THREAD

**Issue by cyphunk** [OpenSMTPD/OpenSMTPD#785]
Letsencrypt's certbot runs routine updates and when it updates a certificate it creates a new one and changes a link to it. Their recommendation is that webservers and mail servers should utilize the link, thereby leaving certbot to update it transparently. OpenSMTPD however doesn't like symlinks due to permissions 777. As a workaround one can create a letsencrypt hook script that is run after update but this is less than optimal. Also one has to then becareful whenever they update or change certs manually with certbot, to be certain to go and manually change their smtpd.conf.

More optimal would be if opensmtpd could support symlinks for the pki certificate file definitions? Developers can disagree and close this though if they disagree. I would understand. Here is the script though which perhaps others may find useful in the future.

    # /etc/letsencrypt/renew-hook.d/smtpd:
    domain="yourdomain.com"
    livecert=$(readlink -f /etc/letsencrypt/live/$domain/privkey.pem)
    sed -i "s#.*pki $domain key.*#pki $domain key \"$livecert\"#" /etc/smtpd.conf
    chmod 640 $livecert
    smtpctl stop
    sleep 1
    smtpd

**Comment by ArchangeGabriel** [comment]
Works for me here, with symlink. Permissions on the symlink are irrelevant.

My setup (relevant parts only):

– `smtpd.conf`
```
pki <domainname> certificate "/etc/smtpd/tls/<domainname>.crt"
pki <domainname> key "/etc/smtpd/tls/<domainname>.key
```
– files in `/etc/smtpd/tls`:
```
lrwxrwxrwx 1 root root <domainname>.crt -> /etc/letsencrypt/live/<domainname>/fullchain.pem
lrwxrwxrwx 1 root root <domainname>.key -> /etc/letsencrypt/live/<domainname>/privkey.pem
```
– files in `/etc/letsencrypt/live/<domainname>/`:
```
lrwxrwxrwx 1 certbot certbot cert.pem -> ../../archive/<domainname>/certX.pem
lrwxrwxrwx 1 certbot certbot chain.pem -> ../../archive/<domainname>/chainX.pem
lrwxrwxrwx 1 certbot certbot fullchain.pem -> ../../archive/<domainname>/fullchainX.pem
lrwxrwxrwx 1 certbot certbot privkey.pem -> ../../archive/<domainname>/privkeyX.pem
```
– files in `/etc/letsencrypt/archive/<domainname>/`:
```
-r--r--r-- 1 root root certX.pem
-r--r--r-- 1 root root chainX.pem
-r--r--r-- 1 root root fullchainX.pem
-r-------- 1 root root privkeyX.pem
```

This last part is the important one. Those are not the default permissions, and AFAIK certbot (but you could be using other tools though) still doesn’t support setting specific permissions, so you either need to change them in your timer script (cron, systemd, whatever) or using a hook just like you do, but much simpler.

**Comment by poolpOrg** [comment]
works for me too, this is a user issue.

**Comment by cyphunk** [comment]
thank you for the feedback. it helped. for future reference: in the process of debugging various setup issues I included that chmod 640 command which changed the permissions of the archive cert files to insecure values, which is why openstmp complained.
