### ISSUE TITLE
extras: tool-stats script seems to be unhappy with logfile turning message lines

### ISSUE THREAD

**Issue by ckeen** [OpenSMTPD/OpenSMTPD#794]
In a cron job I am calling tool-stats weekly based on the OpenSMTPD tutorial. I am getting these messages:

> Subject: Cron <root@mail> /usr/bin/zcat /var/log/maillog.*.gz | /usr/local/bin/tool-stats  | /usr/bin/mail -s "mail  smtpd log report" root                                                                                                                 
>                                                                                                                                               
>tool-stats: strptime failed line 1: Undefined error: 0                                                                                         
>tool-stats: strptime failed line 44: Undefined error: 0                                                                                        
>tool-stats: strptime failed line 45: Undefined error: 0                                                                                        
>tool-stats: strptime failed line 91: Undefined error: 0                                                                                        
>tool-stats: strptime failed line 92: Undefined error: 0                                                                                        
>tool-stats: strptime failed line 146: Undefined error: 0                                                                                       
>tool-stats: strptime failed line 147: Undefined error: 0                                                                                       
>tool-stats: strptime failed line 192: Undefined error: 0                                                                                       
>tool-stats: strptime failed line 193: Undefined error: 0                                                                                       
>tool-stats: strptime failed line 238: Undefined error: 0                                                                                       
>tool-stats: strptime failed line 239: Undefined error: 0                                                                                       
>tool-stats: strptime failed line 318: Undefined error: 0                                                                                       
>tool-stats: strptime failed line 319: Undefined error: 0                                                                                       
>tool-stats: strptime failed line 378: Undefined error: 0                                                                                       
  
These lines look like this:

>2017-06-25T10:00:01.912Z mail newsyslog[59224]: logfile turned over

Maybe the strptime template does not fit these?

**Comment by poolpOrg** [comment]
author doesn't have time to maintain this tool, we will remove it unless someone commits to maintain it.
