### ISSUE TITLE
relay via requires mx?

### ISSUE THREAD

**Issue by star26bsd** [OpenSMTPD/OpenSMTPD#796]
Hi

Why would OpenSMTP want to lookup the MX of my specifically provided smarthost s025.cyon.ch? Do I need to specify it in square brackets like sendmail to circumvent MX lookup?

OpenBSD 6.1, OpenSMTPd 6.0.0.

smtpd.conf:
```
listen on lo0

table aliases db:/etc/mail/aliases.db
table secrets db:/etc/mail/secrets.db

accept for local alias <aliases> deliver to mbox
accept from local for any relay via smtps+auth://label@s025.cyon.ch auth <secrets> as xxx@rickauer.com
```

`$ dmesg | mail -s test xxx@gmail.com`

`$ doas smtpd -vd`

d4fcfce7e420b7a6 smtp event=message address=local host=frido.rickauer.tld msgid=b5b47ec4 from=<stephan@frido.rickauer.tld> to=<xxx@gmail.com> size=34115 ndest=1 proto=ESMTP
debug: scheduler: evp:b5b47ec451bfdfc1 scheduled (mta)
d4fcfce7e420b7a6 smtp event=closed address=local host=frido.rickauer.tld reason=quit
debug: smtp: 0xd60d6c000: deleting session: done
debug: mta: received evp:b5b47ec451bfdfc1 for <xxx@gmail.com>
debug: mta: draining [relay:s025.cyon.ch,smtps,auth=secrets:label,mx] refcount=1, ntask=1, nconnector=0, nconn=0
debug: mta: querying secret for [relay:s025.cyon.ch,smtps,auth=secrets:label,mx]...
debug: mta: querying MX for [relay:s025.cyon.ch,smtps,auth=secrets:label,mx]...
debug: mta: [relay:s025.cyon.ch,smtps,auth=secrets:label,mx] waiting for MX secret
lookup: lookup "label" as CREDENTIALS in table db:secrets -> "xxx@rickauer.com:asdwxax32f34fs"
debug: mta: ... got secret for [relay:s025.cyon.ch,smtps,auth=secrets:label,mx]: AHN1Ym1pc3Npb25Acmlja2F1ZXIuY29tAGFzZHd4YXgzMmYzNGZz
debug: mta: draining [relay:s025.cyon.ch,smtps,auth=secrets:label,mx] refcount=2, ntask=1, nconnector=0, nconn=0
debug: mta: [relay:s025.cyon.ch,smtps,auth=secrets:label,mx] waiting for MX
debug: control -> (null): pipe closed
debug: clearing p=(null), fd=11, pid=0
debug: Failed MX query for s025.cyon.ch:
debug: mta: ... got mx (0xd2688b220, s025.cyon.ch, [relay:s025.cyon.ch,smtps,auth=secrets:label,mx])
smtp-out: Failed to resolve MX for [relay:s025.cyon.ch,smtps,auth=secrets:label,mx]: No MX found for domain
debug: mta: draining [relay:s025.cyon.ch,smtps,auth=secrets:label,mx] refcount=1, ntask=1, nconnector=0, nconn=0
debug: mta_flush([relay:s025.cyon.ch,smtps,auth=secrets:label,mx], 80, "**No MX found for domain**")
0000000000000000 mta event=delivery evpid=b5b47ec451bfdfc1 from=<xxx@rickauer.com> to=<xxx@gmail.com> rcpt=<-> source="-" relay="s025.cyon.ch" delay=0s result="TempFail" stat="No MX found for domain"
debug: mta: freeing [relay:s025.cyon.ch,smtps,auth=secrets:label,mx]
debug: mta: flush for b5b47ec451bfdfc1 (->xxx@gmail.com)

Thanks,
Stephan

**Comment by star26bsd** [comment]
Providing the IP instead of a hostname works.

**Comment by aikudinov** [comment]
s025.cyon.ch has no MX or A record, how would it find IP to connect to?

**Comment by star26bsd** [comment]
Indeed. I've switched to using the IP cause I thought it's an smtpd issue. Now it turns out the remote smtps' tld is .net not .ch - sorry for the noise. Works like a charm. Thanks.
