### ISSUE TITLE
sometimes SMTP sessions disconnect after QUIT before sending reply

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#801]
There seems to be an issue where the SMTP engine will sometimes trigger a client disconnect after a QUIT before the QUIT ack has been sent.

In most cases this is not really an issue, there is no protocol violation, no message loss, but it seems to confuse some software that _expect_ the answer.

**Comment by jeroenp** [comment]
I'm seeing this in a piece of software using the Python 2.7 smtplib module, where quit() waits "forever" on a reply.

Is there a workaround? 

https://github.com/python/cpython/blob/2.7/Lib/smtplib.py#L773

**Comment by poolpOrg** [comment]
can you give the opensmtpd code in github a try ?
we made an SMTP engine cleanup which I just merged.

**Comment by jeroenp** [comment]
Works like a charm!

**Comment by poolpOrg** [comment]
this ticket should have been closed since then,
