### ISSUE TITLE
devops: we need CI

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#805]
We need someone to setup CI for all branches of this repository.

**Comment by jirutka** [comment]
I can set up Travis CI to test OpenSMTD on x86_64 Ubuntu Trusty (glibc) and Alpine Linux (musl libc, using [alpine-chroot-install](https://github.com/alpinelinux/alpine-chroot-install)). We can use Alpine also to test on different architectures using QEMU user-mode emulation (alpine-chroot-install makes it trivial to set up).

I’ve prepared such setup e.g. for binaryen just few weeks ago (see [here](https://github.com/WebAssembly/binaryen/blob/master/.travis.yml)).

**Comment by poolpOrg** [comment]
That would be great, yes

**Comment by jirutka** [comment]
I’ve tried to configure it, but found out that it will be a bit more complicated in the case of OpenSMTPD. I’m going to a vacation tomorrow, I can get back to it in one week.

**Comment by poolpOrg** [comment]
went nowhere but I'm setting up something at work now
