### ISSUE TITLE
devops: we need monitoring

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#806]
Weeks before releases, we often perform twitter shitstorm stress tests to make sure the code is stable in real conditions, we do basic monitoring.

We'd like to have a much better monitoring of the smtpd instance we're testing, covering both smtpd AND the host system.

Suggestions ?

**Comment by jirutka** [comment]
What kind of monitoring do you mean? Whether the service is accessible, response time, usage of system resources, logs monitoring…?

**Comment by poolpOrg** [comment]
As much monitoring as possible really.

smtpd monitoring would graph concurrency, inbound, outbound, tls vs cleartext, etc... basically any information that could be grabbed from syslog post-processing + smtpctl subcommands output. monitoring various timings would be nice too. the idea is to graph pretty much everything possible on a smtpd instance to spot things we wouldn't spot otherwise.

we'd also like graphing the system resources, memory and cpu over time since tests usually run for hours.

**Comment by alexsaezm** [comment]
For parsing a syslog and create graphs, you can use tools like ELK or Prometheus. One of the problems is that, AFAIK, there is no travis-like option (aaS and cheap)

And, another question. Where do you perform those tests? I guess you have a testing machine...

I want to help the project but I know very little about your workflow. Where can I read about this things?

**Comment by poolpOrg** [comment]
we have a test machine that's about all.

so far we used kibana but it required a separate machine because under stress the test machine may be brought to its knees, i'm curious what solutions devops can come up with and then we can determine if they are doable for us

**Comment by alexsaezm** [comment]
Can I reproduce your testing machine configs? How do you perform the test and how do you create the environment? I will try to create a testing environment and evaluate some tools if you want.

**Comment by rockyluke** [comment]
Hi @poolpOrg maybe you can try to install https://github.com/firehol/netdata on your servers. I think you'll love it !

**Comment by mikygee** [comment]
Hello Gilles,

Would it be possible to normalise the syslog messages
* For example "Remove for <session>"... would be renamed "<session> removed"
Many messages start with the session name, not this one.
* could you show your logstash rules ?
* Having smtpd monitored by snmp

I think the problem with kibana/syslog is that it generates many syslogs just for one mail that is sent. That's why the server goes on its knees.
Statistics retrieved with snmp or like apache/nginx status web page or API would be much better. You query the stat you want only when you need it (every 10 seconds, every minute...)

Thank you

**Comment by dR3b** [comment]
Prometheus +1

**Comment by poolpOrg** [comment]
currently working on it using collected + facette

**Comment by dR3b** [comment]
Why are using this "old" tools. There are really better options like Prometheus!

https://github.com/prometheus/prometheus/releases/download/v2.1.0/prometheus-2.1.0.openbsd-amd64.tar.gz

**Comment by mikygee** [comment]
Hello,

I think that opensmtpd should just offer an interface with the snmpd daemon.

The tools (Prometeus, collectd, etc.) should poll the snmpd in order to retrieve statistics
Opensmtpd is not a monitoring app, and should let the snmpd answer to stats questions.

Do you agree ?
