### ISSUE TITLE
devops: automate coverity and scan-build builds once a day

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#807]
Topic says it all.

**Comment by jirutka** [comment]
This should be IMO run on every push to the repository and for every pull request, as part of CI jobs. Or do you mean some specific setup with this?

**Comment by poolpOrg** [comment]
Unfortunately it can't :-(

scan-build can be plugged into CI jobs, that would work, however we have limited quota on coverity as I realized when I wrote a small build bot ...

**Comment by poolpOrg** [comment]
went nowhere, i'll setup something at work
