### ISSUE TITLE
invalid virtual ip or interface: all

### ISSUE THREAD

**Issue by ouafnico** [OpenSMTPD/OpenSMTPD#809]
Hi

Using Debian 9 (stretch), with opensmtpd from repos (6.0.2p1-2), I got this error when starting service:

Aug 07 17:00:19 debian systemd[1]: Starting LSB: opensmtpd Mail Transport Agent...
Aug 07 17:00:19 debian opensmtpd[1076]: Starting MTA: failed!
Aug 07 17:00:19 debian opensmtpd[1076]: invalid virtual ip or interface: all

When I use a line in conf like "listen on all ...".

**Comment by poolpOrg** [comment]
This is not a bug and the message is actually quite accurate :-)

"listen on" expects an interface name or an IP address, "all" is neither one so this is invalid.

**Comment by ouafnico** [comment]
Oh... I saw the "all" example indeed, but i though it will works on linux systems ;p
I will replace with ip address, will the service start without fail if the ip address is not yet added (during boot the opensmtp service start some seconds before the interface get ip address.)
