### ISSUE TITLE
smtpctl update table reports successful even if the table does not exists.

### ISSUE THREAD

**Issue by Zelest** [OpenSMTPD/OpenSMTPD#810]
The user will get a "command succeeded" when running "smtpctl update table foo", even if the table **foo** doesn't exists. A warning is properly logged, but never shown to the user.

Example:
> **$** doas smtpctl update table virtual 
> command succeeded
> **$** doas smtpctl update table virtuals
> command succeeded
> **$** tail -n 2 /var/log/maillog         
> Aug  8 08:58:56 apathy smtpd[5862]: warn: Lookup table not found: "virtual"
> Aug  8 08:58:58 apathy smtpd[5862]: info: Table "virtuals" successfully updated

**Comment by snimmagadda** [comment]
A fix has been committed to the OpenBSD tree. Thanks for the report.

**Comment by snimmagadda** [comment]
The code is now sync-ed up on github and will be part of 6.0.3 release.
