### ISSUE TITLE
portable: reallocarray interpose issue

### ISSUE THREAD

**Issue by dfateyev** [OpenSMTPD/OpenSMTPD#813]
From the RHBZ bug:

> openbsd-compat/reallocarray.c does not check HAVE_REALLOCARRAY, so it is compiled in even if the configure check indicates that the function is present.  As a result, the function provided by glibc is interposed.
>
> The attached patch should correct this.
> (Current upstream sources have a similar issue for explicit_bzero.)

More details are available in Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1480303

**Comment by dfateyev** [comment]
This change should be pretty straightforward.
@poolpOrg could you check it, perhaps?

**Comment by poolpOrg** [comment]
ok, will be merged shortly and part of next snapshot

**Comment by poolpOrg** [comment]
committed, and while at it I added a check for explicit_bzero() as mentioned in the bugzilla ticket.
