### ISSUE TITLE
Message-Id header not added if missing and listener port is 587

### ISSUE THREAD

**Issue by greecemunky** [OpenSMTPD/OpenSMTPD#814]
In a new setup (OS up-to-date Debian testing, OpenSMTPD 6.0.2p1 from Debian packages), Message-Id is not being set.

I started fresh, compiling OpenSMTPD 6.0.2p1 from source to debug.  The following needs to be changed.

File: smtpd/smtp_session.c

From:
```if (s->listener->local || s->listener->port == 587) {```

To:
```if (s->listener->local || ntohs(s->listener->port) == 587) {```

Works as expected now.  I also tested the amended code against port 25 and the header is still not present (also as expected).

FWIW, I don't know C, I just saw ```ntohs(listener->port)``` elsewhere and thought I'd give it a try.  I also am not familiar with push/pulling etc. and don't want to do anything silly so thought I'd raise it here as an issue instead.

Also, can/should the "missing header" check for Date be moved outside the if block?

**Comment by greecemunky** [comment]
Patches against current master branch:

If keeping "missing header" check for Date within if block:

```
--- smtpd/smtp_session.c_orig   2017-09-19 18:20:13.000000000 +1000
+++ smtpd/smtp_session.c        2017-10-12 10:03:08.756026156 +1100
@@ -1234,7 +1234,7 @@
        rfc2822_body_callback(&tx->rfc2822_parser,
            dataline_callback, s);

-       if (s->listener->local || s->listener->port == 587) {
+       if (s->listener->local || ntohs(s->listener->port) == 587) {
                rfc2822_missing_header_callback(&tx->rfc2822_parser, "date",
                    header_missing_callback, s);
                rfc2822_missing_header_callback(&tx->rfc2822_parser, "message-id",
```

Or, if moving "missing header" check for Date outside if block:

```
--- smtpd/smtp_session.c_orig   2017-09-19 18:20:13.000000000 +1000
+++ smtpd/smtp_session.c        2017-10-12 10:07:41.723574708 +1100
@@ -1233,10 +1233,10 @@
            header_domain_append_callback, s);
        rfc2822_body_callback(&tx->rfc2822_parser,
            dataline_callback, s);
+       rfc2822_missing_header_callback(&tx->rfc2822_parser, "date",
+           header_missing_callback, s);

-       if (s->listener->local || s->listener->port == 587) {
-               rfc2822_missing_header_callback(&tx->rfc2822_parser, "date",
-                   header_missing_callback, s);
+       if (s->listener->local || ntohs(s->listener->port) == 587) {
                rfc2822_missing_header_callback(&tx->rfc2822_parser, "message-id",
                    header_missing_callback, s);
        }
```

**Comment by poolpOrg** [comment]
As mentioned in the PR, I think the bug lies elsewhere, the code here reads correct but requires you to do a conversion that should not be necessary.

The reason is that parse.y does htons() on the port when assigning it to the listener, whereas it should stay in host order and only be converted to network order before the bind() call, this way the code in smtp_session.c would be correct as is which .. it actually is.

**Comment by poolpOrg** [comment]
I have committed to OpenBSD a quick fix so that the upcoming minor release will be working correctly, we'll commit a better fix after the release is tagged as it is a bit more tricky.

I' ll synchronize github with the openbsd repository by this week-end, thanks for your report.
