### ISSUE TITLE
Support tagging for `listen on socket`

### ISSUE THREAD

**Issue by Ekleog** [OpenSMTPD/OpenSMTPD#815]
It looks like once, mail sent via the local enqueuer was tagged `local` (https://github.com/OpenSMTPD/OpenSMTPD/issues/295 https://github.com/OpenSMTPD/OpenSMTPD/issues/295). However, this sentence no longer appears in `man smtpd.conf`, so I assume it has become the `from local` argument.

However, `from local` also matches mail submitted via eg. `127.0.0.1:25`... or mail submitted via `127.0.0.1:clamsmtp-out-port` (which I learned to my detriment when I became an open relay for a few hours).

So, would it be possible to either give a special tag to `listen on socket` by making its syntax `listen on socket [tag tag] [mask-source]`, or to actually give a tag not given anywhere else?

Hoping I didn't misread documentation.

**Comment by Ekleog** [comment]
Actually I re-read the docs, and it does still state that incoming messages are tagged `local` (mea culpa for having grepped through the docs to find the message from the commit).

However, it appears to trigger a syntax error when trying to use it? I'm getting a syntax error for
```
accept tagged local from local for any \
  relay via smtp://127.0.0.1:10001 hostname my.hostname.example.org
```

**Comment by Ekleog** [comment]
More investigation led me to https://github.com/OpenSMTPD/OpenSMTPD/blob/portable/smtpd/parse.y#L2088 ; so I assume the `local` tag functionality is still supposed to be present and different from the `from local` tag.

However, maybe it is an issue in the parser, introduced with the introduction of the `local` keyword?

In which case there would be three options:
 *  The easiest: change the `local` tag automatically added to  to something else (which would break retrocompatibility by adding a reserved tag… maybe causing issues if people already used it as a tag?)
 * Add a `tagged [tag]` option to `listen on socket`, and remove this auto-tagging-with-`local` feature (which would I think be my favorite, from a user's standpoint, as it would bring it in line with the other `listen on` options -- having `listen on socket` not being implicitly enabled would be even better, to me, but it'd be a major retrocompatibility breach and would be the subject of another issue)
 * Work around the issue by making the parser more complex so as to support `local` both as a keyword and as a tag (but this would bring quite a lot of complexity in the code for... not much?)

Please let me know if I can do anything more to help (or if you have any other idea for adding a rule matching only messages landing on the local socket with the current OpenSMTPD version, that would be great too!)

**Comment by poolpOrg** [comment]
This is fixed in the new grammar we committed recently and which will be shipped with the next major version of OpenSMTPD in a few months.

You can now write rules that will specifically match the UNIX socket:

    match from socket [...]

**Comment by Ekleog** [comment]
Great, thanks!
