### ISSUE TITLE
opensmtpd cannot read passwd-file on alpine linux

### ISSUE THREAD

**Issue by bl1nk** [OpenSMTPD/OpenSMTPD#816]
Hey there,

I decided to redo my personal mail setup to use a passwd-file instead of system users. I started with a simple config based on [this](https://www.opensmtpd.org/faq/example1.html).  
Dovecot works fine with the passwd-file provided, opensmtpd crashes on start.

```
debug: smtp: will accept at most 2043 clients
setup_proc: klondike done
debug: init private ssl-tree
passwd[7508]: warn: table-proc: bogus data
passwd[7508]: fatal: table-proc: exiting
warn: table-proc: pipe closed
fatal: table-proc: exiting
```

My passwd-file only has one entry for now which is

```
t...@domain.tld:$6$A0…:::::
```

I am running `opensmtpd-6.0.2p1` and tried to use `opensmtpd-extras-201607122008` 
and `opensmtpd-extras-201703132115` with both crashing. The password was 
generated with `smtpctl encrypt`. Host is running on alpine linux 3.6 which is using musl libc, the same config works on a debian, so I think it's related to the rather unusual libc being used.

**Comment by biotecs** [comment]
Might be a problem that there is no passwd table anymore due to: https://man.openbsd.org/smtpd.conf#table

Try to change your passwd to file:

smtpd.conf:
```
table passwd file:/etc/mail/passwd
```

/etc/mail/passwd:
```
user@domain.tld   $2b$10$....
```

**Comment by bl1nk** [comment]
By changing that the passwd file format is not recognized by dovecot anymore, right?

I wanted to use the `table-passwd` which is included in OpenSMTPD/OpenSMTPD-extras [here](https://github.com/OpenSMTPD/OpenSMTPD-extras/tree/master/extras/tables/table-passwd) so dovecot and opensmtpd share one username/password file.

**Comment by biotecs** [comment]
Yes that's true and I forgot about table-passwd in extras. Could you provide your smtpd.conf?

**Comment by bl1nk** [comment]
Sure
```
mailhost = "mail.domain.tld"

pki $mailhost certificate "/etc/letsencrypt/live/domain.tld/fullchain.pem"
pki $mailhost key "/etc/letsencrypt/live/domain.tld/privkey.pem"

table aliases file:/etc/smtpd/aliases
table domains file:/etc/smtpd/domains
table passwd passwd:/etc/smtpd/passwd
table virtuals file:/etc/smtpd/virtuals

listen on lo
listen on eth0 port 25 tls pki $mailhost
listen on eth0 port 587 tls-require pki $mailhost auth <passwd>

accept from local for local alias <aliases> deliver to lmtp "/var/dovecot/lmtp" rcpt-to
accept from any for domain <domains> virtual <virtuals> deliver to lmtp "/var/dovecot/lmtp" rcpt-to
accept from local for any relay
```

**Comment by biotecs** [comment]
Do you use a docker installation with Alpine? If so could you give me the link to the hub, so I can test it?

**Comment by bl1nk** [comment]
I run alpine on a vps with opensmtpd installed via `apk add opensmtpd opensmtpd-table-passwd`. No docker involved.

**Comment by jnbr** [comment]
this looks similar to #833

**Comment by jirutka** [comment]
I have the same problem, but it doesn't seem to be related to #883, 'cause I've already applied patch https://github.com/OpenSMTPD/OpenSMTPD/pull/835.
