### ISSUE TITLE
Missing support for RFC4954 AUTH LOGIN initial-response

### ISSUE THREAD

**Issue by biotecs** [OpenSMTPD/OpenSMTPD#819]
Due to RFC4954 the "AUTH LOGIN" smtp command can be used with username as initial response. In this case the state should change to:
https://github.com/OpenSMTPD/OpenSMTPD/blob/4d34dfe9cffe5683574342d7bbef6a7c9de00e11/smtpd/smtp_session.c#L1688

and return without doing:

https://github.com/OpenSMTPD/OpenSMTPD/blob/4d34dfe9cffe5683574342d7bbef6a7c9de00e11/smtpd/smtp_session.c#L1689

In my opinion there should be something like:

```
smtp_enter_state(s, STATE_AUTH_USERNAME); 
if (strchr(arg, '\0') != NULL) {
    smtp_rfc4954_auth_login(s, arg);
    return;
}
smtp_reply(s, "334 VXNlcm5hbWU6"); 
```
In 2014 there was an accepted pull request already: https://github.com/OpenSMTPD/OpenSMTPD/pull/425. But it is not existent in master anymore.

If you guys can confirm this, I would create a new pull request.

**Comment by b01t** [comment]
This breaks the way the .Net SmtpClient authenticates, meaning a bunch of tools written in .Net can not authenticate with this server. Please (re-) fix? :)

**Comment by poolpOrg** [comment]
fix committed to OpenBSD, will be synced to github shortly.
