### ISSUE TITLE
Recipient receives same mail again and again

### ISSUE THREAD

**Issue by shunyiyi** [OpenSMTPD/OpenSMTPD#827]
_mta: 0x1bd04436b6f0: MTA_READY -> MTA_MAIL
mta: 0x1bd04436b6f0: >>> MAIL FROM:<myname@mydomain.org>
mta: 0x1bd04436b6f0: IO_LOWAT <io:0x1bcfe8ee3100 fd=18 to=300000 fl=W ib=0 ob=0>
mta: 0x1bd04436b6f0: IO_DATAIN <io:0x1bcfe8ee3100 fd=18 to=300000 fl=R ib=8 ob=0>
mta: 0x1bd04436b6f0: <<< 250 ok
mta: 0x1bd04436b6f0: MTA_MAIL -> MTA_RCPT
mta: 0x1bd04436b6f0: >>> RCPT TO:<receiver@163.com>
mta: 0x1bd04436b6f0: IO_LOWAT <io:0x1bcfe8ee3100 fd=18 to=300000 fl=W ib=0 ob=0>
mta: 0x1bd04436b6f0: IO_DATAIN <io:0x1bcfe8ee3100 fd=18 to=300000 fl=R ib=8 ob=0>
mta: 0x1bd04436b6f0: <<< 250 ok
mta: 0x1bd04436b6f0: MTA_RCPT -> MTA_DATA
mta: 0x1bd04436b6f0: >>> DATA
mta: 0x1bd04436b6f0: IO_LOWAT <io:0x1bcfe8ee3100 fd=18 to=300000 fl=W ib=0 ob=0>
mta: 0x1bd0353f36f0: MTA_READY -> MTA_READY
mta: 0x1bd04436b6f0: IO_DATAIN <io:0x1bcfe8ee3100 fd=18 to=300000 fl=R ib=39 ob=0>
mta: 0x1bd04436b6f0: <<< 354 go ahead, end data with CRLF.CRLF
mta: 0x1bd04436b6f0: MTA_DATA -> MTA_BODY
mta: 0x1bd04436b6f0: >>> [...1329 bytes...]
mta: 0x1bd04436b6f0: IO_LOWAT <io:0x1bcfe8ee3100 fd=18 to=300000 fl=W ib=0 ob=0>
mta: 0x1bd04436b6f0: MTA_BODY -> MTA_BODY
mta: 0x1bd04436b6f0: end-of-file
mta: 0x1bd04436b6f0: MTA_BODY -> MTA_EOM
mta: 0x1bd04436b6f0: >>> .
mta: 0x1bd04436b6f0: IO_LOWAT <io:0x1bcfe8ee3100 fd=18 to=300000 fl=W ib=0 ob=0>
mta: 0x1bd0353f36f0: MTA_READY -> MTA_READY
mta: 0x1bd04436b6f0: IO_DATAIN <io:0x1bcfe8ee3100 fd=18 to=300000 fl=R ib=57 ob=0>
mta: 0x1bd04436b6f0: <<< 250 ok message accepted [1517042706.15737.9788,S=1538]
535676272dee095a mta event=error reason=Bad response: non-printable character in reply
535676272dee095a mta event=delivery evpid=c689fb5447bbe4ab from=<myname@mydomain.org> to=<receiver@163.com> rcpt=<-> source="207.148.219.23" relay="123.151.11.21 (mail.163.com)" delay=3s result="TempFail" stat="Bad response: non-printable character in reply"_

When mail has been delivered, it still in the queue. And recipient receives same mail again and again. 
"smtpd -d -T all" file is attached to the back.
[smtpd -d -T all.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/1669952/smtpd.-d.-T.all.txt)

**Comment by ericfaurot** [comment]
Hmmm. We should indeed change that behavior and accept the reponse if the status is correct to avoid that situation. But in this particular case, I don't see where the "non-printable character" is...

**Comment by poolpOrg** [comment]
@ericfaurot wasn't this committed and synced to github ?

**Comment by poolpOrg** [comment]
https://github.com/OpenSMTPD/OpenSMTPD/commit/abd105827fa9491b58dfce6a536bafd427846446#diff-2f8e7073c636fc412210c11590d75ae8L711

This was fixed in a recent commit, closing.
