### ISSUE TITLE
sendmail.opensmtpd problem (CentOS 7 / SELinux).

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#828]
Hello!

I'm having a bit of trouble with OpenSMTPD sendmail (on CentOS 7).

Here is the log from dovecot trying to send a vacation reply via sendmail.

A while ago I had the exact same problem with the nightly logwatch script that tried to use sendmail. It also failed with IO error. However when I triggered the logwatch script manually, then it worked.

[root@bwo dovecot]# stat /usr/sbin/sendmail
  File: ‘/usr/sbin/sendmail’ -> ‘/usr/sbin/smtpctl’

Log with errors as logged by smtpd (log verbose / trace all):

> Jan 29 17:06:35 bwo smtpd[10036]: debug: smtpd: forking mda for session 00fc801c182be803: "/var/run/dovecot/lmtp rcpt-to" as reio
> Jan 29 17:06:35 bwo smtpd[10036]: mproc: parent -> pony : 8 IMSG_MDA_FORK
> Jan 29 17:06:35 bwo smtpd[10040]: imsg: pony <- parent: IMSG_MDA_FORK (len=8, fd=21)
> Jan 29 17:06:35 bwo smtpd[10040]: debug: mda: got mda fd 21 for session 00fc801c182be803 evpid ea268fe9fb39a814
> Jan 29 17:06:35 bwo smtpd[10040]: mda: 0x22c93a0: IO_LOWAT <io:0x23afdb0 fd=21 to=-1 fl=W ib=0 ob=0>
> Jan 29 17:06:35 bwo smtpd[10040]: debug: mda: end-of-file for session 00fc801c182be803 evpid ea268fe9fb39a814
> Jan 29 17:06:35 bwo smtpd[10040]: mda: 0x22c93a0: IO_LOWAT <io:0x23afdb0 fd=21 to=-1 fl=W ib=0 ob=0>
> Jan 29 17:06:35 bwo smtpd[10040]: debug: mda: all data sent for session 00fc801c182be803 evpid ea268fe9fb39a814
> Jan 29 17:06:35 bwo dovecot: lmtp(14268): Connect from local
> Jan 29 17:06:35 bwo smtpd[10038]: mproc: control -> client-proc: enabled
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: increment: control.session
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: control.session (0x448f66): 0 -> 1
> Jan 29 17:06:35 bwo smtpd[10038]: mproc: control -> pony : 4 IMSG_CTL_SMTP_SESSION
> Jan 29 17:06:35 bwo smtpd[10040]: imsg: pony <- control: IMSG_CTL_SMTP_SESSION (len=4)
> Jan 29 17:06:35 bwo smtpd[10040]: debug: smtp: new client on listener: 0x22ef5d0
> Jan 29 17:06:35 bwo smtpd[10040]: smtp: 0x2372660: connected to listener 0x22ef5d0 [hostname=bwo.mrstuudio.ee, port=0, tag=local]
> Jan 29 17:06:35 bwo smtpd[10040]: smtp: 0x2372660: STATE_NEW -> STATE_CONNECTED
> Jan 29 17:06:35 bwo smtpd[10040]: 00fc801de0ebdac2 smtp event=connected address=local host=bwo.mrstuudio.ee
> Jan 29 17:06:35 bwo smtpd[10040]: smtp: 0x2372660: >>> 220 bwo.mrstuudio.ee ESMTP OpenSMTPD
> Jan 29 17:06:35 bwo smtpd[10040]: mproc: pony -> control : 45 IMSG_STAT_INCREMENT
> Jan 29 17:06:35 bwo smtpd[10040]: mproc: pony -> control : 51 IMSG_STAT_INCREMENT
> Jan 29 17:06:35 bwo smtpd[10040]: mproc: pony -> control : 0 IMSG_CTL_SMTP_SESSION
> Jan 29 17:06:35 bwo smtpd[10040]: smtp: 0x2372660: IO_LOWAT <io:0x22bda80 fd=20 to=300000 fl=W ib=0 ob=0>
> Jan 29 17:06:35 bwo smtpd[10038]: imsg: control <- pony: IMSG_STAT_INCREMENT (len=45)
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: increment: smtp.session
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: smtp.session (0x1173c10): 1 -> 2
> Jan 29 17:06:35 bwo smtpd[10038]: imsg: control <- pony: IMSG_STAT_INCREMENT (len=51)
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: increment: smtp.session.local
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: smtp.session.local (0x1173c10): 3 -> 4
> Jan 29 17:06:35 bwo smtpd[10038]: imsg: control <- pony: IMSG_CTL_SMTP_SESSION (len=0, fd=15)
> Jan 29 17:06:35 bwo smtpd[10038]: mproc: control -> client-proc : 0 IMSG_CTL_OK
> Jan 29 17:06:35 bwo smtpd[10040]: smtp: 0x2372660: IO_ERROR <io:0x22bda80 fd=20 to=300000 fl=R ib=0 ob=0>
> Jan 29 17:06:35 bwo smtpd[10040]: 00fc801de0ebdac2 smtp event=closed address=local host=bwo.mrstuudio.ee reason="io-error: Connection reset by peer"
> Jan 29 17:06:35 bwo smtpd[10040]: debug: smtp: 0x2372660: deleting session: IO error
> Jan 29 17:06:35 bwo smtpd[10040]: mproc: pony -> control : 45 IMSG_STAT_DECREMENT
> Jan 29 17:06:35 bwo dovecot: lmtp: Error: server too busy
> Jan 29 17:06:35 bwo smtpd[10038]: imsg: control <- pony: IMSG_STAT_DECREMENT (len=45)
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: decrement: smtp.session
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: smtp.session (0x1173d10): 2 -> 1
> Jan 29 17:06:35 bwo smtpd[10038]: debug: control -> (null): pipe closed
> Jan 29 17:06:35 bwo smtpd[10038]: debug: clearing p=(null), fd=14, pid=0
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: decrement: control.session
> Jan 29 17:06:35 bwo smtpd[10038]: ramstat: control.session (0x448f66): 1 -> 0
> Jan 29 17:06:35 bwo dovecot: lmtp(reio@bwo.mrstuudio.ee): Error: Sendmail process terminated abnormally, exit status 69
> Jan 29 17:06:35 bwo dovecot: lmtp(reio@bwo.mrstuudio.ee): Error: 6N4BGXs4b1q8NwAAinc3nQ: sieve: msgid=<fe283004-cb0d-de0b-d1a7-b68671d31710@mrstuudio.ee>: failed to send vacation response to <"Reio Remma" <reio@mrstuudio.ee>>: Failed to execute sendmail (temporary error)
> Jan 29 17:06:35 bwo dovecot: lmtp(reio@bwo.mrstuudio.ee): 6N4BGXs4b1q8NwAAinc3nQ: sieve: msgid=<fe283004-cb0d-de0b-d1a7-b68671d31710@mrstuudio.ee>: stored mail into mailbox 'INBOX'
> Jan 29 17:06:35 bwo dovecot: lmtp(14268): Disconnect from local: Successful quit
> Jan 29 17:06:35 bwo smtpd[10036]: debug: smtpd: mda process done for session 00fc801c182be803: exited okay

**Comment by dfateyev** [comment]
Haven't faced this issue. Could you test packages from epel?
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-e79327a816
https://koji.fedoraproject.org/koji/taskinfo?taskID=24496682

**Comment by whataboutpereira** [comment]
I'm currently running 6.0.3p1 that I built from source, however I had the same issue with Logwatch with 6.0.2 from epel.

**Comment by whataboutpereira** [comment]
Unfortunately still the same with the epel package (thanks btw! :) ).

> Jan 29 20:57:33 bwo dovecot: lmtp(25171): Connect from local
> Jan 29 20:57:33 bwo smtpd[25121]: e2697e6bd08d77f8 smtp event=connected address=local host=bwo.mrstuudio.ee
> Jan 29 20:57:33 bwo smtpd[25121]: e2697e6bd08d77f8 smtp event=closed address=local host=bwo.mrstuudio.ee reason="io-error: Connection reset by peer"
> Jan 29 20:57:33 bwo dovecot: lmtp: Error: server too busy
> Jan 29 20:57:33 bwo dovecot: lmtp(reio@bwo.mrstuudio.ee): Error: Sendmail process terminated abnormally, exit status 69

**Comment by whataboutpereira** [comment]
Okay, I turned SELinux Enforcing off for a try and it worked then.

There is nothing in the audit.log and I'm stumped on how to get it working with SELinux. :/

**Comment by whataboutpereira** [comment]
As a workaround I changed Dovecot to use submission_host = 127.0.0.1

Looking around I saw postfix et al having lots of different SELinux settings, but none for OpenSMTPD.

**Comment by whataboutpereira** [comment]
I just tried with a clean CentOS 7 system as well. Removed postfix, installed the latest OpenSMTPD from https://koji.fedoraproject.org/koji/taskinfo?taskID=24496682, still the same error.

**Comment by whataboutpereira** [comment]
So I got to delve deeper into the internals of SELinux.

I had to disable_dontaudit to see all the denial message from it.

I got mail via sendmail.opensmtpd working when I added the following SELinux modules:

> module selinux-sendmail-unconfined-socket 1.0;
> 
> require {
> 	type system_mail_t;
> 	type unconfined_service_t;
> 	class unix_stream_socket { read write append };
> }
> 
> #============= system_mail_t ==============
> allow system_mail_t unconfined_service_t:unix_stream_socket { read write append };

> module selinux-dovecot-sendmail 1.0;
> 
> require {
> 	type dovecot_t;
> 	type unconfined_service_t;
> 	class unix_stream_socket { read write append };
> }
> 
> #============= dovecot_t ==============
> allow dovecot_t unconfined_service_t:unix_stream_socket { read write append };

> module selinux-logwatch-sendmail 1.0;
> 
> require {
> 	type logwatch_t;
> 	type unconfined_service_t;
> 	class unix_stream_socket { read write append };
> }
> 
> #============= logwatch_t ==============
> allow logwatch_t unconfined_service_t:unix_stream_socket { read write append };

The IO errors are gone now and I'm finally starting to think I may start upgrading our old CentOS 5 server with QMail to CentOS 7 and OpenSMTPD! :)

**Comment by dfateyev** [comment]
Glad to see you got it working! Although I'm not a SELinux guru, so cannot decide whether the rules above are fully correct. Hopefully, others may find them usable.
As for EPEL package update, you also can leave karma for the update if the package works for you.

**Comment by whataboutpereira** [comment]
Done, with a comment once I got past the Captcha. :)

SELinux is such a hassle, but it's better than nothing I suppose!

**Comment by whataboutpereira** [comment]
Enlisting the aid of a SELinux guru wouldn't be bad though. I noticed sendmail.postfix was using a different SELinux contect to sendmail.opensmtpd.

**Comment by poolpOrg** [comment]
I don't think we can do anything more here so closing :-)
