### ISSUE TITLE
Ability to choose used crypto curves

### ISSUE THREAD

**Issue by ArchangeGabriel** [OpenSMTPD/OpenSMTPD#831]
Since we’re going to have OpenSSL 1.1.x API available soon, I might want to switch my server to X25519 only for KEX. OpenSSL supports setting usable curves (through `SSL_CTX_set1_curves_list` and `SSL_set1_curves_list` AFAIK), and other software (e.g. `nginx`) do it.

Adding such an option to OpenSMTPD would be nice. ;)

**Comment by poolpOrg** [comment]
This has been implemented in the branch [libtls-issue-831-curves](https://github.com/OpenSMTPD/OpenSMTPD/tree/libtls-issue-831-curves).

    smtp curves "X25519:P-256:P-384"
    listen on lo0 tls port 25 [...] curves "X25519:P-256"
    listen on lo0 tls port 26 [...] curves "X25519"

This will be merged to master after the 6.7.0 release is tagged because it relies on the switch to libtls which is too invasive to be part of the next major release. It will be part of the 6.8.0 release due in October.

**Comment by ArchangeGabriel** [comment]
Seems that this did not get merged in the end? I can only setup `protocols` and `ciphers`, while `curves` results in a syntax error. The man page does not reference `curves` either.

**Comment by poolpOrg** [comment]
I had it implemented, I can probably revive that

**Comment by ArchangeGabriel** [comment]
That would be nice. :) Maybe reopen in the meantime?

**Comment by poolpOrg** [comment]
Care to test the following diff ?

[curves.diff.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/12327089/curves.diff.txt)

**Comment by ArchangeGabriel** [comment]
If I’m right, we only need to port https://github.com/OpenSMTPD/OpenSMTPD/commit/3f09ead65dbd3069287211e016789658b813c7ec to current master?

**Comment by ArchangeGabriel** [comment]
(I see the branch also had some kind of sni feature, didn’t dig to much, but if it allows for sni without specifying all pki on every listen directive, I’m all for it!)
