### ISSUE TITLE
Separated SSL settings for different ports

### ISSUE THREAD

**Issue by ArchangeGabriel** [OpenSMTPD/OpenSMTPD#832]
This might not be worth it, but I’m starting this discussion just in case.

My use case is the following: I want my e-mail users to be able to send mail to the reasonably secure outside world, which means I require TLS but do not enforce a too strict set of ciphers, but I would like to restrict as much as possible the available SSL ciphers and curves (for enhanced security) between my users and the server (i.e. on the submission port). And also, I want them to be able to receive mails going from the (reasonably secure again) outside world, so here too I cannot reduce the cipher/curve list arbitrarily for now.

I agree that for outgoing/ingoing emails, this does not really make sense, because an attacker would just have to breach into the outgoing/ingoing connection instead. However, for “internal” emails (from my users to other of my users), this would matter.

Depending on your server usage profile, this might be a tiny use case, but it is, as long as outgoing is concerned (my users receive quite obviously more mails from outside), the main case for me (around 95 % of all sent emails).

**Comment by robert-scheck** [comment]
IMHO it's not only a tiny use-case, but a common real-world scenario appearing also in larger environments, thus it's supported by other common MTAs for ages already.

**Comment by poolpOrg** [comment]
This has been implemented in the branch [libtls-issue-832-ciphers](https://github.com/OpenSMTPD/OpenSMTPD/tree/libtls-issue-832-ciphers).

    listen on lo0 tls port 25 [...] ciphers HIGH
    listen on lo0 tls port 26 [...] ciphers HIGH:null

This will be merged to master **after the 6.7.0 release** because it relies on the switch to `libtls` which is too invasive to be part of the next major release. It will be part of the 6.8.0 release due in October.
