### ISSUE TITLE
Crash on user authentication

### ISSUE THREAD

**Issue by lyn1337** [OpenSMTPD/OpenSMTPD#833]
I'm experiencing a crash when I'm successfully authenticated and try to send.

```
# smtpd -dv
debug: init ssl-tree
info: loading pki information for foo.bar
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for foo.bar
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
info: OpenSMTPD 6.0.3-portable starting
debug: init ssl-tree
info: loading pki information for foo.bar
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for foo.bar
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: control -> klondike[12376] fd=5
setup_peer: control -> lookup[12378] fd=6
setup_peer: control -> pony express[12379] fd=7
setup_peer: control -> queue[12380] fd=8
setup_peer: control -> scheduler[12381] fd=9
debug: init ssl-tree
info: loading pki information for foo.bar
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for foo.bar
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: klondike -> control[12377] fd=5
setup_peer: klondike -> pony express[12379] fd=6
setup_done: ca[12376] done
setup_done: control[12377] done
setup_proc: control done
setup_proc: klondike done
debug: init ssl-tree
info: loading pki information for foo.bar
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for foo.bar
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: pony express -> control[12377] fd=5
setup_peer: pony express -> klondike[12376] fd=6
setup_peer: pony express -> lookup[12378] fd=7
setup_peer: pony express -> queue[12380] fd=8
debug: init ssl-tree
info: loading pki information for foo.bar
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for foo.bar
debug: using "fs" queue backend
debug: init ssl-tree
info: loading pki information for foo.bar
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for foo.bar
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: queue -> control[12377] fd=5
setup_peer: queue -> pony express[12379] fd=6
debug: init ssl-tree
info: loading pki information for foo.bar
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for foo.bar
setup_peer: queue -> lookup[12378] fd=7
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: queue -> scheduler[12381] fd=8
setup_peer: lookup -> control[12377] fd=5
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: lookup -> pony express[12379] fd=6
setup_peer: scheduler -> control[12377] fd=5
setup_peer: lookup -> queue[12380] fd=7
setup_peer: scheduler -> queue[12380] fd=6
setup_done: lka[12378] done
setup_proc: lookup done
setup_proc: pony express done
setup_done: pony[12379] done
setup_done: queue[12380] done
setup_proc: queue done
debug: ca_engine_init: using RSA privsep engine
setup_proc: scheduler done
setup_done: scheduler[12381] done
smtpd: setup done
debug: bounce warning after 4h
debug: parent_send_config_ruleset: reloading
debug: parent_send_config: configuring pony process
debug: parent_send_config: configuring ca process
debug: smtp: listen on 1.2.3.4 port 25 flags 0x401 pki "foo.bar" ca ""
debug: smtp: listen on 1.2.3.4 port 587 flags 0x469 pki "foo.bar" ca ""
debug: pony: rsae_init
debug: init private ssl-tree
debug: pony: rsae_init
debug: smtp: will accept at most 524283 clients
debug: queue: done loading queue into scheduler
debug: smtpd: scanning offline queue...
debug: smtpd: offline scanning done
debug: smtp: new client on listener: 0x562b984c5e20
3325930c6f234157 smtp event=connected address=XXX.XXX.XXX.XXX host=XXXXXXXXXXXXXXX
debug: lka: looking up pki "foo.bar"
debug: session_start_ssl: switching to SSL
debug: pony: rsae_priv_enc
3325930c6f234157 smtp event=starttls address=XXX.XXX.XXX.XXX host=XXXXXXXXXXXXXXX ciphers="version=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256"
debug: lka: authenticating for creds:user@foo.bar
debug: control -> lookup: pipe closed
debug: control agent exiting
debug: parent -> lka: pipe closed
smtpd: process lka socket closed
debug: queue -> lookup: pipe closed
debug: queue agent exiting
debug: scheduler -> queue: pipe closed
debug: scheduler agent exiting
debug: ca -> parent: pipe closed
debug: ca agent exiting
debug: pony -> lookup: pipe closed
debug: pony agent exiting

```

**Comment by greecemunky** [comment]
What does your config look like with respect to auth?

See if running one of the following commands instead provides more output during the auth/crash.

`smtpd -dv -T lookup`
`smtpd -dv -T all`

**Comment by lyn1337** [comment]
@greecemunky
```
cat /etc/smtpd.conf
pki foo.bat certificate "/etc/smtpd/foobar.crt"
pki foo.bar key "/etc/smtpd/foobar.key"

table creds "/etc/smtpd/mailcreds"
table aliases file:/etc/aliases

limit mta for domain gmail.com inet4

listen on eth0 port 587 inet4 tls-require pki 31337.one auth <creds>

accept from any for domain "foo.bar" alias <aliases> deliver to mbox
accept from local for local alias <aliases> deliver to mbox
accept for any relay
```

**Comment by greecemunky** [comment]
Try changing

`table creds "/etc/smtpd/mailcreds"`

to

`table creds file:/etc/smtpd/mailcreds`

**Comment by lyn1337** [comment]
@greecemunky
unchanged results

**Comment by lyn1337** [comment]
@greecemunky
unchanged results

**Comment by greecemunky** [comment]
What does your creds file look like?  Obfuscate the details before sending.

What’s your creds file’s permissions and who’s its owner/group?

Have you tried running smtpd with the suggested arguments?  It might provide more debugging output.

**Comment by lyn1337** [comment]
> What does your creds file look like? Obfuscate the details before sending.

```
# cat /etc/smtpd/mailcreds 
user@foo.bar	$6$C8L.vVgFzpiMAG/b$TiuMOTxt5Jod86a5Kukp6J7FSHhOf1r230Lre8twG2mlWYrSLatWJ/1eD./rP7xCYJAdTjTQ5hbttx874XS3p.
```

> What’s your creds file’s permissions and who’s its owner/group?

root:root 0444
I played with permissions (0777) already; no use.

> Have you tried running smtpd with the suggested arguments? It might provide more debugging output.

I think the only thing it did was listing the content of all loaded tables and the creds file.

**Comment by greecemunky** [comment]
I've replicated your setup as well as I could and it's crashing for me, too.  I attached strace to existing subprocesses and it appears to be the `lookup` process segfaulting (SIGSEGV) resulting in all terminating.

I believe it could be related with the crypt_checkpass function, in particular:

https://github.com/OpenSMTPD/OpenSMTPD/blob/b4921b15d80bf16304380bec28a004250b665cdf/openbsd-compat/crypt_checkpass.c#L20

By commenting the line out and recompiling, it sends the email (although without actual auth checks, so best not to mess with it in production environments).

crypt.h is available on my system, supposedly.

`checking crypt.h usability... yes`
`checking crypt.h presence... yes`
`checking for crypt.h... yes`
...
`checking for library containing crypt... -lcrypt`

I am not sure as to _why_ it's failing though.  Hopefully someone else can assist.

**Comment by greecemunky** [comment]
A guess is that `goodhash` in `crypt(pass, goodhash)` should only be the salt (not salt+hash), and as such returns NULL.

http://man7.org/linux/man-pages/man3/crypt.3.html#RETURN_VALUE

> On success, a pointer to the encrypted password is returned.  On
> error, NULL is returned.

> EINVAL
> _salt_ has the wrong format.

**Comment by lyn1337** [comment]
@greecemunky
Thank you very much for your efforts.

What would a workaround look like to be able to safely send out mail for now?

**Comment by greecemunky** [comment]
I think the best option is to get it fixed.

First, need to obtain the salt - start of `goodhash`, through to 3rd `$`, inclusive.  Then, call `crypt(pass, salt)`.

https://stackoverflow.com/a/2180446 may be a starting point (I've not been able to find better), but I don't know C so I don't want to make things worse.

**Comment by jnbr** [comment]
I can reproduce the error, too.
Calling `crypt(pass, goodhash)` should be fine. See section NOTES in the man page about the salt.

I added a check that the returned value of `crypt(pass, goodhash)` is not `null`. This is not the case.
The segfault happens however, when the returned value of `crypt()` get's dereferenced in `strcmp()`.

I can only reproduce this if linking with `-pie` / configuring with `--with-pie`. If `pie` i not used, it works as expected.

**Comment by lyn1337** [comment]
I'm baffled this issue wasn't reported earlier, I've tinkered with my setup for some time already, thinking it was layer8.

**Comment by lyn1337** [comment]
I'm baffled this issue wasn't reported earlier, I've tinkered with my setup for some time already, thinking it was layer8.

**Comment by lyn1337** [comment]
I'm baffled this issue wasn't reported earlier.
 I've tinkered with my setup for some time already, thinking it was layer8.

**Comment by jnbr** [comment]
from `./configure`
```
checking crypt.h usability... yes
checking crypt.h presence... yes
checking for crypt.h... yes
```

from `make`
```
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I/usr/include   -g -O2  -fPIC -DPIC -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset -D_BSD_SOURCE -D_DEFAULT_SOURCE  -c -o crypt_checkpass.o crypt_checkpass.c
crypt_checkpass.c: In function 'crypt_checkpass':
crypt_checkpass.c:22:13: warning: implicit declaration of function 'crypt'; did you mean 'chroot'? [-Wimplicit-function-declaration]
  if (strcmp(crypt(pass, goodhash), goodhash) == 0)
             ^~~~~
             chroot
crypt_checkpass.c:22:13: warning: passing argument 1 of 'strcmp' makes pointer from integer without a cast [-Wint-conversion]
In file included from crypt_checkpass.c:9:0:
```

This looks like `crypt.h` gets detected but not included in `crypt_checkpass` leading to undefined behaviour (which apparently works out as long `--with-pie` is not used).

Setting `-DHAVE_CRYPT_H` in `CFLAGS` results in a working binary (with pie).

So the remaing step is to check, why `HAVE_CRYPT_H` is not defined in `crypt_checkpass`.

**Comment by greecemunky** [comment]
@jnbr Thanks for the correction, and for your deeper dive into this.

All my efforts so far are mostly stabs in the dark, but if I find time I'll have another play.

**Comment by EmperorArthur** [comment]
This is unfortunately still an issue on Ubuntu Server 18.04.  Which is the newest version Amazon offers for their EC2 instances.

It might be a seperate issue, but Amazon is shipping a version with this bug:
> version: OpenSMTPD 6.0.3-portable

**Comment by Dieken** [comment]
@EmperorArthur   I also got this shit bug.

 See https://github.com/OpenSMTPD/OpenSMTPD/issues/888#issuecomment-436686749

The reason is  "crypt_checkpass.c" doesn't include "includes.h" which includes "config.h" and defines "HAVE_CRYPT_H" defined.

Without this macro,  "crypt_checkpass.c" got an unknown function "crypt",   its return value is regarded as "int" by default according to C language standard.

```
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I/usr/include -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/root/a/opensmtpd-6.0.3p1=. -fstack-protector-strong -Wformat -Werror=format-security  -fPIC -DPIC -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset -D_BSD_SOURCE -D_DEFAULT_SOURCE  -c -o crypt_checkpass.o crypt_checkpass.c
crypt_checkpass.c: In function ‘crypt_checkpass’:
crypt_checkpass.c:20:13: warning: implicit declaration of function ‘crypt’; did you mean ‘chroot’? [-Wimplicit-function-declaration]
  if (strcmp(crypt(pass, goodhash), goodhash) == 0)
             ^~~~~
             chroot
crypt_checkpass.c:20:13: warning: passing argument 1 of ‘strcmp’ makes pointer from integer without a cast [-Wint-conversion]
In file included from crypt_checkpass.c:7:0:
/usr/include/string.h:136:12: note: expected ‘const char *’ but argument is of type ‘int’
 extern int strcmp (const char *__s1, const char *__s2)
            ^~~~~~
```

So the essential fix is to include "includes.h",  not the "NULL" judgement although it's also good catch, crypt() does return NULL on error.

Unluckily Ubuntu 18.04 LTS doesn't  fix this bug yet....
