### ISSUE TITLE
smtpd crashes on authentication with null password.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#836]
I'm currently using table sqlite and the database has users that are not supposed to log in with null passwords. Trying to authenticate such a user however will crash the smtpd process.

It's probably unintentional?

I've now changed the sqlite query to not return data for a users with null passwords.

debug: lka: authenticating for credentials:test@bwo.mrstuudio.ee
lookup: lookup "test@bwo.mrstuudio.ee" as CREDENTIALS in table proc:credentials -> "test@bwo.mrstuudio.ee:(null)"
domains[29920]: warn: table-api: pipe closed
debug: parent -> lka: pipe closed
smtpd: process lka socket closed
debug: queue -> lookup: pipe closed
debug: queue agent exiting
debug: ca -> parent: pipe closed
debug: ca agent exiting
debug: scheduler -> queue: pipe closed
debug: scheduler agent exiting
virtuals[29922]: warn: table-api: pipe closed
debug: control -> lookup: pipe closed
debug: control agent exiting
credentials[29919]: warn: table-api: pipe closed
debug: pony -> lookup: pipe closed
debug: pony agent exiting

**Comment by poolpOrg** [comment]
not intentional no, you found a bug and will commit a fix shortly.

**Comment by poolpOrg** [comment]
The issue has been fixed a while ago, this is the output with an sqlite database I just created with a user holding a NULL password:

    debug: lka: authenticating for creds:test
    lookup: lookup "test" as CREDENTIALS in table proc:creds -> "test:(null)"
    22d24f12bf34f348 smtp authentication user=test result=permfail
    22d24f12bf34f348 smtp failed-command command="AUTH PLAIN (...)" result="535 Authentication failed"
