### ISSUE TITLE
table socketmap error

### ISSUE THREAD

**Issue by edgarpettijohn** [OpenSMTPD/OpenSMTPD#838]
I'm trying to use the socketmap from extras. It connects to the socket but doesn't send data resulting in an error. I am planning on using the socketmap table eventually. I was trying to see what value 'name' would have. I'm not sure what it will be, but it seems it should be configurable similar to the postmap command below. So that the smtpd.conf part would look more like 'table test socketmap:/var/run/sockd.sock:name' I guess depending on what 'name' is by default I suppose this is a bug report plus feature request.

Thanks.

smtpd.conf
table aliases file:/etc/mail/aliases
table secrets file:/etc/mail/secrets
table test socketmap:/var/run/sockd.sock

listen on lo0
accept from source `<test>`
accept for local alias `<aliases>` deliver to mbox

Here is the important bit from smtpd -dv with trace all:
lookup: check "127.0.0.1" as NETADDR in table proc:test -> -1
warn: failure to perform a table lookup on table test
mproc: lka -> pony : 34 IMSG_SMTP_EXPAND_RCPT
expand: 0xcadfa5f5018: clearing expand tree
imsg: pony <- lka: IMSG_SMTP_EXPAND_RCPT (len=34)
smtp: 0xbb84cba7000: >>> 451 Temporary failure

Here is what a session with my test socketmap daemon looks like:
It just accepts connections and prints the data back out.

laptop$ doas ./main -d
new connection on socket 3    /* here is smtpd connecting */
new connection on socket 3   /* here is postfix connecting and its data */
9:test
test,

Command to get above results:
postmap -q "test" socketmap:unix:/var/run/sockd.sock:test

Here is full debug with trace all:
laptop$ doas smtpd -dv
debug: init ssl-tree
info: loading pki information for mail.laptop.com
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for mail.laptop.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
info: OpenSMTPD 6.0.0 starting
debug: init ssl-tree
info: loading pki information for mail.laptop.com
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for mail.laptop.com
debug: init ssl-tree
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: klondike -> control[91445] fd=5
debug: init ssl-tree
info: loading pki information for mail.laptop.com
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for mail.laptop.com
setup_peer: klondike -> pony express[43741] fd=6
setup_proc: klondike done
setup_done: ca[99256] done
info: loading pki information for mail.laptop.com
debug: init ca-tree
debug: init ssl-tree
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: pony express -> control[91445] fd=5
setup_peer: pony express -> klondike[99256] fd=6
info: loading pki keys for mail.laptop.com
setup_peer: pony express -> lookup[65886] fd=7
setup_peer: pony express -> queue[46953] fd=8
debug: init ssl-tree
info: loading pki information for mail.laptop.com
debug: init ca-tree
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: control -> klondike[99256] fd=5
setup_peer: control -> lookup[65886] fd=6
setup_peer: control -> pony express[43741] fd=7
setup_peer: control -> queue[46953] fd=8
setup_peer: control -> scheduler[4760] fd=9
setup_proc: control done
setup_done: control[91445] done
debug: init ssl-tree
info: loading pki keys for mail.laptop.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: lookup -> control[91445] fd=5
setup_peer: lookup -> pony express[43741] fd=6
setup_peer: lookup -> queue[46953] fd=7
setup_proc: lookup done
setup_done: lka[65886] done
setup_proc: pony express done
setup_done: pony[43741] done
debug: init ssl-tree
info: loading pki information for mail.laptop.com
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for mail.laptop.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: queue -> control[91445] fd=5
setup_peer: queue -> pony express[43741] fd=6
setup_peer: queue -> lookup[65886] fd=7
setup_peer: queue -> scheduler[4760] fd=8
setup_proc: queue done
setup_done: queue[46953] done
debug: init ssl-tree
info: loading pki information for mail.laptop.com
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for mail.laptop.com
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: scheduler -> control[91445] fd=5
setup_peer: scheduler -> queue[46953] fd=6
setup_proc: scheduler done
debug: bounce warning after 4h
setup_done: scheduler[4760] done
smtpd: setup done
debug: parent_send_config_ruleset: reloading
debug: parent_send_config: configuring pony process
debug: parent_send_config: configuring ca process
debug: init private ssl-tree
debug: ca_engine_init: using RSA privsep engine
debug: smtp: listen on IPv6:::1 port 25 flags 0x400 pki "" ca ""
debug: smtp: listen on IPv6:fe80::1%lo0 port 25 flags 0x400 pki "" ca ""
debug: smtp: listen on 127.0.0.1 port 25 flags 0x400 pki "" ca ""
debug: smtp: listen on IPv6:::1 port 587 flags 0x449 pki "" ca ""
debug: smtp: listen on IPv6:fe80::1%lo0 port 587 flags 0x449 pki "" ca ""
debug: smtp: listen on 127.0.0.1 port 587 flags 0x449 pki "" ca ""
debug: pony: rsae_init
debug: pony: rsae_init
debug: smtp: will accept at most 499 clients
debug: queue: done loading queue into scheduler
debug: smtpd: scanning offline queue...
debug: smtpd: offline scanning done
mproc: control -> lka: realloc 0 -> 128
mproc: control -> lka : 4 IMSG_CTL_VERBOSE
mproc: control -> pony: realloc 0 -> 128
mproc: control -> pony : 4 IMSG_CTL_VERBOSE
mproc: control -> queue: realloc 0 -> 128
mproc: control -> queue : 4 IMSG_CTL_VERBOSE
mproc: control -> ca: realloc 0 -> 128
mproc: control -> ca : 4 IMSG_CTL_VERBOSE
mproc: control -> scheduler: realloc 0 -> 128
mproc: control -> scheduler : 4 IMSG_CTL_VERBOSE
mproc: control -> parent: realloc 0 -> 128
mproc: control -> parent : 4 IMSG_CTL_VERBOSE
mproc: control -> client-proc : 0 IMSG_CTL_OK
debug: control -> (null): pipe closed
debug: clearing p=(null), fd=12, pid=0
ramstat: decrement: control.session
ramstat: control.session (0x885c8454e79): 1 -> 0
debug: smtp: new client on listener: 0xbb91673a000
smtp: 0xbb84cba7000: connected to listener 0xbb91673a000 [hostname=mail.laptop.com, port=25, tag=]
mproc: pony -> lka: realloc 0 -> 128
mproc: pony -> lka : 32 IMSG_SMTP_DNS_PTR
mproc: pony -> control: realloc 0 -> 128
mproc: pony -> control : 45 IMSG_STAT_INCREMENT
mproc: pony -> control : 51 IMSG_STAT_INCREMENT
imsg: control <- pony: IMSG_STAT_INCREMENT (len=45)
ramstat: increment: smtp.session
ramstat: smtp.session (0x8880de23700): 0 -> 1
imsg: lka <- pony: IMSG_SMTP_DNS_PTR (len=32)
imsg: control <- pony: IMSG_STAT_INCREMENT (len=51)
ramstat: increment: smtp.session.inet4
ramstat: smtp.session.inet4 (0x8882d866fc0): 0 -> 1
mproc: lka -> pony: realloc 0 -> 128
mproc: lka -> pony : 22 IMSG_SMTP_DNS_PTR
imsg: pony <- lka: IMSG_SMTP_DNS_PTR (len=22)
smtp: 0xbb84cba7000: STATE_NEW -> STATE_CONNECTED
a95251b0948ef8cd smtp event=connected address=127.0.0.1 host=localhost
smtp: 0xbb84cba7000: >>> 220 mail.laptop.com ESMTP OpenSMTPD
smtp: 0xbb84cba7000: IO_LOWAT <io:0xbb8bf7bd700 fd=16 to=300000 fl=W ib=0 ob=0>
smtp: 0xbb84cba7000: IO_DATAIN <io:0xbb8bf7bd700 fd=16 to=300000 fl=R ib=15 ob=0>
smtp: 0xbb84cba7000: <<< ehlo test.com
smtp: 0xbb84cba7000: STATE_CONNECTED -> STATE_HELO
smtp: 0xbb84cba7000: >>> 250-mail.laptop.com Hello test.com [127.0.0.1], pleased to meet you
smtp: 0xbb84cba7000: >>> 250-8BITMIME
smtp: 0xbb84cba7000: >>> 250-ENHANCEDSTATUSCODES
smtp: 0xbb84cba7000: >>> 250-SIZE 36700160
smtp: 0xbb84cba7000: >>> 250-DSN
smtp: 0xbb84cba7000: >>> 250 HELP
smtp: 0xbb84cba7000: IO_LOWAT <io:0xbb8bf7bd700 fd=16 to=300000 fl=W ib=0 ob=0>
smtp: 0xbb84cba7000: IO_DATAIN <io:0xbb8bf7bd700 fd=16 to=300000 fl=R ib=25 ob=0>
smtp: 0xbb84cba7000: <<< mail from:<me@test.com>
mproc: pony -> queue: realloc 0 -> 128
mproc: pony -> queue : 8 IMSG_SMTP_MESSAGE_CREATE
imsg: queue <- pony: IMSG_SMTP_MESSAGE_CREATE (len=8)
queue-backend: queue_message_create() -> 1 (f258f7b0)
mproc: queue -> pony: realloc 0 -> 128
mproc: queue -> pony : 16 IMSG_SMTP_MESSAGE_CREATE
imsg: pony <- queue: IMSG_SMTP_MESSAGE_CREATE (len=16)
smtp: 0xbb84cba7000: >>> 250 2.0.0: Ok
smtp: 0xbb84cba7000: IO_LOWAT <io:0xbb8bf7bd700 fd=16 to=300000 fl=W ib=0 ob=0>
smtp: 0xbb84cba7000: IO_DATAIN <io:0xbb8bf7bd700 fd=16 to=300000 fl=R ib=28 ob=0>
smtp: 0xbb84cba7000: <<< rcpt to:<edgar@laptop.com>
mproc: pony -> lka: realloc 128 -> 256
mproc: pony -> lka : 239 IMSG_SMTP_EXPAND_RCPT
imsg: lka <- pony: IMSG_SMTP_EXPAND_RCPT (len=239)
expand: 0xcadfa5f5018: expand_insert() called for address:edgar@laptop.com[parent=0x0]
expand: 0xcadfa5f5018: inserted node 0xcae44488800
expand: lka_expand: address: edgar@laptop.com [depth=0]
lookup: check "127.0.0.1" as NETADDR in table proc:test -> -1
warn: failure to perform a table lookup on table test
mproc: lka -> pony : 34 IMSG_SMTP_EXPAND_RCPT
expand: 0xcadfa5f5018: clearing expand tree
imsg: pony <- lka: IMSG_SMTP_EXPAND_RCPT (len=34)
smtp: 0xbb84cba7000: >>> 451 Temporary failure
a95251b0948ef8cd smtp event=failed-command address=127.0.0.1 host=localhost command="rcpt to:<edgar@laptop.com>" result="451 Temporary failure"
smtp: 0xbb84cba7000: IO_LOWAT <io:0xbb8bf7bd700 fd=16 to=300000 fl=W ib=0 ob=0>
smtp: 0xbb84cba7000: IO_DATAIN <io:0xbb8bf7bd700 fd=16 to=300000 fl=R ib=6 ob=0>
smtp: 0xbb84cba7000: <<< quit
smtp: 0xbb84cba7000: >>> 221 2.0.0: Bye
smtp: 0xbb84cba7000: STATE_HELO -> STATE_QUIT
smtp: 0xbb84cba7000: IO_LOWAT <io:0xbb8bf7bd700 fd=16 to=300000 fl=W ib=0 ob=0>
a95251b0948ef8cd smtp event=closed address=127.0.0.1 host=localhost reason=quit
debug: smtp: 0xbb84cba7000: deleting session: done
mproc: pony -> queue : 4 IMSG_SMTP_MESSAGE_ROLLBACK
mproc: pony -> control : 45 IMSG_STAT_DECREMENT
imsg: control <- pony: IMSG_STAT_DECREMENT (len=45)
imsg: queue <- pony: IMSG_SMTP_MESSAGE_ROLLBACK (len=4)
ramstat: decrement: smtp.session
ramstat: smtp.session (0x8881b596e80): 1 -> 0
queue-backend: queue_message_delete(f258f7b0) -> 1
mproc: queue -> scheduler : 4 IMSG_QUEUE_MESSAGE_ROLLBACK

**Comment by poolpOrg** [comment]
The socketmap table backend has been fixed.
