### ISSUE TITLE
Offline send returns code 75, leading to MUA errors (portable)

### ISSUE THREAD

**Issue by edrozenberg** [OpenSMTPD/OpenSMTPD#840]
When using mutt or (al)pine to send email (via sendmail) with smtpd offline, opensmtpd returns code 75 (deferred).

This leads the MUA's to think the email was not properly transmitted, and the MUA's remain in the message compose screen.

Meanwhile the messages *were* properly added to ```/var/spool/smtpd/offline``` and will be going out when smtpd runs next time.

Alpine shows:
```
[Posting program sendmail -t returned error]
```

Mutt shows:
```
Error sending message, child exited 75 (Deferred.).
```

I know that I could keep smtpd always running, and configure MUA's to always use SMTP server localhost:25, but my goal is to make offline work properly, in case smtpd is ever down or not started.

I believe when mail is properly added to offine that opensmtpd's sendmail should return an OK (0) return code, but I'm no email expert so could be totally wrong about that.

I'm just not able to figure out how to make offline work without MUAs giving errors.

**Comment by edrozenberg** [comment]
Error code 75 also visible via sendmail CLI:

email.txt:
```
To: dest@someplace.com
From: me@server.com
Subject: Hello 
Hello
```
```
# sendmail -t < email.txt
# echo $?
75
```
However, using ```mail``` returns error code 0:
```
$ mail -s "Hello" -r "from-address" to-address
Hello
.
EOT

# echo $?
0
```

**Comment by edgarpettijohn** [comment]
I don't know how correct it is but this should do what you want.

Index: enqueue.c
===================================================================
RCS file: /cvs/src/usr.sbin/smtpd/enqueue.c,v
retrieving revision 1.113
diff -u -p -u -r1.113 enqueue.c
--- enqueue.c   3 Jul 2016 14:30:33 -0000       1.113
+++ enqueue.c   5 Mar 2018 00:39:21 -0000
@@ -867,7 +867,7 @@ enqueue_offline(int argc, char *argv[], 
        if (fclose(ofile) == EOF)
                goto write_error;
 
-       return (EX_TEMPFAIL);
+       return (EX_OK);
 write_error:
        warn("write error");
        ftruncate(fileno(ofile), 0);

**Comment by edgarpettijohn** [comment]
[enqueue.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/1779154/enqueue.txt

I think the attached diff will do what you want.

**Comment by edrozenberg** [comment]
@edgarpettijohn that looks like it would work great, thank you very much! I'm going to test it soon.

Meanwhile I found a workaround: configure MUA's to use the "mail" binary as the sendmail program. The 'mail' binary returns 0 on offline send complete.

Mutt configuration:
```
# .muttrc
set sendmail="mail -t"
```

(Al)pine configuration:

- Start Alpine
- (S)setup -> (C)onfig
- w  (word find/search), then type: Sendmail Path
- Press <ENTER> to edit the Sendmail Path
- Type path as:   mail -t

Note: the ```**-t**``` after the ```mail``` command is important (it tells mail to extract header info from the stdin text it received from mutt/alpine), and this how mutt/alpine send header information.

**Comment by edrozenberg** [comment]
@edgarpettijohn based on this issue https://github.com/OpenSMTPD/OpenSMTPD/issues/301 it appears opensmtpd ```sendmail``` works as intended to return an error code on offline sent.

For that reason I will not pursue patching sendmail, and instead will continue using ```mail -t``` which returns rc=0 on offline sent.

Users who want an error returned for offline sent can use ```sendmail -t```, and users who want an OK coming back can use ```mail -t```. Hope I'm not screwing anybody up by misunderstanding anything here :).

**Comment by poolpOrg** [comment]
exactly, this is not considered an issue, offline means that the delivery is deferred and the sender must be acknowledged by default.

closing
