### ISSUE TITLE
[FR] Security feature: force use of tls for relay excepted for a whitelist of hosts

### ISSUE THREAD

**Issue by ArchangeGabriel** [OpenSMTPD/OpenSMTPD#841]
As stated in the [smtpd.conf(5)](https://man.openbsd.org/smtpd.conf) man page:
>If **tls** is specified, smtpd(8) will refuse to relay unless the remote host provides STARTTLS. If **tls verify** is specified, smtpd(8) will refuse to relay unless the remote host provides STARTTLS and the certificate it presented has been verified.
Note that the **tls** and **tls verify** options should only be used in private networks as they will prevent proper relaying on the Internet.

Indeed, use of `tls` makes it impossible to deliver to several hosts. However, not specifying it implies that anyone can MITM the connection by removing the STARTTLS bit from the initial response.

Since major providers do support TLS on their MTA, it’s only a tiny fraction of the traffic that requires us to endanger the whole security of email. As such, a good compromise could be to have `tls` on by default but allow a whitelist of hosts that do not support TLS to still receive emails from us.

That way, we could even have a script to check using `openssl s_client` (or equivalent from other supported SSL libs) whether things enhanced on remote ends periodically.

Theoretically all of this should be handled by DANE, but it’s still not implemented in OpenSMTPD and by the large majority of service providers.

**Comment by poolpOrg** [comment]
I thought this was an interesting feature but on a second thought I realized it is already doable without requiring a new feature:

    table whitelist { poolp.org, opensmtpd.org }
    
    action unsafe relay
    action safe relay tls
    
    match [...] for domain <whitelist> action unsafe
    match [...] for any action safe

**Comment by ArchangeGabriel** [comment]
Nice. :) Another improvement in this direction will be #924. ;)
