### ISSUE TITLE
"smptctl spf walk" enters infinite loop on malformed SPF records

### ISSUE THREAD

**Issue by ryanakca** [OpenSMTPD/OpenSMTPD#842]
Certain malformed SPF records will cause `smtpctl spf walk` to enter an infinite loop. Consider, for example, the following SPF record for `autohome.com.cn`:
```
$ dig -t TXT autohome.com.cn +short
"v=spf1 mx ip4:124.250.38.146 include:autohome.com.cn -all"
```
Upon encountering this record, `dispatch_txt` in `spfwalk.c` will atempt to parse it, and will follow the inclusion `autohome.com.cn` (lines 189 onwards), and lookup the record all over again, thus entering a loop.

**Comment by poolpOrg** [comment]
A fix has been committed to OpenBSD, will be synched to the github repo by this week-end, among with other fixes.

Thanks for your report
