### ISSUE TITLE
spf walk can be made to print (almost any) arbitrary string

### ISSUE THREAD

**Issue by ryanakca** [OpenSMTPD/OpenSMTPD#844]
spf walk can produce garbage output if the SPF record contains garbage. For example, when run on the domain "airtel.com", it will output the line `125.17.112.209-all`, which will cause `pf` to choke if you try to load the output into a table.

spf walk should check that the strings it outputs are legitimate addresses and not garbage. As it is, I strongly suspect a record of the form
```
"v=spf1 ip4:somepileofgarbage"
``` 
would cause spf walk to output the line `somepileofgarbage` based on the following segment (around line 163) of `smtpd/spfwalk.c`:
```
                if (strncasecmp("ip4:", *ap, 4) == 0) {
                        if (ip_v4 == 1 || ip_both == 1)
                                printf("%s\n", *(ap) + 4);
                        continue;
                }
```

Here's the `airtel.com` SPF record:
```
$ dig -t txt airtel.com +short
"MS=ms91205386"
"MS=ms55822078"
"v=spf1 include:a._spf.airtel.com include:c._spf.airtel.com include:d._spf.airtel.com -all"
$ dig -t txt d._spf.airtel.com +short
"v=spf1 ip4:145.131.155.137 ip4:203.153.220.17 ip4:203.153.220.21 ip4:203.145.128.128/27 ip4:125.18.107.6 ip4:125.18.107.31 ip4:125.18.107.11 ip4:125.17.112.216 ip4:125.17.112.217 ip4:125.17.112.210 ip4:125.17.112.209-all"
```

**Comment by ryanakca** [comment]
The committed fix makes spf walk almost useless, because most large mailers use entries with prefixes, and such entries now get ignored. Please see this pull request https://github.com/OpenSMTPD/OpenSMTPD/pull/845 for a fix.

**Comment by snimmagadda** [comment]
Right, sorry I missed about prefix notation. Testing your fix now.

**Comment by poolpOrg** [comment]
@snimmagadda has the fixed version been committed to OpenBSD ?

**Comment by poolpOrg** [comment]
that's been brought to github
