### ISSUE TITLE
Bug: Too strict address parsing

### ISSUE THREAD

**Issue by chneukirchen** [OpenSMTPD/OpenSMTPD#846]
Using opensmtpd-6.0.3p1 on Linux:

```
% sendmail -t
To: "foo \"bar\" quux" <foo@quux.org>

```

yields `syntax error in address`.

To the best of my reading of RFC5322, this is a valid address, as `"` are escaped using backslashes inside  `"`. Postfix 3.3.0 also accepts it, <s>as well as opensmtpd 5.9.2.</s>

**Comment by chneukirchen** [comment]
http://nimmagadda.net/enqueue.diff fixes the issue.

**Comment by poolpOrg** [comment]
this will be committed soon

**Comment by poolpOrg** [comment]
that's been brought to github
