### ISSUE TITLE
[RFE] Normalise log format

### ISSUE THREAD

**Issue by mikygee** [OpenSMTPD/OpenSMTPD#850]
version: OpenSMTPD 6.0.4

Hello,

Would it be possible to have fields in the message always in the same order
smtpd[5144]: 0d391a61d29e79b1 mta event=starttls ciphers=version=TLSv1.2, cipher=ECDHE-RSA-CHACHA20-POLY1305, bits=256
smtpd[5144]: smtp-out: Server certificate verification succeeded on session 0d391a61d29e79b1

It would be nice to have the second message like this (session number after the colon)
smtpd[5144]: 0d391a61d29e79b1 smtp-out: Server certificate verification succeeded on session

The goal is to match the logs with logstash.

That would be nice

**Comment by whataboutpereira** [comment]
It would also be wonderful if smtp log entries would mention either the port used and/or tag.

**Comment by poolpOrg** [comment]
@mikygee the log format was normalized so the cert line is no longer different than other lines, in addition you might want to look at the reporting API which is far better for an integration with logstash.

@whataboutpereira the reporting API does provide source and dest port used in case you want them in logstash. If you feel they should also appear in regular logs, please open a separate issue.
