### ISSUE TITLE
DNS MX record lookup resulting in NOTIMPL treated as non-recoverable

### ISSUE THREAD

**Issue by lattera** [OpenSMTPD/OpenSMTPD#852]
I have a rather interesting and unique [setup](https://github.com/lattera/articles/blob/master/infosec/tor/2017-01-14_torified_home/article.md). I have OpenSMTPd sitting behind my Tor-ified network. Tor itself is the authoritative name server for the network.

When smtpd receives a message it needs to relay to another MTA, smtpd tries to do an MX record lookup for the hostname (ie, if I send a message to lattera@example.com, smtpd tries an MX lookup for example.com).

Since Tor doesn't support MX records in its DNS code, it returns NOTIMPL as the response code:

```
$ drill gmail.com mx
;; ->>HEADER<<- opcode: QUERY, rcode: NOTIMPL, id: 58038
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; gmail.com.	IN	MX

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: [scrubbed]
;; WHEN: Thu Apr 26 15:05:22 2018
;; MSG SIZE  rcvd: 27
```

OpenSMTPd treats NOTIMPL has a non-recoverable error. If Tor were to have returned NXDOMAIN, smtpd would fallback to doing an A/AAAA lookup. However, in this case, the fallback lookup isn't performed and the DNS_EINVAL error is raised instead. smtpd bounces the message with an "Invalid domain" message passed back to the user.

I'm unsure what would be the best solution here. Perhaps detect NOTIMPL and perform the A/AAAA fallback if NOTIMPL was returned for the MX record lookup?

**Comment by lattera** [comment]
I've implemented the workaround, and OpenSMTPd is happy. :)

So, I wonder if OpenSMTPd could fallback to A/AAAA lookup if the MX lookup results in NOTIMPL (rcode: 4) being returned from the DNS resolver.

**Comment by lattera** [comment]
This simplistic patch fixes this issue.

[opensmtpd-01.patch.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/1985034/opensmtpd-01.patch.txt)

**Comment by poolpOrg** [comment]
@ericfaurot acceptable ?

**Comment by lattera** [comment]
I've now got several production installations of OpenSMTPD with this patch applied. Everything's working fine and dandy.

**Comment by ericfaurot** [comment]
Sorry for the delay. Can you test this diff instead?

[dns.diff.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/2401371/dns.diff.txt)

**Comment by ericfaurot** [comment]
As discussed with @poolpOrg, the original diff seems like the best option.
It's better than the current situation anyway.

committed in cvs
