### ISSUE TITLE
syntax error for helo with address literal

### ISSUE THREAD

**Issue by sdgathman** [OpenSMTPD/OpenSMTPD#869]
smtpd.conf contains:
 ```
helo "[IPv6:fc37:2c50:7583:e01a:1234:1234:1234:1234]"
```
opensmtpd complains: 
```
/etc/opensmtpd/smtpd.conf:10: syntax error
```
Doesn't work without quotes or for IP4 either.

**Comment by whataboutpereira** [comment]
Looking at the man page, "helo" can only be used in action or match directives with the new syntax. https://man.openbsd.org/smtpd.conf

**Comment by sdgathman** [comment]
You are right.  Sorry for the noise.
