### ISSUE TITLE
Progress regarding stable smtpfd release

### ISSUE THREAD

**Issue by zoot** [OpenSMTPD/OpenSMTPD#870]
Hi there

I'm exploring OpenSMTPD for the first time, while investigating its SMTP filtering layer possibilities compared to a system currently running qpsmtpd in front of qmail.

Even though the latter is a very powerful setup, I'm constantly reviewing the landscape of alternatives, as the service scales up.

Given the recent extraction of the filtering extras from OpenSMTPD for future releases, I'd appreciate an idea of when a usable release of smtpfd might be expected and how it might integrate with it? So far, I cannot find any information on the matter.

nginx with the ngx_mail_auth_http module could be used to take care of rDNS, SPF and RBL tests, but I'm loathe to build this extra layer if a usable smtpfd isn't too far away, which might handle these 3 network-level checks.

**Comment by poolpOrg** [comment]
smtpfd is being worked on but I can't tell you precisely when we will release it because we've done that in the past and it didn't turn well.

stay tuned on the mailing list and our IRC channel.
