### ISSUE TITLE
Support SNI when connecting as client to relay

### ISSUE THREAD

**Issue by norrland** [OpenSMTPD/OpenSMTPD#880]
Currently OpenSMTPD does not support connecting to relays using TLS where the remote server is using an certificate with multiple SANs(subject alt name).

Tested on OpenSMTPD 6.4.0 (OpenBSD 6.3-current (GENERIC.MP) #41: Wed Jun 20 23:24:05 MDT 2018)

**Comment by poolpOrg** [comment]
Work is in progress to switch OpenSMTPD from libssl to libtls which makes supporting SNI much easier.

**Comment by ArchangeGabriel** [comment]
I’m in the process of upgrading all my servers to 7.3 (but first I wanted to go through my several hundreds emails for github notification from here :p), will check and report. ;)

**Comment by omar-polo** [comment]
@ArchangeGabriel since it uses libtls now I'd be surprised if SNI is not handled correctly.  The place where all TLS connections are set up is https://github.com/OpenSMTPD/OpenSMTPD/blob/master/usr.sbin/smtpd/ioev.c#L820, and the hostname is passed to `tls_connect_socket(3)` for libtls to use it.

**Comment by ArchangeGabriel** [comment]
I’ve just confirmed it work ootb now, awesome! You can close this ticket. ;)
