### ISSUE TITLE
6.4.0p1 tarball assumes automake-1.15

### ISSUE THREAD

**Issue by Ekleog** [OpenSMTPD/OpenSMTPD#885]
The 6.4.0p1 tarball uploaded at [the website](https://www.opensmtpd.org/archives/opensmtpd-6.4.0p1.tar.gz) currently hard-requires automake-1.15, making it impossible to build with later versions.

Running `sh bootstrap` before building works around the issue by re-generating the faulty file.

**Comment by poolpOrg** [comment]
On my phone, can't check right now, but the tarball doesn't contain a configure script ??I have run the bootstrap before creating the release tarballLe 27 oct. 2018 05:03, Léo Gaspard <notifications@github.com> a écrit :The 6.4.0p1 tarball uploaded at the website currently hard-requires automake-1.15, making it impossible to build with later versions.
Running sh bootstrap before building works around the issue by re-generating the faulty file.

**Comment by Ekleog** [comment]
Hmm actually upon further investigation, this is likely due to my having
to apply the patch from #884 locally to make the build pass, as it means
autotools need to be re-run anyway.

The assumption of automake-1.15 is likely a red herring, as the
configure script does assume it but doesn't appear to actually call it
unless the build system has been modified in some way.

**Comment by Ekleog** [comment]
Closing as it's most likely due to the hotfix from #884 indeed.
