### ISSUE TITLE
aliases with + filtering

### ISSUE THREAD

**Issue by danieljakots** [OpenSMTPD/OpenSMTPD#887]
Hi,

My conf is basically

 table aliases db:/etc/mail/aliases.db
 action "local" maildir alias <aliases>
 match from any for domain "chown.me" action "local"

Previously it was

 table aliases db:/etc/mail/aliases.db
 accept for local alias <aliases> deliver to maildir
 accept from any for domain chown.me alias <aliases> deliver to maildir

I use the + filtering both directly, and with aliases. If I send an
email (from another machine) to foo+bar@, the mail goes correctly in
the bar folder (which is OK). If I send an email (from another machine)
to wtvaliases@ which is listed as foo+bar@chown.me in
my /etc/mail/aliases, it goes in my inbox and not in my bar directory
(which is not ok and worked until now).

Is there a way to get back this behaviour I had before 6.4?

> care to show your /etc/mail/aliases ?  

It's in the form of
wtvaliases:     vigdis+autre@chown.me
I tried as well with
wtvaliases:     vigdis+autre
in case the behaviour changed but I get the same behaviour (i.e. the
mail goes into my inbox instead of the "autre" folder). Before 6.4 if I
didn't put the "@chown.me" part it didn't work. I don't remember the
way it didn't work, just that I needed it.

**Comment by danieljakots** [comment]
Is there any interest in fixing this?

**Comment by poolpOrg** [comment]
On Sun, Nov 25, 2018 at 07:39:13AM -0800, Daniel Jakots wrote:
> Is there any interest in fixing this?
> 

yes, but there's a backlog of issues to fix and I only have one set of hands


-- 
Gilles Chehade						       @poolpOrg

https://www.poolp.org                 tip me: https://paypal.me/poolpOrg

**Comment by poolpOrg** [comment]
A diff is available at:

https://poolp.org/~gilles/subaddress.diff

which should fix the issue (tested on my laptop), please report

**Comment by poolpOrg** [comment]
as discussed on icb, there was an issue indeed but the behaviour you expected was not the correct one either.

discussed with @ericfaurot and committed the fix today.
