### ISSUE TITLE
OpenSMTPD crashing after upgrading Ubuntu from 16.04 LTS to 18.04.1 LTS (Points to TLS issue)

### ISSUE THREAD

**Issue by usonianhorizon** [OpenSMTPD/OpenSMTPD#888]
Stable OpenSMTPD configuration running for over a year now under Ubuntu 16.04 LTS (switched from Postfix).

This morning I upgraded our server to Ubuntu 18.04.1 LTS at which point all attempts at outbound email crash OpenSMTPD service (using Mutt, Roundcube webmail, mobile mail clients).

@poolpOrg I have removed some of the table contents emitted in report.log as they list users that use our server.  I hope that what is left is sufficient.  If not, I can get you the info offline.

Many thanks.

[smtpd.conf.local.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/2554606/smtpd.conf.local.txt)

**edit from @poolpOrg** : removed report log which contained sensitive data

**Comment by poolpOrg** [comment]
@usonianhorizon change your password asap, you have pasted its the report.log you attached !!

**Comment by poolpOrg** [comment]
The crash seems to happen in table-passwd, can you try building and installing table-passwd from the github repository ?

**Comment by poolpOrg** [comment]
I will prepare an -extras release today

**Comment by poolpOrg** [comment]
I released a new tarball from the new extras:

https://www.mail-archive.com/misc@opensmtpd.org/msg04015.html

Please install and confirm that it fixes your issue @usonianhorizon 

@ArchangeGabriel at least now you can point to a release rather than a date :-p

**Comment by ArchangeGabriel** [comment]
@poolpOrg Are those extras be compatible with 6.0.x? We don’t have OpenSMTPd 6.4 yet because we still need to decide/figure out what to do regarding LibreSSL.

**Comment by usonianhorizon** [comment]
@poolpOrg Thanks (for earlier comment and) this release.

Will try asap.  Will need some guidance on this: make and install?

Been up most of the night fretting with our mailserver down :).

**Comment by ArchangeGabriel** [comment]
@usonianhorizon What do you have installed on your system? opensmtd-extras? If so I would look for the package sources and update the version inside it.

**Comment by usonianhorizon** [comment]
@ArchangeGabriel I don't believe that I have opensmtpd-extras:

`# dpkg -l | grep opensmtp`
`ii  opensmtpd                             6.0.3p1-1build1                    amd64        secure, reliable, lean, and easy-to configure SMTP server`

**Comment by poolpOrg** [comment]
@ArchangeGabriel it should be compatible with 6.0.x as we didn't make any change to the API and many people are using the extras from github on 6.0.x setups, I can't guarantee with my word because I haven't got a 6.0.x setup to try myself.

@usonianhorizon :
    ./configure --prefix=/where/to/install --with-table-passwd && make && make install

**Comment by usonianhorizon** [comment]
@ArchangeGabriel Thanks.  I fear I may be reaching limits of understanding the default installation as I don't see table-passwd:

`# cd /`
`# find . -name 'opensmtpd' -print`
`./usr/share/doc/opensmtpd`
`./usr/share/lintian/overrides/opensmtpd`
`./usr/lib/x86_64-linux-gnu/opensmtpd`
`...`

`# find . -name 'table-passwd' -print`
`<NULL>`

`# ls /usr/lib/x86_64-linux-gnu/opensmtpd`
`encrypt  mail.local`

**Comment by ArchangeGabriel** [comment]
OK, I don’t know Ubuntu specifics, but then maybe just try installing with:
```
./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib/x86_64-linux-gnu/opensmtpd \
    --with-table-passwd
make
make install
```

**Comment by usonianhorizon** [comment]
@poolpOrg configure, I think, might need a check for libevent-dev?

Initially, I got the following:

`event_asr_run.c:25:10: fatal error: event.h: No such file or directory`
` #include <event.h>`
`          ^~~~~~~~~`
`compilation terminated.`
`Makefile:374: recipe for target 'event_asr_run.o' failed`

Now I have successful compile, but am still unsure on where to install?

**Comment by usonianhorizon** [comment]
@ArchangeGabriel `<WILCO>`

**Comment by usonianhorizon** [comment]
No luck, I fear.  Still crashing on attempted send.  Could it be that under 16.04 table-passwd was piggy backing off of something else, which got omitted in 18.04.1?  Reaching, I know; just don't have a clue as to what it going on.

Mutt is displaying same error:

`Output of the delivery process (all)`
`msmtp: cannot read from TLS connection: The TLS connection was non-properly terminated.`

**Comment by ArchangeGabriel** [comment]
Well the TLS connection is fine (`openssl s_client -connect smtp.khor.pavastupa.com:587 -servername smtp.khor.pavastupa.com -starttls smtp` works), so the issue is definitively the auth part. Maybe you should post a new log with `table-smtpd` installed? And make sure to remove confidential info from the log. ;)

**Comment by usonianhorizon** [comment]
Indeed! :)

So try this?

`./configure \`
`    --prefix=/usr \`
`    --libexecdir=/usr/lib/x86_64-linux-gnu/opensmtpd \`
`    --with-table-passwd --with-table-smtpd`

**Comment by ArchangeGabriel** [comment]
Sorry, that was a typo, should have read `table-passwd`.

**Comment by usonianhorizon** [comment]
Before I post the updated report.log file, I just want to confirm:

1. I had obscured the passwd in the line `lookup: lookup...as CREDENTIALS in table static:passwd ...`

but had overlooked obscuring the line:

2. `smtp: 0x558a27ef24e0: <<< AUTH PLAIN...`

Was that the only other location, or am I snowblind to it?

And, I am guessing that the relevant part of the log file is only in and around the handshake?

**Comment by ArchangeGabriel** [comment]
I don’t know, @poolpOrg should tell.

**Comment by usonianhorizon** [comment]
One other thing:

I noticed that `make install` installed `table-passwd` in `/usr/lib/x86_64-linux-gnu/opensmtpd/opensmtpd`, and so have moved it to `/usr/lib/x86_64-linux-gnu/opensmtpd` directly, and restarted the service (before generating the updated log file).

I am guessing that the `configure` command should be:

`./configure \`
`    --prefix=/usr \`
`    --libexecdir=/usr/lib/x86_64-linux-gnu \`
`    --with-table-passwd`

**Comment by ArchangeGabriel** [comment]
Hum I have it under `/usr/lib/smtpd/opensmtpd/table-passwd`, so I would say my command was correct.

**Comment by usonianhorizon** [comment]
I thought that is what it should have done, but I copied your command directly, and then noticed one additional level in the install directory.  Weird.

**Comment by ArchangeGabriel** [comment]
No, my `smtpd/opensmtpd` directory is equivalent to your `opensmtpd/opensmtpd` one.

**Comment by jnbr** [comment]
If you don't have it applied, you can try with the patch from https://github.com/OpenSMTPD/OpenSMTPD/pull/835

**Comment by usonianhorizon** [comment]
Ah.  Okay, I will put it back.  Missed the smtpd part of the path.

**Comment by ArchangeGabriel** [comment]
Ah yes. I confused https://bugs.archlinux.org/task/58008 with https://bugs.archlinux.org/task/58127. Your issue is what @jnbr said, especially since this is not in latest 6.0.x release.

**Comment by usonianhorizon** [comment]
Another datapoint that I should have mentioned right off, and was reminded by following @jnbr link down to [opensmtpd cannot read passwd-file on alpine linux](https://github.com/OpenSMTPD/OpenSMTPD/issues/816) is that on our server Dovecot and OpenSMTPd don't share the same passwd file.  I have a Makefile that strips away details to make it conform to the more spartan OpenSMTPd format:

```
        # Strip out all comment lines; pull the first two columns; remove the
        # encryption type prefix, e.g., {SHA-512}
        grep -v '^$$\|^\s*\#' passwd | cut -f 1-2 -d ':' --output-delimiter='    ' | sed 's/{.*}//' > credentials
```
Hence the absence of `table-passwd` on our previously working system.

@jnbr @ArchangeGabriel : what would you suggest as the best course of action?  Remove the debian package and compile and install current straight from source (6.4.x)?  Or could you guide me as to how to apply the patch to 6.0.

Thanks, again, for all of this prompt assistance!

**Comment by poolpOrg** [comment]
@usonianhorizon :
> but had overlooked obscuring the line:
> 
> 1. `smtp: 0x558a27ef24e0: <<< AUTH PLAIN...`
> 
> Was that the only other location, or am I snowblind to it?

Nope that was the only location :-)


> And, I am guessing that the relevant part of the log file is only in and around the handshake?

Yes, ~20 lines before the crash + the crash is what matters usually

**Comment by usonianhorizon** [comment]
@poolpOrg Okay, thanks.  I'm just trying to apply @jnbr patch first, but am running into a problem.  Got the 6.0.3p1 tarball, and replaced `openbsd-compat/crypt_checkpass.c`.  Any guidance on what I am missing? Thanks.

```
...
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I/usr/include   -g -O2  -fPIC -DPIC -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset -D_BSD_SOURCE -D_DEFAULT_SOURCE  -c -o libressl.o libressl.c
In file included from libressl.c:63:0:
libressl.c: In function ‘SSL_CTX_use_certificate_chain’:
libressl.c:84:10: error: ‘SSL_F_SSL_CTX_USE_CERTIFICATE_CHAIN_FILE’ undeclared (first use in this function); did you mean ‘SSL_F_SSL_CTX_USE_CERTIFICATE_FILE’?
   SSLerr(SSL_F_SSL_CTX_USE_CERTIFICATE_CHAIN_FILE, ERR_R_BUF_LIB);
          ^
libressl.c:84:10: note: each undeclared identifier is reported only once for each function it appears in
libressl.c:89:10: error: dereferencing pointer to incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
       ctx->default_passwd_callback,
          ^~
Makefile:429: recipe for target 'libressl.o' failed
make[2]: *** [libressl.o] Error 1
```

**Comment by poolpOrg** [comment]
yes, you are going to be in a lot of pain:

- your Ubuntu upgrade most likely moved you from OpenSSL 1.0.x to OpenSSL 1.1.x
- supporting OpenSSL 1.1.x involves additional patches in the portable branch...

I don't know what's the easiest way to deal with this on your system, either rollback to 6.0.3p1 which was working and only install the new -extras which should be compatible, or install OpenSMTPD 6.4.0 but this will require building and installing LibreSSL, adding the install path to your ldconfig, then build and install OpenSMTPD 6.4.0 depending on LibreSSL.

This is what I would do and I can help you with that but this means you're no longer using your package manager, so it's up to you.

**Comment by fluffykhv** [comment]
> yes, you are going to be in a lot of pain:
> 
> * your Ubuntu upgrade most likely moved you from OpenSSL 1.0.x to OpenSSL 1.1.x
> * supporting OpenSSL 1.1.x involves additional patches in the portable branch...
> 
> I don't know what's the easiest way to deal with this on your system, either rollback to 6.0.3p1 which was working and only install the new -extras which should be compatible, or install OpenSMTPD 6.4.0 but this will require building and installing LibreSSL, adding the install path to your ldconfig, then build and install OpenSMTPD 6.4.0 depending on LibreSSL.

Not only LibreSSL should be built privately but libevent with this LibreSSL private libs too :( I have this pain at FreeBSD 12+ with OpenSSL 1.1.1 in base :(

**Comment by usonianhorizon** [comment]
What I have done is taken the distro source for 6.0.3p1, and replaced crypt_checkpass.c with @jnbr 's patch.  Installed all the dependencies as per [Source Package: opensmtpd (6.0.3p1-1build1)](https://packages.ubuntu.com/source/bionic/opensmtpd) and compiled successfully.  @poolpOrg @fluffykhv you are right:  Had to install `libssl1.0-dev` after uninstalling default `libssl-dev` in base.

Just about to `make install`, and will report back shortly. *Fingers crossed.*

**Comment by poolpOrg** [comment]
> > yes, you are going to be in a lot of pain:
> > 
> > * your Ubuntu upgrade most likely moved you from OpenSSL 1.0.x to OpenSSL 1.1.x
> > * supporting OpenSSL 1.1.x involves additional patches in the portable branch...
> > 
> > I don't know what's the easiest way to deal with this on your system, either rollback to 6.0.3p1 which was working and only install the new -extras which should be compatible, or install OpenSMTPD 6.4.0 but this will require building and installing LibreSSL, adding the install path to your ldconfig, then build and install OpenSMTPD 6.4.0 depending on LibreSSL.
> 
> Not only LibreSSL should be built privately but libevent with this LibreSSL private libs too :( I have this pain at FreeBSD 12+ with OpenSSL 1.1.1 in base :(

really ? libevent depends on OpenSSL ?

**Comment by usonianhorizon** [comment]
No luck :(.  Have confirmed that I compiled with patched crypt_checkpass.c:

```
#  diff crypt_checkpass.c*
3d2
< #include "includes.h"
14,15d12
<       char *c;
<
23,27c20
<       c = crypt(pass, goodhash);
<       if (c == NULL)
<               goto fail;
<
<       if (strcmp(c, goodhash) == 0)
---
>       if (strcmp(crypt(pass, goodhash), goodhash) == 0)
```

Right now I am unable to create the report.log even though `systemctl` seems to be able to start the service properly:

```
smtpd: setup done
mproc: parent -> control: enabled
mproc: parent -> lka: enabled
mproc: parent -> queue: enabled
mproc: parent -> ca: enabled
mproc: parent -> pony: enabled
debug: parent -> ca: pipe closed
smtpd: process ca socket closed
lookup: unknown user _smtpd
control: unknown user _smtpd
scheduler: unknown user _smtpd
pony express: unknown user _smtpd
unknown user _smtpq
```

Did I mess up the `configure` command?

**Comment by usonianhorizon** [comment]
Oops.  Service is starting because `systemd` unit is still pointing to `/usr/sbin/smtpd`, while the newly installed one is in `/usr/local/sbin/smtpd`.  So I haven't actually tested the patched version.  Now how to get the new version to stay alive in non-daemon mode before I start messing with `systemd` unit file?

```
root@khor [09:14] /#  systemctl status opensmtpd.service
● opensmtpd.service - OpenSMTPD SMTP server
   Loaded: loaded (/lib/systemd/system/opensmtpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-11-07 09:09:02 EST; 6min ago
     Docs: man:smtpd(8)
  Process: 2493 ExecStop=/usr/sbin/smtpctl stop (code=exited, status=255)
  Process: 2700 ExecStart=/usr/sbin/smtpd (code=exited, status=0/SUCCESS)
 Main PID: 2701 (smtpd)
    Tasks: 7 (limit: 4666)
   CGroup: /system.slice/opensmtpd.service
           ├─2701 /usr/sbin/smtpd
           ├─2702 smtpd: klondike
           ├─2703 smtpd: control
           ├─2704 smtpd: lookup
           ├─2705 smtpd: pony express
           ├─2706 smtpd: queue
           └─2707 smtpd: scheduler
```

**Comment by usonianhorizon** [comment]
Have created a new `systemd` unit in `/etc/systemd/system` pointing to the updated binaries and now I get a similar failure on service start.  What could be the issue with user _smtpd?  There is both an `opensmtpd` and `opensmtpq` in `/etc/passwd`.

```
#  systemctl status opensmtpd.service
● opensmtpd.service - OpenSMTPD SMTP server
   Loaded: loaded (/etc/systemd/system/opensmtpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-11-07 09:30:10 EST; 4min 16s ago
     Docs: man:smtpd(8)
  Process: 3908 ExecStart=/usr/local/sbin/smtpd (code=exited, status=0/SUCCESS)
 Main PID: 3911 (code=exited, status=1/FAILURE)

Nov 07 09:30:10 khor.pavastupa.com systemd[1]: Starting OpenSMTPD SMTP server...
Nov 07 09:30:10 khor.pavastupa.com smtpd[3908]: info: OpenSMTPD 6.0.3-portable starting
Nov 07 09:30:10 khor.pavastupa.com systemd[1]: Started OpenSMTPD SMTP server.
Nov 07 09:30:10 khor.pavastupa.com smtpd[3912]: klondike: unknown user _smtpd
Nov 07 09:30:10 khor.pavastupa.com smtpd[3913]: control: unknown user _smtpd
Nov 07 09:30:10 khor.pavastupa.com smtpd[3911]: smtpd: process control socket closed
Nov 07 09:30:10 khor.pavastupa.com systemd[1]: opensmtpd.service: Main process exited, code=exited, status=1/FAILURE
Nov 07 09:30:10 khor.pavastupa.com smtpd[3919]: smtpd: unknown user _smtpq
Nov 07 09:30:10 khor.pavastupa.com systemd[1]: opensmtpd.service: Failed with result 'exit-code'.
```

**Comment by whataboutpereira** [comment]
It's looking for the default _smtpd and _smtpq users.

**Comment by usonianhorizon** [comment]
_faceplant_ I just saw that in README.md about default users .  Going to rerun configure to use the system users and groups in base rather than creating the default ones, i.e., `opensmtpd`, `opensmtpq`.

**Comment by usonianhorizon** [comment]
Nearly there, but still need a bit of help.  Have recompiled with the base user and group.  Service starts properly, but spawned processes don't open ports like base does.  Good news is that it hasn't crashed, but then we actually haven't done a successful auth either :)

???
I have been working on this all night, and so am good and truly not seeing clearly.  So if there is something obvious I am missing, please excuse.  Is it possible that it isn't picking up /etc/mail/smtpd.conf.local?

Newly compiled smtpd running as service:

```
#  netstat -ntlp | grep smtp
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      20190/smtpd: pony e
```
Base service:

```
#  netstat -ntlp | grep smtp
tcp        0      0 162.247.78.221:25       0.0.0.0:*               LISTEN      20349/smtpd: pony e
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      20349/smtpd: pony e
tcp        0      0 127.0.0.1:10025         0.0.0.0:*               LISTEN      20349/smtpd: pony e
tcp        0      0 162.247.78.221:587      0.0.0.0:*               LISTEN      20349/smtpd: pony e
tcp        0      0 127.0.0.1:10029         0.0.0.0:*               LISTEN      20349/smtpd: pony e
tcp6       0      0 fe80::216:3cff:febc::25 :::*                    LISTEN      20349/smtpd: pony e
tcp6       0      0 ::1:25                  :::*                    LISTEN      20349/smtpd: pony e
tcp6       0      0 ::1:10025               :::*                    LISTEN      20349/smtpd: pony e
tcp6       0      0 fe80::216:3cff:febc:587 :::*                    LISTEN      20349/smtpd: pony e
tcp6       0      0 ::1:10029               :::*                    LISTEN      20349/smtpd: pony e
```

**Comment by usonianhorizon** [comment]
Back in production (I hope).  Thank you to all, especially to @jnbr for diagnosing what the problem was.

For the sake of completeness I am documenting all the steps I have taken here for anyone else facing the same issue.  Hope that package maintainers also update quickly for those not chasing down the answers on github:

1. Download base source for 6.0.3p1 from [Source Package: opensmtpd (6.0.3p1-1build1)](https://packages.ubuntu.com/source/bionic/opensmtpd) and extract from the tarball.

2. Replace openbsd-compat/crypt_checkpass.c with [patched version](https://github.com/jnbr/OpenSMTPD/blob/9b5f70b93e038df5446bd37a4adac5a0380748e7/openbsd-compat/crypt_checkpass.c)

3. Run `./bootstrap`

4. Run the following `configure` command:

```
./configure \
    --with-user-smtpd=opensmtpd \
    --with-user-queue=opensmtpq \
    --with-group-queue=opensmtpq \
    --with-path-empty=/var/lib/opensmtpd/empty
``` 
This aligns the compile with the defaults used by base.

5.  Run `make && make install`.  This puts `smtpctl` and `smtpd` in `/usr/local/sbin`.

6.  Create a local copy of the `/lib/systemd/system/opensmtpd.service` unit file in `/etc/systemd/system/` and modify to point to newly compiled version, which is in `/usr/local/sbin`:

```
[Unit]
Description=OpenSMTPD SMTP server
Documentation=man:smtpd(8)
After=network.target

[Service]
Type=forking
ExecStart=/usr/local/sbin/smtpd
ExecStop=/usr/local/sbin/smtpctl stop

[Install]
WantedBy=multi-user.target
```

7.  If you have a local copy of smtpd.conf then you need to modify `/usr/local/etc/smtpd.conf`.  In our case, we keep `smtpd.conf.local` in `/etc/mail`, and so we needed to modify `/usr/local/etc/smtpd.conf` to have a single line:

```
include "/etc/mail/smtpd.conf.local"
```

8.  After restarting the service, use `systemctl status opensmtpd.service` to ensure that the service is active paying particular attention that `ExecStop=/usr/local/sbin/smtpctl` and `ExecStart=/usr/local/sbin/smtpd` are pointing to the binaries in `/usr/local/sbin`

9.  Run `netstat -ntlp | grep smtp` to confirm that the open ports match your expectations from your smtpd.conf file.

That's it, I think.  If anything is unclear, please let me know and I will be happy to update.

**Comment by ArchangeGabriel** [comment]
Congrats on fixing this on your setup! :)

@poolpOrg On my side I can confirm that upgrading to latest extra works with 6.0.3p1. ;)

**Comment by poolpOrg** [comment]
Congrats !

I'll let @usonianhorizon close the ticket if ok with him :-)

Thanks to people who helped him.

**Comment by usonianhorizon** [comment]
Closing ticket.

Have filed a bug at [Launchpad](https://bugs.launchpad.net/ubuntu/+source/opensmtpd/+bug/1802146) pointing back to this thread, and so I trust package maintainers will commit upstream and release.  Bug status is still showing `UNDECIDED`, and so hope others facing the issue might find their way to this thread.

Thanks again, everyone!  Going from STABLE LTS to STABLE LTS and having your mail server go down wasn't part of our deployment plan :)

**Comment by EX0l0N** [comment]
For the meantime I've rebuild the package including the fix provided above:

[opensmtpd_6.0.3p1-1build1-fix_amd64.deb](https://raw.exoz.net/opensmtpd/opensmtpd_6.0.3p1-1build1-fix_amd64.deb)

I didn't feel like compiling software on prod and by using a package everything will be back to normal, as soon as the maintainers roll out a new package.
