### ISSUE TITLE
regular user auth not working in 6.4

### ISSUE THREAD

**Issue by flipchan** [OpenSMTPD/OpenSMTPD#899]
Hey,

I am trying to upgrade my opensmtpd email server running on openbsd 6.3 towards a new one on 6.4, i have used a simple config with the new syntax:
cat /etc/mail/smtpd.conf                                                                                                                          
table aliases file:/etc/mail/aliases
#table other-relays file:/etc/mail/other-relays

pki mail.example.com cert "/etc/ssl/mail.example.com.crt"
pki mail.example.com key "/etc/ssl/private/mail.example.com.key"

listen on lo0
listen on vio0 port 587 hostname example.com tls-require pki mail.example.com auth mask-source
listen on vio0 port 25 hostname example.com tls pki mail.example.com

action "mbox" mbox alias <aliases>
action "relay" relay

match for local action "mbox"
match for any action "relay"
match from any for domain example.com action "mbox"

i cant login with a users regular username and passwd which is weird.

In the documentation it says that it is suppose to take regular user creds if not a table is defined which it is not.

 https://man.openbsd.org/smtpd.conf#listen_on
 "Users are authenticated against either their own normal login credentials or a credentials table authtable, the format of which is 
 described in table(5)."

Where in the config am i doing something wrong?

maillog:
Jan 12 16:47:49 host smtpd[95842]: XXXXXXXXXXXXXXX smtp connected address=ip host=ip
Jan 12 16:47:49 host smtpd[95842]: XXXXXXXXXXXXXXX smtp starttls address=ip host=ip ciphers="version=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256"
Jan 12 16:47:49 host smtpd[95842]: XXXXXXXXXXXXXXX smtp authentication user=user address=ip host=ip result=permfail
Jan 12 16:47:49 host smtpd[95842]: XXXXXXXXXXXXXXX smtp failed-command address=ip host=ip command="AUTH PLAIN (...)" result="535 Authentication failed"
Jan 12 16:47:49 host smtpd[95842]: XXXXXXXXXXXXXXX smtp authentication user=user address=ip host=ip result=permfail
Jan 12 16:47:50 host smtpd[95842]: XXXXXXXXXXXXXXX smtp failed-command address=ip host=ip command="AUTH LOGIN (password)" result="535 Authentication failed"

**Comment by poolpOrg** [comment]
This is not a bug but a local configuration issue, please use the mailing list or IRC to get help, not the bug tracker.

**Comment by flipchan** [comment]
solution by mailing list 
https://marc.info/?l=openbsd-misc&m=154747296018907&w=2
