### ISSUE TITLE
Link error with LLD

### ISSUE THREAD

**Issue by Sp1l** [OpenSMTPD/OpenSMTPD#900]
https://github.com/OpenSMTPD/OpenSMTPD/blob/ef2f368219152771ac32adaa05dc1aee4c2bfe29/mk/smtpctl/Makefile.am#L24

Building the latest snapshot on FreeBSD results in a link error
```
libtool: link: cc -DNO_IO -DCONFIG_MINIMUM -DPATH_GZCAT=\"/usr/bin/zcat\" -DPATH_ENCRYPT=\"/usr/local/libexec/opensmtpd/encrypt\" -O2
-fno-strict-aliasing -pipe -march=native -fstack-protector -fPIC -DPIC -Qunused-arguments -Wunknown-warning-option -Wall -Wpointer-ari
th -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasi
ng -fno-builtin-mem_GNU_SOURCE -fstack-protector -o smtpctl ../../smtpd/smtpctl-enqueue.o ../../smtpd/smtpctl-parser.o ../../smtpd/smt
pctl-config.o ../../smtpd/smtpctl-log.o ../../smtpd/smtpctl-envelope.o ../../smtpd/smtpctl-queue_backend.o ../../smtpd/smtpctl-queue_f
s.o ../../smtpd/smtpctl-smtpctl.o ../../smtpd/smtpctl-spfwalk.o ../../smtpd/smtpctl-util.o ../../smtpd/smtpctl-unpack_dns.o ../../smtp
d/smtpctl-compress_backend.o ../../smtpd/smtpctl-compress_gzip.o ../../smtpd/smtpctl-to.o ../../smtpd/smtpctl-expand.o ../../smtpd/smt
pctl-tree.o ../../smtpd/smtpctl-dict.o ../../smtpd/smtpctl-config.o ../../smtpd/smtpctl-parse.o ../../smtpd/smtpctl-limit.o ../../smtp
d/smtpctl-table.o ../../smtpd/smtpctl-table_static.o ../../smtpd/smtpctl-table_db.o ../../smtpd/smtpctl-table_getpwnam.o ../../smtpd/s
mtpctl-table_proc.o ../../smtpd/smtpctl-mailaddr.o ../../smtpd/smtpctl-makemap.o ../../smtpd/smtpctl-crypto.o  -L/usr/lib -L/usr/local
/lib ../../openbsd-compat/libopenbsd-compat.a -lz -lcrypto -lssl -levent -lasr -lcrypt -lutil -lpam -ldl
/usr/bin/ld: error: duplicate symbol: config_default
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(config_default)
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(.text+0x0)

/usr/bin/ld: error: duplicate symbol: config_peer
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(config_peer)
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(.text+0xBA0)

/usr/bin/ld: error: duplicate symbol: config_process
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(config_process)
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(.text+0xB90)

/usr/bin/ld: error: duplicate symbol: purge_config
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(purge_config)
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(.text+0x7F0)

/usr/bin/ld: error: duplicate symbol: set_local
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(set_local)
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(.text+0x530)

/usr/bin/ld: error: duplicate symbol: set_localaddrs
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(set_localaddrs)
>>> defined at config.c
>>>            ../../smtpd/smtpctl-config.o:(.text+0x590)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** [smtpctl] Error code 1
```
linker is LLD
```
$ /usr/bin/ld --version
LLD 6.0.1 (FreeBSD 335540-1200005) (compatible with GNU linkers)
$ uname -a
FreeBSD build.example.net 12.0-RELEASE FreeBSD 12.0-RELEASE r341813 BEASTIE111  amd64
```
Issue is duplicate `config.c` in `mk/smtpctl/Makefile.am` line 24. Removing the duplicate prior to running `configure`.

**Comment by poolpOrg** [comment]
On Sun, Jan 13, 2019 at 04:37:41AM -0800, Bernard Spil wrote:
> https://github.com/OpenSMTPD/OpenSMTPD/blob/ef2f368219152771ac32adaa05dc1aee4c2bfe29/mk/smtpctl/Makefile.am#L24
> 
> Building the latest snapshot on FreeBSD results in a link error
> ```
> libtool: link: cc -DNO_IO -DCONFIG_MINIMUM -DPATH_GZCAT=\"/usr/bin/zcat\" -DPATH_ENCRYPT=\"/usr/local/libexec/opensmtpd/encrypt\" -O2
> -fno-strict-aliasing -pipe -march=native -fstack-protector -fPIC -DPIC -Qunused-arguments -Wunknown-warning-option -Wall -Wpointer-ari
> th -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasi
> ng -fno-builtin-mem_GNU_SOURCE -fstack-protector -o smtpctl ../../smtpd/smtpctl-enqueue.o ../../smtpd/smtpctl-parser.o ../../smtpd/smt
> pctl-config.o ../../smtpd/smtpctl-log.o ../../smtpd/smtpctl-envelope.o ../../smtpd/smtpctl-queue_backend.o ../../smtpd/smtpctl-queue_f
> s.o ../../smtpd/smtpctl-smtpctl.o ../../smtpd/smtpctl-spfwalk.o ../../smtpd/smtpctl-util.o ../../smtpd/smtpctl-unpack_dns.o ../../smtp
> d/smtpctl-compress_backend.o ../../smtpd/smtpctl-compress_gzip.o ../../smtpd/smtpctl-to.o ../../smtpd/smtpctl-expand.o ../../smtpd/smt
> pctl-tree.o ../../smtpd/smtpctl-dict.o ../../smtpd/smtpctl-config.o ../../smtpd/smtpctl-parse.o ../../smtpd/smtpctl-limit.o ../../smtp
> d/smtpctl-table.o ../../smtpd/smtpctl-table_static.o ../../smtpd/smtpctl-table_db.o ../../smtpd/smtpctl-table_getpwnam.o ../../smtpd/s
> mtpctl-table_proc.o ../../smtpd/smtpctl-mailaddr.o ../../smtpd/smtpctl-makemap.o ../../smtpd/smtpctl-crypto.o  -L/usr/lib -L/usr/local
> /lib ../../openbsd-compat/libopenbsd-compat.a -lz -lcrypto -lssl -levent -lasr -lcrypt -lutil -lpam -ldl
> /usr/bin/ld: error: duplicate symbol: config_default
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(config_default)
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(.text+0x0)
> 
> /usr/bin/ld: error: duplicate symbol: config_peer
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(config_peer)
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(.text+0xBA0)
> 
> /usr/bin/ld: error: duplicate symbol: config_process
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(config_process)
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(.text+0xB90)
> 
> /usr/bin/ld: error: duplicate symbol: purge_config
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(purge_config)
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(.text+0x7F0)
> 
> /usr/bin/ld: error: duplicate symbol: set_local
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(set_local)
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(.text+0x530)
> 
> /usr/bin/ld: error: duplicate symbol: set_localaddrs
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(set_localaddrs)
> >>> defined at config.c
> >>>            ../../smtpd/smtpctl-config.o:(.text+0x590)
> cc: error: linker command failed with exit code 1 (use -v to see invocation)
> *** [smtpctl] Error code 1
> ```
> linker is LLD
> ```
> $ /usr/bin/ld --version
> LLD 6.0.1 (FreeBSD 335540-1200005) (compatible with GNU linkers)
> $ uname -a
> FreeBSD build.example.net 12.0-RELEASE FreeBSD 12.0-RELEASE r341813 BEASTIE111  amd64
> ```
> Issue is duplicate `config.c` in `mk/smtpctl/Makefile.am` line 24. Removing the duplicate prior to running `configure`.
> 

Thanks !


-- 
Gilles Chehade						       @poolpOrg

https://www.poolp.org                 tip me: https://paypal.me/poolpOrg

**Comment by poolpOrg** [comment]
bug fix committed, thanks
