### ISSUE TITLE
filter builtin mail-from 

### ISSUE THREAD

**Issue by mischapeters** [OpenSMTPD/OpenSMTPD#901]
I am playing with the filter rules and one of the things I tried was:

```
filter foobar builtin mail-from !mail-from mischa@domain1.nl reject "550 you're not mischa@ you punk"
```

It was catching also the following, which I was not expecting:

```
Jan 14 16:47:05 mx1 smtpd[52162]: dd5426a7c5f5e89a smtp failed-command command="MAIL FROM:<mischa+caf_=company=domain1.nl@domain2.com> SIZE=115525" result="550 you're not mischa@ you punk"
```

Not sure if this is as-designed.
<mischa+caf_=company=domain1.nl@domain2.com> is a forward from a google account to my local mailserver.

**Comment by poolpOrg** [comment]
This seems to be the correct behavior:

You are requesting that any sender that's not mischa@domain1.nl be rejected, and it is rejecting a sender that's mischa@domain2.com

**Comment by mischapeters** [comment]
Than I clearly misunderstood the filter... I thought this was to prevent spoofing where someone would use the to and from to be the same. Is there a way to do that with filters?

**Comment by poolpOrg** [comment]
On Tue, Jan 15, 2019 at 12:40:07AM -0800, Mischa Peters wrote:
> Than I clearly misunderstood the filter... I thought this was to prevent spoofing where someone would use the to and from to be the same. Is there a way to do that with filters?
> 

yes, you misunderstood that filter.

the only way to do that is through a proc filter as of today.


-- 
Gilles Chehade						       @poolpOrg

https://www.poolp.org                 tip me: https://paypal.me/poolpOrg

**Comment by mischapeters** [comment]
Clear! :)
