### ISSUE TITLE
match rule seems to be failing in -current

### ISSUE THREAD

**Issue by mischapeters** [OpenSMTPD/OpenSMTPD#902]
Currently running OpenSMTPD on OpenBSD 6.4 GENERIC#588
With the following rules in smtpd.conf

```
action "local" mbox alias <aliases>
action "maildir" maildir "/var/mail/virtual/%{dest:lowercase}/" virtual <virtuals>
action "relay" relay
action "smartrelay" relay host smtp://mail.domain1.nl

match from any rcpt-to <reject-email> for any reject
match from src <www-relays> ! mail-from <www-senders> for any reject
match from src <www-relays> mail-from <www-senders> action "relay" 
match from any for domain <relay-domains> action "smartrelay"
match from any for domain <domains> action "maildir"
match from local action "smartrelay"
match for any action "relay"
```

```
# cat www-relays 
46.23.xx.xx
```

```
# cat www-senders 
www@www.domain2.nl
```

As soon as an email is send from one of the www-relays with the sender in www-senders I am getting the following error on the sending mail server:

```
Jan 18 14:10:03 www dma[2ec628]: new mail from user=www uid=80 envelope_from=<www@www.domain2.nl>   
Jan 18 14:10:03 www dma[2ec628]: mail to=<info@domain2.nl> queued as 2ec628.801a2d0a0       
Jan 18 14:10:03 www dma[2ec628.801a2d0a0]: trying delivery                                         
Jan 18 14:10:03 www dma[2ec628.801a2d0a0]: using smarthost (mx1.domain1.nl:25)                       
Jan 18 14:10:03 www dma[2ec628.801a2d0a0]: trying remote delivery to mx1.domain1.nl [46.23.xx.xx] pref 0
Jan 18 14:10:03 www dma[2ec628.801a2d0a0]: remote delivery to mx1.domain1.nl[46.23.xx.xx] failed after RCPT TO: 550 Invalid recipient
````

OpenSMTPD is saying:
```
Jan 18 14:10:04 mx1 smtpd[36743]: 00a1b263550db3c7 smtp connected address=46.23.xx.xx host=www.domain2.nl
Jan 18 14:10:04 mx1 smtpd[36743]: 00a1b263550db3c7 smtp failed-command command="RCPT TO:<info@domain2.nl>" result="550 Invalid recipient"
```

This always worked before the syntax change and as far as I am aware this is the correct syntax since version 6.4.0... or is there something missing?

**Comment by poolpOrg** [comment]
On Fri, Jan 18, 2019 at 05:24:39AM -0800, Mischa Peters wrote:
> Currently running OpenSMTPD on OpenBSD 6.4 GENERIC#588
> With the following rules in smtpd.conf
> 
> ```
> action "relay" relay
> 
> match from src <www-relays> ! mail-from <www-senders> for any reject
> match from src <www-relays> mail-from <www-senders> action "relay"
> match for any action "relay"
> ```
> 
> ```
> # cat www-relays 
> 46.23.xx.xx
> ```
> 
> ```
> # cat www-senders 
> www@www.domain2.nl
> ```
> 
> As soon as an email is send from one of the www-relays with the sender in www-senders I am getting the following error on the sending mail server:
> 
> ```
> Jan 18 14:10:03 www dma[2ec628]: new mail from user=www uid=80 envelope_from=<www@www.domain2.nl>   
> Jan 18 14:10:03 www dma[2ec628]: mail to=<info@domain2.nl> queued as 2ec628.801a2d0a0       
> Jan 18 14:10:03 www dma[2ec628.801a2d0a0]: trying delivery                                         
> Jan 18 14:10:03 www dma[2ec628.801a2d0a0]: using smarthost (mx1.domain1.nl:25)                       
> Jan 18 14:10:03 www dma[2ec628.801a2d0a0]: trying remote delivery to mx1.domain1.nl [46.23.xx.xx] pref 0
> Jan 18 14:10:03 www dma[2ec628.801a2d0a0]: remote delivery to mx1.domain1.nl[46.23.xx.xx] failed after RCPT TO: 550 Invalid recipient
> ````
> 
> This always worked before the syntax change and as far as I am aware this is the correct syntax since version 6.4.0... or is there something missing?
> 

without the smtpd logs displaying the entire session, it is hard to take
a guess at why it is being rejected.

please, unless you are confident that you are facing a real issue, not a
configuration error, please take this to the mailing list as issues will
send notifications to all developers and cause them to have a look while
the community could have helped first.

the issue tracker is for bug reports, not support, and you want to avoid
developers assuming you are asking for support the day you open an issue
for real...

this may or may not be a bug, hard to tell from what you posted, but you
should take it to the mailing list and once you have big hints that this
is not a problem on your side, take it here.

cheers,

-- 
Gilles Chehade						       @poolpOrg

https://www.poolp.org                 tip me: https://paypal.me/poolpOrg

**Comment by poolpOrg** [comment]
issue solved on mailing list
