### ISSUE TITLE
Option to reject email from non-existent domains

### ISSUE THREAD

**Issue by arjenz** [OpenSMTPD/OpenSMTPD#904]
Hi,

It might be nice to have an option to reject email from domains that do not exist (or at least, "domains that currently do not resolve into anything useful (MX/A/AAAA) on the local system").

Thanks!
Arjen

**Comment by poolpOrg** [comment]
this is an interesting idea yes

**Comment by poolpOrg** [comment]
So, I implemented the feature you want but it makes more sense to me as a filter than as an option in the daemon because surely there's at least 10 different ways we will want to check the sender domain in the future.

Anyways, enjoy:

https://github.com/poolpOrg/filter-checksenderdomain

**Comment by arjenz** [comment]
Thank you! I'll give it a try.
