### ISSUE TITLE
Unable to build Portable, table.c:66:3 error: 'table_backend_db' undeclared here

### ISSUE THREAD

**Issue by EmperorArthur** [OpenSMTPD/OpenSMTPD#905]
Hello,

I am having trouble building OpenSMTPD. I think there's an issue where an optional feature was accidentally made a requirement.  It probably wasn't caught because most developers working on the project have the option installed.

# The issue
I am unable to build the latest portable branch because the code references "table_backend_db", which is only added if **HAVE_DB_API** is defined.  This is vexing because `./configure` does not error if that is not present, and I'm unsure of what package I need to build/install to fix it.

I suspect this is a bug because I can build the "opensmtpd-6.4.1p2" tag successfully, and the requirements in the Readme have not changed.

# Solution 1:
Modify the code so that it no longer relies on **HAVE_DB_API**.  This is a silent requirements change that may have broken any build system that followed the directions in the Readme.

# Solution 2:
Modify 'configure.ac' to require **HAVE_DB_API** and provide a useful warning about what is missing if that is not found.  Further, update the Readme with the new requirements.

**Comment by poolpOrg** [comment]
hi, thanks for your report

care to pull and give another try ?

**Comment by EmperorArthur** [comment]
Confirmed fixed.  Thanks for the quick reply.
