### ISSUE TITLE
Suggestion: Use Docker Hub as a CI platform / host an official OpenSMTPD docker image

### ISSUE THREAD

**Issue by EmperorArthur** [OpenSMTPD/OpenSMTPD#909]
Docker Hub will automatically pull images from an organization repository and attempt to build them.  By setting up an official repository, not only are users getting the advantage of the latest working code, but they're getting it right from the source.

The other thing Docker Hub can do is run a test suite.  I'm not as familiar with that part, but it should be possible to build some tests where the program would immediately crash to keep it from ever happening again.

For not I'm just suggesting an official repository and automated builds.  Along with builds for some older tags.  That way users don't have to rely on the bleeding edge (called 'latest' in Docker terms) and can use older tagged releases.

[This ](https://cloud.docker.com/repository/docker/emperorarthur/opensmtpd/tags) is what I have right now, but I think people should get things right from the source instead of having to rely on a third party.

**Comment by poolpOrg** [comment]
This is a good idea.

I will take care of it, thanks :+1:

**Comment by poolpOrg** [comment]
The OpenSMTPD organization has been created: https://hub.docker.com/u/opensmtpd

There's still a ton of setup to do but I did a test build based on your Dockerfile, works fine, we'll make this happen ;-)

**Comment by poolpOrg** [comment]
Here's CI for the portable branch:
https://cloud.docker.com/u/opensmtpd/repository/docker/opensmtpd/ci_portable/builds
