### ISSUE TITLE
Docker Hub is not auto building portable images

### ISSUE THREAD

**Issue by EmperorArthur** [OpenSMTPD/OpenSMTPD#912]
Looking at https://hub.docker.com/r/opensmtpd/ci_portable/builds the CI system is not attempting to build portable images.  The last build was 22 days ago on commit 8095619.

The settings should probably look like this (taken from my own copy of the CI system):
![Docker Hub OpenSMTPD build](https://user-images.githubusercontent.com/1515637/54387398-ada48580-4671-11e9-9b7f-5302acb9a70c.PNG)

PS:  Slightly off topic, but the name 'ci_portable' is accurate, but discourages people from using the image as part of a continuous deployment process.  I'm actively using a personal copy of the CI system as my actual deployment.  It's a build artifact, just like a binary, that can just be run in production.

**Comment by EmperorArthur** [comment]
Oh, if that still doesn't fix it, Docker Hub also provided this https://success.docker.com/article/i-have-issues-triggering-autobuilds

**Comment by poolpOrg** [comment]
We won't use Docker Hub for CI:

- GitHub is going to provide free CI/CD for projects with public repositories and we'll be able to run docker instances from our own machines
- Docker Hub required Admin privileges in the repository which makes me uncomfortable
