### ISSUE TITLE
Too many recipients with 7 CC: entries

### ISSUE THREAD

**Issue by 717g301github** [OpenSMTPD/OpenSMTPD#918]
Please help me, as I can see that local OpenSMTPD rejects some emails, even if I just have 6-7 CC: recipients.

I was thinking to place max-rcpt 1000, but it does not help.

I am using opensmtpd 6.0.2p1-3 on Hyperbola GNU/Linux-libre

```
listen on localhost
 
 limit session max-rcpt 1000
 # If you edit the file, you have to run "smtpctl update table aliases"
 table aliases file:/etc/smtpd/aliases
 table secrets file:/etc/smtpd/secrets
 
 accept for local alias <aliases> deliver to maildir
 accept from any for any relay via tls+auth://rcd@example.com:587 auth <secrets>
```

**Comment by poolpOrg** [comment]
This was handled on the mailing list, it is very likely a configuration error as the max rcpt limit is far above this, didn't get a follow up from OP after pinpointing that and requesting more info.

Closing issue.
