### ISSUE TITLE
Make rDNS match with unknown domains

### ISSUE THREAD

**Issue by pywy18** [OpenSMTPD/OpenSMTPD#919]
There is no way to match unknown hosts with the rdns regex functionality.
The hosts with no reverse dns defined never matches the `from rdns` filter.
Could be great to "filter" hosts connecting from ips with no reverse dns configured with this kind of syntax: 
`match ! from rdns [...] reject`

**Comment by poolpOrg** [comment]
implemented and committed to OpenBSD, will hit github soon.

**Comment by pywy18** [comment]
Great news!
