### ISSUE TITLE
What is the syntax error here? 

### ISSUE THREAD

**Issue by allowthere** [OpenSMTPD/OpenSMTPD#920]
My /etc/my-dir/smtpd.conf is

          listen on 0.0.0.0
          accept for any relay

When I run
`smtpd -d -f /etc/my-dir/smtpd.conf`, I get `/etc/my-dir/smtpd.conf:2: syntax error`

What's wrong with `accept for any relay`?

My opensmtpd version is 6.4.1p2.

**Comment by idfake** [comment]
> What's wrong with `accept for any relay`?
> My opensmtpd version is 6.4.1p2.

You might want to look at the relevant manpages. There's been a config syntax change.

**Comment by poolpOrg** [comment]
Also there's an IRC channel and a mailing list, opening issues for configuration support will not get you any help as I ignore them.Use the correct channel and enclose more details, like version and operating system.Le 19 juin 2019 22:37, idfake <notifications@github.com> a écrit :
What's wrong with accept for any relay?
My opensmtpd version is 6.4.1p2.

You might want to look at the relevant manpages. There's been a config syntax change.
