### ISSUE TITLE
The userbase parameter to `mda` appears to be ignored in 6.4.0 when forking the mda

### ISSUE THREAD

**Issue by Ekleog** [OpenSMTPD/OpenSMTPD#923]
My configuration from 6.3.0, once syntactically adapted to the 6.4.0 format, fails delivery with `result=PermFail stat=Error (user unknown)` when trying to do an `action foo mda "/bar" virtual <aliases> userbase <users>`.

The trace shows: `debug: smtpd: forking mda for session […]: [virtual-me] as [virtual-me]`. This makes me think smtpd/smtpd.c:1350 (in `forkmda`) is being hit, while it shouldn't be given `[virtual-me]` is defined in the `<users>` table.

Note all the tables are `file:` tables, so there hopefully should be no problem in reading the table -- also, above in the logs I can see `warn: smtpd: parent_forward_open: /this-directory-does-not-exist/opensmtpd/[virtual-me]: No such file or directory`, as expected given this is the folder I gave in the table, so the parsing should be successful.

**Comment by poolpOrg** [comment]
weird, I have spent quite some time on userbase making sure it was working correctly.

I'll need your configuration file and the log with full context from message being submitted to delivery, please do include -T rules traces too.

I'll be working on smtpd this full week so the sooner you provide this, the more chances it gets investigated and/or fixed soon.

**Comment by Ekleog** [comment]
I've sent you the logs and configuration, with `smtpctl trace all` and `smtpctl log verbose`, by PM over IRC :)

**Comment by poolpOrg** [comment]
On Sun, Jun 23, 2019 at 06:37:36AM -0700, L??o Gaspard wrote:
> I've sent you the logs and configuration, with `smtpctl trace all` and `smtpctl log verbose`, by PM over IRC :)
> 

ok thanks




-- 
Gilles Chehade						       @poolpOrg

https://www.poolp.org            patreon: https://www.patreon.com/gilles

**Comment by poolpOrg** [comment]
I have trouble understanding your config, you should try with a simpler one to reproduce the issue because from what I see here:

The user "leo" from userbase "users" was correctly resolved and an mda session was setup for him:

    Ju  n 22 01:12:21 grym smtpd[14657]: mda: new user 8239c3c54fc76565 for "users:leo"
    Jun 22 01:12:21 grym smtpd[14657]: debug: lka: userinfo users:leo
    Jun 22 01:12:21 grym smtpd[14657]: debug: mda: new session 8239c3c60ce4261a for user "users:leo" evpid 00bac9dfb0278c7d

A process was created to run the MDA, which can only happen if the user from userbase was correctly resolved (it uses the uid/gid it gets from there and would not go that far otherwise). In addition, the "leo as leo" bit is also correct, but what's interesting is that other line which says your MDA has exited abnormally:

    Jun 22 01:12:21 grym smtpd[14657]: debug: smtpd: forking mda for session 8239c3c60ce4261a: leo as leo
    [...]
    Jun 22 01:12:21 grym smtpd[14657]: debug: smtpd: mda process done for session 8239c3c60ce4261a: exited abnormally

And which is very likely what causes the failure.

I don't know what your mda-script.sh does or why it fails, but what I know for sure is that the `userbase` parameter to `mda` is honored as shown below.

Here I created a user _vmail with uid 1008 and setup a userbase so that smtpd user gilles is actually delivered by _vmail:

    $ cat /etc/mail/smtpd.conf-userbase
    table ubase { gilles = 1008:1008:/tmp/bleh }
    listen on socket
    action cat mda "/bin/cat - >> /tmp/foobar" userbase <ubase>
    match from any for local action cat
    $ ls -l /tmp/foobar
    $ echo test | mail gilles
    $ ls -l /tmp/foobar
    -rw-r--r--  1 _vmail  wheel  378 Jun 25 22:16 /tmp/foobar
    $

The same test without `userbase`:

    $ cat /etc/mail/smtpd.conf-nouserbase
    listen on socket
    action cat mda "/bin/cat - >> /tmp/foobar"
    match from any for local action cat
    $ ls -l /tmp/foobar
    $ echo test | mail gilles
    $ ls -l /tmp/foobar
    -rw-r--r--  1 gilles  wheel  378 Jun 25 22:19 /tmp/foobar
    $

I suggest you try to reproduce with a simpler setup to understand what is happening as my basic test exposes correct behavior and your output seems to imply the problem is with your MDA.

**Comment by Ekleog** [comment]
My understanding is that the code doesn't actually go up to forking the mda script, because the `stat=Error (user unknown)` error appears to come from an `EX_NOUSER` int, that can only be raised from 
https://github.com/OpenSMTPD/OpenSMTPD/blob/portable/smtpd/smtpd.c#L1414

This code path is compatible with the `debug: smtpd: forking mda […] leo as leo`  message, that is just a few lines above. The code path makes it look to me like it's attempting a `getpwnam` on… probably `leo`?, which is indeed going to fail.

Does that sound like a possibility to you? I can try to run a patched OpenSMTPD to confirm or infirm hypothesis more easily than run things that risk dropping mails like `cat` as an MDA, but I'd like to minimize the number of such attempts, as it's a downtime at each attempt that will still bounce emails :)

**Comment by Ekleog** [comment]
… actually, thinking about it, maybe replacing the `MDA_PERMFAIL` with `MDA_TEMPFAIL` would allow me to more easily test stuff by at least not bouncing stuff? I'll attempt it if you suggest some places you'd like to see instrumented to confirm things :)

**Comment by poolpOrg** [comment]
> My understanding is that the code doesn't actually go up to forking the mda script, because the `stat=Error (user unknown)` error appears to [come from an `EX_NOUSER` int](https://github.com/OpenSMTPD/OpenSMTPD/blob/portable/smtpd/mda.c#L890), that can only be raised from [here](https://github.com/OpenSMTPD/OpenSMTPD/blob/portable/smtpd/smtpd.c#L1414) according to two `grep` through the source code.
>

This getpwnam() call is _supposedly_ only called when the `user` keyword is specified on an action (as in `action foobar mda "bleh" user _vmail`), with the `mbox` delivery as the user must be enforced to `root` or when an alias or .forward expands to a command.

Maybe slapping a log_debug() here would be interesting to understand what happened:

    if (dsp->u.local.user)
        log_debug("user override: %s", dsp->u.local.user)

> This code path is compatible with the `debug: smtpd: forking mda […] leo as leo` message, that is just a few lines above. The code path makes it look to me like it's attempting a `getpwnam` on… probably `leo`?, which is indeed going to fail.
>

Yes that would be compatible with the line above but it should not happen.


> Does that sound like a possibility to you? I can try to run a patched OpenSMTPD to confirm or infirm hypothesis more easily than run things that risk dropping mails like `cat` as an MDA, but I'd like to minimize the number of such attempts, as it's a downtime at each attempt that will still bounce emails :)

**Comment by poolpOrg** [comment]
Any feedback on this ?

**Comment by Ekleog** [comment]
Didn't get the time to investigate more yet, sorry! I'll make sure to add details here when I manage to figure them out.

**Comment by poolpOrg** [comment]
10:41 < ekleog> __gilles: yeah, sorry for not having had the time to look into that again :/ feel free to close if you want, I've added "look into it" on my personal 
                todo-list, so I should come back to it eventually when I get some more time
