### ISSUE TITLE
Document SMTP limit configuration options

### ISSUE THREAD

**Issue by hostingnuggets** [OpenSMTPD/OpenSMTPD#927]
As discussed on the mailing list it would be great if the smtpd.conf man page could include some documentation about the SMTP limit configuration options such as `max-mails` and `max-rcpt`.

**Comment by poolpOrg** [comment]
I have added the missing documentation bits and committed to OpenBSD, this will be synchronized to github shortly.

**Comment by hostingnuggets** [comment]
Cheers :+1:
