### ISSUE TITLE
spfwalk: handle CNAME in MX records

### ISSUE THREAD

**Issue by norrland** [OpenSMTPD/OpenSMTPD#930]
When doing spf walk on an domain with MX records pointing to a CNAME record, spfwalk will print random IP addresses for that domain.

```
$ echo "kaosdata.name" | smtpctl spf walk
4.107.111.114
127.0.0.99
46b:6f72:7608:6b61:6f73:6461:7461:46e
```
DNS records:
```
$ dig txt kaosdata.name +short
"v=spf1 mx ~all"
```

```
$ dig mx kaosdata.name +short
99 mailet.kaosdata.name.
```

**Comment by ericfaurot** [comment]
This should fix it.

[spfwalk.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/3534987/spfwalk.txt)

**Comment by poolpOrg** [comment]
ok gilles@

**Comment by ericfaurot** [comment]
committed on CVS, will be part of the next sync.
