### ISSUE TITLE
Missing space on rules trace log in current portable.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#932]
Sep  2 15:18:12 orc smtpd[28757]: rule #2 matched: match tag <dynamic:2> from localfor domain domains => deliver_lmtp
Sep  2 15:18:12 orc smtpd[28757]: rule #3 matched: match tag <dynamic:3> from localfor any => relay_outgoing

Sorry for such a trivial report! :)

Running with -T rules yields a missing a space between from local and for any in the logs. :)

**Comment by poolpOrg** [comment]
fix committed to OpenBSD, will be synched here shortly.
