### ISSUE TITLE
compilation errors in portable branch in smtpd/ca.c in function rsae_pub_enc on openbsd 6.5

### ISSUE THREAD

**Issue by mchack23** [OpenSMTPD/OpenSMTPD#936]
When trying to compile the portable branch in openbsd 6.5 it fails with errors:

Making all in smtpd                                                                                                                                                       
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../smtpd -I../../openbsd-compat -I../../openbsd-compat/err_h  -I../../openbsd-compat/paths_h -I. -I/usr/include -I/usr/local/include
  -DSMTPD_CONFDIR=\"/usr/local/etc\"                         -DPATH_CHROOT=\"/var/empty\"              -DPATH_SMTPCTL=\"/usr/local/sbin/smtpctl\"                       -D
PATH_MAILLOCAL=\"/usr/local/libexec/smtpd/mail.local\"   -DPATH_LIBEXEC=\"/usr/local/libexec/smtpd\" -DHAVE_CONFIG_H -DIO_TLS -DCA_FILE=\"/etc/ssl/cert.pem\" -g -O2  -fPI
C -DPIC -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wno-pointer-sign -fno-strict-aliasing -fno-builtin-memset  -D_GNU_SOURCE -DNEED_EVENT_ASR_
RUN -c -o ../../smtpd/smtpd-ca.o `test -f '../../smtpd/ca.c' || echo './'`../../smtpd/ca.c                                                                                
../../smtpd/ca.c: In function 'rsae_pub_enc':                                                                                                                             
../../smtpd/ca.c:438: warning: implicit declaration of function 'RSA_meth_get_pub_enc'                                                                                    
../../smtpd/ca.c:438: error: called object 'RSA_meth_get_pub_enc(rsa_default)' is not a function                                                                          
../../smtpd/ca.c: In function 'rsae_pub_dec':                                                                                                                             
../../smtpd/ca.c:446: warning: implicit declaration of function 'RSA_meth_get_pub_dec'                                                                                    
../../smtpd/ca.c:446: error: called object 'RSA_meth_get_pub_dec(rsa_default)' is not a function
../../smtpd/ca.c: In function 'rsae_priv_enc':                                                                                                                            
../../smtpd/ca.c:457: warning: implicit declaration of function 'RSA_meth_get_priv_enc'                                                                                   
../../smtpd/ca.c:457: error: called object 'RSA_meth_get_priv_enc(rsa_default)' is not a function
../../smtpd/ca.c: In function 'rsae_priv_dec':                                                                                                                            
../../smtpd/ca.c:469: warning: implicit declaration of function 'RSA_meth_get_priv_dec'                                                                                   
../../smtpd/ca.c:469: error: called object 'RSA_meth_get_priv_dec(rsa_default)' is not a function
../../smtpd/ca.c: In function 'rsae_mod_exp':                                                                                                                             
../../smtpd/ca.c:476: warning: implicit declaration of function 'RSA_meth_get_mod_exp'                                                                                    
../../smtpd/ca.c:476: error: called object 'RSA_meth_get_mod_exp(rsa_default)' is not a function
../../smtpd/ca.c: In function 'rsae_bn_mod_exp':                                                                                                                          
../../smtpd/ca.c:484: warning: implicit declaration of function 'RSA_meth_get_bn_mod_exp'                                                                                 
../../smtpd/ca.c:484: error: called object 'RSA_meth_get_bn_mod_exp(rsa_default)' is not a function
../../smtpd/ca.c: In function 'rsae_init':                                           
../../smtpd/ca.c:491: warning: implicit declaration of function 'RSA_meth_get_init'                                                                                       
../../smtpd/ca.c:491: warning: comparison between pointer and integer                                                                                                     
../../smtpd/ca.c:493: error: called object 'RSA_meth_get_init(rsa_default)' is not a function
../../smtpd/ca.c: In function 'rsae_keygen':                                         
../../smtpd/ca.c:509: warning: implicit declaration of function 'RSA_meth_get_keygen'                                                                                     
../../smtpd/ca.c:509: error: called object 'RSA_meth_get_keygen(rsa_default)' is not a function
../../smtpd/ca.c: In function 'rsa_engine_init':                                                                                                                          
../../smtpd/ca.c:654: warning: implicit declaration of function 'RSA_meth_set_pub_enc'                                                                                    
../../smtpd/ca.c:655: warning: implicit declaration of function 'RSA_meth_set_pub_dec'                                                                                    
../../smtpd/ca.c:658: warning: implicit declaration of function 'RSA_meth_set_mod_exp'                                                                                    
../../smtpd/ca.c:659: warning: implicit declaration of function 'RSA_meth_set_bn_mod_exp'                                                                                 
../../smtpd/ca.c:660: warning: implicit declaration of function 'RSA_meth_set_init'                                                                                       
../../smtpd/ca.c:662: warning: implicit declaration of function 'RSA_meth_set_keygen'                                                                                     
../../smtpd/ca.c:669: warning: implicit declaration of function 'RSA_meth_get0_name'                                                                                      
../../smtpd/ca.c:669: warning: passing argument 2 of 'ENGINE_set_name' makes pointer from integer without a cast
../../smtpd/ca.c:687: warning: comparison between pointer and integer                                                                                                     
../../smtpd/ca.c:689: warning: comparison between pointer and integer                                                                                                     
../../smtpd/ca.c:691: warning: comparison between pointer and integer
../../smtpd/ca.c:693: warning: implicit declaration of function 'RSA_meth_set_flags'
../../smtpd/ca.c:694: warning: implicit declaration of function 'RSA_meth_get_flags'
../../smtpd/ca.c:695: warning: implicit declaration of function 'RSA_meth_set0_app_data'
../../smtpd/ca.c:696: warning: implicit declaration of function 'RSA_meth_get0_app_data'
*** Error 1 in mk/smtpd (Makefile:759 '../../smtpd/smtpd-ca.o')
*** Error 1 in mk (Makefile:396 'all-recursive')
*** Error 1 in . (Makefile:443 'all-recursive')
*** Error 1 in /home/mchack/opensmtp (Makefile:350 'all')

To reproduce:
in Openbsd 6.5 as per readme

git clone -b portable git://github.com/OpenSMTPD/OpenSMTPD.git opensmtpd
cd opensmtpd
./bootstrap 

(installed via pkg_add automake 1.16 and libtools to make it work also AUTOCONF_VERSION="2.69";export AUTOCONF_VERSION)

./configure
make

and then there's the error. :/

my machine is on amd64 architecture

**Comment by poolpOrg** [comment]
On OpenBSD you need the master branch, not the portable branch which is for other systems.The master branch is synchronized with OpenBSD's development version so at times (like right now) it may require a feature not available in latest stable release.

**Comment by mchack23** [comment]
I see thanks for the hint :)

**Comment by poolpOrg** [comment]
Oh and if you use an OpenBSD snapshot you already have OpenSMTPD installed, the same version as in the master branch ☺️On Sep 14, 2019 16:56, mchack23 <notifications@github.com> wrote:Closed #936.
