### ISSUE TITLE
Invalid character "/" in localpart when delivering via LMTP.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#937]
I went to make an account on dnswl.org out of curiousity and their confirmation e-mail didn't reach me. It turns out that:

`Sep 14 22:13:22 host smtpd[27198]: b61dca7480d2b716 mda delivery evpid=b9a06e0dc2f14508 from=<hostmaster+public/www-data@dnswl.org> to=<my@mail.address> rcpt=<my@mail.address> user=3 delay=40s result=TempFail stat=Error (temporary failure: "mail.lmtp: LMTP server error: 501 5.5.4 Invalid FROM: Invalid character in localpart")`

I looked at Dovecot LMTP logs and it seems OpenSMTPD is converting the / to : before delivering to Dovecot. It there anything we can do about it?

Luckily I could read it by smtpctl show message. :)

**Comment by poolpOrg** [comment]
there's a bit of code which sanitizes addresses after they are accepted by OpenSMTPD but before they are used in delivery and I think it's being triggered a bit too early.

I'll test a diff

**Comment by poolpOrg** [comment]
can you test this and see if it makes things better ?

[unescape.diff.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/3618187/unescape.diff.txt)

**Comment by whataboutpereira** [comment]
Unfortunately it still fails - here is the excerpt from LMTP rawlog from Dovecot:

`1568705021.498888 MAIL FROM:<hostmaster+public:www-data@dnswl.org>`

The actual address is hostmaster+public/www-data@dnswl.org

The / is turning into a : for some reason.

**Comment by poolpOrg** [comment]
Are you sure the diff is applied correctly, binary reinstalled and daemon restarted ?

I don't see how this can possibly happen:

    laptop$ grep ESCAPE *|grep -v mail.maildir.c
    mda_variables.c:                        if (strchr(MAILADDR_ESCAPE, tmp[i]))
    smtpd.h:#define MAILADDR_ESCAPE         "!#$&*?^`{|}"
    laptop$

There is no escaping from '/' so either OpenSMTPD magically figured it should escape / or Dovecot is doing its own escaping :-/

**Comment by whataboutpereira** [comment]
Just a stab in the relative dark - grepping for "/" and ":" yielded:

mda_variables.c:		*dest = (replace && *string == '/') ? ':' : *string;

I also ran smtpd -dv -T all, but saw no mention of the sender addresss when it was LMTP-d to Dovecot.

If all fails, I'll check with the Dovecot list.

**Comment by poolpOrg** [comment]
indeed, this will need to be reworked as it's error-prone...

can you set replace to 0 before entering the loop and see if it improves the situation ?

**Comment by whataboutpereira** [comment]
Nice, it worked now after a couple of RPM rebuilds and the e-mail landed in Dovecot. :)

Will it break something else now?

**Comment by poolpOrg** [comment]
I don't think it'll have a negative side-effect.

I sent a diff to other OpenSMTPD hackers and waiting for an ok

**Comment by whataboutpereira** [comment]
Wonderful, thank you. Been running with replace 0 since yesterday without problems.

**Comment by poolpOrg** [comment]
diff committed to OpenBSD, will be synched here shortly

**Comment by whataboutpereira** [comment]
Thanks again!

**Comment by whataboutpereira** [comment]
I noticed the changes from OpenBSD are in and can confirm it works with the current portable.
