### ISSUE TITLE
Spaces missing from smtpctl error messages.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#938]
Hello! I found more error messages that are missing spaces:

sudo smtpctl show message 4d79e896a9d17257
smtpctl: No such file or directoryfopen

**Comment by poolpOrg** [comment]
Hello,

You need to provide more details, such as the version you are using and the system because on a recent OpenBSD with a recent OpenSMTPD:

    smtpctl: fopen: No such file or directory

**Comment by whataboutpereira** [comment]
I'm seeing these using the current portable from a couple of days ago on CentOS 7.

**Comment by poolpOrg** [comment]
This should be fixed in the current -portable branch, can you test and confirm ?

**Comment by whataboutpereira** [comment]
The error message is nicely fixed now.

I notice there's a new smtp command in the works now - using it yielded:

smtp: SSL_CTX_load_verify_locations: No such file or directory

I'm compiling on CentOS 7 with static OpenSSL libraries - could that be the problem or would you like me to report it separately?

**Comment by poolpOrg** [comment]
separately pleaseOn Sep 19, 2019 09:57, Reio Remma <notifications@github.com> wrote:The error message is nicely fixed now.
I notice there's a new smtp command in the works now - using it yielded:
smtp: SSL_CTX_load_verify_locations: No such file or directory
I'm compiling on CentOS 7 with static OpenSSL libraries - could that be the problem or would you like me to report it separately?
