### ISSUE TITLE
New smtp command in the current portable.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#939]
I notice there's a new smtp command in the works now - using it yielded:

smtp: SSL_CTX_load_verify_locations: No such file or directory

I'm compiling on CentOS 7 with static OpenSSL 1.1.1 libraries - could that be the problem or might it be a problem with general portability?

**Comment by poolpOrg** [comment]
can you edit smtpc.c and add this just before the SSL_CTX_load_verify_locations() call ?

    warnx("DEFAULT CERT FILE: %s", X509_get_default_cert_file());

I think this is a general portability issue

**Comment by whataboutpereira** [comment]
$ smtp
smtp: DEFAULT CERT FILE: /etc/ssl/cert.pem
smtp: SSL_CTX_load_verify_locations: No such file or directory

I can find the only cert.pem on CentOS 7 here:

$ locate cert.pem
/etc/pki/tls/cert.pem

**Comment by whataboutpereira** [comment]
OpenSMTPD is compiled with --with-path-CAfile=/etc/pki/tls/cert.pem - is that the same file it's looking for?

**Comment by poolpOrg** [comment]
indeed, that's a weird packaging issue though if `X509_get_default_cert_file()` returns a path different than the one configured for OpenSMTPD, it means that OpenSSL and OpenSMTPD were configured to look at different places :-/

**Comment by whataboutpereira** [comment]
It turned out the instructions I had were wrong and the openssl path itself was wrong when I compiled it. Compiling OpenSSL with the proper /etc/pki/tls/cert.pem has gotten rid of the SSL_CTX_load_verify_locations error.
