### ISSUE TITLE
Identify the opensmtpd version and filter api version in the filter protocol

### ISSUE THREAD

**Issue by jdelic** [OpenSMTPD/OpenSMTPD#941]
As far as I can see, when looking at the articles available on poolp.org about OpenSMTPD filters, especially [the latest update](https://poolp.org/posts/2019-06-30/june-2019-report-fion-bpg-and-smtpd/), there is currently no way for a filter to know what version of OpenSMTPD or it's filter API the filter is running against.

With the [introduction of the 'Junk' action](https://poolp.org/posts/2019-09-21/september-2019-report-jules-opensmtpd-6.6.0-upcoming-release-and-related-things/) it's becoming really important as a filter developer to know what actions are available.

The same is a little less true for the introduction of the authentication events in the reporting API since one can probably just code around their "absence".

In any case, before this becomes a problem, I would like to propose that OpenSMTPD sends a startup line to a filter before registration that tells it what version of the API, and potentially OpenSMTPD itself, the filter is running against (as future versions of OpenSMTPD might also allow registration for events that aren't available yet).

Thoughts?

**Comment by poolpOrg** [comment]
I'm not sure what you mean because the protocol version is part of the protocol header in each line

**Comment by whataboutpereira** [comment]
Register lines don't appear to have the version number. Maybe that?

**Comment by poolpOrg** [comment]
mh. why not

**Comment by whataboutpereira** [comment]
config|smtp-session-timeout|300
config|ready
OpenSMTPD eventlog loaded.
report|0.4|1569838169.191163|smtp-in|link-connect|9cc4337faac625b2|host|pass|192.168.1.3:51906|0.0.0.0:25

**Comment by poolpOrg** [comment]
I have added an smtpd-version config key during the initial handshake, this will be sync to github soon.

**Comment by jdelic** [comment]
@poolpOrg  @whataboutpereira 
wow, that's a quick turn-around time :). Thank you!

I actually didn't even realize that the version number was in each line (oops). Does that mean that the version number `0.4` indicates presence of `junk`? In that case my use-case would have been already covered. 

However, having the version as early as possible is definitely useful if the filter protocol introduces new events to register for. So kudos for the change.
