### ISSUE TITLE
Build with libressl is failing

### ISSUE THREAD

**Issue by ngortheone** [OpenSMTPD/OpenSMTPD#944]
Ran into this today:

`OpenSMTPD $ docker build -t opensmtpd-dev . ` 

```
...
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory '/opensmtpd'
Making all in openbsd-compat
make[2]: Entering directory '/opensmtpd/openbsd-compat'
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I../openbsd-compat/err_h -I/usr/include   -g -O2  -fPIC -DPIC -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset -D_BSD_SOURCE -D_DEFAULT_SOURCE  -c -o arc4random.o arc4random.c
arc4random.c:167:21: error: macro "arc4random_stir" passed 1 arguments, but takes just 0
 arc4random_stir(void)
                     ^
arc4random.c:168:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 {
 ^
make[2]: Leaving directory '/opensmtpd/openbsd-compat'
make[2]: *** [Makefile:446: arc4random.o] Error 1
make[1]: Leaving directory '/opensmtpd'
make[1]: *** [Makefile:419: all-recursive] Error 1
make: *** [Makefile:351: all] Error 2
The command '/bin/sh -c ./bootstrap &&     ./configure --with-gnu-ld --sysconfdir=/etc/mail --with-path-empty=/var/lib/opensmtpd/empty/ &&     make &&     make install' returned a non-zero code: 2
```

I am not a C dev, but it looks like a conflicting name with stdlib

**Comment by ngortheone** [comment]
Steps to reproduce
1. Checkout portable branch
2. Run `docker build -t opensmtpd-portable-dev .`

**Comment by ngortheone** [comment]
I am completely puzzled. Same code compiles fine on debain. (compiler version is the same)

**Comment by ngortheone** [comment]
So, here is the problem, but I dunno how to fix it.


./openbsd-compat/openbsd-compat.h
```c
#if defined(HAVE_ARC4RANDOM_STIR)
void arc4random_stir(void);
#elif defined(HAVE_ARC4RANDOM) || defined(LIBRESSL_VERSION_NUMBER)
/* Recent system/libressl implementation; no need for explicit stir */
# define arc4random_stir()
#else
/* openbsd-compat/arc4random.c provides arc4random_stir() */
void arc4random_stir(void);
#endif

```
./openbsd-compat/arc4random.c
```c
void
arc4random_stir(void)
{
	_ARC4_LOCK();
	_rs_stir();
	_ARC4_UNLOCK();
}
```

HAVE_ARC4RANDOM_STIR - not defined
HAVE_ARC4RANDOM - not defined
LIBRESSL_VERSION_NUMBER - defined!

so it results in mismatch between header definition and arc4random.c
```
/* Recent system/libressl implementation; no need for explicit stir */
# define arc4random_stir()
```
vs
```
void
arc4random_stir(void)
```

**Comment by ngortheone** [comment]
all problems go away when I swap libressl with openssl

**Comment by ngortheone** [comment]
Re-opening because it causes problems for users

**Comment by ngortheone** [comment]
#### Alpine Linux 
fails probably due to [old LibreSSL](https://pkgs.alpinelinux.org/packages?name=libressl-dev&branch=v3.10)==2.7.5

And [OpenSSL](https://pkgs.alpinelinux.org/packages?name=openssl&branch=v3.10)==1.1.1d-r0 

So that explains why OpenSSL build works and LibreSSL fails.

**Comment by poolpOrg** [comment]
That is a known issue:

Because OpenSMTPD is developed on OpenBSD which ships LibreSSL, our target is LibreSSL and not OpenSSL. As a result, since the two have some differences in some API, OpenSMTPD > 6.0 no longer bu

**Comment by ngortheone** [comment]
I have seen from the mailing list that LibreSSL >=3 should work. I am in progress of trying it out.

One thing I thought about is that we probably need to post some kind of CHANGES file, similar to what you posted on mailing list

**Comment by poolpOrg** [comment]
yes, I had the same thought when I prepared the release.

On OpenBSD, we have a page to document the changes but there is no such thing for the portable release.

**Comment by ngortheone** [comment]
I will create a PR later today with Changelog. And there should be a way to put this info onto releases tab as well (need to find how though)

**Comment by ngortheone** [comment]
Duplicate of #958 
Closing this one to consolidate conversation in one thread.
