### ISSUE TITLE
OpenSMTPD filters receive escaped "." which breaks DKIM processing.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#948]
As we found out with filter-rspamd, data lines fed to filters beginning with "." are escaped to ".." and whenever that happens, DKIM checks will fail.

Filters should probably be fed pure unescaped lines - the raw incoming mail.

Attached are 2 files:

• filter.txt - the data inside filters.
• delivered.txt - the actual delivered mail

Note the lines starting with ..woff etc.

[filter.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/3733445/filter.txt)
[delivered.txt](https://github.com/OpenSMTPD/OpenSMTPD/files/3733444/delivered.txt)

**Comment by poolpOrg** [comment]
The escaping is legit in OpenSMTPD as this is the SMTP protocol escaping, the filters receive raw lines so they should unescape if they so want to.

Closing this issue as it was fixed in my filter-rspamd, by you ;-)

**Comment by ngortheone** [comment]
I want to add that this information absoulutely must be available to filter developers in a form of documentation.

poolpOrg, is there existing filter dev documentation? If there isnt one where would be the best place to put it?

On October 18, 2019 11:43:22 AM EDT, Gilles Chehade <notifications@github.com> wrote:
>The escaping is legit in OpenSMTPD as this is the SMTP protocol
>escaping, the filters receive raw lines so they should unescape if they
>so want to.
>
>Closing this issue as it was fixed in my filter-rspamd, by you ;-)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenSMTPD/OpenSMTPD/issues/948#issuecomment-543803659

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by poolpOrg** [comment]
@ngortheone the right place is a man page, I had started one but given that the protocol is not yet 1.0 I didnt want to make it part of 6.6.0 so it isnt carved in stone yet. i'll commit it shortly so that it is documented in dev branch and ready for 6.7.0
