### ISSUE TITLE
mail-from regex keeps throwing a syntax error

### ISSUE THREAD

**Issue by rhavenn** [OpenSMTPD/OpenSMTPD#957]
Arch Linux with opensmtpd 6.4.2p1-1

I keep getting a syntax error when trying to use a 'mail-from regex' match. If I drop the regex my match works fine and smtpd starts without issue.

I have the following ACTION:
`action 'mydomain' relay host smtp+tls://mydomain@smtp.office365.com:587 tls auth <secrets>`

I have the MATCH that works:
`match for any mail-from "user@mydomain.com" action 'mydomain'`

but if I switch that to a regex match it fails:
`match for any mail-from regex ".*mydomain.com" action 'mydomain'`

I tried multiple variations of the regex itself from just a `*mydomain.com` to `^.*@mydomain.com$`

Is there a bug here or am I just being obtuse?

**Comment by whataboutpereira** [comment]
How are you testing?

"match for any" is really "match from local for any" and will match only locally originated mails.

I just tested it and it worked, albeit in the current portable (v6.6).

You'll probably want to match the line end with $ as well.

**Comment by whataboutpereira** [comment]
Oh, now I realize regex rules were added only in December 2018, v6.4.0 however is older than that, so shouldn't support regex at all.

**Comment by poolpOrg** [comment]
As pointed by @whataboutpereira, the 6.4.2 release didn't support regex table lookups as they were introduced later, this is why you get a syntax error.

The 6.6.0p1 release is about to happen, very likely Monday, and will bring the regex stuff.

**Comment by rhavenn** [comment]
My bad. Thanks for clarifying. Looking forward to 6.6 :)
