### ISSUE TITLE
"smtpctl encrypt -b rounds" throws an error.

### ISSUE THREAD

**Issue by zelest** [OpenSMTPD/OpenSMTPD#986]
If I run `smtpctl encrypt -b 15 -p`, it gives me an error on OpenBSD 6.6:

> $ smtpctl encrypt -b 15 -p
> possibilities are:
> $

A workaround for OpenBSD users is to use `encrypt(1)`.

**Comment by ngortheone** [comment]
@poolpOrg  on IRC:

> opensmtpd expects credentials to be generated in crypt(3) format
> on openbsd we have an encrypt utility in base to do that
> on other systems, not so much, and people kept having issues figuring out what they should install
> so i quick-hacked an integration of the encrypt utility in portable
> and so it looked the same between opensbd and portable in instructions, i plugged it in smtpctl
> but the smtpctl utility isn t built to handle options
> so while `smtpctl encrypt` works, `smtpctl encrypt -b 42` doesn't
> the option gets parsed by smtpctl before being passwd to encrypt
> the man page states:

```
     encrypt [string]
             Encrypt the password string to a representation suitable for user
             credentials and print it to the standard output.  If string is
             not provided, cleartext passwords are read from standard input.
             It is advised to avoid providing the password as a parameter as
             it will be visible from top(1) and ps(1) output.
```
> I'll figure out if we can do someting with that but this is more of a feature request than a bug really
> we can teach smtpctl to give a proper error message though

**Comment by poolpOrg** [comment]
The man page documents an `smtpctl encrypt [string]` command which supports no options and @zelest passed options to it.

I have improved the error message to let user know that command is invalid and I have killed usage of `getopt()` for the `smtpctl encrypt` subcommand.
